'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { supabase } from '@/lib/supabase';
import styles from '../ops-tools.module.css';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Rec={id:string;kind:string;title:string;status:string;priority:string;sensitivity:string;data:any;occurred_at:string|null;created_at:string};

export default function MaintenancePage(){
  const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[profile,setProfile]=useState<Profile|null>(null),[rows,setRows]=useState<Rec[]>([]),[message,setMessage]=useState('');
  const [ticket,setTicket]=useState({equipment:'',issue:'',priority:'normal',location_detail:''}),[equipment,setEquipment]=useState({name:'',model:'',serial:'',location_detail:'',vendor:'',warranty:''}),[service,setService]=useState({equipment_id:'',summary:'',vendor:'',cost:'',next_due:''});
  const canManage=profile?.app_role==='admin'||profile?.app_role==='manager';
  useEffect(()=>{void init()},[]);
  async function init(){const {data:u}=await supabase.auth.getUser();if(!u.user){window.location.href='/';return;}const {data:p}=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();setProfile((p||null) as Profile|null);if(p?.location_id)await load(p.location_id);setReady(true);}
  async function load(locationId=profile?.location_id||''){if(!locationId)return;const {data,error}=await supabase.from('ops_records').select('id,kind,title,status,priority,sensitivity,data,occurred_at,created_at').eq('location_id',locationId).in('kind',['equipment','maintenance_ticket','equipment_service']).is('deleted_at',null).order('created_at',{ascending:false}).limit(200);setRows((data??[]) as Rec[]);if(error)setMessage('Could not load maintenance data.');}
  const equipmentRows=useMemo(()=>rows.filter(r=>r.kind==='equipment'&&r.status!=='retired'),[rows]),tickets=useMemo(()=>rows.filter(r=>r.kind==='maintenance_ticket'),[rows]),services=useMemo(()=>rows.filter(r=>r.kind==='equipment_service'),[rows]);
  async function addTicket(e:FormEvent){e.preventDefault();if(!profile?.location_id||busy||!ticket.issue.trim())return;setBusy(true);try{const {data:u}=await supabase.auth.getUser();if(!u.user)return;const {error}=await supabase.from('ops_records').insert({location_id:profile.location_id,kind:'maintenance_ticket',title:`Repair · ${(ticket.equipment||ticket.location_detail||'Restaurant issue').trim().slice(0,160)}`,status:'open',priority:ticket.priority,sensitivity:'team',data:{equipment:ticket.equipment.trim().slice(0,200),issue:ticket.issue.trim().slice(0,6000),location_detail:ticket.location_detail.trim().slice(0,1000)},tags:['maintenance','repair'],occurred_at:new Date().toISOString(),created_by:u.user.id,updated_by:u.user.id});if(error)throw error;setTicket({equipment:'',issue:'',priority:'normal',location_detail:''});await load();setMessage('Maintenance ticket submitted.');}catch{setMessage('Could not submit maintenance ticket.');}finally{setBusy(false)}}
  async function addEquipment(e:FormEvent){e.preventDefault();if(!canManage||!profile?.location_id||busy||!equipment.name.trim())return;setBusy(true);try{const {data:u}=await supabase.auth.getUser();if(!u.user)return;const {error}=await supabase.from('ops_records').insert({location_id:profile.location_id,kind:'equipment',title:equipment.name.trim().slice(0,200),status:'active',priority:'normal',sensitivity:'manager',data:{model:equipment.model.trim().slice(0,300),serial:equipment.serial.trim().slice(0,300),location_detail:equipment.location_detail.trim().slice(0,1000),vendor:equipment.vendor.trim().slice(0,500),warranty:equipment.warranty.trim().slice(0,1000)},tags:['equipment'],created_by:u.user.id,updated_by:u.user.id});if(error)throw error;setEquipment({name:'',model:'',serial:'',location_detail:'',vendor:'',warranty:''});await load();setMessage('Equipment added.');}catch{setMessage('Could not add equipment.');}finally{setBusy(false)}}
  async function resolveTicket(id:string){if(!canManage||busy)return;const resolution=prompt('Resolution / repair note')||'';setBusy(true);try{const {data:u}=await supabase.auth.getUser();const {error}=await supabase.from('ops_records').update({status:'resolved',archived_at:new Date().toISOString(),updated_by:u.user?.id||null,data:{resolution:resolution.trim().slice(0,3000)}}).eq('id',id).eq('kind','maintenance_ticket');if(error)throw error;await load();setMessage('Maintenance ticket resolved.');}catch{setMessage('Could not resolve ticket.');}finally{setBusy(false)}}
  async function addService(e:FormEvent){e.preventDefault();if(!canManage||!profile?.location_id||busy||!service.equipment_id||!service.summary.trim())return;const eq=equipmentRows.find(x=>x.id===service.equipment_id);setBusy(true);try{const {data:u}=await supabase.auth.getUser();const {error}=await supabase.from('ops_records').insert({location_id:profile.location_id,kind:'equipment_service',title:`Service · ${eq?.title||'Equipment'}`,status:'completed',priority:'normal',sensitivity:'manager',data:{equipment_id:service.equipment_id,summary:service.summary.trim().slice(0,5000),vendor:service.vendor.trim().slice(0,500),cost:Math.max(0,Number(service.cost)||0),next_due:service.next_due||null},tags:['equipment','service'],occurred_at:new Date().toISOString(),created_by:u.user?.id||null,updated_by:u.user?.id||null});if(error)throw error;setService({equipment_id:'',summary:'',vendor:'',cost:'',next_due:''});await load();setMessage('Service history saved.');}catch{setMessage('Could not save service history.');}finally{setBusy(false)}}
  if(!ready)return <main className={styles.page}>Loading maintenance…</main>;
  if(!profile?.location_id)return <main className={styles.page}>No restaurant location is assigned.</main>;
  return <main className={styles.page}><div className={styles.top}><div><h1>Maintenance</h1><p>Equipment registry, repair tickets and service history.</p></div><Link className={styles.back} href="/">Back to Ops</Link></div>{message&&<div className={message.startsWith('Could not')?styles.error:styles.notice}>{message}</div>}
    <div className={styles.grid}><Metric label="Active equipment" value={String(equipmentRows.length)}/><Metric label="Open tickets" value={String(tickets.filter(t=>t.status==='open').length)}/><Metric label="Urgent repairs" value={String(tickets.filter(t=>t.status==='open'&&t.priority==='urgent').length)}/><Metric label="Service records" value={String(services.length)}/></div>
    <section className={styles.section}><div className={styles.card}><h2>Report a problem</h2><form onSubmit={addTicket}><div className={styles.formGrid}><Field label="Equipment"><input value={ticket.equipment} onChange={e=>setTicket({...ticket,equipment:e.target.value})} placeholder="Walk-in, fryer, POS, sink…"/></Field><Field label="Priority"><select value={ticket.priority} onChange={e=>setTicket({...ticket,priority:e.target.value})}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></Field><Field label="Where is it?"><input value={ticket.location_detail} onChange={e=>setTicket({...ticket,location_detail:e.target.value})}/></Field><Field label="What is wrong?" wide><textarea required value={ticket.issue} onChange={e=>setTicket({...ticket,issue:e.target.value})}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy}>Submit ticket</button></div></form></div></section>
    <section className={styles.section}><h2>Open repair tickets</h2><div className={styles.list}>{tickets.filter(t=>t.status==='open').map(t=><div className={styles.entry} key={t.id}><div className={styles.entryHead}><div><h3>{t.title}</h3><small>{new Date(t.occurred_at||t.created_at).toLocaleString()} · {t.data?.location_detail||'location not specified'}</small></div><span className={styles.pill}>{t.priority}</span></div><div className={styles.details}>{detail('Issue',t.data?.issue)}{detail('Equipment',t.data?.equipment)}</div>{canManage&&<div className={styles.actions}><button className={styles.button} disabled={busy} onClick={()=>resolveTicket(t.id)}>Resolve</button></div>}</div>)}</div></section>
    {canManage&&<><section className={styles.section}><div className={styles.card}><h2>Add equipment</h2><form onSubmit={addEquipment}><div className={styles.formGrid}><Field label="Name"><input required value={equipment.name} onChange={e=>setEquipment({...equipment,name:e.target.value})}/></Field><Field label="Location"><input value={equipment.location_detail} onChange={e=>setEquipment({...equipment,location_detail:e.target.value})}/></Field><Field label="Model"><input value={equipment.model} onChange={e=>setEquipment({...equipment,model:e.target.value})}/></Field><Field label="Serial"><input value={equipment.serial} onChange={e=>setEquipment({...equipment,serial:e.target.value})}/></Field><Field label="Vendor / service company"><input value={equipment.vendor} onChange={e=>setEquipment({...equipment,vendor:e.target.value})}/></Field><Field label="Warranty / notes"><input value={equipment.warranty} onChange={e=>setEquipment({...equipment,warranty:e.target.value})}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy}>Add equipment</button></div></form></div></section>
    <section className={styles.section}><div className={styles.card}><h2>Record service</h2><form onSubmit={addService}><div className={styles.formGrid}><Field label="Equipment"><select value={service.equipment_id} onChange={e=>setService({...service,equipment_id:e.target.value})}><option value="">Choose equipment</option>{equipmentRows.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></Field><Field label="Vendor"><input value={service.vendor} onChange={e=>setService({...service,vendor:e.target.value})}/></Field><Field label="Cost"><input type="number" min="0" step="0.01" value={service.cost} onChange={e=>setService({...service,cost:e.target.value})}/></Field><Field label="Next service due"><input type="date" value={service.next_due} onChange={e=>setService({...service,next_due:e.target.value})}/></Field><Field label="Work completed" wide><textarea required value={service.summary} onChange={e=>setService({...service,summary:e.target.value})}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy}>Save service record</button></div></form></div></section></>}
    {canManage&&<section className={styles.section}><h2>Equipment registry</h2><div className={styles.list}>{equipmentRows.map(e=><div className={styles.entry} key={e.id}><div className={styles.entryHead}><div><h3>{e.title}</h3><small>{e.data?.location_detail||'No location'} · model {e.data?.model||'—'} · serial {e.data?.serial||'—'}</small></div><span className={styles.pill}>{e.status}</span></div></div>)}</div></section>}
  </main>}
function Metric({label,value}:{label:string;value:string}){return <div className={styles.metric}><span>{label}</span><strong>{value}</strong></div>}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={`${styles.field} ${wide?styles.wide:''}`}><span>{label}</span>{children}</label>}
function detail(label:string,value?:string){return value?.trim()?<div className={styles.detail}><b>{label}</b><span>{value}</span></div>:null}
