'use client';

import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase';
import {useI18n} from '@/lib/i18n';
import {addDateDays,dateDayOfWeek} from '@/lib/scheduling-engine';
import {businessDateInZone} from '@/lib/intermediate-hardening';
import styles from '../../ops-tools.module.css';

type Employee={id:string;full_name:string};type Role={id:string;name:string;department:string|null};type Shift={id:string;employee_id:string|null;role_id:string|null;starts_at:string;ends_at:string;status:string;notes:string|null;source:string|null};type Event={id:string;title:string;event_type:string;starts_at:string;ends_at:string;all_day:boolean;description:string|null};
type View='day'|'week'|'month';type Group='time'|'employee'|'role';
const ymd=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const mondayOf=(date:string)=>addDateDays(date,-((dateDayOfWeek(date)+6)%7));
const localDate=(iso:string)=>ymd(new Date(iso));
export default function ScheduleViewsPage(){
 const {locale}=useI18n();const localeCode=locale==='es'?'es-US':'en-US';const fmtTime=(iso:string)=>new Date(iso).toLocaleTimeString(localeCode,{hour:'numeric',minute:'2-digit'}),fmtDate=(d:string)=>new Date(`${d}T12:00:00`).toLocaleDateString(localeCode,{weekday:'short',month:'short',day:'numeric'});const c=locale==='es'?{load:'No se pudieron cargar las vistas del horario.',opening:'Abriendo vistas del horario…',title:'Vistas del Horario',body:'Vistas de día, semana y mes con filtros por departamento, puesto y empleado.',back:'Volver al Horario',view:'Vista',day:'Día',week:'Semana',month:'Mes',layout:'Diseño',time:'Por fecha y hora',employeeBoard:'Tablero por empleado',roleBoard:'Tablero por puesto',department:'Departamento',all:'Todos',management:'Gerencia',other:'Otro',role:'Puesto',allRoles:'Todos los puestos',employee:'Empleado',allEmployees:'Todos los empleados',openOnly:'Solo turnos abiertos',previous:'Anterior',today:'Hoy',next:'Siguiente',shifts:(n:number)=>`${n} turnos`,event:'EVENTO',allDay:'Todo el día',openShift:'Turno abierto',noShifts:'Sin turnos',openShifts:'Turnos abiertos',employeeFallback:'Empleado',roleFallback:'Puesto',status:{draft:'borrador',published:'publicado',open:'abierto',assigned:'asignado',cancelled:'cancelado'} as Record<string,string>}:{load:'Could not load schedule views.',opening:'Opening schedule views…',title:'Schedule Views',body:'Day, week and month views with department, role and employee filters.',back:'Back to Schedule',view:'View',day:'Day',week:'Week',month:'Month',layout:'Layout',time:'By date & time',employeeBoard:'Employee board',roleBoard:'Role board',department:'Department',all:'All',management:'Management',other:'Other',role:'Role',allRoles:'All roles',employee:'Employee',allEmployees:'All employees',openOnly:'Open shifts only',previous:'Previous',today:'Today',next:'Next',shifts:(n:number)=>`${n} shifts`,event:'EVENT',allDay:'All day',openShift:'Open shift',noShifts:'No shifts',openShifts:'Open shifts',employeeFallback:'Employee',roleFallback:'Role',status:{draft:'draft',published:'published',open:'open',assigned:'assigned',cancelled:'cancelled'} as Record<string,string>};
 const [ready,setReady]=useState(false),[message,setMessage]=useState(''),[employees,setEmployees]=useState<Employee[]>([]),[roles,setRoles]=useState<Role[]>([]),[shifts,setShifts]=useState<Shift[]>([]),[events,setEvents]=useState<Event[]>([]),[anchor,setAnchor]=useState(businessDateInZone()),[view,setView]=useState<View>('week'),[group,setGroup]=useState<Group>('time'),[department,setDepartment]=useState('all'),[roleId,setRoleId]=useState('all'),[employeeId,setEmployeeId]=useState('all');
 useEffect(()=>{void load()},[]);
 async function load(){const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}const p=await supabase.from('profiles').select('location_id').eq('id',u.user.id).single();if(p.error||!p.data?.location_id){setMessage(c.load);setReady(true);return}const loc=p.data.location_id;const from=new Date();from.setDate(from.getDate()-70);const to=new Date();to.setDate(to.getDate()+120);const [e,r,s,ev]=await Promise.all([supabase.from('employees').select('id,full_name').eq('location_id',loc).is('deleted_at',null).order('full_name'),supabase.from('employee_roles').select('id,name,department').eq('location_id',loc).order('name'),supabase.from('schedule_shifts').select('id,employee_id,role_id,starts_at,ends_at,status,notes,source').eq('location_id',loc).gte('starts_at',from.toISOString()).lt('starts_at',to.toISOString()).neq('status','cancelled').order('starts_at'),supabase.from('calendar_events').select('id,title,event_type,starts_at,ends_at,all_day,description').eq('location_id',loc).gte('starts_at',from.toISOString()).lt('starts_at',to.toISOString()).is('deleted_at',null).order('starts_at')]);if(s.error)setMessage(s.error.message);setEmployees((e.data??[]) as Employee[]);setRoles((r.data??[]) as Role[]);setShifts((s.data??[]) as Shift[]);setEvents((ev.data??[]) as Event[]);setReady(true)}
 const roleMap=useMemo(()=>new Map(roles.map(r=>[r.id,r])),[roles]),empMap=useMemo(()=>new Map(employees.map(e=>[e.id,e])),[employees]);
 const filtered=useMemo(()=>shifts.filter(s=>{const role=roleMap.get(s.role_id||'');return (department==='all'||role?.department===department)&&(roleId==='all'||s.role_id===roleId)&&(employeeId==='all'||s.employee_id===employeeId)}),[shifts,roleMap,department,roleId,employeeId]);
 const visibleDates=useMemo(()=>{if(view==='day')return [anchor];if(view==='week'){const w=mondayOf(anchor);return Array.from({length:7},(_,i)=>addDateDays(w,i))}const a=new Date(`${anchor}T12:00:00`),first=new Date(a.getFullYear(),a.getMonth(),1),last=new Date(a.getFullYear(),a.getMonth()+1,0);void first;return Array.from({length:last.getDate()},(_,i)=>ymd(new Date(a.getFullYear(),a.getMonth(),i+1)))},[anchor,view]);
 const visible=useMemo(()=>filtered.filter(s=>visibleDates.includes(localDate(s.starts_at))),[filtered,visibleDates]);
 const shiftLabel=(s:Shift)=>`${fmtTime(s.starts_at)}–${fmtTime(s.ends_at)} · ${roleMap.get(s.role_id||'')?.name||c.roleFallback} · ${empMap.get(s.employee_id||'')?.full_name||c.openShift}`;
 function move(delta:number){if(view==='day')setAnchor(addDateDays(anchor,delta));else if(view==='week')setAnchor(addDateDays(anchor,delta*7));else{const a=new Date(`${anchor}T12:00:00`);a.setMonth(a.getMonth()+delta);setAnchor(ymd(a))}}
 const grouped=useMemo(()=>{if(group==='time')return [] as [string,Shift[]][];const map=new Map<string,Shift[]>();for(const s of visible){const key=group==='employee'?(s.employee_id||'open'):(s.role_id||'none');map.set(key,[...(map.get(key)||[]),s])}return [...map.entries()].sort((a,b)=>a[0].localeCompare(b[0]))},[visible,group]);
 if(!ready)return <div className="full-loader"><span>{c.opening}</span></div>;
 return <main className={styles.page}><div className={styles.top}><div><h1>{c.title}</h1><p>{c.body}</p></div><Link className={styles.back} href="/schedule">{c.back}</Link></div>{message&&<div className={styles.notice}>{message}</div>}
 <section className={styles.section}><div className={styles.card}><div className={styles.formGrid}><label className={styles.field}><span>{c.view}</span><select value={view} onChange={e=>setView(e.target.value as View)}><option value="day">{c.day}</option><option value="week">{c.week}</option><option value="month">{c.month}</option></select></label><label className={styles.field}><span>{c.layout}</span><select value={group} onChange={e=>setGroup(e.target.value as Group)}><option value="time">{c.time}</option><option value="employee">{c.employeeBoard}</option><option value="role">{c.roleBoard}</option></select></label><label className={styles.field}><span>{c.department}</span><select value={department} onChange={e=>setDepartment(e.target.value)}><option value="all">{c.all}</option><option value="foh">FOH</option><option value="boh">BOH</option><option value="management">{c.management}</option><option value="other">{c.other}</option></select></label><label className={styles.field}><span>{c.role}</span><select value={roleId} onChange={e=>setRoleId(e.target.value)}><option value="all">{c.allRoles}</option>{roles.filter(r=>department==='all'||r.department===department).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label className={styles.field}><span>{c.employee}</span><select value={employeeId} onChange={e=>setEmployeeId(e.target.value)}><option value="all">{c.allEmployees}</option><option value="open">{c.openOnly}</option>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select></label></div><div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} onClick={()=>move(-1)}>{c.previous}</button><button className={`${styles.button} ${styles.secondary}`} onClick={()=>setAnchor(businessDateInZone())}>{c.today}</button><button className={`${styles.button} ${styles.secondary}`} onClick={()=>move(1)}>{c.next}</button><span className={styles.pill}>{c.shifts(visible.length)}</span></div></div></section>
 {group==='time'?<section className={styles.section}><div style={{display:'grid',gridTemplateColumns:view==='month'?'repeat(auto-fit,minmax(140px,1fr))':'1fr',gap:10}}>{visibleDates.map(date=>{const ds=visible.filter(s=>localDate(s.starts_at)===date);const es=events.filter(ev=>localDate(ev.starts_at)===date);return <div className={styles.card} key={date}><div className={styles.entryHead}><h3>{fmtDate(date)}</h3><span className={styles.pill}>{ds.length}</span></div><div className={styles.list}>{es.map(ev=><div className={styles.entry} key={'event-'+ev.id}><b>{c.event} · {ev.title}</b><small>{ev.all_day?c.allDay:fmtTime(ev.starts_at)+'–'+fmtTime(ev.ends_at)} · {ev.event_type}</small>{ev.description&&<small>{ev.description}</small>}</div>)}{ds.map(s=><div className={styles.entry} key={s.id}><b>{fmtTime(s.starts_at)}–{fmtTime(s.ends_at)}</b><small>{roleMap.get(s.role_id||'')?.name||c.roleFallback} · {empMap.get(s.employee_id||'')?.full_name||c.openShift} · {c.status[s.status]||s.status}</small>{s.notes&&<small>{s.notes}</small>}</div>)}{!ds.length&&<small className={styles.muted}>{c.noShifts}</small>}</div></div>})}</div></section>:<section className={styles.section}><div className={styles.list}>{grouped.map(([key,rows])=><div className={styles.card} key={key}><div className={styles.entryHead}><h2>{group==='employee'?(key==='open'?c.openShifts:empMap.get(key)?.full_name||c.employeeFallback):roleMap.get(key)?.name||c.roleFallback}</h2><span className={styles.pill}>{c.shifts(rows.length)}</span></div><div className={styles.list}>{rows.sort((a,b)=>a.starts_at.localeCompare(b.starts_at)).map(s=><div className={styles.entry} key={s.id}><b>{fmtDate(localDate(s.starts_at))} · {shiftLabel(s)}</b><small>{c.status[s.status]||s.status}{s.notes?` · ${s.notes}`:''}</small></div>)}</div></div>)}</div></section>}
 </main>
}
