'use client';

import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase';
import {addDateDays,dateDayOfWeek} from '@/lib/scheduling-engine';
import {businessDateInZone} from '@/lib/intermediate-hardening';
import styles from '../../ops-tools.module.css';

type Employee={id:string;full_name:string};type Role={id:string;name:string;department:string|null};type Shift={id:string;employee_id:string|null;role_id:string|null;starts_at:string;ends_at:string;status:string;notes:string|null;source:string|null};
type View='day'|'week'|'month';type Group='time'|'employee'|'role';
const ymd=(d:Date)=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const mondayOf=(date:string)=>addDateDays(date,-((dateDayOfWeek(date)+6)%7));
const localDate=(iso:string)=>ymd(new Date(iso));
const fmtTime=(iso:string)=>new Date(iso).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'});
const fmtDate=(d:string)=>new Date(`${d}T12:00:00`).toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'});

export default function ScheduleViewsPage(){
 const [ready,setReady]=useState(false),[message,setMessage]=useState(''),[employees,setEmployees]=useState<Employee[]>([]),[roles,setRoles]=useState<Role[]>([]),[shifts,setShifts]=useState<Shift[]>([]),[anchor,setAnchor]=useState(businessDateInZone()),[view,setView]=useState<View>('week'),[group,setGroup]=useState<Group>('time'),[department,setDepartment]=useState('all'),[roleId,setRoleId]=useState('all'),[employeeId,setEmployeeId]=useState('all');
 useEffect(()=>{void load()},[]);
 async function load(){const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}const p=await supabase.from('profiles').select('location_id').eq('id',u.user.id).single();if(p.error||!p.data?.location_id){setMessage('Could not load schedule views.');setReady(true);return}const loc=p.data.location_id;const from=new Date();from.setDate(from.getDate()-70);const to=new Date();to.setDate(to.getDate()+120);const [e,r,s]=await Promise.all([supabase.from('employees').select('id,full_name').eq('location_id',loc).is('deleted_at',null).order('full_name'),supabase.from('employee_roles').select('id,name,department').eq('location_id',loc).order('name'),supabase.from('schedule_shifts').select('id,employee_id,role_id,starts_at,ends_at,status,notes,source').eq('location_id',loc).gte('starts_at',from.toISOString()).lt('starts_at',to.toISOString()).neq('status','cancelled').order('starts_at')]);if(s.error)setMessage(s.error.message);setEmployees((e.data??[]) as Employee[]);setRoles((r.data??[]) as Role[]);setShifts((s.data??[]) as Shift[]);setReady(true)}
 const roleMap=useMemo(()=>new Map(roles.map(r=>[r.id,r])),[roles]),empMap=useMemo(()=>new Map(employees.map(e=>[e.id,e])),[employees]);
 const filtered=useMemo(()=>shifts.filter(s=>{const role=roleMap.get(s.role_id||'');return (department==='all'||role?.department===department)&&(roleId==='all'||s.role_id===roleId)&&(employeeId==='all'||s.employee_id===employeeId)}),[shifts,roleMap,department,roleId,employeeId]);
 const visibleDates=useMemo(()=>{if(view==='day')return [anchor];if(view==='week'){const w=mondayOf(anchor);return Array.from({length:7},(_,i)=>addDateDays(w,i))}const a=new Date(`${anchor}T12:00:00`),first=new Date(a.getFullYear(),a.getMonth(),1),last=new Date(a.getFullYear(),a.getMonth()+1,0);return Array.from({length:last.getDate()},(_,i)=>ymd(new Date(a.getFullYear(),a.getMonth(),i+1)))},[anchor,view]);
 const visible=useMemo(()=>filtered.filter(s=>visibleDates.includes(localDate(s.starts_at))),[filtered,visibleDates]);
 const shiftLabel=(s:Shift)=>`${fmtTime(s.starts_at)}–${fmtTime(s.ends_at)} · ${roleMap.get(s.role_id||'')?.name||'Role'} · ${empMap.get(s.employee_id||'')?.full_name||'Open shift'}`;
 function move(delta:number){if(view==='day')setAnchor(addDateDays(anchor,delta));else if(view==='week')setAnchor(addDateDays(anchor,delta*7));else{const a=new Date(`${anchor}T12:00:00`);a.setMonth(a.getMonth()+delta);setAnchor(ymd(a))}}
 const grouped=useMemo(()=>{if(group==='time')return [] as [string,Shift[]][];const map=new Map<string,Shift[]>();for(const s of visible){const key=group==='employee'?(s.employee_id||'open'):(s.role_id||'none');map.set(key,[...(map.get(key)||[]),s])}return [...map.entries()].sort((a,b)=>a[0].localeCompare(b[0]))},[visible,group]);
 if(!ready)return <div className="full-loader"><span>Opening schedule views…</span></div>;
 return <main className={styles.page}><div className={styles.top}><div><h1>Schedule Views</h1><p>Day, week and month views with department, role and employee filters.</p></div><Link className={styles.back} href="/schedule">Back to Schedule</Link></div>{message&&<div className={styles.notice}>{message}</div>}
 <section className={styles.section}><div className={styles.card}><div className={styles.formGrid}><label className={styles.field}><span>View</span><select value={view} onChange={e=>setView(e.target.value as View)}><option value="day">Day</option><option value="week">Week</option><option value="month">Month</option></select></label><label className={styles.field}><span>Layout</span><select value={group} onChange={e=>setGroup(e.target.value as Group)}><option value="time">By date & time</option><option value="employee">Employee board</option><option value="role">Role board</option></select></label><label className={styles.field}><span>Department</span><select value={department} onChange={e=>setDepartment(e.target.value)}><option value="all">All</option><option value="foh">FOH</option><option value="boh">BOH</option><option value="management">Management</option><option value="other">Other</option></select></label><label className={styles.field}><span>Role</span><select value={roleId} onChange={e=>setRoleId(e.target.value)}><option value="all">All roles</option>{roles.filter(r=>department==='all'||r.department===department).map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label><label className={styles.field}><span>Employee</span><select value={employeeId} onChange={e=>setEmployeeId(e.target.value)}><option value="all">All employees</option><option value="open">Open shifts only</option>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select></label></div><div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} onClick={()=>move(-1)}>Previous</button><button className={`${styles.button} ${styles.secondary}`} onClick={()=>setAnchor(businessDateInZone())}>Today</button><button className={`${styles.button} ${styles.secondary}`} onClick={()=>move(1)}>Next</button><span className={styles.pill}>{visible.length} shifts</span></div></div></section>
 {group==='time'?<section className={styles.section}><div style={{display:'grid',gridTemplateColumns:view==='month'?'repeat(auto-fit,minmax(140px,1fr))':'1fr',gap:10}}>{visibleDates.map(date=>{const ds=visible.filter(s=>localDate(s.starts_at)===date);return <div className={styles.card} key={date}><div className={styles.entryHead}><h3>{fmtDate(date)}</h3><span className={styles.pill}>{ds.length}</span></div><div className={styles.list}>{ds.map(s=><div className={styles.entry} key={s.id}><b>{fmtTime(s.starts_at)}–{fmtTime(s.ends_at)}</b><small>{roleMap.get(s.role_id||'')?.name||'Role'} · {empMap.get(s.employee_id||'')?.full_name||'Open shift'} · {s.status}</small>{s.notes&&<small>{s.notes}</small>}</div>)}{!ds.length&&<small className={styles.muted}>No shifts</small>}</div></div>})}</div></section>:<section className={styles.section}><div className={styles.list}>{grouped.map(([key,rows])=><div className={styles.card} key={key}><div className={styles.entryHead}><h2>{group==='employee'?(key==='open'?'Open shifts':empMap.get(key)?.full_name||'Employee'):roleMap.get(key)?.name||'Role'}</h2><span className={styles.pill}>{rows.length} shifts</span></div><div className={styles.list}>{rows.sort((a,b)=>a.starts_at.localeCompare(b.starts_at)).map(s=><div className={styles.entry} key={s.id}><b>{fmtDate(localDate(s.starts_at))} · {shiftLabel(s)}</b><small>{s.status}{s.notes?` · ${s.notes}`:''}</small></div>)}</div></div>)}</div></section>}
 </main>
}
