'use client';

import {FormEvent,useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase';
import styles from '../ops-tools.module.css';

type Job={id:string;title:string;description:string;employment_type:string;min_hourly_rate:number|null;max_hourly_rate:number|null;role_name:string|null;location_name:string;published_at:string|null;closes_at:string|null};
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n)||0);
const pretty=(s:string)=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());

export default function CareersPage(){
 const [jobs,setJobs]=useState<Job[]>([]),[jobId,setJobId]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[submitted,setSubmitted]=useState(false),[form,setForm]=useState({full_name:'',email:'',phone:'',availability:'',work_experience:'',why_interested:'',authorized_to_work:false,consent:false,company_website:''});
 useEffect(()=>{void load()},[]);
 async function load(){const {data,error}=await supabase.rpc('public_job_postings',{});if(error)setMessage('Open positions could not be loaded right now.');else{const rows=Array.isArray(data)?data:(data||[]) as Job[];setJobs(rows as Job[]);if(rows[0])setJobId(rows[0].id)}setLoading(false)}
 async function apply(e:FormEvent){e.preventDefault();if(busy||!jobId||!form.full_name.trim()||!form.email.trim()||!form.consent)return;setBusy(true);const {data,error}=await supabase.rpc('submit_job_application',{p_job_posting_id:jobId,p_full_name:form.full_name.trim(),p_email:form.email.trim(),p_phone:form.phone.trim()||null,p_availability:{notes:form.availability.trim()},p_work_experience:form.work_experience.trim()||null,p_why_interested:form.why_interested.trim()||null,p_authorized_to_work:form.authorized_to_work,p_consent:form.consent,p_company_website:form.company_website||null});if(error){setMessage(error.message);setBusy(false);return}setSubmitted(Boolean((data as any)?.ok));setMessage('Application received. Thank you for your interest in El Molino.');setBusy(false)}
 if(loading)return <main className={styles.page}>Loading open positions…</main>;
 return <main className={styles.page}><div className={styles.top}><div><h1>Careers at El Molino</h1><p>Join our restaurant team. Review an open position and apply below.</p></div></div>{message&&<div className={message.toLowerCase().includes('could not')||message.toLowerCase().includes('exists')?styles.error:styles.notice}>{message}</div>}
  <section className={styles.section}><h2>Open positions</h2><div className={styles.list}>{jobs.map(j=><button key={j.id} className={`${styles.entry} ${jobId===j.id?styles.card:''}`} onClick={()=>setJobId(j.id)} style={{textAlign:'left',width:'100%'}}><div className={styles.entryHead}><div><h3>{j.title}</h3><small>{j.location_name} · {pretty(j.employment_type)}{j.role_name?` · ${j.role_name}`:''}</small></div>{j.min_hourly_rate!==null&&<span className={styles.pill}>{j.max_hourly_rate!==null&&j.max_hourly_rate!==j.min_hourly_rate?`${money(j.min_hourly_rate)}–${money(j.max_hourly_rate)}/hr`:`${money(j.min_hourly_rate)}/hr`}</span>}</div><p style={{whiteSpace:'pre-wrap'}}>{j.description}</p></button>)}{!jobs.length&&<div className={styles.empty}>There are no open positions right now.</div>}</div></section>
  {jobs.length>0&&!submitted&&<section className={styles.section}><div className={styles.card}><h2>Apply</h2><form onSubmit={apply}><div className={styles.formGrid}><Field label="Position"><select value={jobId} onChange={e=>setJobId(e.target.value)}>{jobs.map(j=><option key={j.id} value={j.id}>{j.title} · {j.location_name}</option>)}</select></Field><Field label="Full name"><input maxLength={160} autoComplete="name" value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})} required/></Field><Field label="Email"><input type="email" maxLength={320} autoComplete="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/></Field><Field label="Phone"><input type="tel" maxLength={80} autoComplete="tel" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><Field label="Availability" wide><textarea maxLength={4000} placeholder="Days/times you are generally available" value={form.availability} onChange={e=>setForm({...form,availability:e.target.value})}/></Field><Field label="Work experience" wide><textarea maxLength={20000} value={form.work_experience} onChange={e=>setForm({...form,work_experience:e.target.value})}/></Field><Field label="Why are you interested?" wide><textarea maxLength={10000} value={form.why_interested} onChange={e=>setForm({...form,why_interested:e.target.value})}/></Field><label className={styles.checkbox}><input type="checkbox" checked={form.authorized_to_work} onChange={e=>setForm({...form,authorized_to_work:e.target.checked})}/>I am authorized to work in the United States.</label><label className={styles.checkbox}><input type="checkbox" required checked={form.consent} onChange={e=>setForm({...form,consent:e.target.checked})}/>I consent to El Molino using this information to evaluate my application.</label><input tabIndex={-1} autoComplete="off" aria-hidden="true" style={{position:'absolute',left:'-10000px'}} value={form.company_website} onChange={e=>setForm({...form,company_website:e.target.value})}/></div><div className={styles.actions}><button className={styles.button} disabled={busy||!form.consent}>Submit application</button></div></form></div></section>}
 </main>
}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={`${styles.field} ${wide?styles.wide:''}`}><span>{label}</span>{children}</label>}
