'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { supabase } from '@/lib/supabase';
import styles from '../ops-tools.module.css';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Employee={id:string;full_name:string;user_id:string|null;active:boolean};
type Role={id:string;name:string};
type Shift={id:string;employee_id:string|null;role_id:string|null;starts_at:string;ends_at:string;break_minutes:number;status:string;notes:string|null};
type TimeOff={id:string;employee_id:string;starts_on:string;ends_on:string;reason:string|null;status:string;created_at:string};
type ChangeReq={id:string;shift_id:string;request_type:string;requested_by_employee_id:string|null;reason:string|null;status:string;created_at:string};
type Perf={business_date:string;labor_hours:number};
const dtLocal=(d=new Date())=>{const z=new Date(d.getTime()-d.getTimezoneOffset()*60000);return z.toISOString().slice(0,16)};
const addDays=(d:Date,n:number)=>new Date(d.getTime()+n*86400000);
const ymd=(d:Date)=>d.toISOString().slice(0,10);
const hrs=(s:Shift)=>Math.max(0,(new Date(s.ends_at).getTime()-new Date(s.starts_at).getTime())/3600000-(Number(s.break_minutes)||0)/60);

export default function SchedulePage(){
  const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[profile,setProfile]=useState<Profile|null>(null),[employees,setEmployees]=useState<Employee[]>([]),[roles,setRoles]=useState<Role[]>([]),[shifts,setShifts]=useState<Shift[]>([]),[timeOff,setTimeOff]=useState<TimeOff[]>([]),[changes,setChanges]=useState<ChangeReq[]>([]),[perf,setPerf]=useState<Perf[]>([]),[me,setMe]=useState<Employee|null>(null),[message,setMessage]=useState('');
  const startDefault=dtLocal(addDays(new Date(),1)),endDefault=dtLocal(new Date(addDays(new Date(),1).getTime()+8*3600000));
  const [shiftForm,setShiftForm]=useState({employee_id:'',role_id:'',starts_at:startDefault,ends_at:endDefault,break_minutes:'0',notes:''});
  const [offForm,setOffForm]=useState({starts_on:ymd(addDays(new Date(),7)),ends_on:ymd(addDays(new Date(),7)),reason:''});
  const canManage=profile?.app_role==='admin'||profile?.app_role==='manager';
  useEffect(()=>{void init()},[]);
  async function init(){const {data:u}=await supabase.auth.getUser();if(!u.user){window.location.href='/';return;}const {data:p}=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();setProfile((p||null) as Profile|null);if(p?.location_id)await load(p.location_id,u.user.id);setReady(true);}
  async function load(locationId=profile?.location_id||'',userId?:string){if(!locationId)return;const from=addDays(new Date(),-7).toISOString(),to=addDays(new Date(),28).toISOString(),fromDay=ymd(addDays(new Date(),-7)),toDay=ymd(addDays(new Date(),28));const [e,r,s,o,c,p]=await Promise.all([
    supabase.from('employees').select('id,full_name,user_id,active').eq('location_id',locationId).is('deleted_at',null).eq('active',true).order('full_name'),
    supabase.from('employee_roles').select('id,name').order('name'),
    supabase.from('schedule_shifts').select('id,employee_id,role_id,starts_at,ends_at,break_minutes,status,notes').eq('location_id',locationId).gte('starts_at',from).lt('starts_at',to).order('starts_at'),
    supabase.from('time_off_requests').select('id,employee_id,starts_on,ends_on,reason,status,created_at').eq('location_id',locationId).gte('ends_on',fromDay).lte('starts_on',toDay).order('created_at',{ascending:false}),
    supabase.from('shift_change_requests').select('id,shift_id,request_type,requested_by_employee_id,reason,status,created_at').eq('location_id',locationId).order('created_at',{ascending:false}).limit(60),
    supabase.from('restaurant_daily_performance').select('business_date,labor_hours').eq('location_id',locationId).gte('business_date',fromDay).lte('business_date',toDay)
  ]);const emp=(e.data??[]) as Employee[];setEmployees(emp);setRoles((r.data??[]) as Role[]);setShifts((s.data??[]) as Shift[]);setTimeOff((o.data??[]) as TimeOff[]);setChanges((c.data??[]) as ChangeReq[]);setPerf((p.data??[]) as Perf[]);const uid=userId||(await supabase.auth.getUser()).data.user?.id;setMe(emp.find(x=>x.user_id===uid)||null);if(e.error||r.error||s.error||o.error||c.error||p.error)setMessage('Some schedule data could not be loaded.');}
  const week=useMemo(()=>{const now=new Date();const day=now.getDay();const monday=new Date(now);monday.setHours(0,0,0,0);monday.setDate(now.getDate()-((day+6)%7));const end=addDays(monday,7);const list=shifts.filter(s=>new Date(s.starts_at)>=monday&&new Date(s.starts_at)<end&&s.status!=='cancelled');const scheduled=list.reduce((n,s)=>n+hrs(s),0);const actual=perf.filter(p=>p.business_date>=ymd(monday)&&p.business_date<ymd(end)).reduce((n,p)=>n+Number(p.labor_hours||0),0);return {scheduled,actual,monday,end};},[shifts,perf]);
  async function createShift(e:FormEvent){e.preventDefault();if(!canManage||!profile?.location_id||busy)return;const st=new Date(shiftForm.starts_at),en=new Date(shiftForm.ends_at);if(!Number.isFinite(st.getTime())||!Number.isFinite(en.getTime())||en<=st){setMessage('Choose a valid shift start and end.');return;}setBusy(true);try{const {data:u}=await supabase.auth.getUser();const {error}=await supabase.from('schedule_shifts').insert({location_id:profile.location_id,employee_id:shiftForm.employee_id||null,role_id:shiftForm.role_id||null,starts_at:st.toISOString(),ends_at:en.toISOString(),break_minutes:Math.max(0,Math.min(480,Number(shiftForm.break_minutes)||0)),status:shiftForm.employee_id?'scheduled':'open',notes:shiftForm.notes.trim().slice(0,2000)||null,created_by:u.user?.id||null,updated_by:u.user?.id||null});if(error)throw error;setMessage('Shift added.');await load();}catch{setMessage('Could not add that shift.');}finally{setBusy(false)}}
  async function requestTimeOff(e:FormEvent){e.preventDefault();if(!me||!profile?.location_id||busy)return;if(offForm.ends_on<offForm.starts_on){setMessage('Time-off end date cannot be before the start date.');return;}setBusy(true);try{const {error}=await supabase.from('time_off_requests').insert({location_id:profile.location_id,employee_id:me.id,starts_on:offForm.starts_on,ends_on:offForm.ends_on,reason:offForm.reason.trim().slice(0,2000)||null});if(error)throw error;setOffForm({...offForm,reason:''});setMessage('Time-off request submitted.');await load();}catch{setMessage('Could not submit time off.');}finally{setBusy(false)}}
  async function callOut(shift:Shift){if(!me||shift.employee_id!==me.id||busy||!profile?.location_id)return;const reason=prompt('Call-out reason (optional)')||'';setBusy(true);try{const {error}=await supabase.from('shift_change_requests').insert({location_id:profile.location_id,shift_id:shift.id,request_type:'callout',requested_by_employee_id:me.id,reason:reason.trim().slice(0,2000)||null});if(error)throw error;setMessage('Call-out sent to management for review.');await load();}catch{setMessage('Could not submit the call-out.');}finally{setBusy(false)}}
  async function reviewTimeOff(req:TimeOff,status:'approved'|'denied'){if(!canManage||busy)return;setBusy(true);try{const {data:u}=await supabase.auth.getUser();const {error}=await supabase.from('time_off_requests').update({status,reviewed_by:u.user?.id||null,reviewed_at:new Date().toISOString()}).eq('id',req.id).eq('status','pending');if(error)throw error;await load();setMessage(`Time off ${status}.`);}catch{setMessage('Could not review time off.');}finally{setBusy(false)}}
  async function reviewChange(req:ChangeReq,status:'approved'|'denied'){if(!canManage||busy)return;setBusy(true);try{const {data:u}=await supabase.auth.getUser();const a=await supabase.from('shift_change_requests').update({status,reviewed_by:u.user?.id||null,reviewed_at:new Date().toISOString()}).eq('id',req.id).eq('status','pending');if(a.error)throw a.error;if(status==='approved'&&req.request_type==='callout'){const b=await supabase.from('schedule_shifts').update({status:'open',employee_id:null}).eq('id',req.shift_id);if(b.error)throw b.error;}await load();setMessage(`Shift request ${status}.`);}catch{setMessage('Could not review that shift request.');}finally{setBusy(false)}}
  const empName=(id:string|null)=>employees.find(e=>e.id===id)?.full_name||(id?'Unknown':'Open shift'),roleName=(id:string|null)=>roles.find(r=>r.id===id)?.name||'';
  if(!ready)return <main className={styles.page}>Loading schedule…</main>;
  if(!profile?.location_id)return <main className={styles.page}>No restaurant location is assigned to this account.</main>;
  return <main className={styles.page}>
    <div className={styles.top}><div><h1>Schedule</h1><p>Shifts, time off, call-outs and coverage.</p></div><Link className={styles.back} href="/">Back to Ops</Link></div>
    {message&&<div className={message.startsWith('Could not')||message.startsWith('Some')?styles.error:styles.notice}>{message}</div>}
    <div className={styles.grid}><Metric label="Scheduled hours this week" value={week.scheduled.toFixed(1)}/><Metric label="Actual labor hours entered" value={week.actual.toFixed(1)}/><Metric label="Open shifts" value={String(shifts.filter(s=>s.status==='open').length)}/><Metric label="Pending requests" value={String(timeOff.filter(x=>x.status==='pending').length+changes.filter(x=>x.status==='pending').length)}/></div>
    {canManage&&<section className={styles.section}><div className={styles.card}><h2>Add shift</h2><form onSubmit={createShift}><div className={styles.formGrid}><Field label="Employee"><select value={shiftForm.employee_id} onChange={e=>setShiftForm({...shiftForm,employee_id:e.target.value})}><option value="">Open shift</option>{employees.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></Field><Field label="Role"><select value={shiftForm.role_id} onChange={e=>setShiftForm({...shiftForm,role_id:e.target.value})}><option value="">No role</option>{roles.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="Start"><input type="datetime-local" value={shiftForm.starts_at} onChange={e=>setShiftForm({...shiftForm,starts_at:e.target.value})}/></Field><Field label="End"><input type="datetime-local" value={shiftForm.ends_at} onChange={e=>setShiftForm({...shiftForm,ends_at:e.target.value})}/></Field><Field label="Unpaid break minutes"><input type="number" min="0" max="480" value={shiftForm.break_minutes} onChange={e=>setShiftForm({...shiftForm,break_minutes:e.target.value})}/></Field><Field label="Notes"><input maxLength={2000} value={shiftForm.notes} onChange={e=>setShiftForm({...shiftForm,notes:e.target.value})}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy}>Add shift</button></div></form></div></section>}
    {me&&<section className={styles.section}><div className={styles.card}><h2>Request time off</h2><form onSubmit={requestTimeOff}><div className={styles.formGrid}><Field label="First day"><input type="date" value={offForm.starts_on} onChange={e=>setOffForm({...offForm,starts_on:e.target.value})}/></Field><Field label="Last day"><input type="date" value={offForm.ends_on} onChange={e=>setOffForm({...offForm,ends_on:e.target.value})}/></Field><Field label="Reason" wide><input maxLength={2000} value={offForm.reason} onChange={e=>setOffForm({...offForm,reason:e.target.value})}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy}>Submit request</button></div></form></div></section>}
    <section className={styles.section}><h2>Upcoming shifts</h2><div className={styles.list}>{shifts.filter(s=>new Date(s.ends_at)>new Date()).slice(0,80).map(s=><div className={styles.entry} key={s.id}><div className={styles.entryHead}><div><h3>{empName(s.employee_id)} {roleName(s.role_id)&&`· ${roleName(s.role_id)}`}</h3><small>{new Date(s.starts_at).toLocaleString()} – {new Date(s.ends_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})} · {hrs(s).toFixed(1)} hrs</small></div><span className={styles.pill}>{s.status}</span></div>{s.notes&&<div className={styles.details}>{detail('Notes',s.notes)}</div>}{me&&s.employee_id===me.id&&s.status==='scheduled'&&!changes.some(c=>c.shift_id===s.id&&c.status==='pending')&&<div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>callOut(s)}>Call out / request coverage</button></div>}</div>)}</div></section>
    {canManage&&<section className={styles.section}><h2>Manager approval queue</h2><div className={styles.list}>{timeOff.filter(x=>x.status==='pending').map(x=><div className={styles.entry} key={x.id}><div className={styles.entryHead}><div><h3>Time off · {empName(x.employee_id)}</h3><small>{x.starts_on} through {x.ends_on}</small></div><span className={styles.pill}>pending</span></div>{x.reason&&<div className={styles.details}>{detail('Reason',x.reason)}</div>}<div className={styles.actions}><button className={styles.button} disabled={busy} onClick={()=>reviewTimeOff(x,'approved')}>Approve</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>reviewTimeOff(x,'denied')}>Deny</button></div></div>)}{changes.filter(x=>x.status==='pending').map(x=><div className={styles.entry} key={x.id}><div className={styles.entryHead}><div><h3>{x.request_type} · {empName(x.requested_by_employee_id)}</h3><small>{shifts.find(s=>s.id===x.shift_id)?new Date(shifts.find(s=>s.id===x.shift_id)!.starts_at).toLocaleString():'Shift'}</small></div><span className={styles.pill}>pending</span></div>{x.reason&&<div className={styles.details}>{detail('Reason',x.reason)}</div>}<div className={styles.actions}><button className={styles.button} disabled={busy} onClick={()=>reviewChange(x,'approved')}>Approve</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>reviewChange(x,'denied')}>Deny</button></div></div>)}</div></section>}
  </main>;
}
function Metric({label,value}:{label:string;value:string}){return <div className={styles.metric}><span>{label}</span><strong>{value}</strong></div>}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={`${styles.field} ${wide?styles.wide:''}`}><span>{label}</span>{children}</label>}
function detail(label:string,value:string){return <div className={styles.detail}><b>{label}</b><span>{value}</span></div>}
