'use client';

import {FormEvent,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase';
import {useI18n} from '@/lib/i18n';
import styles from '../../ops-tools.module.css';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};type Employee={id:string;full_name:string;user_id:string|null};type Role={id:string;name:string};type Shift={id:string;employee_id:string|null;role_id:string|null;starts_at:string;ends_at:string;status:string};type Feedback={id:string;shift_id:string;employee_id:string;overall_rating:number;workload_rating:number|null;staffing_rating:number|null;comment:string|null;manager_reviewed:boolean;manager_note:string|null;created_at:string};
export default function ScheduleFeedbackPage(){
 const {locale}=useI18n();const localeCode=locale==='es'?'es-US':'en-US',fmt=(iso:string)=>new Date(iso).toLocaleString(localeCode,{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});const c=locale==='es'?{load:'No se pudieron cargar los comentarios de turnos.',saved:'Comentarios del turno guardados.',reviewPrompt:'Nota opcional de gerencia:',reviewed:'Comentarios marcados como revisados.',opening:'Abriendo comentarios de turnos…',title:'Comentarios de Turnos',body:'Registra cómo se sintieron realmente los turnos completados para que las decisiones de personal tengan evidencia.',back:'Volver al Horario',rate:'Calificar un turno completado',shift:'Turno',choose:'Elegir turno reciente',overall:'Turno en general',workload:'Carga de trabajo manejable',staffing:'Nivel de personal',know:'¿Qué debe saber la gerencia?',save:'Guardar Comentarios',responses:'Respuestas',managerReview:'Revisión de gerencia',shiftFallback:'Turno',overallSmall:'general',workloadSmall:'carga',staffingSmall:'personal',reviewedLabel:'revisado',newLabel:'nuevo',employeeNote:'Nota del empleado',managerNote:'Nota de gerencia',mark:'Marcar Revisado',none:'Aún no hay comentarios de turnos completados.',ratings:['','Muy malo','Malo','Aceptable','Bueno','Excelente']}:{load:'Could not load shift feedback.',saved:'Shift feedback saved.',reviewPrompt:'Optional manager note:',reviewed:'Feedback marked reviewed.',opening:'Opening shift feedback…',title:'Shift Feedback',body:'Capture how completed shifts actually felt so staffing decisions have evidence behind them.',back:'Back to Schedule',rate:'Rate a completed shift',shift:'Shift',choose:'Choose recent shift',overall:'Overall shift',workload:'Workload manageability',staffing:'Staffing level',know:'What should management know?',save:'Save Feedback',responses:'Responses',managerReview:'Manager review',shiftFallback:'Shift',overallSmall:'overall',workloadSmall:'workload',staffingSmall:'staffing',reviewedLabel:'reviewed',newLabel:'new',employeeNote:'Employee note',managerNote:'Manager note',mark:'Mark Reviewed',none:'No completed-shift feedback yet.',ratings:['','Very poor','Poor','Okay','Good','Excellent']};
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[profile,setProfile]=useState<Profile|null>(null),[me,setMe]=useState<Employee|null>(null),[employees,setEmployees]=useState<Employee[]>([]),[roles,setRoles]=useState<Role[]>([]),[shifts,setShifts]=useState<Shift[]>([]),[feedback,setFeedback]=useState<Feedback[]>([]),[selected,setSelected]=useState(''),[form,setForm]=useState({overall:5,workload:3,staffing:3,comment:''});
 const canManage=profile?.app_role==='admin'||profile?.app_role==='manager';
 useEffect(()=>{void load()},[]);
 async function load(){setBusy(true);const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}const p=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();if(p.error||!p.data?.location_id){setMessage(c.load);setReady(true);setBusy(false);return}const pr=p.data as Profile;setProfile(pr);const loc=pr.location_id!;const since=new Date(Date.now()-60*86400000).toISOString();const [e,r,s,f]=await Promise.all([supabase.from('employees').select('id,full_name,user_id').eq('location_id',loc).is('deleted_at',null).order('full_name'),supabase.from('employee_roles').select('id,name').eq('location_id',loc).order('name'),supabase.from('schedule_shifts').select('id,employee_id,role_id,starts_at,ends_at,status').eq('location_id',loc).gte('ends_at',since).lte('ends_at',new Date().toISOString()).neq('status','callout').order('ends_at',{ascending:false}).limit(500),supabase.from('schedule_shift_feedback').select('id,shift_id,employee_id,overall_rating,workload_rating,staffing_rating,comment,manager_reviewed,manager_note,created_at').eq('location_id',loc).order('created_at',{ascending:false}).limit(500)]);const es=(e.data??[]) as Employee[];setEmployees(es);setMe(es.find(x=>x.user_id===u.user.id)||null);setRoles((r.data??[]) as Role[]);setShifts((s.data??[]) as Shift[]);setFeedback((f.data??[]) as Feedback[]);setReady(true);setBusy(false)}
 const emp=(id:string|null)=>employees.find(x=>x.id===id)?.full_name||c.employeeNote.replace(' note',''),role=(id:string|null)=>roles.find(x=>x.id===id)?.name||c.shiftFallback,shift=(id:string)=>shifts.find(x=>x.id===id);
 const myEligible=useMemo(()=>shifts.filter(s=>s.employee_id===me?.id&&new Date(s.ends_at)>new Date(Date.now()-14*86400000)),[shifts,me]);const avg=(key:'overall_rating'|'workload_rating'|'staffing_rating')=>{const xs=feedback.map(x=>x[key]).filter((x):x is number=>typeof x==='number');return xs.length?(xs.reduce((a,b)=>a+b,0)/xs.length).toFixed(1):'—'};
 async function submit(e:FormEvent){e.preventDefault();if(!selected||busy)return;setBusy(true);const {error}=await supabase.rpc('submit_shift_feedback',{p_shift_id:selected,p_overall_rating:form.overall,p_workload_rating:form.workload,p_staffing_rating:form.staffing,p_comment:form.comment.trim()||null});setMessage(error?error.message:c.saved);if(!error)setForm({overall:5,workload:3,staffing:3,comment:''});await load();setBusy(false)}
 async function review(id:string){if(!canManage||busy)return;const note=prompt(c.reviewPrompt)||null;setBusy(true);const {error}=await supabase.rpc('review_shift_feedback',{p_feedback_id:id,p_manager_note:note});setMessage(error?error.message:c.reviewed);await load();setBusy(false)}
 if(!ready)return <div className="full-loader"><span>{c.opening}</span></div>;
 return <main className={styles.page}><div className={styles.top}><div><h1>{c.title}</h1><p>{c.body}</p></div><Link className={styles.back} href="/schedule">{c.back}</Link></div>{message&&<div className={styles.notice}>{message}</div>}
 {me&&<section className={styles.section}><div className={styles.card}><h2>{c.rate}</h2><form onSubmit={submit}><div className={styles.formGrid}><label className={`${styles.field} ${styles.wide}`}><span>{c.shift}</span><select value={selected} onChange={e=>{setSelected(e.target.value);const existing=feedback.find(f=>f.shift_id===e.target.value&&f.employee_id===me.id);if(existing)setForm({overall:existing.overall_rating,workload:existing.workload_rating??3,staffing:existing.staffing_rating??3,comment:existing.comment||''})}}><option value="">{c.choose}</option>{myEligible.map(s=><option key={s.id} value={s.id}>{fmt(s.starts_at)} · {role(s.role_id)}</option>)}</select></label><Rating label={c.overall} value={form.overall} onChange={v=>setForm({...form,overall:v})} labels={c.ratings}/><Rating label={c.workload} value={form.workload} onChange={v=>setForm({...form,workload:v})} labels={c.ratings}/><Rating label={c.staffing} value={form.staffing} onChange={v=>setForm({...form,staffing:v})} labels={c.ratings}/><label className={`${styles.field} ${styles.wide}`}><span>{c.know}</span><textarea maxLength={3000} value={form.comment} onChange={e=>setForm({...form,comment:e.target.value})}/></label></div><div className={styles.actions}><button className={styles.button} disabled={busy||!selected}>{c.save}</button></div></form></div></section>}
 {canManage&&<><section className={styles.section}><div className={styles.grid}><Metric label={c.responses} value={String(feedback.length)}/><Metric label={c.overall} value={avg('overall_rating')}/><Metric label={c.workload} value={avg('workload_rating')}/><Metric label={c.staffing} value={avg('staffing_rating')}/></div></section><section className={styles.section}><h2>{c.managerReview}</h2><div className={styles.list}>{feedback.map(f=>{const s=shift(f.shift_id);return <div className={styles.entry} key={f.id}><div className={styles.entryHead}><div><h3>{emp(f.employee_id)} · {s?role(s.role_id):c.shiftFallback}</h3><small>{s?fmt(s.starts_at):new Date(f.created_at).toLocaleString(localeCode)} · {c.overallSmall} {f.overall_rating}/5 · {c.workloadSmall} {f.workload_rating??'—'}/5 · {c.staffingSmall} {f.staffing_rating??'—'}/5</small></div><span className={styles.pill}>{f.manager_reviewed?c.reviewedLabel:c.newLabel}</span></div>{f.comment&&<div className={styles.details}><div className={styles.detail}><b>{c.employeeNote}</b><span>{f.comment}</span></div>{f.manager_note&&<div className={styles.detail}><b>{c.managerNote}</b><span>{f.manager_note}</span></div>}</div>}{!f.manager_reviewed&&<div className={styles.actions}><button className={styles.button} disabled={busy} onClick={()=>review(f.id)}>{c.mark}</button></div>}</div>})}{!feedback.length&&<div className={styles.empty}>{c.none}</div>}</div></section></>}
 </main>
}
function Rating({label,value,onChange,labels}:{label:string;value:number;onChange:(v:number)=>void;labels:string[]}){return <label className={styles.field}><span>{label}</span><select value={value} onChange={e=>onChange(Number(e.target.value))}>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} — {labels[n]}</option>)}</select></label>}
function Metric({label,value}:{label:string;value:string}){return <div className={styles.metric}><span>{label}</span><strong>{value}</strong></div>}
