'use client';

import {FormEvent,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase';
import styles from '../../ops-tools.module.css';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};type Employee={id:string;full_name:string;user_id:string|null};type Role={id:string;name:string};type Shift={id:string;employee_id:string|null;role_id:string|null;starts_at:string;ends_at:string;status:string};type Feedback={id:string;shift_id:string;employee_id:string;overall_rating:number;workload_rating:number|null;staffing_rating:number|null;comment:string|null;manager_reviewed:boolean;manager_note:string|null;created_at:string};
const fmt=(iso:string)=>new Date(iso).toLocaleString([],{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
export default function ScheduleFeedbackPage(){
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[profile,setProfile]=useState<Profile|null>(null),[me,setMe]=useState<Employee|null>(null),[employees,setEmployees]=useState<Employee[]>([]),[roles,setRoles]=useState<Role[]>([]),[shifts,setShifts]=useState<Shift[]>([]),[feedback,setFeedback]=useState<Feedback[]>([]),[selected,setSelected]=useState(''),[form,setForm]=useState({overall:5,workload:3,staffing:3,comment:''});
 const canManage=profile?.app_role==='admin'||profile?.app_role==='manager';
 useEffect(()=>{void load()},[]);
 async function load(){setBusy(true);const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}const p=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();if(p.error||!p.data?.location_id){setMessage('Could not load shift feedback.');setReady(true);setBusy(false);return}const pr=p.data as Profile;setProfile(pr);const loc=pr.location_id!;const since=new Date(Date.now()-60*86400000).toISOString();const [e,r,s,f]=await Promise.all([supabase.from('employees').select('id,full_name,user_id').eq('location_id',loc).is('deleted_at',null).order('full_name'),supabase.from('employee_roles').select('id,name').eq('location_id',loc).order('name'),supabase.from('schedule_shifts').select('id,employee_id,role_id,starts_at,ends_at,status').eq('location_id',loc).gte('ends_at',since).lte('ends_at',new Date().toISOString()).neq('status','callout').order('ends_at',{ascending:false}).limit(500),supabase.from('schedule_shift_feedback').select('id,shift_id,employee_id,overall_rating,workload_rating,staffing_rating,comment,manager_reviewed,manager_note,created_at').eq('location_id',loc).order('created_at',{ascending:false}).limit(500)]);const es=(e.data??[]) as Employee[];setEmployees(es);setMe(es.find(x=>x.user_id===u.user.id)||null);setRoles((r.data??[]) as Role[]);setShifts((s.data??[]) as Shift[]);setFeedback((f.data??[]) as Feedback[]);setReady(true);setBusy(false)}
 const emp=(id:string|null)=>employees.find(x=>x.id===id)?.full_name||'Employee',role=(id:string|null)=>roles.find(x=>x.id===id)?.name||'Shift';const shift=(id:string)=>shifts.find(x=>x.id===id);
 const myEligible=useMemo(()=>shifts.filter(s=>s.employee_id===me?.id&&new Date(s.ends_at)>new Date(Date.now()-14*86400000)),[shifts,me]);const avg=(key:'overall_rating'|'workload_rating'|'staffing_rating')=>{const xs=feedback.map(x=>x[key]).filter((x):x is number=>typeof x==='number');return xs.length?(xs.reduce((a,b)=>a+b,0)/xs.length).toFixed(1):'—'};
 async function submit(e:FormEvent){e.preventDefault();if(!selected||busy)return;setBusy(true);const {error}=await supabase.rpc('submit_shift_feedback',{p_shift_id:selected,p_overall_rating:form.overall,p_workload_rating:form.workload,p_staffing_rating:form.staffing,p_comment:form.comment.trim()||null});setMessage(error?error.message:'Shift feedback saved.');if(!error)setForm({overall:5,workload:3,staffing:3,comment:''});await load();setBusy(false)}
 async function review(id:string){if(!canManage||busy)return;const note=prompt('Optional manager note:')||null;setBusy(true);const {error}=await supabase.rpc('review_shift_feedback',{p_feedback_id:id,p_manager_note:note});setMessage(error?error.message:'Feedback marked reviewed.');await load();setBusy(false)}
 if(!ready)return <div className="full-loader"><span>Opening shift feedback…</span></div>;
 return <main className={styles.page}><div className={styles.top}><div><h1>Shift Feedback</h1><p>Capture how completed shifts actually felt so staffing decisions have evidence behind them.</p></div><Link className={styles.back} href="/schedule">Back to Schedule</Link></div>{message&&<div className={styles.notice}>{message}</div>}
 {me&&<section className={styles.section}><div className={styles.card}><h2>Rate a completed shift</h2><form onSubmit={submit}><div className={styles.formGrid}><label className={`${styles.field} ${styles.wide}`}><span>Shift</span><select value={selected} onChange={e=>{setSelected(e.target.value);const existing=feedback.find(f=>f.shift_id===e.target.value&&f.employee_id===me.id);if(existing)setForm({overall:existing.overall_rating,workload:existing.workload_rating??3,staffing:existing.staffing_rating??3,comment:existing.comment||''})}}><option value="">Choose recent shift</option>{myEligible.map(s=><option key={s.id} value={s.id}>{fmt(s.starts_at)} · {role(s.role_id)}</option>)}</select></label><Rating label="Overall shift" value={form.overall} onChange={v=>setForm({...form,overall:v})}/><Rating label="Workload manageability" value={form.workload} onChange={v=>setForm({...form,workload:v})}/><Rating label="Staffing level" value={form.staffing} onChange={v=>setForm({...form,staffing:v})}/><label className={`${styles.field} ${styles.wide}`}><span>What should management know?</span><textarea maxLength={3000} value={form.comment} onChange={e=>setForm({...form,comment:e.target.value})}/></label></div><div className={styles.actions}><button className={styles.button} disabled={busy||!selected}>Save Feedback</button></div></form></div></section>}
 {canManage&&<><section className={styles.section}><div className={styles.grid}><Metric label="Responses" value={String(feedback.length)}/><Metric label="Overall" value={avg('overall_rating')}/><Metric label="Workload" value={avg('workload_rating')}/><Metric label="Staffing" value={avg('staffing_rating')}/></div></section><section className={styles.section}><h2>Manager review</h2><div className={styles.list}>{feedback.map(f=>{const s=shift(f.shift_id);return <div className={styles.entry} key={f.id}><div className={styles.entryHead}><div><h3>{emp(f.employee_id)} · {s?role(s.role_id):'Shift'}</h3><small>{s?fmt(s.starts_at):f.created_at} · overall {f.overall_rating}/5 · workload {f.workload_rating??'—'}/5 · staffing {f.staffing_rating??'—'}/5</small></div><span className={styles.pill}>{f.manager_reviewed?'reviewed':'new'}</span></div>{f.comment&&<div className={styles.details}><div className={styles.detail}><b>Employee note</b><span>{f.comment}</span></div>{f.manager_note&&<div className={styles.detail}><b>Manager note</b><span>{f.manager_note}</span></div>}</div>}{!f.manager_reviewed&&<div className={styles.actions}><button className={styles.button} disabled={busy} onClick={()=>review(f.id)}>Mark Reviewed</button></div>}</div>})}{!feedback.length&&<div className={styles.empty}>No completed-shift feedback yet.</div>}</div></section></>}
 </main>
}
function Rating({label,value,onChange}:{label:string;value:number;onChange:(v:number)=>void}){return <label className={styles.field}><span>{label}</span><select value={value} onChange={e=>onChange(Number(e.target.value))}><option value={1}>1 — Very poor</option><option value={2}>2 — Poor</option><option value={3}>3 — Okay</option><option value={4}>4 — Good</option><option value={5}>5 — Excellent</option></select></label>}
function Metric({label,value}:{label:string;value:string}){return <div className={styles.metric}><span>{label}</span><strong>{value}</strong></div>}
