'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, CheckCircle2, Circle, ClipboardCheck, Loader2, UserRound } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type Employee={id:string;full_name:string};
type Task={id:string;title:string;description:string|null;status:string;priority:string;due_at:string|null;assigned_user_id:string|null;assigned_employee_id:string|null;assigned_role_id:string|null};
type RoleAssignment={role_id:string};
type Run={id:string;checklist_template_id:string;assigned_employee_id:string|null;assigned_role_id:string|null;business_date:string;completed_at:string|null};
type Template={id:string;title:string;period:string};
type Item={id:string;checklist_run_id:string;completed:boolean;checklist_template_items?:{label:string;item_number:number}|null};
const today=()=>new Date().toLocaleDateString('en-CA');

export default function MyWorkPage(){
 const [loading,setLoading]=useState(true),[message,setMessage]=useState(''),[userId,setUserId]=useState(''),[employee,setEmployee]=useState<Employee|null>(null),[roles,setRoles]=useState<RoleAssignment[]>([]),[tasks,setTasks]=useState<Task[]>([]),[runs,setRuns]=useState<Run[]>([]),[templates,setTemplates]=useState<Template[]>([]),[items,setItems]=useState<Item[]>([]);
 useEffect(()=>{void load()},[]);
 async function load(){setLoading(true);const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return;}setUserId(u.user.id);const e=await supabase.from('employees').select('id,full_name').eq('user_id',u.user.id).is('deleted_at',null).maybeSingle();const emp=(e.data||null) as Employee|null;setEmployee(emp);let roleIds:string[]=[];if(emp){const ra=await supabase.from('employee_role_assignments').select('role_id').eq('employee_id',emp.id);setRoles((ra.data??[]) as RoleAssignment[]);roleIds=(ra.data??[]).map((x:any)=>x.role_id)}const [t,r,ct]=await Promise.all([supabase.from('tasks').select('id,title,description,status,priority,due_at,assigned_user_id,assigned_employee_id,assigned_role_id').is('deleted_at',null).order('due_at',{ascending:true,nullsFirst:false}).limit(500),supabase.from('checklist_runs').select('id,checklist_template_id,assigned_employee_id,assigned_role_id,business_date,completed_at').eq('business_date',today()),supabase.from('checklist_templates').select('id,title,period').eq('active',true)]);const taskRows=((t.data??[]) as Task[]).filter(x=>x.assigned_user_id===u.user.id||(emp&&x.assigned_employee_id===emp.id)||(x.assigned_role_id&&roleIds.includes(x.assigned_role_id)));const runRows=((r.data??[]) as Run[]).filter(x=>(emp&&x.assigned_employee_id===emp.id)||(x.assigned_role_id&&roleIds.includes(x.assigned_role_id))||(!x.assigned_employee_id&&!x.assigned_role_id));setTasks(taskRows);setRuns(runRows);setTemplates((ct.data??[]) as Template[]);const ids=runRows.map(x=>x.id);if(ids.length){const it=await supabase.from('checklist_run_items').select('id,checklist_run_id,completed,checklist_template_items(label,item_number)').in('checklist_run_id',ids).order('created_at');setItems((it.data??[]) as unknown as Item[])}else setItems([]);setLoading(false)}
 async function toggleTask(t:Task){const next=t.status!=='done';const old=tasks;setTasks(xs=>xs.map(x=>x.id===t.id?{...x,status:next?'done':'open'}:x));const {error}=await supabase.from('tasks').update({status:next?'done':'open',completed_at:next?new Date().toISOString():null}).eq('id',t.id);if(error){setTasks(old);setMessage(error.message);return;}await load()}
 async function toggleItem(item:Item){const next=!item.completed;const old=items;setItems(xs=>xs.map(x=>x.id===item.id?{...x,completed:next}:x));const {error}=await supabase.from('checklist_run_items').update({completed:next,completed_by:next?userId:null,completed_at:next?new Date().toISOString():null}).eq('id',item.id);if(error){setItems(old);setMessage(error.message);return;}await load()}
 const openTasks=tasks.filter(t=>t.status!=='done'&&t.status!=='cancelled');const completed=tasks.filter(t=>t.status==='done');
 const runView=useMemo(()=>runs.map(r=>({run:r,template:templates.find(t=>t.id===r.checklist_template_id),items:items.filter(i=>i.checklist_run_id===r.id).sort((a,b)=>(a.checklist_template_items?.item_number??0)-(b.checklist_template_items?.item_number??0))})),[runs,templates,items]);
 if(loading)return <div className="full-loader"><Loader2 className="spin"/><span>Loading your work…</span></div>;
 return <div className="app-shell"><header className="topbar"><a className="round-button" href="/" aria-label="Back"><ArrowLeft/></a><div style={{flex:1}}><div className="brand-kicker">El Molino Ops</div><div className="brand-title">My Work</div></div></header><main className="page">{message&&<div className="toast-message">{message}</div>}<div className="page-heading"><h1>{employee?employee.full_name:'Your assignments'}</h1><p>Only the work assigned to you, your employee record, your roles, or today’s unassigned shift checklists.</p></div>{!employee&&<div className="notice"><UserRound size={16}/> Your login is not linked to an employee record yet. Direct user assignments still appear here.</div>}<div className="metric-grid" style={{marginTop:14}}><div className="metric"><strong>{openTasks.length}</strong><span>open tasks</span></div><div className="metric"><strong>{runView.length}</strong><span>today’s checklists</span></div></div><div className="section-title"><h2>Assignments</h2><span>{openTasks.length} open</span></div>{openTasks.length?<div className="list">{openTasks.map(t=><button className="list-item" key={t.id} onClick={()=>toggleTask(t)}><span className="task-check"><Circle/></span><span className="list-main"><b>{t.title}</b><small>{t.due_at?new Date(t.due_at).toLocaleString():'No due date'} · {t.priority}</small>{t.description&&<small>{t.description}</small>}</span></button>)}</div>:<div className="empty-state"><CheckCircle2/><b>No open assignments</b><span>Assigned work will appear here.</span></div>}<div className="section-title"><h2>Today’s checklists</h2><span>{today()}</span></div>{runView.length?<div className="list">{runView.map(({run,template,items:runItems})=><div className="card" key={run.id}><div className="card-title-row"><div><h3>{template?.title||'Checklist'}</h3><small style={{color:'var(--muted)'}}>{runItems.filter(x=>x.completed).length}/{runItems.length} complete</small></div>{run.completed_at&&<span className="status">done</span>}</div><div className="list" style={{marginTop:10}}>{runItems.map(i=><button className={`list-item ${i.completed?'completed-row':''}`} key={i.id} onClick={()=>toggleItem(i)}><span className="task-check">{i.completed?<CheckCircle2/>:<Circle/>}</span><span className="list-main"><b>{i.checklist_template_items?.label||'Checklist item'}</b></span></button>)}</div></div>)}</div>:<div className="empty-state"><ClipboardCheck/><b>No checklist work assigned</b><span>Shift checklist items assigned to you or your role will appear here.</span></div>}{completed.length>0&&<><div className="section-title"><h2>Completed</h2><span>{completed.length}</span></div><div className="list">{completed.slice(0,12).map(t=><button className="list-item completed-row" key={t.id} onClick={()=>toggleTask(t)}><CheckCircle2/><span className="list-main"><b>{t.title}</b><small>Tap to reopen</small></span></button>)}</div></>}</main></div>;
}
