'use client';

import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase';
import styles from '../../ops-tools.module.css';
import {businessDateInZone} from '@/lib/intermediate-hardening';
import {addDateDays,dateDayOfWeek} from '@/lib/scheduling-engine';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Employee={id:string;full_name:string};
type Compliance={employee_id:string;date_of_birth:string|null;minor_rules_enabled:boolean;notes:string|null};
type Period={id:string;starts_on:string;ends_on:string;revision:number};
type SchoolDay={school_date:string;school_in_session:boolean;school_starts_at:string|null;school_ends_at:string|null;notes:string|null};
type SchoolDraft={configured:boolean;school_in_session:boolean;school_starts_at:string;school_ends_at:string;notes:string};
type Warning={severity:string;code:string;shift_id?:string;employee_id?:string;employee_name?:string;date?:string;hours?:number;limit?:number;required_hours?:number;actual_hours?:number;cutoff?:string};
const mondayOf=(d:string)=>addDateDays(d,-((dateDayOfWeek(d)+6)%7));
const hhmm=(v:string|null|undefined)=>v?String(v).slice(0,5):'';
const label=(code:string)=>code.replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase());
export default function CompliancePage(){
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[profile,setProfile]=useState<Profile|null>(null),[weekStart,setWeekStart]=useState(()=>mondayOf(businessDateInZone())),[period,setPeriod]=useState<Period|null>(null),[employees,setEmployees]=useState<Employee[]>([]),[compliance,setCompliance]=useState<Record<string,Compliance>>({}),[school,setSchool]=useState<Record<string,SchoolDraft>>({}),[warnings,setWarnings]=useState<Warning[]>([]);
 const canManage=profile?.app_role==='admin'||profile?.app_role==='manager';const weekDates=useMemo(()=>Array.from({length:7},(_,i)=>addDateDays(weekStart,i)),[weekStart]);
 useEffect(()=>{void init()},[]);
 async function init(){const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}const p=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();if(p.error||!p.data?.location_id){setMessage('Could not load compliance access.');setReady(true);return}const pr=p.data as Profile;setProfile(pr);await load(pr,weekStart);setReady(true)}
 async function load(pr=profile,ws=weekStart){if(!pr?.location_id)return;setBusy(true);try{if(!(pr.app_role==='admin'||pr.app_role==='manager')){setBusy(false);return}const per=await supabase.rpc('ensure_schedule_period',{p_starts_on:ws});if(per.error)throw per.error;setPeriod(per.data as Period);const [e,c,sc]=await Promise.all([supabase.from('employees').select('id,full_name').eq('location_id',pr.location_id).eq('active',true).is('deleted_at',null).order('full_name'),supabase.from('employee_compliance_profiles').select('employee_id,date_of_birth,minor_rules_enabled,notes').eq('location_id',pr.location_id),supabase.from('schedule_school_calendar_days').select('school_date,school_in_session,school_starts_at,school_ends_at,notes').eq('location_id',pr.location_id).gte('school_date',ws).lte('school_date',addDateDays(ws,6))]);for(const x of [e,c,sc])if(x.error)throw x.error;setEmployees((e.data??[]) as Employee[]);const cm:Record<string,Compliance>={};for(const x of c.data??[])cm[x.employee_id]=x as Compliance;for(const emp of e.data??[])if(!cm[emp.id])cm[emp.id]={employee_id:emp.id,date_of_birth:null,minor_rules_enabled:true,notes:null};setCompliance(cm);const rows=(sc.data??[]) as SchoolDay[],sm:Record<string,SchoolDraft>={};for(let i=0;i<7;i++){const d=addDateDays(ws,i),r=rows.find(x=>x.school_date===d);sm[d]=r?{configured:true,school_in_session:r.school_in_session,school_starts_at:hhmm(r.school_starts_at)||'08:00',school_ends_at:hhmm(r.school_ends_at)||'15:00',notes:r.notes||''}:{configured:false,school_in_session:false,school_starts_at:'08:00',school_ends_at:'15:00',notes:''}}setSchool(sm);const wr=await supabase.rpc('schedule_compliance_warnings',{p_period_id:per.data.id});if(wr.error)throw wr.error;setWarnings((wr.data??[]) as Warning[])}catch(e:any){setMessage(e?.message||'Could not load compliance data.')}finally{setBusy(false)}}
 async function changeWeek(days:number){if(busy)return;const ws=addDateDays(weekStart,days);setWeekStart(ws);await load(profile,ws)}
 async function saveEmployee(id:string){if(!canManage||busy)return;const x=compliance[id];setBusy(true);const {error}=await supabase.rpc('upsert_employee_compliance_profile',{p_employee_id:id,p_date_of_birth:x.date_of_birth||null,p_minor_rules_enabled:x.minor_rules_enabled,p_notes:x.notes?.trim()||null});setMessage(error?error.message:'Compliance profile saved.');await load();setBusy(false)}
 async function saveSchoolDay(date:string){if(!canManage||busy)return;const x=school[date];if(x.school_in_session&&(!x.school_starts_at||!x.school_ends_at||x.school_ends_at<=x.school_starts_at)){setMessage('School end must be after school start.');return}setBusy(true);const {error}=await supabase.rpc('set_schedule_school_day',{p_school_date:date,p_school_in_session:x.school_in_session,p_school_starts_at:x.school_in_session?x.school_starts_at:null,p_school_ends_at:x.school_in_session?x.school_ends_at:null,p_notes:x.notes.trim()||null});setMessage(error?error.message:`School calendar saved for ${date}.`);await load();setBusy(false)}
 const configuredCount=Object.values(school).filter(x=>x.configured).length;
 if(!ready)return <div className="full-loader"><span>Opening compliance…</span></div>;
 return <main className={styles.page}><div className={styles.top}><div><h1>Scheduling Compliance</h1><p>Manager-only youth scheduling data, school calendar and rest/clopen warnings.</p></div><Link className={styles.back} href="/schedule">Back to Schedule</Link></div>{message&&<div className={message.toLowerCase().includes('could not')?styles.error:styles.notice}>{message}</div>}{!canManage?<div className={styles.error}>Manager access is required. Birth dates and school calendars are not exposed to employee accounts.</div>:<>
 <section className={styles.section}><div className={styles.card}><div className={styles.entryHead}><div><h2>Week of {weekStart}</h2><small>{configuredCount}/7 school-calendar days explicitly configured · {period?`revision ${period.revision}`:'loading'}</small></div><div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>changeWeek(-7)}>Previous</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>changeWeek(7)}>Next</button></div></div><div className={styles.notice} style={{marginTop:12}}>An unconfigured date is <b>unknown</b>, never automatically treated as a school day or a non-school day. The engine only applies school-day/week hour limits after the calendar is explicit.</div></div></section>
 <section className={styles.section}><h2>Warnings</h2><div className={styles.list}>{warnings.map((w,i)=><div className={styles.entry} key={`${w.code}-${w.shift_id||w.employee_id||i}-${i}`}><div className={styles.entryHead}><div><h3>{label(w.code)}</h3><small>{w.employee_name||'Employee'}{w.date?` · ${w.date}`:''}{w.hours!=null?` · ${Number(w.hours).toFixed(1)} hrs`:''}{w.limit!=null?` · limit ${w.limit}`:''}{w.required_hours!=null?` · ${w.actual_hours} / ${w.required_hours} rest hrs`:''}{w.cutoff?` · cutoff ${hhmm(w.cutoff)}`:''}</small></div><span className={styles.pill}>{String(w.severity||'warning').toUpperCase()}</span></div></div>)}{warnings.length===0&&<div className={styles.card}><b>No compliance warnings for this schedule.</b><p>This means the configured data produced no warnings; it is not a substitute for management review.</p></div>}</div></section>
 <section className={styles.section}><h2>School calendar</h2><div className={styles.list}>{weekDates.map(date=>{const x=school[date]||{configured:false,school_in_session:false,school_starts_at:'08:00',school_ends_at:'15:00',notes:''};return <div className={styles.entry} key={date}><div className={styles.entryHead}><div><h3>{date}</h3><small>{x.configured?'Explicitly configured':'UNKNOWN — configure this date'}</small></div><span className={styles.pill}>{x.configured?(x.school_in_session?'SCHOOL':'NO SCHOOL'):'UNKNOWN'}</span></div><div className={styles.formGrid}><label className={styles.field}><span>School in session</span><input type="checkbox" checked={x.school_in_session} onChange={e=>setSchool({...school,[date]:{...x,school_in_session:e.target.checked}})}/></label>{x.school_in_session&&<><label className={styles.field}><span>School starts</span><input type="time" value={x.school_starts_at} onChange={e=>setSchool({...school,[date]:{...x,school_starts_at:e.target.value}})}/></label><label className={styles.field}><span>School ends</span><input type="time" value={x.school_ends_at} onChange={e=>setSchool({...school,[date]:{...x,school_ends_at:e.target.value}})}/></label></>}<label className={styles.field}><span>Note</span><input maxLength={1000} value={x.notes} onChange={e=>setSchool({...school,[date]:{...x,notes:e.target.value}})}/></label></div><div className={styles.actions}><button className={styles.button} disabled={busy} onClick={()=>saveSchoolDay(date)}>Save Day</button></div></div>})}</div></section>
 <section className={styles.section}><h2>Employee compliance profiles</h2><div className={styles.list}>{employees.map(e=>{const x=compliance[e.id]||{employee_id:e.id,date_of_birth:null,minor_rules_enabled:true,notes:null};return <div className={styles.entry} key={e.id}><h3>{e.full_name}</h3><div className={styles.formGrid}><label className={styles.field}><span>Date of birth</span><input type="date" max={businessDateInZone()} value={x.date_of_birth||''} onChange={ev=>setCompliance({...compliance,[e.id]:{...x,date_of_birth:ev.target.value||null}})}/></label><label className={styles.field}><span>Run minor-hour warnings</span><input type="checkbox" checked={x.minor_rules_enabled} onChange={ev=>setCompliance({...compliance,[e.id]:{...x,minor_rules_enabled:ev.target.checked}})}/></label><label className={styles.field}><span>Manager-only note</span><input maxLength={2000} value={x.notes||''} onChange={ev=>setCompliance({...compliance,[e.id]:{...x,notes:ev.target.value}})}/></label></div><div className={styles.actions}><button className={styles.button} disabled={busy} onClick={()=>saveEmployee(e.id)}>Save Profile</button></div></div>})}{employees.length===0&&<div className={styles.card}><b>No active employees loaded.</b></div>}</div></section>
 </>}</main>
}
