'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { supabase } from '@/lib/supabase';
import styles from '../ops-tools.module.css';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Rec={id:string;title:string;status:string;priority:string;data:any;occurred_at:string|null;created_at:string;created_by:string|null};
const localInput=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)};

export default function IncidentsPage(){
  const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[profile,setProfile]=useState<Profile|null>(null),[rows,setRows]=useState<Rec[]>([]),[message,setMessage]=useState('');
  const [form,setForm]=useState({type:'guest_injury',occurred_at:localInput(),people:'',witnesses:'',description:'',immediate_action:'',emergency_services:false,medical_attention:false,property_damage:false,police_report:'',follow_up:'',priority:'high'});
  const canManage=profile?.app_role==='admin'||profile?.app_role==='manager';
  useEffect(()=>{void init()},[]);
  async function init(){const {data:u}=await supabase.auth.getUser();if(!u.user){window.location.href='/';return;}const {data:p}=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();setProfile((p||null) as Profile|null);if(p?.location_id)await load(p.location_id);setReady(true);}
  async function load(locationId=profile?.location_id||''){if(!locationId)return;const {data,error}=await supabase.from('ops_records').select('id,title,status,priority,data,occurred_at,created_at,created_by').eq('location_id',locationId).eq('kind','incident').is('deleted_at',null).order('occurred_at',{ascending:false,nullsFirst:false}).order('created_at',{ascending:false}).limit(150);setRows((data??[]) as Rec[]);if(error)setMessage('Could not load incident records.');}
  const open=useMemo(()=>rows.filter(r=>r.status!=='resolved'&&r.status!=='closed').length,[rows]);
  async function submit(e:FormEvent){e.preventDefault();if(!profile?.location_id||busy||!form.description.trim())return;const occurred=new Date(form.occurred_at);if(!Number.isFinite(occurred.getTime())){setMessage('Choose a valid incident date and time.');return;}setBusy(true);try{const {data:u}=await supabase.auth.getUser();if(!u.user)return;const label=form.type.replaceAll('_',' ');const data={incident_type:form.type,people:form.people.trim().slice(0,3000),witnesses:form.witnesses.trim().slice(0,3000),description:form.description.trim().slice(0,10000),immediate_action:form.immediate_action.trim().slice(0,6000),emergency_services:form.emergency_services,medical_attention:form.medical_attention,property_damage:form.property_damage,police_report:form.police_report.trim().slice(0,2000),follow_up:form.follow_up.trim().slice(0,5000)};const {error}=await supabase.from('ops_records').insert({location_id:profile.location_id,kind:'incident',title:`${label} · ${occurred.toLocaleDateString()}`.slice(0,200),status:'open',priority:form.priority,sensitivity:'private',data,tags:['incident',form.type],occurred_at:occurred.toISOString(),created_by:u.user.id,updated_by:u.user.id});if(error)throw error;setForm({type:'guest_injury',occurred_at:localInput(),people:'',witnesses:'',description:'',immediate_action:'',emergency_services:false,medical_attention:false,property_damage:false,police_report:'',follow_up:'',priority:'high'});await load();setMessage('Incident report saved privately for management review.');}catch{setMessage('Could not save the incident report.');}finally{setBusy(false)}}
  async function resolve(row:Rec){if(!canManage||busy)return;const note=prompt('Manager resolution / follow-up note')||'';setBusy(true);try{const {data:u}=await supabase.auth.getUser();const {error}=await supabase.from('ops_records').update({status:'resolved',archived_at:new Date().toISOString(),updated_by:u.user?.id||null,data:{...row.data,manager_resolution:note.trim().slice(0,5000),resolved_at:new Date().toISOString()}}).eq('id',row.id).eq('kind','incident');if(error)throw error;await load();setMessage('Incident marked resolved.');}catch{setMessage('Could not resolve that incident.');}finally{setBusy(false)}}
  if(!ready)return <main className={styles.page}>Loading incidents…</main>;
  if(!profile?.location_id)return <main className={styles.page}>No restaurant location is assigned.</main>;
  return <main className={styles.page}><div className={styles.top}><div><h1>Incident Reporting</h1><p>Private, time-stamped documentation for injuries, safety, conduct and property events.</p></div><Link className={styles.back} href="/">Back to Ops</Link></div>{message&&<div className={message.startsWith('Could not')?styles.error:styles.notice}>{message}</div>}
    <div className={styles.grid}><Metric label="Visible incident records" value={String(rows.length)}/><Metric label="Open for follow-up" value={String(open)}/><Metric label="High / urgent" value={String(rows.filter(r=>['high','urgent'].includes(r.priority)&&r.status==='open').length)}/><Metric label="Resolved" value={String(rows.filter(r=>r.status==='resolved').length)}/></div>
    <section className={styles.section}><div className={styles.card}><h2>New incident report</h2><p className={styles.muted}>Employees can see reports they created; managers can see all incident reports for the location.</p><form onSubmit={submit}><div className={styles.formGrid}>
      <Field label="Incident type"><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option value="guest_injury">Guest injury</option><option value="employee_injury">Employee injury</option><option value="property_damage">Property damage</option><option value="theft_loss">Theft / loss</option><option value="harassment_conduct">Conduct / harassment</option><option value="intoxication_refusal">Intoxication / refusal of service</option><option value="food_safety">Food safety</option><option value="security">Security</option><option value="other">Other</option></select></Field>
      <Field label="Occurred"><input type="datetime-local" value={form.occurred_at} onChange={e=>setForm({...form,occurred_at:e.target.value})}/></Field>
      <Field label="Priority"><select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></Field>
      <Field label="People involved"><textarea value={form.people} onChange={e=>setForm({...form,people:e.target.value})}/></Field>
      <Field label="Witnesses"><textarea value={form.witnesses} onChange={e=>setForm({...form,witnesses:e.target.value})}/></Field>
      <Field label="What happened" wide><textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field>
      <Field label="Immediate action taken" wide><textarea value={form.immediate_action} onChange={e=>setForm({...form,immediate_action:e.target.value})}/></Field>
      <Field label="Police / report number"><input value={form.police_report} onChange={e=>setForm({...form,police_report:e.target.value})}/></Field>
      <Field label="Required follow-up"><textarea value={form.follow_up} onChange={e=>setForm({...form,follow_up:e.target.value})}/></Field>
      <label className={styles.checkbox}><input type="checkbox" checked={form.emergency_services} onChange={e=>setForm({...form,emergency_services:e.target.checked})}/> Emergency services involved</label>
      <label className={styles.checkbox}><input type="checkbox" checked={form.medical_attention} onChange={e=>setForm({...form,medical_attention:e.target.checked})}/> Medical attention involved</label>
      <label className={styles.checkbox}><input type="checkbox" checked={form.property_damage} onChange={e=>setForm({...form,property_damage:e.target.checked})}/> Property damage involved</label>
    </div><div className={styles.actions}><button className={styles.button} disabled={busy}>Save incident report</button></div></form></div></section>
    <section className={styles.section}><h2>{canManage?'Incident register':'My incident reports'}</h2><div className={styles.list}>{rows.length?rows.map(r=><article className={styles.entry} key={r.id}><div className={styles.entryHead}><div><h3>{r.title}</h3><small>{new Date(r.occurred_at||r.created_at).toLocaleString()}</small></div><span className={styles.pill}>{r.priority} · {r.status}</span></div><div className={styles.details}>{detail('Description',r.data?.description)}{detail('People',r.data?.people)}{detail('Witnesses',r.data?.witnesses)}{detail('Immediate action',r.data?.immediate_action)}{detail('Follow-up',r.data?.follow_up)}{detail('Manager resolution',r.data?.manager_resolution)}</div>{canManage&&r.status==='open'&&<div className={styles.actions}><button className={styles.button} disabled={busy} onClick={()=>resolve(r)}>Resolve / close</button></div>}</article>):<div className={styles.empty}>No incident reports visible to this account.</div>}</div></section>
  </main>}
function Metric({label,value}:{label:string;value:string}){return <div className={styles.metric}><span>{label}</span><strong>{value}</strong></div>}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={`${styles.field} ${wide?styles.wide:''}`}><span>{label}</span>{children}</label>}
function detail(label:string,value?:string){return value?.trim()?<div className={styles.detail}><b>{label}</b><span>{value}</span></div>:null}
