'use client';

import { DragEvent, useEffect, useState } from 'react';
import { ArrowLeft, Check, FileSpreadsheet, Loader2, Upload, X } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Job={id:string;file_name:string;import_type:string;status:string;headers:string[];row_count:number;error_count:number;created_at:string};

type Parsed={headers:string[];rows:Record<string,string>[]};

function parseCsv(text:string):Parsed{
  const matrix:string[][]=[];let row:string[]=[],cell='',quoted=false;
  for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(ch===','&&!quoted){row.push(cell);cell='';}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);cell='';if(row.some(v=>v.trim()))matrix.push(row);row=[];}else cell+=ch;}
  row.push(cell);if(row.some(v=>v.trim()))matrix.push(row);const headers=(matrix.shift()||[]).map((h,i)=>h.trim()||`column_${i+1}`);return {headers,rows:matrix.map(r=>Object.fromEntries(headers.map((h,i)=>[h,(r[i]??'').trim()]))) };
}

export default function ImportPage(){
  const [profile,setProfile]=useState<Profile|null>(null),[jobs,setJobs]=useState<Job[]>([]),[parsed,setParsed]=useState<Parsed|null>(null),[fileName,setFileName]=useState(''),[type,setType]=useState('generic'),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);
  const canManage=profile?.app_role==='admin'||profile?.app_role==='manager';
  useEffect(()=>{void load()},[]);
  async function load(){const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return;}const {data:p}=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();setProfile(p as Profile);const {data:j}=await supabase.from('import_jobs').select('id,file_name,import_type,status,headers,row_count,error_count,created_at').order('created_at',{ascending:false}).limit(50);setJobs((j??[]) as Job[]);setLoading(false);}
  function flash(v:string){setMessage(v);setTimeout(()=>setMessage(''),4500)}
  async function read(file:File){if(file.size>10*1024*1024)return flash('CSV imports are limited to 10 MB per staged job.');if(!file.name.toLowerCase().endsWith('.csv')&&file.type!=='text/csv')return flash('Use CSV for structured imports. XLSX can still be stored in Files & Media until spreadsheet parsing is enabled.');const text=await file.text();const p=parseCsv(text);if(!p.headers.length||!p.rows.length)return flash('No tabular rows were found.');if(p.rows.length>5000)return flash('This first import workflow supports up to 5,000 rows per job.');setFileName(file.name);setParsed(p);}
  function choose(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(f)void read(f);e.target.value=''}
  function drop(e:DragEvent){e.preventDefault();const f=e.dataTransfer.files?.[0];if(f)void read(f)}
  async function stage(){if(!profile?.location_id||!parsed||!fileName)return;setSaving(true);const {data:u}=await supabase.auth.getUser();if(!u.user){setSaving(false);return;}const {data:j,error}=await supabase.from('import_jobs').insert({location_id:profile.location_id,created_by:u.user.id,import_type:type,file_name:fileName,headers:parsed.headers,row_count:parsed.rows.length,status:'staged'}).select('id').single();if(error){setSaving(false);return flash(error.message);}const batch=parsed.rows.map((data,i)=>({import_job_id:j.id,row_number:i+2,data,validation_errors:[]}));for(let i=0;i<batch.length;i+=500){const {error:rErr}=await supabase.from('import_rows').insert(batch.slice(i,i+500));if(rErr){await supabase.from('import_jobs').update({status:'failed',error_count:1,metadata:{error:rErr.message}}).eq('id',j.id);setSaving(false);return flash(rErr.message);}}setParsed(null);setFileName('');setSaving(false);await load();flash('Import staged for review. No authoritative records were changed.');}
  if(loading)return <div className="full-loader"><Loader2 className="spin"/><span>Loading imports…</span></div>;
  if(!canManage)return <main className="page"><a className="back-link" href="/">‹ Back</a><div className="empty-state"><FileSpreadsheet/><b>Manager access required</b><span>Structured imports can change operational data after approval.</span></div></main>;
  return <div className="app-shell"><header className="topbar"><a className="round-button" href="/tools" aria-label="Back"><ArrowLeft/></a><div style={{flex:1}}><div className="brand-kicker">El Molino Ops</div><div className="brand-title">Data Import</div></div></header><main className="page">{message&&<div className="toast-message">{message}</div>}<div className="page-heading"><h1>Stage an import</h1><p>Preview outside data before it can affect official restaurant records.</p></div><div className="drop-zone" onDragOver={e=>e.preventDefault()} onDrop={drop}><Upload/><b>Drop a CSV here</b><small>or choose a file from this device</small><label className="btn secondary">Choose CSV<input hidden type="file" accept=".csv,text/csv" onChange={choose}/></label></div>{parsed&&<><div className="section-title"><h2>Preview</h2><span>{parsed.rows.length} rows</span></div><div className="card"><div className="field"><label>Import type</label><select className="select" value={type} onChange={e=>setType(e.target.value)}><option value="generic">Generic data</option><option value="employees">Employees</option><option value="menu">Menu / products</option><option value="inventory">Inventory</option><option value="toast">Toast export</option><option value="vendors">Vendors</option></select></div><div className="preview-table-wrap"><table className="preview-table"><thead><tr>{parsed.headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{parsed.rows.slice(0,10).map((r,i)=><tr key={i}>{parsed.headers.map(h=><td key={h}>{r[h]}</td>)}</tr>)}</tbody></table></div><div className="preview-actions"><button className="btn ghost" onClick={()=>{setParsed(null);setFileName('')}}><X size={16}/> Cancel</button><button className="btn" disabled={saving} onClick={stage}>{saving?<Loader2 className="spin" size={16}/>:<Check size={16}/>} Stage {parsed.rows.length} rows</button></div></div></>}<div className="section-title"><h2>Import history</h2><span>{jobs.length}</span></div>{jobs.length?<div className="list">{jobs.map(j=><div className="list-item" key={j.id}><div className="icon-wrap"><FileSpreadsheet size={18}/></div><div className="list-main"><b>{j.file_name}</b><small>{j.import_type} · {j.row_count} rows · {new Date(j.created_at).toLocaleString()}</small></div><span className="status">{j.status}</span></div>)}</div>:<div className="empty-state"><FileSpreadsheet/><b>No import jobs</b><span>Your staged import history will appear here.</span></div>}</main></div>;
}
