'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { supabase } from '@/lib/supabase';
import { useI18n } from '@/lib/i18n';
import styles from '../ops-tools.module.css';
import { businessDateInZone } from '@/lib/intermediate-hardening';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Employee={id:string;user_id:string|null;full_name:string};
type Template={id:string;title:string;period:'opening'|'mid_shift'|'closing'|'other';active:boolean};
type TemplateItem={id:string;checklist_template_id:string;item_number:number;label:string;requires_photo:boolean};
type Run={id:string;checklist_template_id:string;assigned_employee_id:string|null;business_date:string;started_at:string|null;completed_at:string|null;created_by:string|null};
type RunItem={id:string;checklist_run_id:string;template_item_id:string;completed:boolean;completed_by:string|null;completed_at:string|null;note:string|null};
type TempData={equipment?:string;temperature_f?:number;min_f?:number|null;max_f?:number|null;in_range?:boolean;corrective_action?:string};
type TempLog={id:string;title:string;data:TempData&{point_id?:string};occurred_at:string|null;created_at:string;created_by:string|null};
type TempPoint={id:string;label:string;min_f:number|null;max_f:number|null;active:boolean};
const today=()=>businessDateInZone();

export default function SafetyPage(){
  const {locale}=useI18n();const t=(en:string,es:string)=>locale==='es'?es:en;const localeCode=locale==='es'?'es-US':'en-US';const periodLabel=(v:string)=>locale==='es'?({opening:'Apertura',mid_shift:'Mitad de turno',closing:'Cierre',other:'Otro'}[v]||v):v.replaceAll('_',' ');
  const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[profile,setProfile]=useState<Profile|null>(null),[me,setMe]=useState<Employee|null>(null),[templates,setTemplates]=useState<Template[]>([]),[templateItems,setTemplateItems]=useState<TemplateItem[]>([]),[runs,setRuns]=useState<Run[]>([]),[runItems,setRunItems]=useState<RunItem[]>([]),[temps,setTemps]=useState<TempLog[]>([]),[points,setPoints]=useState<TempPoint[]>([]),[message,setMessage]=useState('');
  const [templateForm,setTemplateForm]=useState({title:'',period:'opening',items:''}),[pointForm,setPointForm]=useState({label:'',min_f:'',max_f:''}),[tempForm,setTempForm]=useState({point_id:'',temperature_f:'',corrective_action:''});
  const canManage=profile?.app_role==='admin'||profile?.app_role==='manager';
  useEffect(()=>{void init()},[]);
  async function init(){const {data:u}=await supabase.auth.getUser();if(!u.user){window.location.href='/';return;}const {data:p}=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();setProfile((p||null) as Profile|null);if(p?.location_id)await load(p.location_id,u.user.id);setReady(true);}
  async function load(locationId=profile?.location_id||'',userId?:string){if(!locationId)return;const [e,templateResult,ti,r,ri,tp,tmp]=await Promise.all([
    supabase.from('employees').select('id,user_id,full_name').eq('location_id',locationId).is('deleted_at',null).eq('active',true),
    supabase.from('checklist_templates').select('id,title,period,active').eq('location_id',locationId).eq('active',true).order('period').order('title'),
    supabase.from('checklist_template_items').select('id,checklist_template_id,item_number,label,requires_photo').order('item_number'),
    supabase.from('checklist_runs').select('id,checklist_template_id,assigned_employee_id,business_date,started_at,completed_at,created_by').eq('business_date',today()).order('created_at',{ascending:false}),
    supabase.from('checklist_run_items').select('id,checklist_run_id,template_item_id,completed,completed_by,completed_at,note'),
    supabase.from('food_safety_temperature_points').select('id,label,min_f,max_f,active').eq('location_id',locationId).eq('active',true).order('label'),
    supabase.from('ops_records').select('id,title,data,occurred_at,created_at,created_by').eq('location_id',locationId).eq('kind','temperature_log').is('deleted_at',null).order('occurred_at',{ascending:false,nullsFirst:false}).limit(40)
  ]);const employees=(e.data??[]) as Employee[];const uid=userId||(await supabase.auth.getUser()).data.user?.id;setMe(employees.find(x=>x.user_id===uid)||null);setTemplates((templateResult.data??[]) as Template[]);setTemplateItems((ti.data??[]) as TemplateItem[]);setRuns((r.data??[]) as Run[]);setRunItems((ri.data??[]) as RunItem[]);setPoints((tp.data??[]) as TempPoint[]);setTemps((tmp.data??[]) as TempLog[]);if(e.error||templateResult.error||ti.error||r.error||ri.error||tp.error||tmp.error)setMessage(t('Some safety data could not be loaded.','Algunos datos de seguridad no se pudieron cargar.'));}
  const completedToday=useMemo(()=>runs.filter(r=>r.completed_at).length,[runs]);
  const openRuns=useMemo(()=>runs.filter(r=>!r.completed_at).length,[runs]);
  const outOfRange=useMemo(()=>temps.filter(t=>t.data?.in_range===false&&new Date(t.occurred_at||t.created_at).toDateString()===new Date().toDateString()).length,[temps]);
  async function createTemplate(e:FormEvent){e.preventDefault();if(!canManage||!profile?.location_id||busy||!templateForm.title.trim())return;const labels=templateForm.items.split('\n').map(x=>x.trim()).filter(Boolean).slice(0,100);if(!labels.length){setMessage(t('Add at least one checklist item.','Agrega al menos un elemento a la lista.'));return;}setBusy(true);try{const {error}=await supabase.rpc('create_checklist_template_with_items',{p_title:templateForm.title.trim().slice(0,200),p_period:templateForm.period,p_labels:labels});if(error)throw error;setTemplateForm({title:'',period:'opening',items:''});await load();setMessage(t('Checklist template created.','Plantilla de lista creada.'));}catch{setMessage(t('Could not create checklist template. Nothing partial was saved.','No se pudo crear la plantilla. No se guardó nada parcialmente.'));}finally{setBusy(false)}}
  async function startRun(template:Template){if(!profile?.location_id||busy)return;const existing=runs.find(r=>r.checklist_template_id===template.id);if(existing){setMessage(existing.completed_at?t('That checklist is already completed today.','Esa lista ya se completó hoy.'):t('That checklist is already open today.','Esa lista ya está abierta hoy.'));return;}setBusy(true);try{const {error}=await supabase.rpc('start_today_checklist',{p_template_id:template.id});if(error)throw error;await load();setMessage(`${template.title} ${t('started.','iniciada.')}`);}catch{setMessage(t('Could not start that checklist.','No se pudo iniciar esa lista.'));}finally{setBusy(false)}}
  async function toggleItem(item:RunItem){if(busy)return;setBusy(true);try{const {error}=await supabase.rpc('set_checklist_item_completed',{p_item_id:item.id,p_completed:!item.completed});if(error)throw error;await load();}catch{setMessage(t('Could not update that checklist item.','No se pudo actualizar ese elemento.'));}finally{setBusy(false)}}
  async function addPoint(e:FormEvent){e.preventDefault();if(!canManage||!profile?.location_id||busy||!pointForm.label.trim())return;const min=pointForm.min_f===''?null:Number(pointForm.min_f),max=pointForm.max_f===''?null:Number(pointForm.max_f);if((min===null&&max===null)||(min!==null&&!Number.isFinite(min))||(max!==null&&!Number.isFinite(max))||(min!==null&&max!==null&&max<min)){setMessage(t('Set a valid minimum and/or maximum range.','Define un rango mínimo y/o máximo válido.'));return;}setBusy(true);try{const {error}=await supabase.from('food_safety_temperature_points').insert({location_id:profile.location_id,label:pointForm.label.trim().slice(0,200),min_f:min,max_f:max});if(error)throw error;setPointForm({label:'',min_f:'',max_f:''});await load();setMessage(t('Temperature point saved.','Punto de temperatura guardado.'));}catch{setMessage(t('Could not save temperature point.','No se pudo guardar el punto de temperatura.'));}finally{setBusy(false)}}
  async function logTemp(e:FormEvent){e.preventDefault();if(!profile?.location_id||busy||!tempForm.point_id||tempForm.temperature_f==='')return;const point=points.find(p=>p.id===tempForm.point_id);if(!point){setMessage(t('Choose a configured temperature point.','Elige un punto de temperatura configurado.'));return;}const temp=Number(tempForm.temperature_f),min=point.min_f===null?null:Number(point.min_f),max=point.max_f===null?null:Number(point.max_f);if(!Number.isFinite(temp)){setMessage(t('Enter a valid temperature.','Ingresa una temperatura válida.'));return;}const inRange=(min===null||temp>=min)&&(max===null||temp<=max);if(!inRange&&!tempForm.corrective_action.trim()){setMessage(t('Add a corrective action for an out-of-range temperature.','Agrega una acción correctiva para una temperatura fuera de rango.'));return;}setBusy(true);try{const data={point_id:point.id,equipment:point.label,temperature_f:temp,min_f:min,max_f:max,in_range:inRange,corrective_action:tempForm.corrective_action.trim().slice(0,3000)};const {error}=await supabase.from('ops_records').insert({location_id:profile.location_id,kind:'temperature_log',title:`Temperature · ${point.label}`,status:inRange?'active':'attention',priority:inRange?'normal':'high',sensitivity:'team',data,tags:['food-safety','temperature'],occurred_at:new Date().toISOString()});if(error)throw error;setTempForm({point_id:'',temperature_f:'',corrective_action:''});await load();setMessage(inRange?t('Temperature logged.','Temperatura registrada.'):t('Out-of-range temperature and corrective action logged.','Temperatura fuera de rango y acción correctiva registradas.'));}catch{setMessage(t('Could not save temperature log.','No se pudo guardar el registro de temperatura.'));}finally{setBusy(false)}}
  const templateName=(id:string)=>templates.find(t=>t.id===id)?.title||t('Checklist','Lista de verificación'),itemLabel=(id:string)=>templateItems.find(i=>i.id===id)?.label||t('Checklist item','Elemento de la lista');
  if(!ready)return <main className={styles.page}>{t('Loading food safety…','Cargando seguridad alimentaria…')}</main>;
  if(!profile?.location_id)return <main className={styles.page}>{t('No restaurant location is assigned.','No hay una ubicación de restaurante asignada.')}</main>;
  return <main className={styles.page}>
    <div className={styles.top}><div><h1>{t('Food Safety','Seguridad Alimentaria')}</h1><p>{t('Opening/closing execution, temperatures and corrective actions.','Ejecución de apertura/cierre, temperaturas y acciones correctivas.')}</p></div><Link className={styles.back} href="/">{t('Back to Ops','Volver a Operaciones')}</Link></div>
    {message&&<div className={message.startsWith('Could not')||message.startsWith('Some')||message.startsWith('No se pudo')||message.startsWith('Algunos')?styles.error:styles.notice}>{message}</div>}
    <div className={styles.grid}><Metric label={t('Checklists completed today','Listas completadas hoy')} value={String(completedToday)}/><Metric label={t('Open checklist runs','Listas abiertas')} value={String(openRuns)}/><Metric label={t('Out-of-range today','Fuera de rango hoy')} value={String(outOfRange)}/><Metric label={t('Active templates','Plantillas activas')} value={String(templates.length)}/></div>
    {canManage&&<section className={styles.section}><div className={styles.card}><h2>{t('Temperature point setup','Configuración de puntos de temperatura')}</h2><p className={styles.muted}>{t('Managers define the acceptable range once. Staff cannot change the range while taking a reading.','Los gerentes definen el rango aceptable. El personal no puede cambiarlo al tomar una lectura.')}</p><form onSubmit={addPoint}><div className={styles.formGrid}><Field label={t('Equipment / item','Equipo / artículo')}><input maxLength={200} value={pointForm.label} onChange={e=>setPointForm({...pointForm,label:e.target.value})}/></Field><Field label={t('Minimum acceptable °F','Mínimo aceptable °F')}><input type="number" step="0.1" value={pointForm.min_f} onChange={e=>setPointForm({...pointForm,min_f:e.target.value})}/></Field><Field label={t('Maximum acceptable °F','Máximo aceptable °F')}><input type="number" step="0.1" value={pointForm.max_f} onChange={e=>setPointForm({...pointForm,max_f:e.target.value})}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy}>{t('Save temperature point','Guardar punto de temperatura')}</button></div></form></div></section>}
    <section className={styles.section}><div className={styles.card}><h2>{t('Temperature check','Control de temperatura')}</h2><p className={styles.muted}>{t('Select a manager-configured point. Out-of-range readings require a corrective action.','Selecciona un punto configurado. Las lecturas fuera de rango requieren una acción correctiva.')}</p><form onSubmit={logTemp}><div className={styles.formGrid}><Field label={t('Equipment / item','Equipo / artículo')}><select value={tempForm.point_id} onChange={e=>setTempForm({...tempForm,point_id:e.target.value})}><option value="">{t('Choose configured point','Elegir punto configurado')}</option>{points.map(p=><option key={p.id} value={p.id}>{p.label} · {p.min_f??'—'} to {p.max_f??'—'} °F</option>)}</select></Field><Field label={t('Temperature °F','Temperatura °F')}><input type="number" step="0.1" value={tempForm.temperature_f} onChange={e=>setTempForm({...tempForm,temperature_f:e.target.value})}/></Field><Field label={t('Corrective action if out of range','Acción correctiva si está fuera de rango')} wide><textarea maxLength={3000} value={tempForm.corrective_action} onChange={e=>setTempForm({...tempForm,corrective_action:e.target.value})}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy||!points.length}>{t('Log temperature','Registrar temperatura')}</button></div>{!points.length&&<div className={styles.empty}>{t('A manager must create at least one temperature point before readings can be logged.','Un gerente debe crear al menos un punto antes de registrar lecturas.')}</div>}</form></div></section>
    <section className={styles.section}><h2>{t("Today's checklists",'Listas de hoy')}</h2><div className={styles.list}>{templates.map(template=>{const run=runs.find(r=>r.checklist_template_id===template.id&&!r.completed_at)||runs.find(r=>r.checklist_template_id===template.id&&r.completed_at);return <div className={styles.entry} key={template.id}><div className={styles.entryHead}><div><h3>{template.title}</h3><small>{periodLabel(template.period)} · {run?.completed_at?t('completed','completada'):run?t('in progress','en progreso'):t('not started','sin iniciar')}</small></div><span className={styles.pill}>{run?.completed_at?t('done','lista'):run?t('open','abierta'):periodLabel(template.period)}</span></div>{!run&&<div className={styles.actions}><button className={styles.button} disabled={busy} onClick={()=>startRun(template)}>{t('Start checklist','Iniciar lista')}</button></div>}{run&&<div className={styles.list} style={{marginTop:10}}>{runItems.filter(i=>i.checklist_run_id===run.id).map(i=><button key={i.id} className={`${styles.button} ${styles.secondary}`} disabled={busy||Boolean(run.completed_at)} onClick={()=>toggleItem(i)} style={{textAlign:'left'}}>{i.completed?'✓':'○'} {itemLabel(i.template_item_id)}</button>)}</div>}</div>})}{!templates.length&&<div className={styles.empty}>{t('No checklist templates yet. A manager can create opening, mid-shift or closing checklists below.','Aún no hay plantillas. Un gerente puede crear listas de apertura, mitad de turno o cierre.')}</div>}</div></section>
    {canManage&&<section className={styles.section}><div className={styles.card}><h2>{t('Create checklist template','Crear plantilla de lista')}</h2><form onSubmit={createTemplate}><div className={styles.formGrid}><Field label={t('Title','Título')}><input maxLength={200} value={templateForm.title} onChange={e=>setTemplateForm({...templateForm,title:e.target.value})}/></Field><Field label={t('Period','Período')}><select value={templateForm.period} onChange={e=>setTemplateForm({...templateForm,period:e.target.value})}><option value="opening">{t('Opening','Apertura')}</option><option value="mid_shift">{t('Mid shift','Mitad de turno')}</option><option value="closing">{t('Closing','Cierre')}</option><option value="other">{t('Other','Otro')}</option></select></Field><Field label={t('Checklist items — one per line','Elementos — uno por línea')} wide><textarea value={templateForm.items} onChange={e=>setTemplateForm({...templateForm,items:e.target.value})} placeholder={t('Verify walk-in temperature\nCheck sanitizer setup\nInspect line cleanliness','Verificar temperatura de cámara\nRevisar preparación de desinfectante\nInspeccionar limpieza de línea')}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy}>{t('Create template','Crear plantilla')}</button></div></form></div></section>}
    <section className={styles.section}><h2>{t('Recent temperature logs','Registros recientes de temperatura')}</h2><div className={styles.list}>{temps.length?temps.map(log=><div className={styles.entry} key={log.id}><div className={styles.entryHead}><div><h3>{log.data?.equipment||log.title}</h3><small>{new Date(log.occurred_at||log.created_at).toLocaleString(localeCode)} · {Number(log.data?.temperature_f).toFixed(1)}°F</small></div><span className={styles.pill}>{log.data?.in_range===false?t('out of range','fuera de rango'):t('in range','en rango')}</span></div>{log.data?.min_f!==null||log.data?.max_f!==null?<div className={styles.details}>{detail(t('Accepted range','Rango aceptado'),`${log.data?.min_f??'—'} to ${log.data?.max_f??'—'} °F`)}{log.data?.corrective_action?detail(t('Corrective action','Acción correctiva'),log.data.corrective_action):null}</div>:null}</div>):<div className={styles.empty}>{t('No temperature logs yet.','Aún no hay registros de temperatura.')}</div>}</div></section>
  </main>;
}
function Metric({label,value}:{label:string;value:string}){return <div className={styles.metric}><span>{label}</span><strong>{value}</strong></div>}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={`${styles.field} ${wide?styles.wide:''}`}><span>{label}</span>{children}</label>}
function detail(label:string,value:string){return <div className={styles.detail}><b>{label}</b><span>{value}</span></div>}
