'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { supabase } from '@/lib/supabase';
import styles from '../ops-tools.module.css';
import { businessDateInZone } from '@/lib/intermediate-hardening';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Employee={id:string;user_id:string|null;full_name:string};
type Template={id:string;title:string;period:'opening'|'mid_shift'|'closing'|'other';active:boolean};
type TemplateItem={id:string;checklist_template_id:string;item_number:number;label:string;requires_photo:boolean};
type Run={id:string;checklist_template_id:string;assigned_employee_id:string|null;business_date:string;started_at:string|null;completed_at:string|null;created_by:string|null};
type RunItem={id:string;checklist_run_id:string;template_item_id:string;completed:boolean;completed_by:string|null;completed_at:string|null;note:string|null};
type TempData={equipment?:string;temperature_f?:number;min_f?:number|null;max_f?:number|null;in_range?:boolean;corrective_action?:string};
type TempLog={id:string;title:string;data:TempData&{point_id?:string};occurred_at:string|null;created_at:string;created_by:string|null};
type TempPoint={id:string;label:string;min_f:number|null;max_f:number|null;active:boolean};
const today=()=>businessDateInZone();

export default function SafetyPage(){
  const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[profile,setProfile]=useState<Profile|null>(null),[me,setMe]=useState<Employee|null>(null),[templates,setTemplates]=useState<Template[]>([]),[templateItems,setTemplateItems]=useState<TemplateItem[]>([]),[runs,setRuns]=useState<Run[]>([]),[runItems,setRunItems]=useState<RunItem[]>([]),[temps,setTemps]=useState<TempLog[]>([]),[points,setPoints]=useState<TempPoint[]>([]),[message,setMessage]=useState('');
  const [templateForm,setTemplateForm]=useState({title:'',period:'opening',items:''}),[pointForm,setPointForm]=useState({label:'',min_f:'',max_f:''}),[tempForm,setTempForm]=useState({point_id:'',temperature_f:'',corrective_action:''});
  const canManage=profile?.app_role==='admin'||profile?.app_role==='manager';
  useEffect(()=>{void init()},[]);
  async function init(){const {data:u}=await supabase.auth.getUser();if(!u.user){window.location.href='/';return;}const {data:p}=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();setProfile((p||null) as Profile|null);if(p?.location_id)await load(p.location_id,u.user.id);setReady(true);}
  async function load(locationId=profile?.location_id||'',userId?:string){if(!locationId)return;const [e,t,ti,r,ri,tp,tmp]=await Promise.all([
    supabase.from('employees').select('id,user_id,full_name').eq('location_id',locationId).is('deleted_at',null).eq('active',true),
    supabase.from('checklist_templates').select('id,title,period,active').eq('location_id',locationId).eq('active',true).order('period').order('title'),
    supabase.from('checklist_template_items').select('id,checklist_template_id,item_number,label,requires_photo').order('item_number'),
    supabase.from('checklist_runs').select('id,checklist_template_id,assigned_employee_id,business_date,started_at,completed_at,created_by').eq('business_date',today()).order('created_at',{ascending:false}),
    supabase.from('checklist_run_items').select('id,checklist_run_id,template_item_id,completed,completed_by,completed_at,note'),
    supabase.from('food_safety_temperature_points').select('id,label,min_f,max_f,active').eq('location_id',locationId).eq('active',true).order('label'),
    supabase.from('ops_records').select('id,title,data,occurred_at,created_at,created_by').eq('location_id',locationId).eq('kind','temperature_log').is('deleted_at',null).order('occurred_at',{ascending:false,nullsFirst:false}).limit(40)
  ]);const employees=(e.data??[]) as Employee[];const uid=userId||(await supabase.auth.getUser()).data.user?.id;setMe(employees.find(x=>x.user_id===uid)||null);setTemplates((t.data??[]) as Template[]);setTemplateItems((ti.data??[]) as TemplateItem[]);setRuns((r.data??[]) as Run[]);setRunItems((ri.data??[]) as RunItem[]);setPoints((tp.data??[]) as TempPoint[]);setTemps((tmp.data??[]) as TempLog[]);if(e.error||t.error||ti.error||r.error||ri.error||tp.error||tmp.error)setMessage('Some safety data could not be loaded.');}
  const completedToday=useMemo(()=>runs.filter(r=>r.completed_at).length,[runs]);
  const openRuns=useMemo(()=>runs.filter(r=>!r.completed_at).length,[runs]);
  const outOfRange=useMemo(()=>temps.filter(t=>t.data?.in_range===false&&new Date(t.occurred_at||t.created_at).toDateString()===new Date().toDateString()).length,[temps]);
  async function createTemplate(e:FormEvent){e.preventDefault();if(!canManage||!profile?.location_id||busy||!templateForm.title.trim())return;const labels=templateForm.items.split('\n').map(x=>x.trim()).filter(Boolean).slice(0,100);if(!labels.length){setMessage('Add at least one checklist item.');return;}setBusy(true);try{const {error}=await supabase.rpc('create_checklist_template_with_items',{p_title:templateForm.title.trim().slice(0,200),p_period:templateForm.period,p_labels:labels});if(error)throw error;setTemplateForm({title:'',period:'opening',items:''});await load();setMessage('Checklist template created.');}catch{setMessage('Could not create checklist template. Nothing partial was saved.');}finally{setBusy(false)}}
  async function startRun(template:Template){if(!profile?.location_id||busy)return;const existing=runs.find(r=>r.checklist_template_id===template.id);if(existing){setMessage(existing.completed_at?'That checklist is already completed today.':'That checklist is already open today.');return;}setBusy(true);try{const {error}=await supabase.rpc('start_today_checklist',{p_template_id:template.id});if(error)throw error;await load();setMessage(`${template.title} started.`);}catch{setMessage('Could not start that checklist.');}finally{setBusy(false)}}
  async function toggleItem(item:RunItem){if(busy)return;setBusy(true);try{const {error}=await supabase.rpc('set_checklist_item_completed',{p_item_id:item.id,p_completed:!item.completed});if(error)throw error;await load();}catch{setMessage('Could not update that checklist item.');}finally{setBusy(false)}}
  async function addPoint(e:FormEvent){e.preventDefault();if(!canManage||!profile?.location_id||busy||!pointForm.label.trim())return;const min=pointForm.min_f===''?null:Number(pointForm.min_f),max=pointForm.max_f===''?null:Number(pointForm.max_f);if((min===null&&max===null)||(min!==null&&!Number.isFinite(min))||(max!==null&&!Number.isFinite(max))||(min!==null&&max!==null&&max<min)){setMessage('Set a valid minimum and/or maximum range.');return;}setBusy(true);try{const {error}=await supabase.from('food_safety_temperature_points').insert({location_id:profile.location_id,label:pointForm.label.trim().slice(0,200),min_f:min,max_f:max});if(error)throw error;setPointForm({label:'',min_f:'',max_f:''});await load();setMessage('Temperature point saved.');}catch{setMessage('Could not save temperature point.');}finally{setBusy(false)}}
  async function logTemp(e:FormEvent){e.preventDefault();if(!profile?.location_id||busy||!tempForm.point_id||tempForm.temperature_f==='')return;const point=points.find(p=>p.id===tempForm.point_id);if(!point){setMessage('Choose a configured temperature point.');return;}const temp=Number(tempForm.temperature_f),min=point.min_f===null?null:Number(point.min_f),max=point.max_f===null?null:Number(point.max_f);if(!Number.isFinite(temp)){setMessage('Enter a valid temperature.');return;}const inRange=(min===null||temp>=min)&&(max===null||temp<=max);if(!inRange&&!tempForm.corrective_action.trim()){setMessage('Add a corrective action for an out-of-range temperature.');return;}setBusy(true);try{const data={point_id:point.id,equipment:point.label,temperature_f:temp,min_f:min,max_f:max,in_range:inRange,corrective_action:tempForm.corrective_action.trim().slice(0,3000)};const {error}=await supabase.from('ops_records').insert({location_id:profile.location_id,kind:'temperature_log',title:`Temperature · ${point.label}`,status:inRange?'active':'attention',priority:inRange?'normal':'high',sensitivity:'team',data,tags:['food-safety','temperature'],occurred_at:new Date().toISOString()});if(error)throw error;setTempForm({point_id:'',temperature_f:'',corrective_action:''});await load();setMessage(inRange?'Temperature logged.':'Out-of-range temperature and corrective action logged.');}catch{setMessage('Could not save temperature log.');}finally{setBusy(false)}}
  const templateName=(id:string)=>templates.find(t=>t.id===id)?.title||'Checklist',itemLabel=(id:string)=>templateItems.find(i=>i.id===id)?.label||'Checklist item';
  if(!ready)return <main className={styles.page}>Loading food safety…</main>;
  if(!profile?.location_id)return <main className={styles.page}>No restaurant location is assigned.</main>;
  return <main className={styles.page}>
    <div className={styles.top}><div><h1>Food Safety</h1><p>Opening/closing execution, temperatures and corrective actions.</p></div><Link className={styles.back} href="/">Back to Ops</Link></div>
    {message&&<div className={message.startsWith('Could not')||message.startsWith('Some')?styles.error:styles.notice}>{message}</div>}
    <div className={styles.grid}><Metric label="Checklists completed today" value={String(completedToday)}/><Metric label="Open checklist runs" value={String(openRuns)}/><Metric label="Out-of-range today" value={String(outOfRange)}/><Metric label="Active templates" value={String(templates.length)}/></div>
    {canManage&&<section className={styles.section}><div className={styles.card}><h2>Temperature point setup</h2><p className={styles.muted}>Managers define the acceptable range once. Staff cannot change the range while taking a reading.</p><form onSubmit={addPoint}><div className={styles.formGrid}><Field label="Equipment / item"><input maxLength={200} value={pointForm.label} onChange={e=>setPointForm({...pointForm,label:e.target.value})}/></Field><Field label="Minimum acceptable °F"><input type="number" step="0.1" value={pointForm.min_f} onChange={e=>setPointForm({...pointForm,min_f:e.target.value})}/></Field><Field label="Maximum acceptable °F"><input type="number" step="0.1" value={pointForm.max_f} onChange={e=>setPointForm({...pointForm,max_f:e.target.value})}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy}>Save temperature point</button></div></form></div></section>}
    <section className={styles.section}><div className={styles.card}><h2>Temperature check</h2><p className={styles.muted}>Select a manager-configured point. Out-of-range readings require a corrective action.</p><form onSubmit={logTemp}><div className={styles.formGrid}><Field label="Equipment / item"><select value={tempForm.point_id} onChange={e=>setTempForm({...tempForm,point_id:e.target.value})}><option value="">Choose configured point</option>{points.map(p=><option key={p.id} value={p.id}>{p.label} · {p.min_f??'—'} to {p.max_f??'—'} °F</option>)}</select></Field><Field label="Temperature °F"><input type="number" step="0.1" value={tempForm.temperature_f} onChange={e=>setTempForm({...tempForm,temperature_f:e.target.value})}/></Field><Field label="Corrective action if out of range" wide><textarea maxLength={3000} value={tempForm.corrective_action} onChange={e=>setTempForm({...tempForm,corrective_action:e.target.value})}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy||!points.length}>Log temperature</button></div>{!points.length&&<div className={styles.empty}>A manager must create at least one temperature point before readings can be logged.</div>}</form></div></section>
    <section className={styles.section}><h2>Today's checklists</h2><div className={styles.list}>{templates.map(t=>{const run=runs.find(r=>r.checklist_template_id===t.id&&!r.completed_at)||runs.find(r=>r.checklist_template_id===t.id&&r.completed_at);return <div className={styles.entry} key={t.id}><div className={styles.entryHead}><div><h3>{t.title}</h3><small>{t.period.replaceAll('_',' ')} · {run?.completed_at?'completed':run?'in progress':'not started'}</small></div><span className={styles.pill}>{run?.completed_at?'done':run?'open':t.period}</span></div>{!run&&<div className={styles.actions}><button className={styles.button} disabled={busy} onClick={()=>startRun(t)}>Start checklist</button></div>}{run&&<div className={styles.list} style={{marginTop:10}}>{runItems.filter(i=>i.checklist_run_id===run.id).map(i=><button key={i.id} className={`${styles.button} ${styles.secondary}`} disabled={busy||Boolean(run.completed_at)} onClick={()=>toggleItem(i)} style={{textAlign:'left'}}>{i.completed?'✓':'○'} {itemLabel(i.template_item_id)}</button>)}</div>}</div>})}{!templates.length&&<div className={styles.empty}>No checklist templates yet. A manager can create opening, mid-shift or closing checklists below.</div>}</div></section>
    {canManage&&<section className={styles.section}><div className={styles.card}><h2>Create checklist template</h2><form onSubmit={createTemplate}><div className={styles.formGrid}><Field label="Title"><input maxLength={200} value={templateForm.title} onChange={e=>setTemplateForm({...templateForm,title:e.target.value})}/></Field><Field label="Period"><select value={templateForm.period} onChange={e=>setTemplateForm({...templateForm,period:e.target.value})}><option value="opening">Opening</option><option value="mid_shift">Mid shift</option><option value="closing">Closing</option><option value="other">Other</option></select></Field><Field label="Checklist items — one per line" wide><textarea value={templateForm.items} onChange={e=>setTemplateForm({...templateForm,items:e.target.value})} placeholder={'Verify walk-in temperature\nCheck sanitizer setup\nInspect line cleanliness'}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy}>Create template</button></div></form></div></section>}
    <section className={styles.section}><h2>Recent temperature logs</h2><div className={styles.list}>{temps.length?temps.map(t=><div className={styles.entry} key={t.id}><div className={styles.entryHead}><div><h3>{t.data?.equipment||t.title}</h3><small>{new Date(t.occurred_at||t.created_at).toLocaleString()} · {Number(t.data?.temperature_f).toFixed(1)}°F</small></div><span className={styles.pill}>{t.data?.in_range===false?'out of range':'in range'}</span></div>{t.data?.min_f!==null||t.data?.max_f!==null?<div className={styles.details}>{detail('Accepted range',`${t.data?.min_f??'—'} to ${t.data?.max_f??'—'} °F`)}{t.data?.corrective_action?detail('Corrective action',t.data.corrective_action):null}</div>:null}</div>):<div className={styles.empty}>No temperature logs yet.</div>}</div></section>
  </main>;
}
function Metric({label,value}:{label:string;value:string}){return <div className={styles.metric}><span>{label}</span><strong>{value}</strong></div>}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={`${styles.field} ${wide?styles.wide:''}`}><span>{label}</span>{children}</label>}
function detail(label:string,value:string){return <div className={styles.detail}><b>{label}</b><span>{value}</span></div>}
