'use client';

import {FormEvent,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase';
import {useI18n} from '@/lib/i18n';
import styles from '../ops-tools.module.css';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Pool={id:string;name:string;cadence:'daily'|'weekly'|'pay_period';distribution_method:'equal'|'hours'|'weighted_hours';active:boolean;description:string|null};
type Receiver={id:string;pool_id:string;receiver_type:'role'|'employee';role_id:string|null;employee_id:string|null;weight:number};
type Run={id:string;pool_id:string;starts_on:string;ends_on:string;status:'draft'|'final'|'cancelled';total_contributions:number;total_distributed:number;finalized_at:string|null};
type Contribution={id:string;run_id:string;employee_id:string|null;role_id:string|null;source:string;amount:number;note:string|null;created_at:string};
type Distribution={id:string;run_id:string;employee_id:string;eligible_hours:number;receiver_weight:number;amount:number};
type Employee={id:string;full_name:string};type Role={id:string;name:string};
type TipReport={starts_on:string;ends_on:string;total_distributed:number;employees:{employee_id:string;full_name:string;tip_amount:number;eligible_hours:number;runs:number}[];pools:{pool_id:string;pool_name:string;distributed:number;runs:number}[];partially_overlapping_runs_excluded:number};
type MyReport={starts_on:string;ends_on:string;total:number;distributions:{run_id:string;pool_name:string;starts_on:string;ends_on:string;eligible_hours:number;weight:number;amount:number}[]};
const today=()=>new Date().toISOString().slice(0,10);const monthStart=()=>`${today().slice(0,8)}01`;

export default function TipsPage(){
 const {locale}=useI18n();const t=(en:string,es:string)=>locale==='es'?es:en;const localeCode=locale==='es'?'es-US':'en-US';const money=(n:number)=>new Intl.NumberFormat(localeCode,{style:'currency',currency:'USD'}).format(Number(n)||0);
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[profile,setProfile]=useState<Profile|null>(null),[enabled,setEnabled]=useState(true),[employeeVisibility,setEmployeeVisibility]=useState(true),[pools,setPools]=useState<Pool[]>([]),[receivers,setReceivers]=useState<Receiver[]>([]),[runs,setRuns]=useState<Run[]>([]),[contribs,setContribs]=useState<Contribution[]>([]),[distributions,setDistributions]=useState<Distribution[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[roles,setRoles]=useState<Role[]>([]),[poolId,setPoolId]=useState(''),[runId,setRunId]=useState(''),[referenceDate,setReferenceDate]=useState(today()),[poolForm,setPoolForm]=useState({name:'',cadence:'daily' as Pool['cadence'],method:'weighted_hours' as Pool['distribution_method'],description:''}),[receiver,setReceiver]=useState({type:'role' as 'role'|'employee',target:'',weight:'1'}),[contribution,setContribution]=useState({amount:'',source:'manual',employee_id:'',role_id:'',note:''}),[range,setRange]=useState({start:monthStart(),end:today()}),[report,setReport]=useState<TipReport|null>(null),[myReport,setMyReport]=useState<MyReport|null>(null);
 const manager=profile?.app_role==='admin'||profile?.app_role==='manager';const selectedPool=pools.find(p=>p.id===poolId)||null;const selectedRun=runs.find(r=>r.id===runId)||null;
 const runContrib=useMemo(()=>contribs.filter(c=>c.run_id===runId),[contribs,runId]);const runDist=useMemo(()=>distributions.filter(d=>d.run_id===runId),[distributions,runId]);
 useEffect(()=>{void load()},[]);
 async function load(){setBusy(true);const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}const p=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();if(p.error||!p.data?.location_id){setMessage(t('Could not load tip access.','No se pudo cargar el acceso a propinas.'));setReady(true);setBusy(false);return}const pr=p.data as Profile;setProfile(pr);
  if(!['admin','manager'].includes(pr.app_role)){const mr=await supabase.rpc('my_tip_report',{p_starts_on:range.start,p_ends_on:range.end});if(mr.error)setMessage(mr.error.message);else setMyReport(mr.data as MyReport);setReady(true);setBusy(false);return}
  const [s,pl,rc,rn,co,di,em,ro]=await Promise.all([supabase.from('tip_settings').select('enabled,employee_visibility').eq('location_id',pr.location_id).maybeSingle(),supabase.from('tip_pools').select('id,name,cadence,distribution_method,active,description').eq('location_id',pr.location_id).order('active',{ascending:false}).order('name'),supabase.from('tip_pool_receivers').select('id,pool_id,receiver_type,role_id,employee_id,weight').eq('location_id',pr.location_id),supabase.from('tip_pool_runs').select('id,pool_id,starts_on,ends_on,status,total_contributions,total_distributed,finalized_at').eq('location_id',pr.location_id).order('starts_on',{ascending:false}).limit(100),supabase.from('tip_contributions').select('id,run_id,employee_id,role_id,source,amount,note,created_at').eq('location_id',pr.location_id).order('created_at',{ascending:false}).limit(500),supabase.from('tip_distributions').select('id,run_id,employee_id,eligible_hours,receiver_weight,amount').eq('location_id',pr.location_id).limit(1000),supabase.from('employees').select('id,full_name').eq('location_id',pr.location_id).eq('active',true).is('deleted_at',null).order('full_name'),supabase.from('employee_roles').select('id,name').eq('location_id',pr.location_id).order('name')]);
  if([s,pl,rc,rn,co,di,em,ro].some(x=>x.error))setMessage(t('Some tip data could not be loaded.','No se pudieron cargar algunos datos de propinas.'));setEnabled(s.data?.enabled??true);setEmployeeVisibility(s.data?.employee_visibility??true);const ps=(pl.data??[]) as Pool[];const rs=(rn.data??[]) as Run[];setPools(ps);setReceivers((rc.data??[]) as Receiver[]);setRuns(rs);setContribs((co.data??[]) as Contribution[]);setDistributions((di.data??[]) as Distribution[]);setEmployees((em.data??[]) as Employee[]);setRoles((ro.data??[]) as Role[]);const nextPool=poolId||ps.find(x=>x.active)?.id||ps[0]?.id||'';setPoolId(nextPool);const nextRun=runId||rs.find(x=>x.pool_id===nextPool)?.id||'';setRunId(nextRun);setReady(true);setBusy(false)}
 async function refreshReport(){if(!profile?.location_id)return;setBusy(true);const rpc=manager?'tip_pool_report':'my_tip_report';const {data,error}=await supabase.rpc(rpc,{p_starts_on:range.start,p_ends_on:range.end});if(error)setMessage(error.message);else if(manager)setReport(data as TipReport);else setMyReport(data as MyReport);setBusy(false)}
 async function saveSettings(){if(!manager||!profile?.location_id||busy)return;setBusy(true);const {error}=await supabase.from('tip_settings').upsert({location_id:profile.location_id,enabled,employee_visibility:employeeVisibility},{onConflict:'location_id'});setMessage(error?error.message:t('Tip settings saved.','Configuración de propinas guardada.'));setBusy(false)}
 async function createPool(e:FormEvent){e.preventDefault();if(!manager||!profile?.location_id||busy||!poolForm.name.trim())return;setBusy(true);const {data,error}=await supabase.from('tip_pools').insert({location_id:profile.location_id,name:poolForm.name.trim().slice(0,120),cadence:poolForm.cadence,distribution_method:poolForm.method,description:poolForm.description.trim().slice(0,2000)||null}).select('id').single();if(error)setMessage(error.message);else{setPoolForm({name:'',cadence:'daily',method:'weighted_hours',description:''});setPoolId(data.id);setMessage(t('Tip pool created.','Fondo de propinas creado.'));await load()}setBusy(false)}
 async function deactivatePool(p:Pool){if(!manager||busy||!p.active)return;setBusy(true);const {error}=await supabase.from('tip_pools').update({active:false}).eq('id',p.id);setMessage(error?error.message:t('Tip pool deactivated. Historical runs remain intact.','Fondo desactivado. Los períodos históricos permanecen intactos.'));await load();setBusy(false)}
 async function addReceiver(e:FormEvent){e.preventDefault();if(!manager||!poolId||!receiver.target||busy)return;const weight=Number(receiver.weight);if(!Number.isFinite(weight)||weight<=0||weight>100)return setMessage(t('Receiver weight must be greater than 0 and at most 100.','El peso del receptor debe ser mayor que 0 y como máximo 100.'));setBusy(true);const {error}=await supabase.rpc('upsert_tip_pool_receiver',{p_pool_id:poolId,p_receiver_type:receiver.type,p_target_id:receiver.target,p_weight:weight});if(!error)setReceiver({...receiver,target:'',weight:'1'});setMessage(error?error.message:t('Tip receiver saved.','Receptor de propinas guardado.'));await load();setBusy(false)}
 async function removeReceiver(id:string){if(!manager||busy)return;setBusy(true);const {error}=await supabase.rpc('remove_tip_pool_receiver',{p_receiver_id:id});setMessage(error?error.message:t('Tip receiver removed.','Receptor de propinas eliminado.'));await load();setBusy(false)}
 async function ensureRun(){if(!manager||!poolId||busy)return;setBusy(true);const {data,error}=await supabase.rpc('ensure_tip_pool_run',{p_pool_id:poolId,p_reference_date:referenceDate});if(error)setMessage(error.message);else{const row=data as Run;setRunId(row.id);setMessage(`${t('Draft run ready','Período borrador listo')}: ${row.starts_on} – ${row.ends_on}.`);await load()}setBusy(false)}
 async function addContribution(e:FormEvent){e.preventDefault();if(!manager||!runId||busy)return;const amount=Number(contribution.amount);if(!Number.isFinite(amount)||amount===0)return setMessage(t('Contribution amount cannot be zero.','El monto de la contribución no puede ser cero.'));setBusy(true);const {error}=await supabase.rpc('add_tip_contribution',{p_run_id:runId,p_amount:amount,p_source:contribution.source,p_employee_id:contribution.employee_id||null,p_role_id:contribution.role_id||null,p_note:contribution.note.trim()||null});if(!error)setContribution({amount:'',source:'manual',employee_id:'',role_id:'',note:''});setMessage(error?error.message:t('Contribution added.','Contribución agregada.'));await load();setBusy(false)}
 async function removeContribution(id:string){if(!manager||busy)return;setBusy(true);const {error}=await supabase.rpc('remove_tip_contribution',{p_contribution_id:id});setMessage(error?error.message:t('Contribution removed.','Contribución eliminada.'));await load();setBusy(false)}
 async function runAction(action:'generate'|'finalize'|'cancel'){if(!manager||!runId||busy)return;setBusy(true);const rpc=action==='generate'?'generate_tip_distributions':action==='finalize'?'finalize_tip_pool_run':'cancel_tip_pool_run';const {error}=await supabase.rpc(rpc,{p_run_id:runId});setMessage(error?error.message:action==='generate'?t('Distributions generated from approved worked hours.','Distribuciones generadas con horas trabajadas aprobadas.'):action==='finalize'?t('Tip run finalized and locked.','Período de propinas finalizado y bloqueado.'):t('Tip run cancelled.','Período de propinas cancelado.'));await load();setBusy(false)}
 if(!ready)return <main className={styles.page}>{t('Loading tips…','Cargando propinas…')}</main>;if(!profile?.location_id)return <main className={styles.page}>{t('No restaurant location is assigned.','No hay una ubicación del restaurante asignada.')}</main>;
 if(!manager)return <main className={styles.page}><div className={styles.top}><div><h1>{t('My Tips','Mis Propinas')}</h1><p>{t('Finalized tip distributions visible to your employee account.','Distribuciones finalizadas visibles para tu cuenta de empleado.')}</p></div><Link className={styles.back} href="/tools">{t('Back to Tools','Volver a Herramientas')}</Link></div>{message&&<div className={styles.notice}>{message}</div>}<section className={styles.section}><div className={styles.card}><div className={styles.formGrid}><DateField label={t('From','Desde')} value={range.start} onChange={v=>setRange({...range,start:v})}/><DateField label={t('To','Hasta')} value={range.end} onChange={v=>setRange({...range,end:v})}/></div><div className={styles.actions}><button className={styles.button} disabled={busy} onClick={refreshReport}>{t('Refresh','Actualizar')}</button></div></div></section><div className={styles.grid}><Metric label={t('Finalized tips','Propinas finalizadas')} value={money(myReport?.total||0)}/><Metric label={t('Distributions','Distribuciones')} value={String(myReport?.distributions?.length||0)}/></div><section className={styles.section}><div className={styles.list}>{myReport?.distributions?.map(d=><div className={styles.entry} key={`${d.run_id}-${d.pool_name}`}><div className={styles.entryHead}><div><h3>{d.pool_name}</h3><small>{d.starts_on} – {d.ends_on} · {Number(d.eligible_hours).toFixed(2)} {t('eligible hours','horas elegibles')}</small></div><strong>{money(d.amount)}</strong></div></div>)}{!myReport?.distributions?.length&&<div className={styles.empty}>{t('No finalized tip distributions in this range.','No hay distribuciones finalizadas en este rango.')}</div>}</div></section></main>;
 return <main className={styles.page}>
  <div className={styles.top}><div><h1>{t('Tip Pooling','Fondos de Propinas')}</h1><p>{t('Pool rules, contributions, approved-hour distributions and payroll-ready totals.','Reglas, contribuciones, distribuciones por horas aprobadas y totales listos para nómina.')}</p></div><Link className={styles.back} href="/tools">{t('Back to Tools','Volver a Herramientas')}</Link></div>{message&&<div className={message.toLowerCase().includes('could not')?styles.error:styles.notice}>{message}</div>}
  <div className={styles.grid}><Metric label={t('Active pools','Fondos activos')} value={String(pools.filter(p=>p.active).length)}/><Metric label={t('Draft runs','Períodos borrador')} value={String(runs.filter(r=>r.status==='draft').length)}/><Metric label={t('Finalized runs','Períodos finalizados')} value={String(runs.filter(r=>r.status==='final').length)}/><Metric label={t('Selected run total','Total del período seleccionado')} value={money(selectedRun?.total_contributions||0)}/></div>
  <section className={styles.section}><div className={styles.card}><h2>{t('Settings','Configuración')}</h2><div className={styles.actions}><label className={styles.checkbox}><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>{t('Enable tip pooling','Activar fondos de propinas')}</label><label className={styles.checkbox}><input type="checkbox" checked={employeeVisibility} onChange={e=>setEmployeeVisibility(e.target.checked)}/>{t('Employees can view finalized tips','Los empleados pueden ver propinas finalizadas')}</label><button className={styles.button} disabled={busy} onClick={saveSettings}>{t('Save settings','Guardar configuración')}</button></div></div></section>
  <section className={styles.section}><div className={styles.split}><div className={styles.card}><h2>{t('Create pool','Crear fondo')}</h2><form onSubmit={createPool}><div className={styles.formGrid}><label className={styles.field}><span>{t('Name','Nombre')}</span><input maxLength={120} value={poolForm.name} onChange={e=>setPoolForm({...poolForm,name:e.target.value})}/></label><label className={styles.field}><span>{t('Cadence','Frecuencia')}</span><select value={poolForm.cadence} onChange={e=>setPoolForm({...poolForm,cadence:e.target.value as Pool['cadence']})}><option value="daily">{t('Daily','Diaria')}</option><option value="weekly">{t('Weekly','Semanal')}</option><option value="pay_period">{t('Pay period','Período de pago')}</option></select></label><label className={styles.field}><span>{t('Distribution','Distribución')}</span><select value={poolForm.method} onChange={e=>setPoolForm({...poolForm,method:e.target.value as Pool['distribution_method']})}><option value="weighted_hours">{t('Weighted hours','Horas ponderadas')}</option><option value="hours">{t('Hours','Horas')}</option><option value="equal">{t('Equal','Igual')}</option></select></label><label className={styles.field}><span>{t('Description','Descripción')}</span><input maxLength={2000} value={poolForm.description} onChange={e=>setPoolForm({...poolForm,description:e.target.value})}/></label></div><div className={styles.actions}><button className={styles.button} disabled={busy}>{t('Create pool','Crear fondo')}</button></div></form></div><div className={styles.card}><h2>{t('Pool selection','Selección de fondo')}</h2><label className={styles.field}><span>{t('Pool','Fondo')}</span><select value={poolId} onChange={e=>{setPoolId(e.target.value);const r=runs.find(x=>x.pool_id===e.target.value);setRunId(r?.id||'')}}><option value="">{t('Choose pool','Elegir fondo')}</option>{pools.map(p=><option key={p.id} value={p.id}>{p.name} · {p.active?t('active','activo'):t('inactive','inactivo')}</option>)}</select></label>{selectedPool&&<><p className={styles.muted}>{selectedPool.cadence.replace('_',' ')} · {selectedPool.distribution_method.replace('_',' ')}</p>{selectedPool.active&&<button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>deactivatePool(selectedPool)}>{t('Deactivate pool','Desactivar fondo')}</button>}</>}</div></div></section>
  {selectedPool&&<section className={styles.section}><div className={styles.card}><h2>{t('Receiving roles / employees','Puestos / empleados receptores')}</h2><form onSubmit={addReceiver}><div className={styles.formGrid}><label className={styles.field}><span>{t('Receiver type','Tipo de receptor')}</span><select value={receiver.type} onChange={e=>setReceiver({type:e.target.value as 'role'|'employee',target:'',weight:receiver.weight})}><option value="role">{t('Role','Puesto')}</option><option value="employee">{t('Employee','Empleado')}</option></select></label><label className={styles.field}><span>{t('Receiver','Receptor')}</span><select value={receiver.target} onChange={e=>setReceiver({...receiver,target:e.target.value})}><option value="">{t('Choose','Elegir')}</option>{receiver.type==='role'?roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>):employees.map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select></label><label className={styles.field}><span>{t('Weight','Peso')}</span><input type="number" min="0.01" max="100" step="0.01" value={receiver.weight} onChange={e=>setReceiver({...receiver,weight:e.target.value})}/></label></div><div className={styles.actions}><button className={styles.button} disabled={busy}>{t('Save receiver','Guardar receptor')}</button></div></form><div className={styles.list} style={{marginTop:12}}>{receivers.filter(r=>r.pool_id===poolId).map(r=><div className={styles.entry} key={r.id}><div className={styles.entryHead}><div><h3>{r.receiver_type==='role'?roles.find(x=>x.id===r.role_id)?.name:employees.find(x=>x.id===r.employee_id)?.full_name}</h3><small>{t('Weight','Peso')} {r.weight}</small></div><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>removeReceiver(r.id)}>{t('Remove','Eliminar')}</button></div></div>)}{!receivers.some(r=>r.pool_id===poolId)&&<div className={styles.empty}>{t('Add at least one receiver before generating distributions.','Agrega al menos un receptor antes de generar distribuciones.')}</div>}</div></div></section>}
  {selectedPool&&<section className={styles.section}><div className={styles.card}><h2>{t('Run','Período')}</h2><div className={styles.formGrid}><DateField label={t('Reference date','Fecha de referencia')} value={referenceDate} onChange={setReferenceDate}/><label className={styles.field}><span>{t('Existing run','Período existente')}</span><select value={runId} onChange={e=>setRunId(e.target.value)}><option value="">{t('Choose run','Elegir período')}</option>{runs.filter(r=>r.pool_id===poolId).map(r=><option key={r.id} value={r.id}>{r.starts_on} – {r.ends_on} · {r.status}</option>)}</select></label></div><div className={styles.actions}><button className={styles.button} disabled={busy||!selectedPool.active} onClick={ensureRun}>{t('Create / open run','Crear / abrir período')}</button></div>{selectedRun&&<div className={styles.details}><Detail label={t('Status','Estado')} value={selectedRun.status}/><Detail label={t('Window','Rango')} value={`${selectedRun.starts_on} – ${selectedRun.ends_on}`}/><Detail label={t('Contributions','Contribuciones')} value={money(selectedRun.total_contributions)}/><Detail label={t('Distributed','Distribuido')} value={money(selectedRun.total_distributed)}/></div>}</div></section>}
  {selectedRun?.status==='draft'&&<section className={styles.section}><div className={styles.card}><h2>{t('Contributions','Contribuciones')}</h2><form onSubmit={addContribution}><div className={styles.formGrid}><label className={styles.field}><span>{t('Amount','Monto')}</span><input type="number" step="0.01" value={contribution.amount} onChange={e=>setContribution({...contribution,amount:e.target.value})}/></label><label className={styles.field}><span>{t('Source','Origen')}</span><select value={contribution.source} onChange={e=>setContribution({...contribution,source:e.target.value})}><option value="manual">{t('Manual','Manual')}</option><option value="pos_import">{t('POS import','Importación POS')}</option><option value="adjustment">{t('Adjustment','Ajuste')}</option></select></label><label className={styles.field}><span>{t('Employee attribution (optional)','Atribución a empleado (opcional)')}</span><select value={contribution.employee_id} onChange={e=>setContribution({...contribution,employee_id:e.target.value,role_id:''})}><option value="">{t('None','Ninguna')}</option>{employees.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></label><label className={styles.field}><span>{t('Role attribution (optional)','Atribución a puesto (opcional)')}</span><select value={contribution.role_id} onChange={e=>setContribution({...contribution,role_id:e.target.value,employee_id:''})}><option value="">{t('None','Ninguna')}</option>{roles.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className={`${styles.field} ${styles.wide}`}><span>{t('Note','Nota')}</span><input maxLength={2000} value={contribution.note} onChange={e=>setContribution({...contribution,note:e.target.value})}/></label></div><div className={styles.actions}><button className={styles.button} disabled={busy}>{t('Add contribution','Agregar contribución')}</button></div></form><div className={styles.list} style={{marginTop:12}}>{runContrib.map(c=><div className={styles.entry} key={c.id}><div className={styles.entryHead}><div><h3>{money(c.amount)}</h3><small>{c.source} · {c.note||t('No note','Sin nota')}</small></div><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>removeContribution(c.id)}>{t('Remove','Eliminar')}</button></div></div>)}</div><div className={styles.actions}><button className={styles.button} disabled={busy||!runContrib.length} onClick={()=>runAction('generate')}>{t('Generate distributions','Generar distribuciones')}</button><button className={styles.button} disabled={busy||!runDist.length} onClick={()=>runAction('finalize')}>{t('Finalize & lock','Finalizar y bloquear')}</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>runAction('cancel')}>{t('Cancel run','Cancelar período')}</button></div></div></section>}
  {selectedRun&&runDist.length>0&&<section className={styles.section}><div className={styles.card}><h2>{t('Distribution preview','Vista previa de distribución')}</h2><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>{t('Employee','Empleado')}</th><th>{t('Eligible hours','Horas elegibles')}</th><th>{t('Weight','Peso')}</th><th>{t('Amount','Monto')}</th></tr></thead><tbody>{runDist.map(d=><tr key={d.id}><td>{employees.find(e=>e.id===d.employee_id)?.full_name||t('Employee','Empleado')}</td><td>{Number(d.eligible_hours).toFixed(2)}</td><td>{d.receiver_weight}</td><td>{money(d.amount)}</td></tr>)}</tbody></table></div></div></section>}
  <section className={styles.section}><div className={styles.card}><h2>{t('Tip report','Informe de propinas')}</h2><div className={styles.formGrid}><DateField label={t('From','Desde')} value={range.start} onChange={v=>setRange({...range,start:v})}/><DateField label={t('To','Hasta')} value={range.end} onChange={v=>setRange({...range,end:v})}/></div><div className={styles.actions}><button className={styles.button} disabled={busy} onClick={refreshReport}>{t('Run report','Generar informe')}</button></div>{report&&<><div className={styles.grid} style={{marginTop:12}}><Metric label={t('Distributed','Distribuido')} value={money(report.total_distributed)}/><Metric label={t('Employees','Empleados')} value={String(report.employees.length)}/><Metric label={t('Pools','Fondos')} value={String(report.pools.length)}/><Metric label={t('Partial runs excluded','Períodos parciales excluidos')} value={String(report.partially_overlapping_runs_excluded)}/></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>{t('Employee','Empleado')}</th><th>{t('Eligible hours','Horas elegibles')}</th><th>{t('Runs','Períodos')}</th><th>{t('Tips','Propinas')}</th></tr></thead><tbody>{report.employees.map(e=><tr key={e.employee_id}><td>{e.full_name}</td><td>{e.eligible_hours}</td><td>{e.runs}</td><td>{money(e.tip_amount)}</td></tr>)}</tbody></table></div></>}</div></section>
 </main>
}
function Metric({label,value}:{label:string;value:string}){return <div className={styles.metric}><span>{label}</span><strong>{value}</strong></div>}
function Detail({label,value}:{label:string;value:string}){return <div className={styles.detail}><b>{label}</b><span>{value}</span></div>}
function DateField({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className={styles.field}><span>{label}</span><input type="date" value={value} onChange={e=>onChange(e.target.value)}/></label>}
