'use client';

import {FormEvent,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase';
import {businessDateInZone} from '@/lib/intermediate-hardening';
import styles from '../ops-tools.module.css';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Employee={id:string;full_name:string};type Role={id:string;name:string};
type Pool={id:string;name:string;cadence:'daily'|'weekly'|'pay_period';distribution_method:'equal'|'hours'|'weighted_hours';active:boolean;description:string|null;created_at:string;updated_at:string};
type Receiver={id:string;pool_id:string;receiver_type:'role'|'employee';role_id:string|null;employee_id:string|null;weight:number};
type Run={id:string;pool_id:string;starts_on:string;ends_on:string;status:'draft'|'final'|'cancelled';total_contributions:number;total_distributed:number;finalized_at:string|null;cancelled_at:string|null;created_at:string};
type Contribution={id:string;run_id:string;employee_id:string|null;role_id:string|null;source:'manual'|'pos_import'|'adjustment';amount:number;note:string|null;created_at:string};
type Distribution={id:string;run_id:string;pool_id:string;employee_id:string;eligible_hours:number;receiver_weight:number;distribution_basis:number;amount:number};
type Audit={id:number;run_id:string;action:string;details:any;created_at:string};
type TipSettings={enabled:boolean;employee_visibility:boolean};
type ManagerReport={starts_on:string;ends_on:string;employees:{employee_id:string;full_name:string;tip_amount:number;eligible_hours:number;runs:number}[];pools:{pool_id:string;pool_name:string;distributed:number;runs:number}[];total_distributed:number;partially_overlapping_runs_excluded:number};
type MyReport={employee_id:string;starts_on:string;ends_on:string;total:number;distributions:{run_id:string;pool_name:string;starts_on:string;ends_on:string;eligible_hours:number;weight:number;amount:number}[]};

const today=()=>businessDateInZone();const firstOfMonth=()=>`${today().slice(0,8)}01`;const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n)||0);const n=(v:unknown,f=0)=>Number.isFinite(Number(v))?Number(v):f;

export default function TipsPage(){
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[profile,setProfile]=useState<Profile|null>(null),[settings,setSettings]=useState<TipSettings>({enabled:true,employee_visibility:true});
 const [employees,setEmployees]=useState<Employee[]>([]),[roles,setRoles]=useState<Role[]>([]),[pools,setPools]=useState<Pool[]>([]),[receivers,setReceivers]=useState<Receiver[]>([]),[runs,setRuns]=useState<Run[]>([]),[contributions,setContributions]=useState<Contribution[]>([]),[distributions,setDistributions]=useState<Distribution[]>([]),[audits,setAudits]=useState<Audit[]>([]);
 const [range,setRange]=useState({from:firstOfMonth(),to:today()}),[managerReport,setManagerReport]=useState<ManagerReport|null>(null),[myReport,setMyReport]=useState<MyReport|null>(null),[selectedRun,setSelectedRun]=useState('');
 const [poolEdit,setPoolEdit]=useState<string|null>(null),[poolForm,setPoolForm]=useState({name:'',cadence:'daily' as Pool['cadence'],distribution_method:'weighted_hours' as Pool['distribution_method'],active:true,description:''});
 const [receiverForm,setReceiverForm]=useState({pool_id:'',receiver_type:'role' as 'role'|'employee',target_id:'',weight:'1'}),[runForm,setRunForm]=useState({pool_id:'',reference_date:today()}),[contribForm,setContribForm]=useState({amount:'',source:'manual' as Contribution['source'],employee_id:'',role_id:'',note:''});
 const canManage=profile?.app_role==='admin'||profile?.app_role==='manager';
 useEffect(()=>{void init()},[]);
 async function init(){const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}const p=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();if(p.error||!p.data?.location_id){setMessage('Could not load tip access.');setReady(true);return}const pr=p.data as Profile;setProfile(pr);await load(pr,pr.location_id);setReady(true)}
 async function load(pr=profile,loc=profile?.location_id||''){if(!loc)return;setBusy(true);try{const cfg=await supabase.from('tip_settings').select('enabled,employee_visibility').eq('location_id',loc).maybeSingle();if(cfg.data)setSettings(cfg.data as TipSettings);
   if(pr?.app_role==='admin'||pr?.app_role==='manager'){
     const [e,r,pool,recv,run,con,dist,audit]=await Promise.all([
       supabase.from('employees').select('id,full_name').eq('location_id',loc).eq('active',true).is('deleted_at',null).order('full_name'),supabase.from('employee_roles').select('id,name').eq('location_id',loc).order('name'),supabase.from('tip_pools').select('id,name,cadence,distribution_method,active,description,created_at,updated_at').eq('location_id',loc).order('name'),supabase.from('tip_pool_receivers').select('id,pool_id,receiver_type,role_id,employee_id,weight').eq('location_id',loc),supabase.from('tip_pool_runs').select('id,pool_id,starts_on,ends_on,status,total_contributions,total_distributed,finalized_at,cancelled_at,created_at').eq('location_id',loc).order('starts_on',{ascending:false}).limit(150),supabase.from('tip_contributions').select('id,run_id,employee_id,role_id,source,amount,note,created_at').eq('location_id',loc).order('created_at',{ascending:false}).limit(1000),supabase.from('tip_distributions').select('id,run_id,pool_id,employee_id,eligible_hours,receiver_weight,distribution_basis,amount').eq('location_id',loc).limit(2000),supabase.from('tip_run_audit').select('id,run_id,action,details,created_at').eq('location_id',loc).order('created_at',{ascending:false}).limit(500)
     ]);setEmployees((e.data??[]) as Employee[]);setRoles((r.data??[]) as Role[]);setPools((pool.data??[]) as Pool[]);setReceivers((recv.data??[]) as Receiver[]);const runRows=(run.data??[]) as Run[];setRuns(runRows);setContributions((con.data??[]) as Contribution[]);setDistributions((dist.data??[]) as Distribution[]);setAudits((audit.data??[]) as Audit[]);const pick=selectedRun&&runRows.some(x=>x.id===selectedRun)?selectedRun:runRows[0]?.id||'';setSelectedRun(pick);const rep=await supabase.rpc('tip_pool_report',{p_starts_on:range.from,p_ends_on:range.to});if(!rep.error)setManagerReport(rep.data as ManagerReport);
   }else{const mine=await supabase.rpc('my_tip_report',{p_starts_on:range.from,p_ends_on:range.to});if(mine.error)setMessage(mine.error.message);else setMyReport(mine.data as MyReport)}
 }catch(error:any){setMessage(error?.message||'Could not load tip data.')}finally{setBusy(false)}}
 const poolName=(id:string)=>pools.find(p=>p.id===id)?.name||'Tip pool';const employeeName=(id:string|null)=>employees.find(e=>e.id===id)?.full_name||(id?'Employee':'—');const roleName=(id:string|null)=>roles.find(r=>r.id===id)?.name||(id?'Role':'—');const run=useMemo(()=>runs.find(r=>r.id===selectedRun)||null,[runs,selectedRun]);const runContrib=useMemo(()=>contributions.filter(c=>c.run_id===selectedRun),[contributions,selectedRun]);const runDist=useMemo(()=>distributions.filter(d=>d.run_id===selectedRun),[distributions,selectedRun]);const runAudit=useMemo(()=>audits.filter(a=>a.run_id===selectedRun),[audits,selectedRun]);
 async function refreshReports(){if(range.to<range.from){setMessage('Report end date must be on or after the start date.');return}setBusy(true);if(canManage){const {data,error}=await supabase.rpc('tip_pool_report',{p_starts_on:range.from,p_ends_on:range.to});setManagerReport(error?null:data as ManagerReport);setMessage(error?error.message:'Tip report refreshed.')}else{const {data,error}=await supabase.rpc('my_tip_report',{p_starts_on:range.from,p_ends_on:range.to});setMyReport(error?null:data as MyReport);setMessage(error?error.message:'Tip report refreshed.')}setBusy(false)}
 async function saveSettings(){if(!canManage||!profile?.location_id||busy)return;setBusy(true);const {error}=await supabase.from('tip_settings').upsert({location_id:profile.location_id,...settings},{onConflict:'location_id'});setMessage(error?error.message:'Tip settings saved.');await load();setBusy(false)}
 function editPool(p?:Pool){if(!p){setPoolEdit(null);setPoolForm({name:'',cadence:'daily',distribution_method:'weighted_hours',active:true,description:''})}else{setPoolEdit(p.id);setPoolForm({name:p.name,cadence:p.cadence,distribution_method:p.distribution_method,active:p.active,description:p.description||''})}}
 async function savePool(e:FormEvent){e.preventDefault();if(!canManage||!profile?.location_id||busy)return;if(!poolForm.name.trim())return setMessage('Tip pool name is required.');setBusy(true);const payload={location_id:profile.location_id,name:poolForm.name.trim().slice(0,120),cadence:poolForm.cadence,distribution_method:poolForm.distribution_method,active:poolForm.active,description:poolForm.description.trim().slice(0,2000)||null};const r=poolEdit?await supabase.from('tip_pools').update(payload).eq('id',poolEdit):await supabase.from('tip_pools').insert(payload);setMessage(r.error?r.error.message:poolEdit?'Tip pool updated.':'Tip pool created.');if(!r.error){editPool();await load()}setBusy(false)}
 async function saveReceiver(e:FormEvent){e.preventDefault();if(!canManage||!receiverForm.pool_id||!receiverForm.target_id||busy)return;setBusy(true);const {error}=await supabase.rpc('upsert_tip_pool_receiver',{p_pool_id:receiverForm.pool_id,p_receiver_type:receiverForm.receiver_type,p_target_id:receiverForm.target_id,p_weight:n(receiverForm.weight,1)});setMessage(error?error.message:'Tip receiver saved.');if(!error){setReceiverForm({...receiverForm,target_id:'',weight:'1'});await load()}setBusy(false)}
 async function removeReceiver(id:string){if(!canManage||busy||!confirm('Remove this receiving rule from future distributions? Finalized distributions remain unchanged.'))return;setBusy(true);const {error}=await supabase.rpc('remove_tip_pool_receiver',{p_receiver_id:id});setMessage(error?error.message:'Receiving rule removed.');await load();setBusy(false)}
 async function ensureRun(e:FormEvent){e.preventDefault();if(!canManage||!runForm.pool_id||busy)return;setBusy(true);const {data,error}=await supabase.rpc('ensure_tip_pool_run',{p_pool_id:runForm.pool_id,p_reference_date:runForm.reference_date});if(error)setMessage(error.message);else{const row=data as Run;setSelectedRun(row.id);setMessage(`Tip run ready: ${row.starts_on} through ${row.ends_on}.`);await load()}setBusy(false)}
 async function addContribution(e:FormEvent){e.preventDefault();if(!run||run.status!=='draft'||busy)return;const amount=n(contribForm.amount);if(amount===0)return setMessage('Contribution amount cannot be zero.');if(contribForm.source!=='adjustment'&&amount<0)return setMessage('Negative corrections must use Adjustment source.');setBusy(true);const {error}=await supabase.rpc('add_tip_contribution',{p_run_id:run.id,p_amount:amount,p_source:contribForm.source,p_employee_id:contribForm.employee_id||null,p_role_id:contribForm.role_id||null,p_note:contribForm.note.trim().slice(0,2000)||null});setMessage(error?error.message:'Contribution added.');if(!error){setContribForm({amount:'',source:'manual',employee_id:'',role_id:'',note:''});await load()}setBusy(false)}
 async function removeContribution(id:string){if(!run||run.status!=='draft'||busy)return;setBusy(true);const {error}=await supabase.rpc('remove_tip_contribution',{p_contribution_id:id});setMessage(error?error.message:'Contribution removed; audit history retained.');await load();setBusy(false)}
 async function runAction(action:'generate'|'finalize'|'cancel'){if(!run||run.status!=='draft'||busy)return;if(action==='finalize'&&!confirm('Finalize this tip run? Contributions and distributions will become immutable.'))return;setBusy(true);const name=action==='generate'?'generate_tip_distributions':action==='finalize'?'finalize_tip_pool_run':'cancel_tip_pool_run';const arg={p_run_id:run.id};const {data,error}=await supabase.rpc(name,arg);setMessage(error?error.message:action==='generate'?`Distributions generated for ${(data as any)?.recipients??0} recipient(s).`:action==='finalize'?'Tip run finalized and locked.':'Tip run cancelled; history retained.');await load();setBusy(false)}
 if(!ready)return <div className="full-loader"><span>Opening tips…</span></div>;
 return <main className={styles.page}><div className={styles.top}><div><h1>Tips & Tip Pools</h1><p>Audited tip contributions, approved-hours distribution, finalized payroll reports and employee visibility.</p></div><Link className={styles.back} href="/tools">Back to Tools</Link></div>{message&&<div className={message.toLowerCase().includes('could not')||message.toLowerCase().includes('invalid')||message.toLowerCase().includes('required')?styles.error:styles.notice}>{message}</div>}
 <section className={styles.section}><div className={styles.card}><h2>{canManage?'Tip report':'My tip report'}</h2><div className={styles.formGrid}><Field label="From"><input type="date" value={range.from} onChange={e=>setRange({...range,from:e.target.value})}/></Field><Field label="Through"><input type="date" value={range.to} onChange={e=>setRange({...range,to:e.target.value})}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy} onClick={refreshReports}>Refresh Report</button></div>{canManage&&managerReport&&<><div className={styles.grid} style={{marginTop:14}}><Metric label="Distributed" value={money(managerReport.total_distributed)}/><Metric label="Employees" value={String(managerReport.employees.length)}/><Metric label="Pools" value={String(managerReport.pools.length)}/><Metric label="Partial runs excluded" value={String(managerReport.partially_overlapping_runs_excluded)}/></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Employee</th><th>Tips</th><th>Eligible hours</th><th>Runs</th></tr></thead><tbody>{managerReport.employees.map(x=><tr key={x.employee_id}><td>{x.full_name}</td><td>{money(x.tip_amount)}</td><td>{x.eligible_hours}</td><td>{x.runs}</td></tr>)}</tbody></table></div></>}{!canManage&&myReport&&<><div className={styles.grid} style={{marginTop:14}}><Metric label="My distributed tips" value={money(myReport.total)}/><Metric label="Distributions" value={String(myReport.distributions.length)}/></div><div className={styles.list}>{myReport.distributions.map((d,i)=><div className={styles.entry} key={`${d.run_id}-${i}`}><div className={styles.entryHead}><div><b>{d.pool_name}</b><small>{d.starts_on} – {d.ends_on} · {d.eligible_hours} eligible hrs · weight {d.weight}</small></div><span className={styles.pill}>{money(d.amount)}</span></div></div>)}{!myReport.distributions.length&&<div className={styles.empty}>No finalized tip distributions in this range.</div>}</div></>}</div></section>
 {canManage&&<><section className={styles.section}><div className={styles.card}><h2>Tip settings</h2><div className={styles.formGrid}><Bool label="Tip pooling enabled" checked={settings.enabled} onChange={v=>setSettings({...settings,enabled:v})}/><Bool label="Employees can see finalized tips" checked={settings.employee_visibility} onChange={v=>setSettings({...settings,employee_visibility:v})}/></div><div className={styles.actions}><button className={styles.button} disabled={busy} onClick={saveSettings}>Save Tip Settings</button></div></div></section>
 <section className={styles.section}><div className={styles.card}><h2>Tip pools</h2><p>Once a pool has finalized history, its cadence and distribution method are locked. Create a new pool to change those accounting rules.</p><form onSubmit={savePool}><div className={styles.formGrid}><Field label="Name"><input maxLength={120} value={poolForm.name} onChange={e=>setPoolForm({...poolForm,name:e.target.value})}/></Field><Field label="Cadence"><select value={poolForm.cadence} onChange={e=>setPoolForm({...poolForm,cadence:e.target.value as Pool['cadence']})}><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="pay_period">Pay period</option></select></Field><Field label="Distribution"><select value={poolForm.distribution_method} onChange={e=>setPoolForm({...poolForm,distribution_method:e.target.value as Pool['distribution_method']})}><option value="equal">Equal</option><option value="hours">Approved worked hours</option><option value="weighted_hours">Weighted approved hours</option></select></Field><Field label="Description"><input maxLength={2000} value={poolForm.description} onChange={e=>setPoolForm({...poolForm,description:e.target.value})}/></Field><Bool label="Active" checked={poolForm.active} onChange={v=>setPoolForm({...poolForm,active:v})}/></div><div className={styles.actions}><button type="button" className={`${styles.button} ${styles.secondary}`} onClick={()=>editPool()}>New Pool</button><button className={styles.button} disabled={busy}>{poolEdit?'Save Pool':'Create Pool'}</button></div></form><div className={styles.list}>{pools.map(p=><div className={styles.entry} key={p.id}><div className={styles.entryHead}><div><h3>{p.name}</h3><small>{p.cadence.replace('_',' ')} · {p.distribution_method.replace('_',' ')} · {receivers.filter(r=>r.pool_id===p.id).length} receiving rules</small></div><span className={styles.pill}>{p.active?'active':'inactive'}</span></div><div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>editPool(p)}>Edit</button></div></div>)}</div></div></section>
 <section className={styles.section}><div className={styles.card}><h2>Receiving rules</h2><form onSubmit={saveReceiver}><div className={styles.formGrid}><Field label="Pool"><select value={receiverForm.pool_id} onChange={e=>setReceiverForm({...receiverForm,pool_id:e.target.value})}><option value="">Choose pool</option>{pools.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Receiver type"><select value={receiverForm.receiver_type} onChange={e=>setReceiverForm({...receiverForm,receiver_type:e.target.value as 'role'|'employee',target_id:''})}><option value="role">Role</option><option value="employee">Specific employee</option></select></Field><Field label={receiverForm.receiver_type==='role'?'Role':'Employee'}><select value={receiverForm.target_id} onChange={e=>setReceiverForm({...receiverForm,target_id:e.target.value})}><option value="">Choose target</option>{receiverForm.receiver_type==='role'?roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>):employees.map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select></Field><Field label="Weight"><input type="number" min="0.01" max="100" step="0.01" value={receiverForm.weight} onChange={e=>setReceiverForm({...receiverForm,weight:e.target.value})}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy||!receiverForm.pool_id||!receiverForm.target_id}>Save Receiving Rule</button></div></form><div className={styles.list}>{receivers.map(r=><div className={styles.entry} key={r.id}><div className={styles.entryHead}><div><b>{poolName(r.pool_id)} · {r.receiver_type==='role'?roleName(r.role_id):employeeName(r.employee_id)}</b><small>Weight {r.weight}</small></div><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>removeReceiver(r.id)}>Remove</button></div></div>)}</div></div></section>
 <section className={styles.section}><div className={styles.card}><h2>Tip runs</h2><form onSubmit={ensureRun}><div className={styles.formGrid}><Field label="Pool"><select value={runForm.pool_id} onChange={e=>setRunForm({...runForm,pool_id:e.target.value})}><option value="">Choose pool</option>{pools.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field><Field label="Reference date"><input type="date" value={runForm.reference_date} onChange={e=>setRunForm({...runForm,reference_date:e.target.value})}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy||!runForm.pool_id}>Open / Find Run</button></div></form><div className={styles.list}>{runs.map(r=><button key={r.id} type="button" className={styles.entry} style={{textAlign:'left',width:'100%'}} onClick={()=>setSelectedRun(r.id)}><div className={styles.entryHead}><div><b>{poolName(r.pool_id)}</b><small>{r.starts_on} – {r.ends_on} · contributions {money(r.total_contributions)} · distributed {money(r.total_distributed)}</small></div><span className={styles.pill}>{r.status}</span></div></button>)}</div></div></section>
 {run&&<section className={styles.section}><div className={styles.card}><div className={styles.entryHead}><div><h2>{poolName(run.pool_id)} · {run.starts_on} – {run.ends_on}</h2><small>Financial state is {run.status}. Finalized runs are immutable.</small></div><span className={styles.pill}>{run.status}</span></div><div className={styles.grid}><Metric label="Contributions" value={money(runContrib.reduce((s,x)=>s+Number(x.amount),0))}/><Metric label="Distributed" value={money(runDist.reduce((s,x)=>s+Number(x.amount),0))}/><Metric label="Recipients" value={String(runDist.length)}/><Metric label="Audit events" value={String(runAudit.length)}/></div>{run.status==='draft'&&<><form onSubmit={addContribution}><div className={styles.formGrid}><Field label="Amount"><input type="number" step="0.01" value={contribForm.amount} onChange={e=>setContribForm({...contribForm,amount:e.target.value})}/></Field><Field label="Source"><select value={contribForm.source} onChange={e=>setContribForm({...contribForm,source:e.target.value as Contribution['source']})}><option value="manual">Manual contribution</option><option value="pos_import">POS import</option><option value="adjustment">Adjustment (+ / -)</option></select></Field><Field label="Employee attribution (optional)"><select value={contribForm.employee_id} onChange={e=>setContribForm({...contribForm,employee_id:e.target.value})}><option value="">None</option>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select></Field><Field label="Role attribution (optional)"><select value={contribForm.role_id} onChange={e=>setContribForm({...contribForm,role_id:e.target.value})}><option value="">None</option>{roles.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></Field><Field label="Note"><input maxLength={2000} value={contribForm.note} onChange={e=>setContribForm({...contribForm,note:e.target.value})}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy}>Add Contribution</button><button type="button" className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>runAction('generate')}>Generate Distributions</button><button type="button" className={styles.button} disabled={busy||!runDist.length} onClick={()=>runAction('finalize')}>Finalize & Lock</button><button type="button" className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>runAction('cancel')}>Cancel Run</button></div></form></>}
 <h3>Contributions</h3><div className={styles.list}>{runContrib.map(c=><div className={styles.entry} key={c.id}><div className={styles.entryHead}><div><b>{money(c.amount)} · {c.source.replace('_',' ')}</b><small>{employeeName(c.employee_id)}{c.role_id?` · ${roleName(c.role_id)}`:''}{c.note?` · ${c.note}`:''}</small></div>{run.status==='draft'&&<button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>removeContribution(c.id)}>Remove</button>}</div></div>)}</div>
 <h3>Distributions</h3><div className={styles.tableWrap}>{runDist.length?<table className={styles.table}><thead><tr><th>Employee</th><th>Eligible hrs</th><th>Weight</th><th>Basis</th><th>Amount</th></tr></thead><tbody>{runDist.map(d=><tr key={d.id}><td>{employeeName(d.employee_id)}</td><td>{d.eligible_hours}</td><td>{d.receiver_weight}</td><td>{d.distribution_basis}</td><td>{money(d.amount)}</td></tr>)}</tbody></table>:<div className={styles.empty}>Generate distributions after contributions and approved time-clock hours are ready.</div>}</div>
 <h3>Audit trail</h3><div className={styles.list}>{runAudit.map(a=><div className={styles.entry} key={a.id}><b>{a.action.replaceAll('_',' ')}</b><small>{new Date(a.created_at).toLocaleString()}{a.details?` · ${JSON.stringify(a.details)}`:''}</small></div>)}</div></div></section>}</>}
 </main>
}
function Metric({label,value}:{label:string;value:string}){return <div className={styles.metric}><span>{label}</span><strong>{value}</strong></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className={styles.field}><span>{label}</span>{children}</label>}
function Bool({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className={styles.field}><span>{label}</span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/></label>}
