'use client';

import {FormEvent,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase';
import styles from '../../ops-tools.module.css';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Employee={id:string;full_name:string;user_id:string|null};
type Role={id:string;name:string};
type AvailRow={day_of_week:number;available_from:string|null;available_to:string|null;unavailable:boolean};
type AvailDraft={mode:'any'|'custom'|'unavailable';from:string;to:string};
type AvailReq={id:string;employee_id:string;request_kind:'recurring'|'temporary';effective_from:string|null;effective_to:string|null;availability_rows:any[];reason:string|null;status:string;manager_note:string|null;created_at:string};
type TimeOff={id:string;employee_id:string;starts_on:string;ends_on:string;reason:string|null;status:string;category:'unpaid'|'paid'|'paid_sick';full_day:boolean;starts_at_time:string|null;ends_at_time:string|null;manager_note:string|null;created_at:string};
type Blocked={id:string;starts_on:string;ends_on:string;role_ids:string[]|null;reason:string|null};
type Settings={availability_approval_required:boolean;temporary_availability_enabled:boolean;paid_time_off_enabled:boolean;paid_sick_time_off_enabled:boolean};

const DAYS=[{d:1,n:'Monday'},{d:2,n:'Tuesday'},{d:3,n:'Wednesday'},{d:4,n:'Thursday'},{d:5,n:'Friday'},{d:6,n:'Saturday'},{d:0,n:'Sunday'}];
const blankDraft=()=>Object.fromEntries(DAYS.map(x=>[x.d,{mode:'any',from:'10:00',to:'22:00'}])) as Record<number,AvailDraft>;
const dateLabel=(d:string)=>new Date(`${d}T12:00:00`).toLocaleDateString([],{weekday:'short',month:'short',day:'numeric',year:'numeric'});
const timeLabel=(t:string|null)=>t?new Date(`2000-01-01T${t}`).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):'';

export default function ScheduleRequestsPage(){
  const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const [profile,setProfile]=useState<Profile|null>(null),[me,setMe]=useState<Employee|null>(null),[employees,setEmployees]=useState<Employee[]>([]),[roles,setRoles]=useState<Role[]>([]);
  const [settings,setSettings]=useState<Settings>({availability_approval_required:true,temporary_availability_enabled:true,paid_time_off_enabled:false,paid_sick_time_off_enabled:false});
  const [availability,setAvailability]=useState<AvailRow[]>([]),[availRequests,setAvailRequests]=useState<AvailReq[]>([]),[timeOff,setTimeOff]=useState<TimeOff[]>([]),[blocked,setBlocked]=useState<Blocked[]>([]);
  const [availabilityKind,setAvailabilityKind]=useState<'recurring'|'temporary'>('recurring'),[availDraft,setAvailDraft]=useState<Record<number,AvailDraft>>(blankDraft),[effectiveFrom,setEffectiveFrom]=useState(''),[effectiveTo,setEffectiveTo]=useState(''),[availReason,setAvailReason]=useState('');
  const [off,setOff]=useState({category:'unpaid' as 'unpaid'|'paid'|'paid_sick',full_day:true,starts_on:'',ends_on:'',starts_at_time:'15:00',ends_at_time:'17:00',reason:''});
  const [block,setBlock]=useState({starts_on:'',ends_on:'',role_id:'',reason:''});
  const canManage=profile?.app_role==='admin'||profile?.app_role==='manager';

  useEffect(()=>{void load()},[]);
  async function load(){setBusy(true);const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}const p=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();if(p.error||!p.data?.location_id){setMessage('Could not load scheduling requests.');setReady(true);setBusy(false);return}const pr=p.data as Profile;setProfile(pr);const loc=pr.location_id!;
    const [e,r,s,a,ar,to,bl]=await Promise.all([
      supabase.from('employees').select('id,full_name,user_id').eq('location_id',loc).eq('active',true).is('deleted_at',null).order('full_name'),
      supabase.from('employee_roles').select('id,name').eq('location_id',loc).order('name'),
      supabase.from('schedule_settings').select('availability_approval_required,temporary_availability_enabled,paid_time_off_enabled,paid_sick_time_off_enabled').eq('location_id',loc).maybeSingle(),
      supabase.from('employee_availability').select('employee_id,day_of_week,available_from,available_to,unavailable').eq('location_id',loc),
      supabase.from('availability_change_requests').select('id,employee_id,request_kind,effective_from,effective_to,availability_rows,reason,status,manager_note,created_at').eq('location_id',loc).order('created_at',{ascending:false}).limit(250),
      supabase.from('time_off_requests').select('id,employee_id,starts_on,ends_on,reason,status,category,full_day,starts_at_time,ends_at_time,manager_note,created_at').eq('location_id',loc).order('created_at',{ascending:false}).limit(250),
      supabase.from('time_off_blocked_days').select('id,starts_on,ends_on,role_ids,reason').eq('location_id',loc).order('starts_on')
    ]);
    const es=(e.data??[]) as Employee[];const mine=es.find(x=>x.user_id===u.user.id)||null;setEmployees(es);setMe(mine);setRoles((r.data??[]) as Role[]);if(s.data)setSettings({...settings,...s.data});setAvailRequests((ar.data??[]) as AvailReq[]);setTimeOff((to.data??[]) as TimeOff[]);setBlocked((bl.data??[]) as Blocked[]);
    const mineAv=(a.data??[]).filter((x:any)=>x.employee_id===mine?.id) as AvailRow[];setAvailability(mineAv);const next=blankDraft();for(const row of mineAv)next[row.day_of_week]=row.unavailable?{mode:'unavailable',from:'10:00',to:'22:00'}:{mode:'custom',from:String(row.available_from||'10:00').slice(0,5),to:String(row.available_to||'22:00').slice(0,5)};setAvailDraft(next);setReady(true);setBusy(false)}
  const employeeName=(id:string)=>employees.find(x=>x.id===id)?.full_name||'Employee';
  const roleName=(id:string)=>roles.find(x=>x.id===id)?.name||'Role';
  const myAvailRequests=useMemo(()=>availRequests.filter(x=>x.employee_id===me?.id),[availRequests,me]);
  const myTimeOff=useMemo(()=>timeOff.filter(x=>x.employee_id===me?.id),[timeOff,me]);
  const pendingAvail=useMemo(()=>availRequests.filter(x=>x.status==='pending'),[availRequests]);
  const pendingOff=useMemo(()=>timeOff.filter(x=>x.status==='pending'),[timeOff]);

  async function submitAvailability(e:FormEvent){e.preventDefault();if(!me||busy)return;if(availabilityKind==='temporary'&&(!effectiveFrom||!effectiveTo||effectiveTo<effectiveFrom)){setMessage('Choose a valid temporary availability date range.');return}const rows=DAYS.filter(({d})=>availDraft[d].mode!=='any').map(({d})=>{const x=availDraft[d];return {day_of_week:d,unavailable:x.mode==='unavailable',available_from:x.mode==='custom'?x.from:null,available_to:x.mode==='custom'?x.to:null}});if(!rows.length){setMessage('Choose at least one unavailable day or custom availability window.');return}setBusy(true);const {data,error}=await supabase.rpc('submit_availability_request',{p_rows:rows,p_effective_from:availabilityKind==='temporary'?effectiveFrom:null,p_effective_to:availabilityKind==='temporary'?effectiveTo:null,p_reason:availReason.trim()||null});if(error)setMessage(error.message);else{const status=(data as any)?.status;setMessage(status==='approved'?'Availability updated.':'Availability request sent for manager approval.');setAvailReason('');await load()}setBusy(false)}
  async function cancelAvailability(id:string){if(busy)return;setBusy(true);const {error}=await supabase.rpc('cancel_my_availability_request',{p_request_id:id});setMessage(error?error.message:'Availability request cancelled.');await load();setBusy(false)}
  async function reviewAvailability(id:string,decision:'approved'|'denied'){if(!canManage||busy)return;const note=decision==='denied'?prompt('Optional note for the employee:')||null:null;setBusy(true);const {error}=await supabase.rpc('review_availability_request',{p_request_id:id,p_decision:decision,p_manager_note:note});setMessage(error?error.message:`Availability ${decision}.`);await load();setBusy(false)}
  async function submitTimeOff(e:FormEvent){e.preventDefault();if(!me||!profile?.location_id||busy)return;if(!off.starts_on||!off.ends_on||off.ends_on<off.starts_on){setMessage('Choose valid time-off dates.');return}if(!off.full_day&&(off.starts_on!==off.ends_on||off.ends_at_time<=off.starts_at_time)){setMessage('Partial time off must be one day with a valid time range.');return}setBusy(true);const {data:u}=await supabase.auth.getUser();const {error}=await supabase.from('time_off_requests').insert({location_id:profile.location_id,employee_id:me.id,starts_on:off.starts_on,ends_on:off.ends_on,reason:off.reason.trim()||null,status:'pending',requested_by:u.user?.id,category:off.category,full_day:off.full_day,starts_at_time:off.full_day?null:off.starts_at_time,ends_at_time:off.full_day?null:off.ends_at_time});setMessage(error?error.message:'Time-off request submitted.');if(!error)setOff({...off,reason:''});await load();setBusy(false)}
  async function cancelTimeOff(id:string){if(busy)return;setBusy(true);const {error}=await supabase.from('time_off_requests').update({status:'cancelled'}).eq('id',id).eq('status','pending');setMessage(error?error.message:'Time-off request cancelled.');await load();setBusy(false)}
  async function reviewTimeOff(id:string,decision:'approved'|'denied'){if(!canManage||busy)return;setBusy(true);const {error}=await supabase.rpc('review_time_off_request',{p_request_id:id,p_decision:decision});setMessage(error?error.message:`Time off ${decision}.`);await load();setBusy(false)}
  async function addBlocked(e:FormEvent){e.preventDefault();if(!canManage||!profile?.location_id||busy)return;if(!block.starts_on||!block.ends_on||block.ends_on<block.starts_on){setMessage('Choose a valid blocked-date range.');return}setBusy(true);const {error}=await supabase.from('time_off_blocked_days').insert({location_id:profile.location_id,starts_on:block.starts_on,ends_on:block.ends_on,role_ids:block.role_id?[block.role_id]:null,reason:block.reason.trim()||null});setMessage(error?error.message:'Blocked time-off dates saved.');if(!error)setBlock({starts_on:'',ends_on:'',role_id:'',reason:''});await load();setBusy(false)}
  async function removeBlocked(id:string){if(!canManage||busy)return;setBusy(true);const {error}=await supabase.from('time_off_blocked_days').delete().eq('id',id);setMessage(error?error.message:'Blocked dates removed.');await load();setBusy(false)}

  if(!ready)return <div className="full-loader"><span>Opening requests…</span></div>;
  return <main className={styles.page}>
    <div className={styles.top}><div><h1>Availability & Time Off</h1><p>Recurring availability, temporary changes, partial-day requests, PTO categories and manager approvals.</p></div><Link className={styles.back} href="/schedule">Back to Schedule</Link></div>
    {message&&<div className={styles.notice}>{message}</div>}
    {!me&&!canManage&&<div className={styles.error}>Your login is not linked to an active employee record yet.</div>}

    {me&&<><section className={styles.section}><div className={styles.card}><h2>Availability</h2><p>Recurring availability stays in effect until changed. Temporary availability overrides it only for the date range you choose.</p><form onSubmit={submitAvailability}><div className={styles.formGrid}><label className={styles.field}><span>Request type</span><select value={availabilityKind} onChange={e=>setAvailabilityKind(e.target.value as any)}><option value="recurring">Change recurring availability</option>{settings.temporary_availability_enabled&&<option value="temporary">Temporary availability</option>}</select></label>{availabilityKind==='temporary'&&<><label className={styles.field}><span>Effective from</span><input type="date" value={effectiveFrom} onChange={e=>setEffectiveFrom(e.target.value)}/></label><label className={styles.field}><span>Effective through</span><input type="date" min={effectiveFrom} value={effectiveTo} onChange={e=>setEffectiveTo(e.target.value)}/></label></>}<label className={`${styles.field} ${styles.wide}`}><span>Reason / note</span><input maxLength={1000} value={availReason} onChange={e=>setAvailReason(e.target.value)} placeholder="School, childcare, temporary commitment…"/></label></div><div className={styles.list} style={{marginTop:12}}>{DAYS.map(({d,n})=>{const x=availDraft[d];return <div className={styles.entry} key={d}><div className={styles.formGrid}><label className={styles.field}><span>{n}</span><select value={x.mode} onChange={e=>setAvailDraft(v=>({...v,[d]:{...x,mode:e.target.value as any}}))}><option value="any">No restriction</option><option value="custom">Available during</option><option value="unavailable">Unavailable</option></select></label>{x.mode==='custom'&&<><label className={styles.field}><span>From</span><input type="time" value={x.from} onChange={e=>setAvailDraft(v=>({...v,[d]:{...x,from:e.target.value}}))}/></label><label className={styles.field}><span>To</span><input type="time" value={x.to} onChange={e=>setAvailDraft(v=>({...v,[d]:{...x,to:e.target.value}}))}/></label></>}</div></div>})}</div><div className={styles.actions}><button className={styles.button} disabled={busy}>Submit Availability</button><span className={styles.muted}>{settings.availability_approval_required?'Manager approval required':'Changes apply immediately'}</span></div></form></div></section>

    <section className={styles.section}><div className={styles.card}><h2>Request time off</h2><form onSubmit={submitTimeOff}><div className={styles.formGrid}><label className={styles.field}><span>Type</span><select value={off.category} onChange={e=>setOff({...off,category:e.target.value as any})}><option value="unpaid">Unpaid</option>{settings.paid_time_off_enabled&&<option value="paid">Paid</option>}{settings.paid_sick_time_off_enabled&&<option value="paid_sick">Paid sick</option>}</select></label><label className={styles.field}><span>Duration</span><select value={off.full_day?'full':'partial'} onChange={e=>setOff({...off,full_day:e.target.value==='full'})}><option value="full">Full day(s)</option><option value="partial">Part of one day</option></select></label><label className={styles.field}><span>First day</span><input type="date" value={off.starts_on} onChange={e=>setOff({...off,starts_on:e.target.value,ends_on:off.full_day?off.ends_on:e.target.value})}/></label><label className={styles.field}><span>Last day</span><input type="date" min={off.starts_on} disabled={!off.full_day} value={off.ends_on} onChange={e=>setOff({...off,ends_on:e.target.value})}/></label>{!off.full_day&&<><label className={styles.field}><span>From</span><input type="time" value={off.starts_at_time} onChange={e=>setOff({...off,starts_at_time:e.target.value})}/></label><label className={styles.field}><span>To</span><input type="time" value={off.ends_at_time} onChange={e=>setOff({...off,ends_at_time:e.target.value})}/></label></>}<label className={`${styles.field} ${styles.wide}`}><span>Reason</span><input maxLength={2000} value={off.reason} onChange={e=>setOff({...off,reason:e.target.value})}/></label></div><div className={styles.actions}><button className={styles.button} disabled={busy}>Submit Time Off</button></div></form></div></section>

    <section className={styles.section}><h2>My requests</h2><div className={styles.list}>{[...myAvailRequests.map(x=>({kind:'Availability',id:x.id,status:x.status,title:x.request_kind==='temporary'?`${x.effective_from} – ${x.effective_to}`:'Recurring availability',detail:x.reason||'',cancel:()=>cancelAvailability(x.id)})),...myTimeOff.map(x=>({kind:'Time off',id:x.id,status:x.status,title:x.full_day?`${dateLabel(x.starts_on)} – ${dateLabel(x.ends_on)}`:`${dateLabel(x.starts_on)} · ${timeLabel(x.starts_at_time)}–${timeLabel(x.ends_at_time)}`,detail:`${x.category.replace('_',' ')}${x.reason?` · ${x.reason}`:''}`,cancel:()=>cancelTimeOff(x.id)}))].sort((a,b)=>b.id.localeCompare(a.id)).map(x=><div className={styles.entry} key={`${x.kind}-${x.id}`}><div className={styles.entryHead}><div><h3>{x.kind} · {x.title}</h3><small>{x.detail}</small></div><span className={styles.pill}>{x.status}</span></div>{x.status==='pending'&&<div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={x.cancel}>Cancel</button></div>}</div>)}</div></section></>}

    {canManage&&<><section className={styles.section}><h2>Manager approval queue</h2><div className={styles.list}>{pendingAvail.map(x=><div className={styles.entry} key={x.id}><div className={styles.entryHead}><div><h3>{employeeName(x.employee_id)} · {x.request_kind} availability</h3><small>{x.request_kind==='temporary'?`${x.effective_from} – ${x.effective_to} · `:''}{x.reason||'No reason provided'}</small></div><span className={styles.pill}>AVAILABILITY</span></div><div className={styles.details}>{(x.availability_rows||[]).map((r:any,i:number)=><div className={styles.detail} key={i}><b>{DAYS.find(d=>d.d===Number(r.day_of_week))?.n||'Day'}</b><span>{r.unavailable?'Unavailable':`${String(r.available_from).slice(0,5)}–${String(r.available_to).slice(0,5)}`}</span></div>)}</div><div className={styles.actions}><button className={styles.button} disabled={busy} onClick={()=>reviewAvailability(x.id,'approved')}>Approve</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>reviewAvailability(x.id,'denied')}>Deny</button></div></div>)}{pendingOff.map(x=><div className={styles.entry} key={x.id}><div className={styles.entryHead}><div><h3>{employeeName(x.employee_id)} · {x.category.replace('_',' ')}</h3><small>{x.full_day?`${x.starts_on} – ${x.ends_on}`:`${x.starts_on} · ${timeLabel(x.starts_at_time)}–${timeLabel(x.ends_at_time)}`}{x.reason?` · ${x.reason}`:''}</small></div><span className={styles.pill}>TIME OFF</span></div><div className={styles.actions}><button className={styles.button} disabled={busy} onClick={()=>reviewTimeOff(x.id,'approved')}>Approve</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>reviewTimeOff(x.id,'denied')}>Deny</button></div></div>)}{!pendingAvail.length&&!pendingOff.length&&<div className={styles.empty}>No scheduling requests are waiting for approval.</div>}</div></section>

    <section className={styles.section}><div className={styles.card}><h2>Blocked time-off dates</h2><p>Use this for holidays, events, or staffing-sensitive dates. Paid sick requests are still allowed to be submitted.</p><form onSubmit={addBlocked}><div className={styles.formGrid}><label className={styles.field}><span>From</span><input type="date" value={block.starts_on} onChange={e=>setBlock({...block,starts_on:e.target.value})}/></label><label className={styles.field}><span>Through</span><input type="date" min={block.starts_on} value={block.ends_on} onChange={e=>setBlock({...block,ends_on:e.target.value})}/></label><label className={styles.field}><span>Role (optional)</span><select value={block.role_id} onChange={e=>setBlock({...block,role_id:e.target.value})}><option value="">All roles</option>{roles.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select></label><label className={styles.field}><span>Reason</span><input maxLength={1000} value={block.reason} onChange={e=>setBlock({...block,reason:e.target.value})}/></label></div><div className={styles.actions}><button className={styles.button} disabled={busy}>Block Dates</button></div></form><div className={styles.list}>{blocked.map(x=><div className={styles.entry} key={x.id}><div className={styles.entryHead}><div><h3>{x.starts_on} – {x.ends_on}</h3><small>{x.role_ids?.length?x.role_ids.map(roleName).join(', '):'All roles'}{x.reason?` · ${x.reason}`:''}</small></div><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>removeBlocked(x.id)}>Remove</button></div></div>)}</div></div></section></>}
  </main>
}
