'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import {AlertTriangle,ArrowLeft,CheckCircle2,ClipboardCheck,Flag,Loader2,RefreshCw,ShieldCheck,Users} from 'lucide-react';
import {supabase} from '@/lib/supabase';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Employee={id:string;full_name:string};
type Task={task_key:string;cohort_role:'manager'|'staff';ordinal:number;label:string;critical:boolean};
type Participant={id:string;employee_id:string;employee_name:string;cohort_role:'manager'|'staff';device_label:string|null;enrolled_at:string;days_used:number;results:Record<string,Outcome>};
type Defect={id:string;severity:'P0'|'P1'|'P2'|'P3';category:string;summary:string;status:'open'|'resolved';opened_at:string;resolved_at:string|null};
type Rollout={stage_percent:number;status:'planned'|'active'|'completed'|null;schedule_cycle_verified:boolean|null;stop_triggered:boolean|null;started_at:string|null;completed_at:string|null};
type Outcome='pass'|'fail'|'confusing'|'not_applicable';
type GateSet=Record<string,boolean>;
type Mutation={attempts:number;eligible_attempts:number;successes:number;failures:number;policy_rejections:number;success_rate:number|null;successful_expected_mutations_without_commit_evidence:number;committed_mutations_without_gateway_id:number;by_operation:Array<{operation:string;attempts:number;successes:number;failures:number;policy_rejections:number}>};
type Snapshot={since:string;mutations:Mutation;participant_count:number;manager_count:number;staff_count:number;managers_with_3_days:number;staff_with_3_days:number;participants_with_7_days:number;expected_task_results:number;passed_task_results:number;not_applicable_task_results:number;task_completion_rate:number|null;critical_tasks_total:number;critical_tasks_exercised:number;open_p0_p1_defects:number;privacy_incidents:number;data_integrity_incidents:number;rollout_stages_completed:number;dogfood_exit:GateSet;closed_pilot_exit:GateSet;ga_exit:GateSet;tasks:Task[];participants:Participant[];defects:Defect[];rollout:Rollout[]};

const outcomeLabel:Record<Outcome,string>={pass:'Pass',fail:'Fail',confusing:'Confusing',not_applicable:'Not applicable'};
const formatPct=(v:number|null)=>v==null?'No evidence':`${v.toFixed(2)}%`;
const allPass=(g:GateSet)=>Object.values(g).length>0&&Object.values(g).every(Boolean);

export default function PilotScorecardPage(){
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[profile,setProfile]=useState<Profile|null>(null),[employees,setEmployees]=useState<Employee[]>([]),[snapshot,setSnapshot]=useState<Snapshot|null>(null),[message,setMessage]=useState(''),[employeeId,setEmployeeId]=useState(''),[deviceLabel,setDeviceLabel]=useState(''),[severity,setSeverity]=useState<Defect['severity']>('P2'),[category,setCategory]=useState('workflow'),[summary,setSummary]=useState('');
 useEffect(()=>{void load()},[]);
 async function load(){setLoading(true);setMessage('');const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}const p=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();const me=p.data as Profile|null;if(!me||!['admin','manager'].includes(me.app_role)){location.href='/my-work';return}setProfile(me);const [e,s]=await Promise.all([supabase.from('employees').select('id,full_name').eq('active',true).is('deleted_at',null).order('full_name').limit(500),supabase.rpc('pilot_scorecard_snapshot',{p_since:new Date(Date.now()-7*86400000).toISOString()})]);if(e.error||s.error){setMessage('Pilot evidence could not be loaded.');setEmployees((e.data??[]) as Employee[]);setSnapshot(null)}else{setEmployees((e.data??[]) as Employee[]);setSnapshot(s.data as Snapshot)}setLoading(false)}
 async function enroll(e:FormEvent){e.preventDefault();if(busy||!employeeId)return;setBusy(true);const {error}=await supabase.rpc('pilot_enroll_employee',{p_employee_id:employeeId,p_device_label:deviceLabel.trim()||null});setBusy(false);setMessage(error?'Could not enroll that participant.':'Participant enrolled.');if(!error){setEmployeeId('');setDeviceLabel('');await load()}}
 async function setResult(participantId:string,taskKey:string,outcome:Outcome){if(busy)return;setBusy(true);const {error}=await supabase.rpc('pilot_record_task_result',{p_participant_id:participantId,p_task_key:taskKey,p_outcome:outcome});setBusy(false);setMessage(error?'Could not record that task result.':'Task evidence recorded.');if(!error)await load()}
 async function deactivate(id:string){if(busy||!confirm('Remove this participant from the active pilot denominator? Historical evidence remains retained.'))return;setBusy(true);const {error}=await supabase.rpc('pilot_set_participant_active',{p_participant_id:id,p_active:false});setBusy(false);setMessage(error?'Could not update that participant.':'Participant removed from the active pilot.');if(!error)await load()}
 async function reportDefect(e:FormEvent){e.preventDefault();if(busy||summary.trim().length<3)return;setBusy(true);const {error}=await supabase.rpc('pilot_report_defect',{p_severity:severity,p_category:category,p_summary:summary.trim()});setBusy(false);setMessage(error?'Could not record that defect.':'Pilot defect recorded.');if(!error){setSummary('');await load()}}
 async function resolveDefect(id:string){if(busy)return;setBusy(true);const {error}=await supabase.rpc('pilot_resolve_defect',{p_defect_id:id});setBusy(false);setMessage(error?'Could not resolve that defect.':'Defect resolved.');if(!error)await load()}
 async function setStage(stage:number,status:'planned'|'active'|'completed'){if(busy||profile?.app_role!=='admin')return;const complete=status==='completed';if(complete&&!confirm(`Certify that the ${stage}% rollout survived a real schedule publication/change cycle with no stop condition?`))return;setBusy(true);const {error}=await supabase.rpc('pilot_set_rollout_stage',{p_stage_percent:stage,p_status:status,p_schedule_cycle_verified:complete,p_stop_triggered:false});setBusy(false);setMessage(error?'Could not update that rollout stage.':'Rollout evidence updated.');if(!error)await load()}
 const tasksByRole=useMemo(()=>({manager:(snapshot?.tasks??[]).filter(t=>t.cohort_role==='manager'),staff:(snapshot?.tasks??[]).filter(t=>t.cohort_role==='staff')}),[snapshot]);
 if(loading)return <div className="full-loader"><Loader2 className="spin"/><span>Loading pilot evidence…</span></div>;
 if(!snapshot)return <main className="page"><a href="/manager">‹ Manager</a><div className="empty-state"><AlertTriangle/><b>Pilot scorecard unavailable</b><span>{message||'No scorecard evidence is available.'}</span></div></main>;
 const m=snapshot.mutations,mutationGate=m.success_rate!=null&&m.success_rate>=99,taskGate=snapshot.task_completion_rate!=null&&snapshot.task_completion_rate>=95;
 return <div className="app-shell"><header className="topbar"><a className="round-button" href="/manager" aria-label="Back"><ArrowLeft/></a><div style={{flex:1}}><div className="brand-kicker">Release evidence</div><div className="brand-title">Pilot Scorecard</div></div><button className="round-button" disabled={busy} onClick={()=>load()} aria-label="Refresh"><RefreshCw/></button></header><main className="page">
  {message&&<div className="toast-message">{message}</div>}
  <div className="page-heading"><h1>Authoritative pilot gates</h1><p>Server-timestamped participant days, observed critical tasks, trusted mutation outcomes, defects, and staged rollout evidence. Missing evidence stays missing; it is never inferred from pageviews.</p></div>
  <div className="metric-grid"><div className="metric"><strong>{snapshot.participant_count}</strong><span>active participants</span></div><div className="metric"><strong>{formatPct(snapshot.task_completion_rate)}</strong><span>critical task completion</span></div><div className="metric"><strong>{formatPct(m.success_rate)}</strong><span>critical mutation success</span></div><div className="metric"><strong>{snapshot.open_p0_p1_defects}</strong><span>open P0/P1 defects</span></div></div>

  <div className="section-title"><h2>Exit gates</h2><span>no synthetic passes</span></div><div className="quick-grid">
   <GateCard title="Dogfood exit" pass={allPass(snapshot.dogfood_exit)} text={`${snapshot.managers_with_3_days}/3 managers · ${snapshot.staff_with_3_days}/5 staff with 3 days · ${snapshot.critical_tasks_exercised}/${snapshot.critical_tasks_total} critical tasks exercised`}/>
   <GateCard title="Closed pilot" pass={allPass(snapshot.closed_pilot_exit)} text={`${snapshot.participants_with_7_days}/${snapshot.participant_count} participants with 7 days · task ${formatPct(snapshot.task_completion_rate)} · mutations ${formatPct(m.success_rate)}`}/>
   <GateCard title="General availability" pass={allPass(snapshot.ga_exit)} text={`${snapshot.rollout_stages_completed}/3 rollout stages completed with a verified schedule cycle`}/>
  </div>

  <div className="section-title"><h2>Mutation integrity</h2><span>{mutationGate?'≥99% passing':'gate not yet met'}</span></div><div className="metric-grid"><div className="metric"><strong>{m.eligible_attempts}</strong><span>eligible attempts</span></div><div className="metric"><strong>{m.failures}</strong><span>failures</span></div><div className="metric"><strong>{m.policy_rejections}</strong><span>policy rejections excluded</span></div><div className="metric"><strong>{m.successful_expected_mutations_without_commit_evidence}</strong><span>successes missing commit evidence</span></div></div>
  {m.committed_mutations_without_gateway_id>0&&<div className="notice"><AlertTriangle/> {m.committed_mutations_without_gateway_id} committed critical mutation{m.committed_mutations_without_gateway_id===1?'':'s'} lacked a trusted gateway operation ID in the selected window.</div>}
  <details className="card"><summary><b>Operation breakdown</b></summary><div className="list">{m.by_operation.length?m.by_operation.map(o=><div className="list-item" key={o.operation}><div className="list-main"><b>{o.operation}</b><small>{o.attempts} attempts · {o.successes} success · {o.failures} failure · {o.policy_rejections} policy rejection</small></div></div>):<div className="empty-state"><ClipboardCheck/><b>No mutation evidence yet</b><span>Real critical writes will populate this section.</span></div>}</div></details>

  <div className="section-title"><h2>Participants & critical tasks</h2><span>{taskGate?'≥95% passing':'gate not yet met'}</span></div><form className="card form" onSubmit={enroll}><label>Enroll active employee<select className="select" required value={employeeId} onChange={e=>setEmployeeId(e.target.value)}><option value="">Select employee</option>{employees.filter(e=>!snapshot.participants.some(p=>p.employee_id===e.id)).map(e=><option value={e.id} key={e.id}>{e.full_name}</option>)}</select></label><label>Device / browser label (optional)<input className="input" maxLength={120} value={deviceLabel} onChange={e=>setDeviceLabel(e.target.value)} placeholder="iPhone Safari, front office iPad…"/></label><button className="btn" disabled={busy||!employeeId}><Users/> Enroll participant</button></form>
  <div className="list">{snapshot.participants.length?snapshot.participants.map(p=><details className="card" key={p.id}><summary><b>{p.employee_name}</b> · {p.cohort_role} · {p.days_used} operating day{p.days_used===1?'':'s'}</summary><div className="notice" style={{margin:'10px 0'}}>{p.device_label||'No device label'} · enrolled {new Date(p.enrolled_at).toLocaleDateString()}</div><div className="list">{tasksByRole[p.cohort_role].map(t=><div className="list-item" key={t.task_key}><div className="list-main"><b>{t.ordinal}. {t.label}</b><small>{p.results[t.task_key]?outcomeLabel[p.results[t.task_key]]:'Not observed'}</small></div><select className="select compact-select" disabled={busy} value={p.results[t.task_key]||''} onChange={e=>e.target.value&&setResult(p.id,t.task_key,e.target.value as Outcome)} aria-label={`Result for ${t.label}`}><option value="">Not observed</option>{(Object.keys(outcomeLabel) as Outcome[]).map(o=><option value={o} key={o}>{outcomeLabel[o]}</option>)}</select></div>)}</div><button className="btn secondary" disabled={busy} onClick={()=>deactivate(p.id)}>Remove from active pilot</button></details>):<div className="empty-state"><Users/><b>No participants enrolled</b><span>Enroll real managers and staff to begin the pilot denominator.</span></div>}</div>

  <div className="section-title"><h2>Pilot defects</h2><span>{snapshot.open_p0_p1_defects} open P0/P1</span></div><form className="card form" onSubmit={reportDefect}><div className="row-actions"><select className="select" value={severity} onChange={e=>setSeverity(e.target.value as Defect['severity'])}><option>P0</option><option>P1</option><option>P2</option><option>P3</option></select><select className="select" value={category} onChange={e=>setCategory(e.target.value)}><option value="privacy">Privacy</option><option value="data_integrity">Data integrity</option><option value="workflow">Workflow</option><option value="notification">Notification</option><option value="usability">Usability</option><option value="other">Other</option></select></div><input className="input" required minLength={3} maxLength={240} value={summary} onChange={e=>setSummary(e.target.value)} placeholder="Short non-sensitive defect summary"/><button className="btn" disabled={busy||summary.trim().length<3}><Flag/> Record defect</button></form>
  <div className="list">{snapshot.defects.map(d=><div className="list-item" key={d.id}><AlertTriangle/><div className="list-main"><b>{d.severity} · {d.category.replace(/_/g,' ')}</b><small>{d.summary} · {d.status}</small></div>{d.status==='open'&&<button disabled={busy} onClick={()=>resolveDefect(d.id)}>Resolve</button>}</div>)}</div>
  {(snapshot.privacy_incidents>0||snapshot.data_integrity_incidents>0)&&<div className="notice"><ShieldCheck/> Pilot history contains {snapshot.privacy_incidents} privacy incident{snapshot.privacy_incidents===1?'':'s'} and {snapshot.data_integrity_incidents} data-integrity incident{snapshot.data_integrity_incidents===1?'':'s'}. Historical incidents are never erased by resolving a defect.</div>}

  <div className="section-title"><h2>Staged general availability</h2><span>admin certification</span></div><div className="quick-grid">{snapshot.rollout.map((r,i)=>{const stage=r.stage_percent||[25,50,100][i];const status=r.status||'planned';return <div className="quick-card" key={stage}><CheckCircle2/><b>{stage}% rollout</b><small>{status}{r.schedule_cycle_verified?' · schedule cycle verified':''}{r.stop_triggered?' · STOP TRIGGERED':''}</small>{profile?.app_role==='admin'&&<div className="row-actions" style={{marginTop:8}}>{status==='planned'&&<button className="btn secondary" disabled={busy} onClick={()=>setStage(stage,'active')}>Start</button>}{status==='active'&&<button className="btn" disabled={busy} onClick={()=>setStage(stage,'completed')}>Certify cycle & complete</button>}</div>}</div>})}</div>
 </main></div>
}

function GateCard({title,pass,text}:{title:string;pass:boolean;text:string}){return <div className="quick-card">{pass?<CheckCircle2/>:<AlertTriangle/>}<b>{title}</b><small>{pass?'PASS · ':'NOT YET · '}{text}</small></div>}
