'use client';

import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, Camera, FileText, Link2, Loader2, Mic, Square, Video } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type Profile={location_id:string|null};
type Kind='photo'|'video'|'audio'|'document'|'file';
type Target={entityType:'ops_record'|'task'|'procedure'|'knowledge';entityId:string}|null;
const MAX_FILE_BYTES=50*1024*1024;

export default function CapturePage(){
  const [profile,setProfile]=useState<Profile|null>(null),[message,setMessage]=useState(''),[recording,setRecording]=useState(false),[elapsed,setElapsed]=useState(0),[loading,setLoading]=useState(true),[target,setTarget]=useState<Target>(null);
  const recorder=useRef<MediaRecorder|null>(null),chunks=useRef<Blob[]>([]),timer=useRef<number|null>(null);
  useEffect(()=>{const qs=new URLSearchParams(location.search);const entityType=qs.get('entityType'),entityId=qs.get('entityId');if(entityId&&['ops_record','task','procedure','knowledge'].includes(entityType||''))setTarget({entityType:entityType as Target extends infer T?any:never,entityId});void load();return()=>{if(timer.current)clearInterval(timer.current);if(recorder.current?.state==='recording')recorder.current.stop()}},[]);
  async function load(){const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return;}const {data}=await supabase.from('profiles').select('location_id').eq('id',u.user.id).single();setProfile(data as Profile);setLoading(false)}
  function flash(s:string){setMessage(s);setTimeout(()=>setMessage(''),4500)}
  async function upload(file:File,kind?:Kind){if(!profile?.location_id)return;if(file.size<=0)return flash('That file is empty.');if(file.size>MAX_FILE_BYTES)return flash('That file is larger than 50 MB. Use a smaller source file.');const {data:u}=await supabase.auth.getUser();if(!u.user)return;const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_').slice(-160)||'upload';const path=`${profile.location_id}/${u.user.id}/${Date.now()}-${safe}`;flash(`Uploading ${file.name}…`);const up=await supabase.storage.from('el-molino-files').upload(path,file,{contentType:file.type||undefined,upsert:false});if(up.error)return flash(up.error.message);const derived:Kind=kind||(file.type.startsWith('image/')?'photo':file.type.startsWith('video/')?'video':file.type.startsWith('audio/')?'audio':file.type==='application/pdf'?'document':'file');const {data:f,error}=await supabase.from('files').insert({location_id:profile.location_id,uploaded_by:u.user.id,file_name:file.name.slice(0,255),mime_type:file.type||null,size_bytes:file.size,storage_path:path,kind:derived,title:file.name.slice(0,255),metadata:{captured_in_app:true}}).select('id').single();if(error){await supabase.storage.from('el-molino-files').remove([path]);return flash(error.message)}if(target){const link=await supabase.from('entity_file_links').insert({location_id:profile.location_id,entity_type:target.entityType,entity_id:target.entityId,file_id:f.id,created_by:u.user.id});if(link.error){await supabase.from('files').delete().eq('id',f.id);await supabase.storage.from('el-molino-files').remove([path]);return flash(`Upload rolled back because it could not be attached: ${link.error.message}`)}}await supabase.from('activity_log').insert({location_id:profile.location_id,actor_user_id:u.user.id,action:target?'captured_and_attached':'captured',entity_type:target?.entityType||'file',entity_id:target?.entityId||f.id,summary:`Captured ${derived}: ${file.name}${target?' and attached it to the record':''}`});flash(target?'Saved and attached to the record.':'Saved to Files & Media.')}
  async function startRecording(){if(!navigator.mediaDevices?.getUserMedia)return flash('Audio recording is not supported in this browser.');try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const type=MediaRecorder.isTypeSupported('audio/webm')?'audio/webm':'';const r=new MediaRecorder(stream,type?{mimeType:type}:undefined);chunks.current=[];r.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};r.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(chunks.current,{type:r.mimeType||'audio/webm'});const ext=(r.mimeType||'').includes('mp4')?'m4a':'webm';await upload(new File([blob],`voice-note-${new Date().toISOString().replace(/[:.]/g,'-')}.${ext}`,{type:blob.type}),'audio')};recorder.current=r;r.start(500);setElapsed(0);setRecording(true);timer.current=window.setInterval(()=>setElapsed(x=>x+1),1000)}catch(e){flash(e instanceof Error?e.message:'Microphone permission was denied.')}}
  function stopRecording(){if(recorder.current?.state==='recording')recorder.current.stop();if(timer.current)clearInterval(timer.current);timer.current=null;setRecording(false)}
  function choose(e:React.ChangeEvent<HTMLInputElement>,kind?:Kind){const f=e.target.files?.[0];if(f)void upload(f,kind);e.target.value=''}
  if(loading)return <div className="full-loader"><Loader2 className="spin"/><span>Opening Capture…</span></div>;
  return <div className="app-shell"><header className="topbar"><a className="round-button" href={target?.entityType==='ops_record'?`/ops`:'/'} aria-label="Back"><ArrowLeft/></a><div style={{flex:1}}><div className="brand-kicker">El Molino Ops</div><div className="brand-title">Capture</div></div></header><main className="page">{message&&<div className="toast-message">{message}</div>}<div className="page-heading"><h1>Teach the system</h1><p>Capture what is physically in the restaurant while you are standing there.</p></div>{target&&<div className="notice" style={{marginBottom:14,display:'flex',alignItems:'center',gap:8}}><Link2 size={16}/> New captures will be attached to the record you came from.</div>}<div className="capture-grid"><label className="capture-card"><Camera/><div><b>Take a photo</b><small>Equipment, station, product, storage or setup</small></div><input hidden type="file" accept="image/*" capture="environment" onChange={e=>choose(e,'photo')}/></label><label className="capture-card"><Video/><div><b>Record video</b><small>Demonstrate a process or setup</small></div><input hidden type="file" accept="video/*" capture="environment" onChange={e=>choose(e,'video')}/></label><button className={`capture-card ${recording?'recording':''}`} onClick={recording?stopRecording:startRecording}>{recording?<Square/>:<Mic/>}<div><b>{recording?'Stop voice note':'Record voice note'}</b><small>{recording?`${Math.floor(elapsed/60)}:${String(elapsed%60).padStart(2,'0')} recording`:'Explain what you are showing or how something works'}</small></div></button><label className="capture-card"><FileText/><div><b>Add a document</b><small>Manual, invoice, recipe sheet, spreadsheet or PDF</small></div><input hidden type="file" accept=".pdf,.doc,.docx,.csv,.xlsx,.txt,image/*" onChange={e=>choose(e)}/></label></div><div className="notice" style={{marginTop:16}}>Captured files are stored privately in the Johns Island file library. Files are limited to 50 MB per upload. AI interpretation/transcription is a separate processing step so the original source is always preserved.</div></main></div>;
}
