'use client';

import {useEffect,useState} from 'react';
import {AlertTriangle,ArrowLeft,CheckCircle2,Copy,Loader2,RefreshCw,RotateCcw,ShieldCheck,Trash2} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import {useI18n} from '@/lib/i18n';

type Profile={app_role:string};
type Health={ok:boolean;checks?:{name:string;ok:boolean;required:boolean;detail?:string}[];ai?:{mode:string;providers:Record<string,boolean>}};
type Duplicate={entity_type:string;left_id:string;left_title:string;right_id:string;right_title:string;score:number};
type Trash={table:'ops_records'|'tasks'|'employees'|'knowledge_items'|'procedures';id:string;title:string;deleted_at:string};

export default function DiagnosticsPage(){
 const {locale}=useI18n();
 const c=locale==='es'?{restoreError:'No se pudo restaurar ese registro.',already:'Ese registro ya fue restaurado o modificado en otro lugar.',restored:(title:string)=>`${title} restaurado.`,running:'Ejecutando diagnósticos…',back:'Atrás',title:'Diagnósticos',refresh:'Actualizar',health:'Estado del sistema',healthBody:'Estado de producción, recuperación y detección de duplicados para administradores.',live:'Estado en vivo',healthy:'saludable',attention:'requiere atención',required:'requerido',optional:'opcional',ok:'bien',fail:'fallo',aiMode:'Modo de IA',providers:'Proveedores gratuitos configurados',none:'ninguno; el respaldo local permanece activo',duplicates:'Posibles duplicados',similarity:'similitud',noDupes:'No se encontraron duplicados probables',noDupesBody:'Conocimiento y procedimientos superaron el umbral de similitud actual.',trash:'Papelera recuperable',restore:'Restaurar',empty:'La papelera está vacía',emptyBody:'No hay registros recuperables esperando.',table:(s:string)=>s==='tasks'?'tareas':s==='ops_records'?'registros operativos':s==='employees'?'empleados':s==='knowledge_items'?'conocimiento':s==='procedures'?'procedimientos':s.replaceAll('_',' ')}:{restoreError:'Could not restore that record.',already:'That record was already restored or changed elsewhere.',restored:(title:string)=>`${title} restored.`,running:'Running diagnostics…',back:'Back',title:'Diagnostics',refresh:'Refresh',health:'System health',healthBody:'Production health, recovery and duplicate detection for administrators.',live:'Live health',healthy:'healthy',attention:'attention',required:'required',optional:'optional',ok:'ok',fail:'fail',aiMode:'AI mode',providers:'Configured free providers',none:'none; local fallback remains active',duplicates:'Potential duplicates',similarity:'similarity',noDupes:'No likely duplicates found',noDupesBody:'Knowledge and procedures passed the current similarity threshold.',trash:'Recoverable trash',restore:'Restore',empty:'Trash is empty',emptyBody:'No recoverable records are waiting.',table:(s:string)=>s.replaceAll('_',' ')};
 const localeCode=locale==='es'?'es-US':'en-US';
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[health,setHealth]=useState<Health|null>(null),[dupes,setDupes]=useState<Duplicate[]>([]),[trash,setTrash]=useState<Trash[]>([]);
 useEffect(()=>{void load()},[]);
 async function load(){setLoading(true);const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return;}const p=await supabase.from('profiles').select('app_role').eq('id',u.user.id).single();if((p.data as Profile)?.app_role!=='admin'){location.href='/';return;}const [h,k,pr,t,o,e]=await Promise.all([fetch('/api/health',{cache:'no-store'}).then(r=>r.json()).catch(()=>null),supabase.rpc('find_potential_duplicates',{p_entity:'knowledge',p_threshold:.62}),supabase.rpc('find_potential_duplicates',{p_entity:'procedure',p_threshold:.62}),supabase.from('tasks').select('id,title,deleted_at').not('deleted_at','is',null),supabase.from('ops_records').select('id,title,deleted_at').not('deleted_at','is',null),supabase.from('employees').select('id,full_name,deleted_at').not('deleted_at','is',null)]);const [dt,do_,de]=[t.data??[],o.data??[],e.data??[]];const [dk,dp]=[k.data??[],pr.data??[]];const [kk,pp]=await Promise.all([supabase.from('knowledge_items').select('id,title,deleted_at').not('deleted_at','is',null),supabase.from('procedures').select('id,title,deleted_at').not('deleted_at','is',null)]);setHealth(h);setDupes([...(dk as Duplicate[]),...(dp as Duplicate[])]);setTrash([...(dt as any[]).map(x=>({...x,table:'tasks'})),...(do_ as any[]).map(x=>({...x,table:'ops_records'})),...(de as any[]).map(x=>({id:x.id,title:x.full_name,deleted_at:x.deleted_at,table:'employees'})),...((kk.data??[]) as any[]).map(x=>({...x,table:'knowledge_items'})),...((pp.data??[]) as any[]).map(x=>({...x,table:'procedures'}))] as Trash[]);setLoading(false)}
 function flash(x:string){setMessage(x);setTimeout(()=>setMessage(''),3500)}
 async function restore(row:Trash){if(busy)return;setBusy(true);const {data,error}=await supabase.from(row.table).update({deleted_at:null}).eq('id',row.id).not('deleted_at','is',null).select('id').maybeSingle();setBusy(false);if(error)return flash(c.restoreError);if(!data){await load();return flash(c.already)}await load();flash(c.restored(row.title))}
 if(loading)return <div className="full-loader"><Loader2 className="spin"/><span>{c.running}</span></div>;
 return <div className="app-shell"><header className="topbar"><a className="round-button" href="/admin" aria-label={c.back}><ArrowLeft/></a><div style={{flex:1}}><div className="brand-kicker">El Molino Ops</div><div className="brand-title">{c.title}</div></div><button disabled={busy} className="round-button" onClick={()=>load()} aria-label={c.refresh}><RefreshCw/></button></header><main className="page">{message&&<div className="toast-message" role="status">{message}</div>}<div className="page-heading"><h1>{c.health}</h1><p>{c.healthBody}</p></div><div className="section-title"><h2>{c.live}</h2><span>{health?.ok?c.healthy:c.attention}</span></div><div className="list">{health?.checks?.map(x=><div className="list-item" key={x.name}>{x.ok?<CheckCircle2/>:<AlertTriangle/>}<div className="list-main"><b>{x.name.replace(/_/g,' ')}</b><small>{x.detail||''}{x.required?` · ${c.required}`:` · ${c.optional}`}</small></div><span className="status">{x.ok?c.ok:c.fail}</span></div>)}</div>{health?.ai&&<div className="notice" style={{marginTop:12}}><ShieldCheck size={16}/> {c.aiMode}: {health.ai.mode}. {c.providers}: {Object.entries(health.ai.providers).filter(([,v])=>v).map(([k])=>k).join(', ')||c.none}.</div>}<div className="section-title"><h2>{c.duplicates}</h2><span>{dupes.length}</span></div>{dupes.length?<div className="list">{dupes.slice(0,50).map((d,i)=><div className="list-item" key={`${d.left_id}-${d.right_id}-${i}`}><Copy/><div className="list-main"><b>{d.left_title} ↔ {d.right_title}</b><small>{d.entity_type} · {c.similarity} {Math.round(Number(d.score)*100)}%</small></div></div>)}</div>:<div className="empty-state"><CheckCircle2/><b>{c.noDupes}</b><span>{c.noDupesBody}</span></div>}<div className="section-title"><h2>{c.trash}</h2><span>{trash.length}</span></div>{trash.length?<div className="list">{trash.map(r=><div className="list-item" key={`${r.table}-${r.id}`}><Trash2/><div className="list-main"><b>{r.title}</b><small>{c.table(r.table)} · {new Date(r.deleted_at).toLocaleString(localeCode)}</small></div><button disabled={busy} className="mini-action" onClick={()=>restore(r)}><RotateCcw size={13}/> {c.restore}</button></div>)}</div>:<div className="empty-state"><Trash2/><b>{c.empty}</b><span>{c.emptyBody}</span></div>}</main></div>;
}
