'use client';

import { useEffect, useState } from 'react';
import { AlertTriangle, ArrowLeft, CheckCircle2, Copy, Loader2, RefreshCw, RotateCcw, ShieldCheck, Trash2 } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type Profile={app_role:string};
type Health={ok:boolean;checks?:{name:string;ok:boolean;required:boolean;detail?:string}[];ai?:{mode:string;providers:Record<string,boolean>}};
type Duplicate={entity_type:string;left_id:string;left_title:string;right_id:string;right_title:string;score:number};
type Trash={table:'ops_records'|'tasks'|'employees'|'knowledge_items'|'procedures';id:string;title:string;deleted_at:string};

export default function DiagnosticsPage(){
 const [loading,setLoading]=useState(true),[message,setMessage]=useState(''),[health,setHealth]=useState<Health|null>(null),[dupes,setDupes]=useState<Duplicate[]>([]),[trash,setTrash]=useState<Trash[]>([]);
 useEffect(()=>{void load()},[]);
 async function load(){setLoading(true);const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return;}const p=await supabase.from('profiles').select('app_role').eq('id',u.user.id).single();if((p.data as Profile)?.app_role!=='admin'){location.href='/';return;}const [h,k,pr,t,o,e]=await Promise.all([fetch('/api/health',{cache:'no-store'}).then(r=>r.json()).catch(()=>null),supabase.rpc('find_potential_duplicates',{p_entity:'knowledge',p_threshold:.62}),supabase.rpc('find_potential_duplicates',{p_entity:'procedure',p_threshold:.62}),supabase.from('tasks').select('id,title,deleted_at').not('deleted_at','is',null),supabase.from('ops_records').select('id,title,deleted_at').not('deleted_at','is',null),supabase.from('employees').select('id,full_name,deleted_at').not('deleted_at','is',null)]);const [dt,do_,de]=[t.data??[],o.data??[],e.data??[]];const [dk,dp]=[k.data??[],pr.data??[]];const [kk,pp]=await Promise.all([supabase.from('knowledge_items').select('id,title,deleted_at').not('deleted_at','is',null),supabase.from('procedures').select('id,title,deleted_at').not('deleted_at','is',null)]);setHealth(h);setDupes([...(dk as Duplicate[]),...(dp as Duplicate[])]);setTrash([...(dt as any[]).map(x=>({...x,table:'tasks'})),...(do_ as any[]).map(x=>({...x,table:'ops_records'})),...(de as any[]).map(x=>({id:x.id,title:x.full_name,deleted_at:x.deleted_at,table:'employees'})),...((kk.data??[]) as any[]).map(x=>({...x,table:'knowledge_items'})),...((pp.data??[]) as any[]).map(x=>({...x,table:'procedures'}))] as Trash[]);setLoading(false)}
 function flash(x:string){setMessage(x);setTimeout(()=>setMessage(''),3500)}
 async function restore(row:Trash){const {error}=await supabase.from(row.table).update({deleted_at:null}).eq('id',row.id);if(error)return flash(error.message);await load();flash(`${row.title} restored.`)}
 if(loading)return <div className="full-loader"><Loader2 className="spin"/><span>Running diagnostics…</span></div>;
 return <div className="app-shell"><header className="topbar"><a className="round-button" href="/admin" aria-label="Back"><ArrowLeft/></a><div style={{flex:1}}><div className="brand-kicker">El Molino Ops</div><div className="brand-title">Diagnostics</div></div><button className="round-button" onClick={()=>load()} aria-label="Refresh"><RefreshCw/></button></header><main className="page">{message&&<div className="toast-message">{message}</div>}<div className="page-heading"><h1>System health</h1><p>Production health, recovery and duplicate detection for administrators.</p></div><div className="section-title"><h2>Live health</h2><span>{health?.ok?'healthy':'attention'}</span></div><div className="list">{health?.checks?.map(c=><div className="list-item" key={c.name}>{c.ok?<CheckCircle2/>:<AlertTriangle/>}<div className="list-main"><b>{c.name.replace(/_/g,' ')}</b><small>{c.detail||''}{c.required?' · required':' · optional'}</small></div><span className="status">{c.ok?'ok':'fail'}</span></div>)}</div>{health?.ai&&<div className="notice" style={{marginTop:12}}><ShieldCheck size={16}/> AI mode: {health.ai.mode}. Configured free providers: {Object.entries(health.ai.providers).filter(([,v])=>v).map(([k])=>k).join(', ')||'none; local fallback remains active'}.</div>}<div className="section-title"><h2>Potential duplicates</h2><span>{dupes.length}</span></div>{dupes.length?<div className="list">{dupes.slice(0,50).map((d,i)=><div className="list-item" key={`${d.left_id}-${d.right_id}-${i}`}><Copy/><div className="list-main"><b>{d.left_title} ↔ {d.right_title}</b><small>{d.entity_type} · similarity {Math.round(Number(d.score)*100)}%</small></div></div>)}</div>:<div className="empty-state"><CheckCircle2/><b>No likely duplicates found</b><span>Knowledge and procedures passed the current similarity threshold.</span></div>}<div className="section-title"><h2>Recoverable trash</h2><span>{trash.length}</span></div>{trash.length?<div className="list">{trash.map(r=><div className="list-item" key={`${r.table}-${r.id}`}><Trash2/><div className="list-main"><b>{r.title}</b><small>{r.table.replace(/_/g,' ')} · {new Date(r.deleted_at).toLocaleString()}</small></div><button className="mini-action" onClick={()=>restore(r)}><RotateCcw size={13}/> Restore</button></div>)}</div>:<div className="empty-state"><Trash2/><b>Trash is empty</b><span>No recoverable records are waiting.</span></div>}</main></div>;
}
