'use client';

import {useEffect,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase';
import {addDateDays,dateDayOfWeek} from '@/lib/scheduling-engine';
import {businessDateInZone} from '@/lib/intermediate-hardening';
import styles from '../../ops-tools.module.css';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Period={id:string;starts_on:string;ends_on:string;status:string;revision:number};
type Issue={severity:string;code:string;date?:string;requirement_id?:string;name?:string;required?:number;target?:number;assigned?:number;count?:number;employee_name?:string;hours?:number;limit?:number;required_hours?:number;actual_hours?:number;cutoff?:string;source?:'coverage'|'compliance'};
const mondayOf=(date:string)=>addDateDays(date,-((dateDayOfWeek(date)+6)%7));

export default function ScheduleWarningsPage(){
  const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[profile,setProfile]=useState<Profile|null>(null),[period,setPeriod]=useState<Period|null>(null),[week,setWeek]=useState(mondayOf(businessDateInZone())),[issues,setIssues]=useState<Issue[]>([]),[lastFix,setLastFix]=useState<any>(null);
  const canManage=profile?.app_role==='admin'||profile?.app_role==='manager';
  useEffect(()=>{void init()},[]);
  async function init(){const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}const p=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();if(p.error||!p.data?.location_id){setMessage('Could not load scheduling warnings.');setReady(true);return}setProfile(p.data as Profile);await loadWeek(week,p.data as Profile);setReady(true)}
  async function loadWeek(ws=week,pr=profile){if(!pr?.location_id)return;setBusy(true);let row:any=null;if(pr.app_role==='admin'||pr.app_role==='manager'){const r=await supabase.rpc('ensure_schedule_period',{p_starts_on:ws});if(r.error)setMessage(r.error.message);else row=r.data}else{const r=await supabase.from('schedule_periods').select('id,starts_on,ends_on,status,revision').eq('location_id',pr.location_id).eq('starts_on',ws).maybeSingle();row=r.data}setPeriod(row as Period|null);if(row)await validate(row.id,pr);else setIssues([]);setBusy(false)}
  async function validate(id=period?.id,pr=profile){if(!id)return;const coverage=await supabase.rpc('schedule_period_validation',{p_period_id:id});if(coverage.error){setMessage(coverage.error.message);return}let combined=((Array.isArray(coverage.data)?coverage.data:[]) as Issue[]).map(x=>({...x,source:'coverage' as const}));if(pr?.app_role==='admin'||pr?.app_role==='manager'){const compliance=await supabase.rpc('schedule_compliance_warnings',{p_period_id:id});if(compliance.error)setMessage(compliance.error.message);else combined=combined.concat(((Array.isArray(compliance.data)?compliance.data:[]) as Issue[]).map(x=>({...x,source:'compliance' as const})))}setIssues(combined)}
  async function changeWeek(days:number){const ws=addDateDays(week,days);setWeek(ws);setLastFix(null);await loadWeek(ws)}
  async function quickFix(toTarget:boolean){if(!period||!canManage||busy)return;if(period.status!=='draft'){setMessage('Reopen the schedule before using Quick Fix.');return}setBusy(true);const {data,error}=await supabase.rpc('quick_fix_schedule_period',{p_period_id:period.id,p_fill_to_target:toTarget});if(error)setMessage(error.message);else{setLastFix(data);setMessage(toTarget?'Quick Fix filled as much target coverage as safely possible.':'Quick Fix filled minimum coverage wherever safely possible.');await validate(period.id)}setBusy(false)}
  const errorCount=issues.filter(x=>x.severity==='error').length,warningCount=issues.filter(x=>x.severity==='warning').length,complianceCount=issues.filter(x=>x.source==='compliance').length;
  if(!ready)return <div className="full-loader"><span>Checking schedule…</span></div>;
  return <main className={styles.page}><div className={styles.top}><div><h1>Warnings & Quick Fix</h1><p>Coverage, rest, youth-scheduling and open-shift warnings in one place. Quick Fix only fills coverage gaps; it never overrides compliance rules.</p></div><Link className={styles.back} href="/schedule">Back to Schedule</Link></div>{message&&<div className={styles.notice}>{message}</div>}
    {!canManage&&<div className={styles.error}>Manager access is required for Quick Fix and manager-only compliance warnings.</div>}
    <section className={styles.section}><div className={styles.card}><div className={styles.entryHead}><div><h2>{week} – {addDateDays(week,6)}</h2><small>{period?`${period.status.toUpperCase()} · revision ${period.revision}`:'No schedule period'}</small></div><div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>changeWeek(-7)}>Previous</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>changeWeek(7)}>Next</button></div></div><div className={styles.grid}><Metric label="Errors" value={String(errorCount)}/><Metric label="Warnings" value={String(warningCount)}/><Metric label="Compliance" value={String(complianceCount)}/><Metric label="Status" value={issues.length?'Needs review':'Clear'}/></div>{canManage&&<div className={styles.actions}><button className={styles.button} disabled={busy||!period||period.status!=='draft'} onClick={()=>quickFix(false)}>Quick Fix Minimum</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy||!period||period.status!=='draft'} onClick={()=>quickFix(true)}>Fill Toward Target</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy||!period} onClick={()=>validate()}>Recheck</button><Link className={`${styles.button} ${styles.secondary}`} href="/schedule/pool">Open Shift Pool</Link><Link className={`${styles.button} ${styles.secondary}`} href="/schedule/compliance">Compliance Setup</Link></div>}</div></section>
    {lastFix&&<section className={styles.section}><div className={styles.card}><h2>Last Quick Fix result</h2><div className={styles.grid}><Metric label="Assigned" value={String(lastFix.filled_shifts??0)}/><Metric label="Open shifts created" value={String(lastFix.created_open_shifts??0)}/><Metric label="Open shifts reused" value={String(lastFix.reused_open_shifts??0)}/><Metric label="Unsafe attempts rejected" value={String(lastFix.rejected_candidate_attempts??0)}/></div><p>Rejected attempts are expected safety behavior: the database refused a candidate that failed a hard rule, and Quick Fix continued searching instead of forcing the assignment.</p></div></section>}
    <section className={styles.section}><h2>Current warnings</h2><div className={styles.list}>{issues.map((x,i)=><div className={styles.entry} key={`${x.source}-${x.code}-${x.date||''}-${i}`}><div className={styles.entryHead}><div><h3>{String(x.name||x.code).replaceAll('_',' ')}</h3><small>{x.employee_name?`${x.employee_name} · `:''}{x.date?`${x.date} · `:''}{x.required!==undefined?`${x.assigned??0}/${x.required} minimum`:x.target!==undefined?`${x.assigned??0}/${x.target} target`:x.count!==undefined?`${x.count} shift(s)`:x.hours!==undefined?`${Number(x.hours).toFixed(1)} hrs${x.limit!==undefined?` / ${x.limit} limit`:''}`:x.required_hours!==undefined?`${x.actual_hours??0}/${x.required_hours} rest hrs`:x.cutoff?`cutoff ${String(x.cutoff).slice(0,5)}`:''}</small></div><span className={styles.pill}>{x.source} · {x.severity}</span></div>{x.code==='open_shifts'&&<div className={styles.actions}><Link className={styles.button} href="/schedule/pool">View Open Shifts</Link></div>}{x.source==='compliance'&&<div className={styles.actions}><Link className={`${styles.button} ${styles.secondary}`} href="/schedule/compliance">Review Compliance Data</Link></div>}</div>)}{!issues.length&&<div className={styles.empty}>No schedule warnings for this week.</div>}</div></section>
  </main>
}
function Metric({label,value}:{label:string;value:string}){return <div className={styles.metric}><span>{label}</span><strong>{value}</strong></div>}
