import test from 'node:test';import assert from 'node:assert/strict';
import {canPreviewMime,dependencyCreatesCycle,endNotBeforeStart,hasDuplicateHeaders,isTaskTerminal,isValidEntityId,safeDateInput,safeMoney,safePageLimit,safeStorageSegment,stableUnique,strongEnoughPassword,toIsoOrNull,uniqueHeaders,validCsvShape,validEmail,validFileName,validRecurrenceInput,validTarget} from '../lib/app-hardening.ts';

test('100 unique cross-app adversarial conditions are guarded',()=>{
let n=0;const c=(ok:boolean)=>{n++;assert.equal(ok,true,`case ${n}`)};
// Calendar/date integrity 1-15
c(safeDateInput('not-a-date')===null);c(toIsoOrNull('')===null);c(endNotBeforeStart('2026-08-12T12:00','2026-08-12T11:59')===false);c(endNotBeforeStart('2026-08-12T12:00','2026-08-12T12:00'));c(safeDateInput('2026-02-30T12:00')!==null);c(validRecurrenceInput('FREQ=HOURLY')===false);c(validRecurrenceInput('DROP TABLE')===false);c(validRecurrenceInput('FREQ=WEEKLY;BYDAY=MO'));c(validRecurrenceInput(''));c(safeDateInput('\u0000')===null);c(endNotBeforeStart('',''));c(endNotBeforeStart('2026-08-12T12:00',''));c(toIsoOrNull('bogus')===null);c(validRecurrenceInput('freq=daily'));c(validRecurrenceInput('FREQ=YEARLY')===false);
// CSV/import 16-35
c(hasDuplicateHeaders(['Name','name']));c(hasDuplicateHeaders(['a','b'])===false);c(new Set(uniqueHeaders(['Name','name'])).size===2);c(uniqueHeaders(['',''])[0]==='column_1');c(validCsvShape([],[])===false);c(validCsvShape(['a'],[])===false);c(validCsvShape(Array(201).fill('x'),[{}])===false);c(validCsvShape(['a'],Array(5001).fill({}))===false);c(validCsvShape(['a'],[{a:'1'}]));c(uniqueHeaders(['A','A','A'])[2]==='A_3');c(uniqueHeaders([' A ','a'])[1]==='a_2');c(hasDuplicateHeaders(['',''])===false);c(uniqueHeaders(['','x'])[0]==='column_1');c(uniqueHeaders(['x',''])[1]==='column_2');c(validCsvShape(Array(200).fill('x'),[{}]));c(validCsvShape(['a'],Array(5000).fill({})));c(uniqueHeaders(['x','X'])[0]==='x');c(uniqueHeaders(['x','X'])[1]==='X_2');c(hasDuplicateHeaders([' x ','X']));c(validCsvShape(['a','b'],[{a:'',b:''}]));
// Files/capture 36-55
c(validFileName('')===false);c(validFileName('x'.repeat(256))===false);c(validFileName('ok.pdf'));c(validFileName('bad\u0000.pdf')===false);c(safeStorageSegment('../../a.pdf').includes('/')===false);c(safeStorageSegment('a b.pdf')==='a_b.pdf');c(safeStorageSegment('')==='upload');c(canPreviewMime('application/pdf'));c(canPreviewMime('image/png'));c(canPreviewMime('video/mp4'));c(canPreviewMime('audio/webm'));c(canPreviewMime('text/plain'));c(canPreviewMime('application/x-msdownload')===false);c(isValidEntityId('bad')===false);c(isValidEntityId('550e8400-e29b-41d4-a716-446655440000'));c(validTarget('task','550e8400-e29b-41d4-a716-446655440000'));c(validTarget('evil','550e8400-e29b-41d4-a716-446655440000')===false);c(validTarget('task','../x')===false);c(safeStorageSegment('é report.pdf').includes(' ')===false);c(safeStorageSegment('a///b')==='a_b');
// Task/dependency 56-75
const deps=[{task_id:'b',depends_on_task_id:'a'},{task_id:'c',depends_on_task_id:'b'}];c(dependencyCreatesCycle('a','c',deps));c(dependencyCreatesCycle('a','a',deps));c(dependencyCreatesCycle('d','a',deps)===false);c(dependencyCreatesCycle('b','c',deps));c(dependencyCreatesCycle('x','y',[])===false);c(isTaskTerminal('done'));c(isTaskTerminal('cancelled'));c(isTaskTerminal('open')===false);c(isTaskTerminal('DONE'));c(safePageLimit(-1)===1);c(safePageLimit(0)===1);c(safePageLimit(1001)===1000);c(safePageLimit(NaN)===50);c(safePageLimit(12.9)===12);c(stableUnique([{id:'a'},{id:'a'},{id:'b'}],x=>x.id).length===2);c(dependencyCreatesCycle('a','b',[{task_id:'b',depends_on_task_id:'c'},{task_id:'c',depends_on_task_id:'a'}]));c(dependencyCreatesCycle('a','z',[{task_id:'z',depends_on_task_id:'y'}])===false);c(isTaskTerminal(' cancelled '));c(safePageLimit(Infinity)===50);c(stableUnique(['a','a','b'],x=>x).join(',')==='a,b');
// Account/input 76-90
c(validEmail('a@b.com'));c(validEmail('a@b')===false);c(validEmail('a b@c.com')===false);c(validEmail('')===false);c(strongEnoughPassword('abcdefghij')===false);c(strongEnoughPassword('1234567890')===false);c(strongEnoughPassword('abc1234567'));c(strongEnoughPassword('short1')===false);c(safeMoney(-2)===0);c(safeMoney(12.5)===12.5);c(safeMoney(null)===null);c(safeMoney(Number.NaN)===null);c(validEmail(' A@B.COM '));c(strongEnoughPassword('ABCDEFGHI1'));c(safeMoney(Infinity)===null);
// Boundary/dedupe 91-100
c(safePageLimit(1)===1);c(safePageLimit(1000)===1000);c(validFileName('a'.repeat(255)));c(canPreviewMime(null)===false);c(validTarget('procedure','550e8400-e29b-41d4-a716-446655440000'));c(validTarget('knowledge','550e8400-e29b-41d4-a716-446655440000'));c(validTarget('ops_record','550e8400-e29b-41d4-a716-446655440000'));c(stableUnique([],x=>String(x)).length===0);c(uniqueHeaders(['Name','NAME','name']).join('|')==='Name|NAME_2|name_3');c(validRecurrenceInput('FREQ=MONTHLY'));
assert.equal(n,100);
});
