import test from 'node:test';import assert from 'node:assert/strict';import {basicConversationAnswer,clearlyUnrelated,contextualSearchQuestion,isCapability,isCapabilityFollowup} from '../lib/ask-conversation.ts';
const h=(...x:[('user'|'assistant'),string][])=>x.map(([role,content])=>({role,content}));
test('Ask El Molino behaves conversationally and only restricts subject matter',()=>{
assert.ok(isCapability('Hey, what is every thing you can do?'));
assert.ok(isCapability('What can you do?'));
assert.ok(isCapability('Tell me what you can do.'));
assert.match(basicConversationAnswer('Hi')||'',/Hey/);
assert.match(basicConversationAnswer("I'm confused",h(['assistant','Task Center handles assignments.']))||'',/explain that differently/i);
assert.match(basicConversationAnswer('Where did you get that from?',h(['assistant','I can answer questions about this app and El Molino.']))||'',/app.*feature|reference/i);
assert.match(basicConversationAnswer('Where did you get that from?',h(['assistant','From approved internal El Molino knowledge I found: hours']))||'',/approved information/i);
assert.match(basicConversationAnswer("That's not what I asked",h(['assistant','Wrong answer']))||'',/misunderstood/i);
assert.equal(basicConversationAnswer('Repeat your last answer',h(['assistant','Last answer here'])),'Last answer here');
assert.equal(clearlyUnrelated('What are the restaurant hours?'),false);
assert.equal(clearlyUnrelated('Help me think through labor for Friday night'),false);
assert.equal(clearlyUnrelated('How should I coach a server who keeps missing side work?'),false);
assert.equal(clearlyUnrelated('Write a better closing checklist'),false);
assert.equal(clearlyUnrelated('What can you do?'),false);
assert.equal(clearlyUnrelated('Why?',h(['user','How should we lower labor at El Molino?'],['assistant','Try cutting overlap.'])),false);
assert.equal(clearlyUnrelated('What about managers?',h(['user','How should training work at El Molino?'],['assistant','Start with onboarding.'])),false);
assert.equal(clearlyUnrelated('Who won the NFL game?'),true);
assert.equal(clearlyUnrelated('Tell me about the Mustang GT engine'),true);
assert.equal(clearlyUnrelated('What is bitcoin doing?'),true);
assert.equal(clearlyUnrelated('Recommend an anime'),true);
const history=h(['user','How should we improve closing at El Molino?'],['assistant','Use a checklist.']);
assert.match(contextualSearchQuestion('Why?',history),/closing at El Molino/i);
assert.ok(isCapabilityFollowup('Go deeper',h(['user','What can you do?'],['assistant','I can answer questions and help with tasks and procedures.'])));
});
