import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {businessDateInZone,canApproveProcedure,canConvertProcedure,canFinishChecklist,canToggleChecklistItem,cappedExactLabel,checklistProgress,chooseLatestRun,contiguousStepNumbers,dedupeById,fileSizeLabel,isOpenStatus,isOverdue,maxSafeRows,menuMatches,nextStepNumber,norm,priceLabel,safeAttachmentCount,safeBusinessDate,safeDateMs,safeFileTitle,safeKindQuery,safeMessage,safeRecentCutoff,safeStatus,safeTimestampLabel,searchable,stableSortByName,staleResponse,validBusinessDate,validChecklistPeriod,validMoney,validPriority,validProcedureInstruction,validProcedureTitle,validStorageRef,visibleMenuItem} from '../lib/intermediate-hardening.ts';

test('100 unique intermediate workflow failures are guarded',()=>{let n=0;const c=(v:boolean)=>{n++;assert.equal(v,true,`intermediate case ${n}`)};
// MENU / CATALOG 1-20
c(visibleMenuItem({active:false,name:'Taco'})===false);c(visibleMenuItem({active:true,name:'   '})===false);c(visibleMenuItem({active:true,name:'Taco'}));c(validMoney(-1)===null);c(validMoney(Infinity)===null);c(validMoney('abc')===null);c(validMoney(12.5)===12.5);c(validMoney(100001)===null);c(priceLabel(-2)==='—');c(priceLabel('12.5')==='$12.50');c(searchable('  BIRRIA\nTACO  ')==='birria taco');c(searchable('x'.repeat(200)).length===120);c(menuMatches({name:'Birria taco'},'Tacos','birria'));c(menuMatches({name:'Quesadilla'},'Tacos','tacos'));c(menuMatches({description:'slow cooked beef'},'Specials','beef'));c(menuMatches({price_source:'Toast'},'Specials','toast'));c(menuMatches({name:'Quesadilla'},'Tacos','pizza')===false);c(dedupeById([{id:'1'},{id:'1'},{id:'2'}]).length===2);c(stableSortByName([{name:'z'},{name:'A'}])[0].name==='A');c(norm('  taco\u0000  ',20)==='taco');
// MANAGER DASHBOARD 21-40
c(businessDateInZone(new Date('2026-08-13T03:30:00Z'))==='08/12/2026'||businessDateInZone(new Date('2026-08-13T03:30:00Z'))==='2026-08-12');c(safeDateMs('bad')===null);c(isOverdue('bad',1000)===false);c(isOverdue('1970-01-01T00:00:00.500Z',1000));c(safeStatus(' Done ')==='done');c(isOpenStatus('done')===false);c(isOpenStatus('cancelled')===false);c(isOpenStatus('OPEN'));c(validPriority('URGENT')==='urgent');c(validPriority('nonsense')==='normal');c(cappedExactLabel(199,200)==='199');c(cappedExactLabel(200,200)==='200+');c(safeKindQuery('maintenance_ticket')==='maintenance_ticket');c(safeKindQuery('../incident?')==='incident');c(chooseLatestRun([{created_at:'2026-01-01T00:00:00Z'},{created_at:'2026-02-01T00:00:00Z'}])?.created_at.startsWith('2026-02'));c(chooseLatestRun([])===null);c(staleResponse(4,5));c(staleResponse(5,5)===false);c(maxSafeRows(999999)===10000);c(maxSafeRows(NaN)===500);
// PROCEDURES 41-60
c(validProcedureTitle('')===null);c(validProcedureTitle('a')===null);c(validProcedureTitle('  Open grill  ')==='Open grill');c(validProcedureInstruction('')===null);c(validProcedureInstruction('a')===null);c(validProcedureInstruction('  Turn off gas  ')==='Turn off gas');c(validChecklistPeriod('opening')==='opening');c(validChecklistPeriod('mid shift')==='mid_shift');c(validChecklistPeriod('night')===null);c(canApproveProcedure(0,'Valid title')===false);c(canApproveProcedure(1,'')===false);c(canApproveProcedure(1,'Valid title'));c(nextStepNumber([])===1);c(nextStepNumber([{step_number:1},{step_number:4}])===5);c(contiguousStepNumbers([{step_number:1},{step_number:2}]));c(contiguousStepNumbers([{step_number:1},{step_number:3}])===false);c(canConvertProcedure('draft',3)===false);c(canConvertProcedure('approved',0)===false);c(canConvertProcedure('approved',2));c(norm('x'.repeat(9000),8000).length===8000);
// SHIFT EXECUTION 61-80
c(validBusinessDate('2026-08-12'));c(validBusinessDate('08/12/2026')===false);c(validBusinessDate('2026-8-2')===false);c(safeRecentCutoff(7,new Date('2026-08-12T12:00:00Z').getTime())==='2026-08-05');c(safeRecentCutoff(0,new Date('2026-08-12T12:00:00Z').getTime())==='2026-08-11');c(safeRecentCutoff(500,new Date('2026-08-12T12:00:00Z').getTime())==='2026-05-14');c(canToggleChecklistItem(null,false));c(canToggleChecklistItem('2026-08-12T12:00:00Z',false)===false);c(canToggleChecklistItem(null,true)===false);c(checklistProgress([]).complete===false);c(checklistProgress([{completed:true},{completed:false}]).done===1);c(checklistProgress([{completed:true},{completed:true}]).complete);c(canFinishChecklist(null,[])===false);c(canFinishChecklist(null,[{completed:true}]));c(canFinishChecklist('2026-08-12T12:00:00Z',[{completed:true}])===false);c(chooseLatestRun([{created_at:'2026-01-01T00:00:00Z',started_at:null},{created_at:'2026-01-02T00:00:00Z',started_at:'2026-01-03T00:00:00Z'}])?.started_at?.startsWith('2026-01-03')===true);c(safeStatus('In Progress')==='in_progress');c(isOpenStatus('complete')===false);c(validChecklistPeriod('closing')==='closing');c(validChecklistPeriod('CLOSING')==='closing');
// FILES & MEDIA 81-100
c(fileSizeLabel(null)==='0 B');c(fileSizeLabel(-1)==='Unknown size');c(fileSizeLabel(0)==='0 B');c(fileSizeLabel(1023)==='1023 B');c(fileSizeLabel(1024)==='1.0 KB');c(fileSizeLabel(1048576)==='1.0 MB');c(fileSizeLabel(1073741824)==='1.0 GB');c(safeTimestampLabel('bad')==='Unknown date');c(safeFileTitle('', 'x.pdf')==='x.pdf');c(safeFileTitle('', '')==='Untitled file');c(validStorageRef('bucket','folder/file.pdf'));c(validStorageRef('','folder/file.pdf')===false);c(validStorageRef('bucket','../secret')===false);c(validStorageRef('bucket','/root/file')===false);c(safeAttachmentCount(-1)===0);c(safeAttachmentCount(2.9)===2);c(safeAttachmentCount(100000)===9999);c(safeMessage('permission denied for relation files','Could not load files.')==='Could not load files.');c(safeMessage('Normal friendly error','Fallback')==='Normal friendly error');c(maxSafeRows(0)===1);
assert.equal(n,100)});

test('intermediate fixes are wired into their production screens',()=>{const menu=fs.readFileSync('app/menu/page.tsx','utf8'),manager=fs.readFileSync('app/manager/page.tsx','utf8'),procedures=fs.readFileSync('app/procedures/page.tsx','utf8'),shift=fs.readFileSync('app/shift/page.tsx','utf8'),files=fs.readFileSync('app/files/page.tsx','utf8');assert.match(menu,/visibleMenuItem/);assert.match(menu,/priceLabel/);assert.match(manager,/businessDateInZone/);assert.match(manager,/chooseLatestRun/);assert.match(procedures,/canApproveProcedure/);assert.match(procedures,/validChecklistPeriod/);assert.match(shift,/canToggleChecklistItem/);assert.match(shift,/canFinishChecklist/);assert.match(files,/fileSizeLabel/);assert.match(files,/validStorageRef/)});
