import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {BACKUP_FORMAT,boundedText,chunkRanges,isRestaurantInternalPath,nextFocus,optimisticConflict,parseBackupText,safeAriaText,safeCacheName,safeTabIndex,shouldAcceptAsyncResult,validateBackup,validIsoDate,validUuid} from '../lib/round4-hardening.ts';
import {BACKUP_SCHEMA_VERSION,BACKUP_TABLES} from '../lib/backup-manifest.ts';
const LOC='550e8400-e29b-41d4-a716-446655440000',ID='6ba7b810-9dad-41d1-80b4-00c04fd430c8',FP='0123456789abcdef0123456789abcdef';
const emptyTables=()=>Object.fromEntries(BACKUP_TABLES.map(t=>[t,[]]));
const backup=(extra:any={})=>{const base:any={format:BACKUP_FORMAT,schema_version:BACKUP_SCHEMA_VERSION,schema_fingerprint:FP,exported_at:'2026-08-12T23:00:00.000Z',location_id:LOC,manifest:{tables:[...BACKUP_TABLES],excluded:{}},storage:{objects_included:false,note:'Database recovery only'},tables:{...emptyTables(),tasks:[{id:ID,location_id:LOC,title:'x'}]}};if(Object.prototype.hasOwnProperty.call(extra,'tables')){const t=extra.tables;base.tables=t===null?t:{...emptyTables(),...t};const {tables:_,...rest}=extra;return{...base,...rest,tables:base.tables}}return{...base,...extra}};
test('100 unique round-four deep failure modes stay guarded',()=>{let n=0;const c=(v:boolean)=>{n++;assert.equal(v,true,`round4 case ${n}`)};
// Backup/restore integrity 1-30
c(!validateBackup(null).ok);c(!validateBackup([]).ok);c(!validateBackup({}).ok);c(!validateBackup(backup({format:'v1'})).ok);c(!validateBackup(backup({exported_at:'bad'})).ok);c(!validateBackup(backup({location_id:'bad'})).ok);c(!validateBackup(backup(),ID).ok);c(!validateBackup(backup({tables:null})).ok);c(!validateBackup(backup({tables:{tasks:'bad'}})).ok);c(!validateBackup(backup({tables:{tasks:[null]}})).ok);c(!validateBackup(backup({tables:{tasks:[{id:'bad',location_id:LOC}]}})).ok);c(!validateBackup(backup({tables:{tasks:[{id:ID,location_id:'6ba7b810-9dad-41d1-80b4-00c04fd430c8'}]}})).ok);c(!validateBackup(backup({tables:{tasks:[{id:ID,location_id:LOC},{id:ID,location_id:LOC}]}})).ok);c(validateBackup(backup()).ok);c(validateBackup(backup()).rowCount===1);c(validateBackup(backup()).tables.includes('tasks'));c(!validateBackup(backup({tables:{mystery:[]}})).ok&&validateBackup(backup({tables:{mystery:[]}})).errors.some(x=>x.includes('unsupported table')));c(validateBackup(backup({tables:{}})).warnings.some(x=>x.includes('no rows')));c(parseBackupText('').check.ok===false);c(parseBackupText('{').check.errors.some(x=>x.includes('malformed')));c(parseBackupText(JSON.stringify(backup()),LOC).check.ok);c(parseBackupText(JSON.stringify(backup()),ID).check.ok===false);c(validUuid(LOC));c(!validUuid('000'));c(validIsoDate('2026-11-01T05:30:00Z'));c(!validIsoDate('not-date'));c(!validIsoDate('x'.repeat(65)));c(validateBackup(backup({tables:{tasks:[{id:null,location_id:LOC}]}})).ok);c(validateBackup(backup({tables:{tasks:[]}})).ok);c(validateBackup(backup({tables:{tasks:[],employees:[]}})).tables.length===BACKUP_TABLES.length);
// Input/path/screen-reader guards 31-55
c(isRestaurantInternalPath('/ops'));c(isRestaurantInternalPath('/?tab=ai'));c(!isRestaurantInternalPath('https://evil.example'));c(!isRestaurantInternalPath('//evil.example'));c(!isRestaurantInternalPath('/\\evil'));c(!isRestaurantInternalPath('/bad\u0000'));c(safeAriaText('  Hello\nworld ')==='Hello world');c(safeAriaText('')==='Item');c(safeAriaText('', 'Fallback')==='Fallback');c(safeAriaText('x'.repeat(300)).length===160);c(boundedText(' a\u0000b ',5)==='ab');c(boundedText('abcdef',3)==='abc');c(boundedText('abc',-2)==='');c(safeCacheName('el-molino-static-v4')==='el-molino-static-v4');c(safeCacheName('other-cache')===null);c(safeCacheName('el-molino-'+ 'x'.repeat(90))===null);c(safeTabIndex(3,5)===3);c(safeTabIndex(-1,5)===0);c(safeTabIndex(99,5)===4);c(safeTabIndex(NaN,5)===-1);c(safeTabIndex(0,0)===-1);c(nextFocus(0,1,3)===1);c(nextFocus(2,1,3)===0);c(nextFocus(0,-1,3)===2);c(nextFocus(0,1,0)===-1);
// Pagination/high-volume/concurrency 56-75
c(chunkRanges(0).length===0);c(chunkRanges(1)[0].to===0);c(chunkRanges(1000).length===1);c(chunkRanges(1001).length===2);c(chunkRanges(1001)[1].from===1000);c(chunkRanges(1001)[1].to===1000);c(chunkRanges(10000,5000).length===2);c(chunkRanges(999999).length===500);c(chunkRanges(-3).length===0);c(chunkRanges(3,0).length===1);c(shouldAcceptAsyncResult(4,4));c(!shouldAcceptAsyncResult(4,5));c(!shouldAcceptAsyncResult(4,4,false));c(!optimisticConflict({updated_at:'a'},{updated_at:'a'}));c(optimisticConflict({updated_at:'a'},{updated_at:'b'}));c(!optimisticConflict({updated_at:null},{updated_at:'b'}));c(!optimisticConflict({},{updated_at:'b'}));c(boundedText('x'.repeat(60000),60000).length===50000);c(chunkRanges(5001,5000)[1].to===5000);c(chunkRanges(500001).at(-1)?.to===499999);
// Service-worker corruption/offline recovery source contracts 76-88
const sw=fs.readFileSync('public/sw.js','utf8');c(sw.includes("el-molino-static-v4"));c(sw.includes('Promise.allSettled'));c(sw.includes("status:503"));c(sw.includes("'cache-control':'no-store'"));c(sw.includes('viewport-fit=cover'));c(sw.includes("type==='CLEAR_CACHES'"));c(sw.includes("url.pathname.startsWith('/_next/static/')"));c(sw.includes('networkFirst(req,true)'));c(!sw.includes('cache.addAll(STATIC)'));c(sw.includes("fetch(req,{cache:'no-store'})"));c(sw.includes('purgeOld'));c(sw.includes('startsWith(\'el-molino-\')'));c(sw.includes('Try again'));
// Accessibility and restore dry-run source contracts 89-100
const ga=fs.readFileSync('app/global-actions.tsx','utf8'),restore=fs.readFileSync('app/admin/restore/page.tsx','utf8'),css=fs.readFileSync('app/command.css','utf8');c(ga.includes('aria-activedescendant'));c(ga.includes('role="combobox"'));c(ga.includes('role="option"'));c(ga.includes('aria-selected'));c(ga.includes('trapTab'));c(ga.includes('previousFocus'));c(css.includes('.sr-only'));c(css.includes('[aria-selected="true"]'));c(restore.includes('Dry-run validation'));c(restore.includes('Nothing has been written'));c(restore.includes("profile.app_role!=='admin'"));c(restore.includes('parseBackupText'));
assert.equal(n,100)});
