import test from 'node:test';import assert from 'node:assert/strict';
import {backupRanges,boundedText,businessDate,canDemoteAdmin,canRestore,canSubmitText,clampSignedUrlSeconds,dedupeBy,focusIndex,inviteActionable,isRole,mergeNotifications,newestRequestWins,nonNegativeCount,notificationKey,optimisticRollback,pageCount,safeAriaLabel,safeInternalHref,safeJsonForDownload,safeLocalDateTime,safeOfflineWrite,sanitizeAuditMessage,searchableQuery,shouldReloadForServiceWorker,staleEntityUpdate,uniqueRecent,validPageSize} from '../lib/round3-hardening.ts';

test('100 unique third-round production failure modes are guarded',()=>{let n=0;const c=(v:boolean)=>{n++;assert.equal(v,true,`case ${n}`)};
// Permissions / invitations / restore 1-15
c(isRole('admin'));c(isRole('manager'));c(isRole('employee'));c(!isRole('owner'));c(!canDemoteAdmin([{id:'a',app_role:'admin'}],'a','manager'));c(canDemoteAdmin([{id:'a',app_role:'admin'},{id:'b',app_role:'admin'}],'a','manager'));c(canDemoteAdmin([{id:'a',app_role:'manager'}],'a','employee'));c(inviteActionable('pending',null));c(!inviteActionable('revoked',null));c(!inviteActionable('accepted',null));c(!inviteActionable('pending','2020-01-01T00:00:00Z',Date.now()));c(inviteActionable('pending','2099-01-01T00:00:00Z',Date.now()));c(!inviteActionable('pending','not-a-date'));c(canRestore('2026-08-12T12:00:00Z'));c(!canRestore(null));
// Search/navigation/stale responses 16-35
c(searchableQuery(' a ')==='');c(searchableQuery(' hi ')==='hi');c(searchableQuery('  many   spaces  ')==='many spaces');c(searchableQuery('x'.repeat(200)).length===120);c(!searchableQuery('\u0000\n').length);c(safeInternalHref('/tasks')==='/tasks');c(safeInternalHref('/tasks?q=abc')==='/tasks?q=abc');c(safeInternalHref('https://evil.test')==='/');c(safeInternalHref('//evil.test')==='/');c(safeInternalHref('javascript:alert(1)')==='/');c(safeInternalHref('/ok\u0000bad')==='/');c(dedupeBy([{id:'1'},{id:'1'},{id:'2'}],x=>x.id).length===2);c(dedupeBy([{id:''},{id:'2'}],x=>x.id).length===1);c(newestRequestWins(4,4));c(!newestRequestWins(3,4));c(uniqueRecent([{id:'a'},{id:'a'},{id:'b'}],x=>x.id).length===2);c(uniqueRecent([{id:'a'},{id:'b'}],x=>x.id,1).length===1);c(validPageSize(0)===1);c(validPageSize(999,200)===200);c(pageCount(1001,500)===3);
// Discussions / concurrent writes / text 36-50
c(canSubmitText('hello'));c(!canSubmitText('   '));c(!canSubmitText('x'.repeat(5001)));c(boundedText('  hi  ',10)==='hi');c(boundedText('a\u0000b',10)==='ab');c(optimisticRollback('before',true,'after')==='before');c(optimisticRollback('before',false,'after')==='after');c(staleEntityUpdate('v1','v2'));c(!staleEntityUpdate('v1','v1'));c(!staleEntityUpdate(null,'v1'));c(safeOfflineWrite(true,'write'));c(!safeOfflineWrite(false,'write'));c(!safeOfflineWrite(false,'idempotent'));c(safeOfflineWrite(false,'read'));c(nonNegativeCount(-2)===0);
// Backup / large data / audit 51-65
c(backupRanges(0).length===0);c(backupRanges(1,1000).length===1);c(backupRanges(1001,1000).length===2);c(backupRanges(10000,1000).length===10);c(backupRanges(10001,1000).length===11);c(backupRanges(10,0).length===10);c(backupRanges(100,99999).length===1);c(safeJsonForDownload({a:1}).includes('"a"'));let threw=false;try{safeJsonForDownload({x:'z'.repeat(100)},20)}catch{threw=true}c(threw);c(sanitizeAuditMessage('Bearer abc.def.ghi').includes('[redacted]'));c(!sanitizeAuditMessage('Bearer abc.def.ghi').includes('abc.def.ghi'));c(sanitizeAuditMessage('sb_publishable_SECRET').includes('[redacted-key]'));c(sanitizeAuditMessage('x'.repeat(2000)).length<=1000);c(nonNegativeCount('12')===12);c(nonNegativeCount('bad')===0);
// Timezone / DST / date display 66-78
c(businessDate(new Date('2026-01-01T04:30:00Z'),'America/New_York')==='12/31/2025'||businessDate(new Date('2026-01-01T04:30:00Z'),'America/New_York')==='2025-12-31');c(businessDate(new Date('2026-07-01T03:30:00Z'),'America/New_York').includes('06/30/2026')||businessDate(new Date('2026-07-01T03:30:00Z'),'America/New_York').includes('2026-06-30'));c(safeLocalDateTime('bad')==='Invalid date');c(safeLocalDateTime('2026-08-12T12:00:00Z').length>0);c(clampSignedUrlSeconds(0)===30);c(clampSignedUrlSeconds(99999)===900);c(clampSignedUrlSeconds(NaN)===120);c(clampSignedUrlSeconds(120.9)===120);c(pageCount(0,50)===0);c(pageCount(1,50)===1);c(pageCount(500,500)===1);c(pageCount(501,500)===2);c(validPageSize(NaN)===50);
// Notifications / PWA update / accessibility 79-100
c(notificationKey({id:'x'})==='x');c(notificationKey({type:'task',entity_type:'task',entity_id:'1',message:'m'}).includes('task'));c(mergeNotifications([{id:'1'}],[{id:'1'},{id:'2'}]).length===2);c(mergeNotifications([],[{id:'1'}]).length===1);c(shouldReloadForServiceWorker({controllerChanged:true,documentVisible:true,hasBlockingDialog:false,dirty:false}));c(!shouldReloadForServiceWorker({controllerChanged:true,documentVisible:false,hasBlockingDialog:false,dirty:false}));c(!shouldReloadForServiceWorker({controllerChanged:true,documentVisible:true,hasBlockingDialog:true,dirty:false}));c(!shouldReloadForServiceWorker({controllerChanged:true,documentVisible:true,hasBlockingDialog:false,dirty:true}));c(!shouldReloadForServiceWorker({controllerChanged:false,documentVisible:true,hasBlockingDialog:false,dirty:false}));c(safeAriaLabel('','Close')==='Close');c(safeAriaLabel(' Search ','Fallback')==='Search');c(focusIndex(0,1,3)===1);c(focusIndex(2,1,3)===0);c(focusIndex(0,-1,3)===2);c(focusIndex(0,1,0)===-1);c(clampSignedUrlSeconds(30)===30);c(clampSignedUrlSeconds(900)===900);c(dedupeBy([1,2,2,3],x=>String(x)).join(',')==='1,2,3');c(uniqueRecent([{id:'a'},{id:'b'},{id:'a'}],x=>x.id,100)[0].id==='a');c(!canRestore('bad'));c(boundedText('x'.repeat(200),50).length===50);c(safeInternalHref('/saved#x')==='/saved#x');
assert.equal(n,100)});
