import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
const s=readFileSync('app/schedule/page.tsx','utf8'),settings=readFileSync('app/schedule/settings/page.tsx','utf8');
test('schedule links all parity workspaces',()=>{for(const path of ['/schedule/pool','/schedule/requests','/schedule/views','/schedule/feedback','/schedule/warnings','/schedule/breaks','/schedule/publish','/schedule/settings','/schedule/labor','/schedule/attendance','/schedule/compliance','/schedule/templates','/schedule/activity','/schedule/team','/calendar'])assert.ok(s.includes(path),path)});
test('schedule exposes skill levels partial offers and scheduled breaks',()=>{assert.match(s,/set_employee_role_skill/);assert.match(s,/Offer Part/);assert.match(s,/scheduledBreaks/);assert.match(settings,/shift_pool_allow_partial/)});

test('expanded scheduling parity workspaces keep their real backend contracts',()=>{
 const labor=readFileSync('app/schedule/labor/page.tsx','utf8'),attendance=readFileSync('app/schedule/attendance/page.tsx','utf8'),compliance=readFileSync('app/schedule/compliance/page.tsx','utf8'),templates=readFileSync('app/schedule/templates/page.tsx','utf8'),activity=readFileSync('app/schedule/activity/page.tsx','utf8'),team=readFileSync('app/schedule/team/page.tsx','utf8'),warnings=readFileSync('app/schedule/warnings/page.tsx','utf8'),views=readFileSync('app/schedule/views/page.tsx','utf8');
 assert.match(labor,/schedule_labor_budget_report/);assert.match(attendance,/record_schedule_attendance_flag/);assert.match(compliance,/schedule_compliance_warnings/);assert.match(compliance,/set_schedule_school_day/);assert.match(templates,/copy_schedule_period/);assert.match(templates,/save_schedule_period_as_template/);assert.match(templates,/duplicate_schedule_shift/);assert.match(activity,/schedule_shift_change_log/);assert.match(activity,/shift_pool_offers/);assert.match(team,/employee_schedule_profiles/);assert.match(warnings,/schedule_compliance_warnings/);assert.match(views,/calendar_events/);
});
