'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, CalendarDays, ChevronLeft, ChevronRight, Clock, Loader2, Plus } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type EventRow={id:string;title:string;description:string|null;event_type:string;starts_at:string;ends_at:string|null;all_day:boolean;recurrence_rule:string|null};
type Task={id:string;title:string;due_at:string|null;status:string;priority:string};
type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};

export default function CalendarPage(){
  const [month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1));
  const [events,setEvents]=useState<EventRow[]>([]),[tasks,setTasks]=useState<Task[]>([]),[profile,setProfile]=useState<Profile|null>(null),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
  const [title,setTitle]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[recurrence,setRecurrence]=useState('');
  const canManage=profile?.app_role==='admin'||profile?.app_role==='manager';
  useEffect(()=>{void load()},[month]);
  async function load(){setLoading(true);const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return;}const {data:p}=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();setProfile(p as Profile);const from=new Date(month.getFullYear(),month.getMonth(),1);const to=new Date(month.getFullYear(),month.getMonth()+1,1);const [e,t]=await Promise.all([supabase.from('calendar_events').select('id,title,description,event_type,starts_at,ends_at,all_day,recurrence_rule').gte('starts_at',from.toISOString()).lt('starts_at',to.toISOString()).order('starts_at'),supabase.from('tasks').select('id,title,due_at,status,priority').not('due_at','is',null).gte('due_at',from.toISOString()).lt('due_at',to.toISOString()).is('deleted_at',null).order('due_at')]);setEvents((e.data??[]) as EventRow[]);setTasks((t.data??[]) as Task[]);setLoading(false);}
  async function create(e:FormEvent){e.preventDefault();if(!profile?.location_id||!title.trim()||!start)return;const {data:u}=await supabase.auth.getUser();if(!u.user)return;const {error}=await supabase.from('calendar_events').insert({location_id:profile.location_id,title:title.trim(),starts_at:new Date(start).toISOString(),ends_at:end?new Date(end).toISOString():null,recurrence_rule:recurrence.trim()||null,created_by:u.user.id});setMessage(error?error.message:'Calendar event created.');if(!error){setTitle('');setStart('');setEnd('');setRecurrence('');await load();}}
  const days=useMemo(()=>{const first=new Date(month.getFullYear(),month.getMonth(),1);const last=new Date(month.getFullYear(),month.getMonth()+1,0);const out:(Date|null)[]=[];for(let i=0;i<first.getDay();i++)out.push(null);for(let d=1;d<=last.getDate();d++)out.push(new Date(month.getFullYear(),month.getMonth(),d));return out},[month]);
  const itemsFor=(d:Date)=>{const key=d.toDateString();return [...events.filter(e=>new Date(e.starts_at).toDateString()===key).map(e=>({id:`e-${e.id}`,title:e.title,time:new Date(e.starts_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}),type:'event'})),...tasks.filter(t=>t.due_at&&new Date(t.due_at).toDateString()===key).map(t=>({id:`t-${t.id}`,title:t.title,time:new Date(t.due_at!).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}),type:'task'}))]};
  return <div className="app-shell"><header className="topbar"><a className="round-button" href="/" aria-label="Back"><ArrowLeft/></a><div style={{flex:1}}><div className="brand-kicker">El Molino Ops</div><div className="brand-title">Calendar</div></div></header><main className="page">{message&&<div className="toast-message">{message}</div>}<div className="calendar-head"><button className="round-button" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}><ChevronLeft/></button><div><h1>{month.toLocaleDateString([],{month:'long',year:'numeric'})}</h1><p>Tasks, events and recurring operations</p></div><button className="round-button" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}><ChevronRight/></button></div>{loading?<div className="full-loader"><Loader2 className="spin"/></div>:<><div className="calendar-weekdays">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=><span key={x}>{x}</span>)}</div><div className="calendar-grid">{days.map((d,i)=><div className={`calendar-day ${!d?'blank':''}`} key={i}>{d&&<><b>{d.getDate()}</b><div className="day-items">{itemsFor(d).slice(0,3).map(x=><span className={x.type} key={x.id}><small>{x.time}</small>{x.title}</span>)}</div></>}</div>)}</div></>}{canManage&&<><div className="section-title"><h2>Add event</h2><span>manager</span></div><div className="card"><form className="form" onSubmit={create}><input className="input" placeholder="Event title" value={title} onChange={e=>setTitle(e.target.value)} required/><div className="two-col"><div className="field"><label>Starts</label><input className="input" type="datetime-local" value={start} onChange={e=>setStart(e.target.value)} required/></div><div className="field"><label>Ends</label><input className="input" type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)}/></div></div><div className="field"><label>Recurrence (optional)</label><input className="input" placeholder="Example: FREQ=WEEKLY;BYDAY=MO" value={recurrence} onChange={e=>setRecurrence(e.target.value)}/></div><button className="btn"><Plus size={16}/> Add to calendar</button></form></div></>}</main></div>;
}
