'use client';

import {FormEvent,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase';
import styles from '../ops-tools.module.css';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Employee={id:string;full_name:string};
type DirectoryRow={employee_id:string;full_name:string};
type Role={id:string;name:string;department:string|null};
type Announcement={id:string;title:string;body:string;priority:'normal'|'important'|'urgent';expires_at:string|null;sent_at:string;archived_at:string|null;requires_acknowledgment:boolean};
type Recipient={announcement_id:string;employee_id:string;read_at:string|null;acknowledged_at:string|null;reminder_count:number;last_reminded_at:string|null};
type Shoutout={id:string;from_employee_id:string;to_employee_id:string;category:string;message:string;created_at:string;hidden_at:string|null};
type Reaction={shoutout_id:string;employee_id:string;reaction:'applause'|'heart'|'fire'|'thanks';created_at:string};
type Target='all'|'employee'|'role'|'department';
const categories=['great_job','teamwork','guest_service','leadership','hustle','growth','other'] as const;
const reactions=['applause','heart','fire','thanks'] as const;
const label=(s:string)=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const blankAnnouncement=()=>({title:'',body:'',priority:'normal',target:'all' as Target,target_id:'',expires_at:'',requires_acknowledgment:false});

export default function TeamPage(){
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[profile,setProfile]=useState<Profile|null>(null),[me,setMe]=useState<string|null>(null),[employees,setEmployees]=useState<Employee[]>([]),[roles,setRoles]=useState<Role[]>([]),[announcements,setAnnouncements]=useState<Announcement[]>([]),[recipients,setRecipients]=useState<Recipient[]>([]),[shoutouts,setShoutouts]=useState<Shoutout[]>([]),[reactionRows,setReactionRows]=useState<Reaction[]>([]),[announcement,setAnnouncement]=useState(blankAnnouncement),[shoutout,setShoutout]=useState({to_employee_id:'',category:'great_job',message:''});
 const manager=profile?.app_role==='admin'||profile?.app_role==='manager';
 const departments=useMemo(()=>Array.from(new Set(roles.map(r=>r.department).filter((x):x is string=>Boolean(x)))).sort(),[roles]);
 const activeAnnouncements=useMemo(()=>announcements.filter(a=>!a.archived_at).sort((a,b)=>b.sent_at.localeCompare(a.sent_at)),[announcements]);
 useEffect(()=>{void load()},[]);
 async function load(){setBusy(true);const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}const p=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();if(p.error||!p.data?.location_id){setMessage('Could not load team access.');setReady(true);setBusy(false);return}const pr=p.data as Profile;setProfile(pr);const [eid,e,r,a,ar,s,sr]=await Promise.all([supabase.rpc('time_clock_employee_id_for_user',{}),supabase.rpc('staff_directory',{}),supabase.from('employee_roles').select('id,name,department').eq('location_id',pr.location_id).order('name'),supabase.from('team_announcements').select('id,title,body,priority,expires_at,sent_at,archived_at,requires_acknowledgment').eq('location_id',pr.location_id).order('sent_at',{ascending:false}).limit(200),supabase.from('team_announcement_recipients').select('announcement_id,employee_id,read_at,acknowledged_at,reminder_count,last_reminded_at').eq('location_id',pr.location_id).limit(5000),supabase.from('team_shoutouts').select('id,from_employee_id,to_employee_id,category,message,created_at,hidden_at').eq('location_id',pr.location_id).order('created_at',{ascending:false}).limit(300),supabase.from('team_shoutout_reactions').select('shoutout_id,employee_id,reaction,created_at').eq('location_id',pr.location_id).limit(5000)]);if([eid,e,r,a,ar,s,sr].some(x=>x.error))setMessage('Some team data could not be loaded.');setMe((eid.data as string|null)||null);setEmployees(((e.data??[]) as DirectoryRow[]).map(x=>({id:x.employee_id,full_name:x.full_name})));setRoles((r.data??[]) as Role[]);setAnnouncements((a.data??[]) as Announcement[]);setRecipients((ar.data??[]) as Recipient[]);setShoutouts((s.data??[]) as Shoutout[]);setReactionRows((sr.data??[]) as Reaction[]);setReady(true);setBusy(false)}
 const name=(id:string)=>employees.find(e=>e.id===id)?.full_name||'Team member';
 const recipient=(announcementId:string)=>recipients.find(r=>r.announcement_id===announcementId&&r.employee_id===me);
 async function sendAnnouncement(e:FormEvent){e.preventDefault();if(!manager||busy||!announcement.title.trim()||!announcement.body.trim())return;if(announcement.target!=='all'&&!announcement.target_id)return setMessage('Choose an announcement audience.');setBusy(true);const roleIds=announcement.target==='role'?[announcement.target_id]:null,departmentsArg=announcement.target==='department'?[announcement.target_id]:null,employeeIds=announcement.target==='employee'?[announcement.target_id]:null;const {data,error}=await supabase.rpc('send_team_announcement',{p_title:announcement.title.trim(),p_body:announcement.body.trim(),p_priority:announcement.priority,p_role_ids:roleIds,p_departments:departmentsArg,p_employee_ids:employeeIds,p_expires_at:announcement.expires_at?new Date(announcement.expires_at).toISOString():null,p_requires_acknowledgment:announcement.requires_acknowledgment});if(error)setMessage(error.message);else{setAnnouncement(blankAnnouncement());setMessage(`Announcement sent to ${Number((data as any)?.recipients||0)} teammate${Number((data as any)?.recipients||0)===1?'':'s'}${(data as any)?.requires_acknowledgment?' · acknowledgment required':''}.`);await load()}setBusy(false)}
 async function markRead(id:string){if(busy)return;setBusy(true);const {error}=await supabase.rpc('mark_team_announcement_read',{p_announcement_id:id});setMessage(error?error.message:'Announcement marked read.');await load();setBusy(false)}
 async function remind(id:string){if(!manager||busy)return;setBusy(true);const {data,error}=await supabase.rpc('remind_unread_team_announcement',{p_announcement_id:id});setMessage(error?error.message:`Reminder recorded for ${Number(data||0)} unread recipient${Number(data||0)===1?'':'s'}.`);await load();setBusy(false)}
 async function archive(id:string){if(!manager||busy)return;setBusy(true);const {error}=await supabase.rpc('archive_team_announcement',{p_announcement_id:id});setMessage(error?error.message:'Announcement archived.');await load();setBusy(false)}
 async function createShoutout(e:FormEvent){e.preventDefault();if(!me||busy||!shoutout.to_employee_id||!shoutout.message.trim())return;setBusy(true);const {error}=await supabase.rpc('create_team_shoutout',{p_to_employee_id:shoutout.to_employee_id,p_category:shoutout.category,p_message:shoutout.message.trim()});if(!error)setShoutout({to_employee_id:'',category:'great_job',message:''});setMessage(error?error.message:'Shout-out posted.');await load();setBusy(false)}
 async function toggleReaction(id:string,reaction:Reaction['reaction']){if(!me||busy)return;setBusy(true);const exists=reactionRows.some(r=>r.shoutout_id===id&&r.employee_id===me&&r.reaction===reaction);const {error}=exists?await supabase.rpc('remove_team_shoutout_reaction',{p_shoutout_id:id,p_reaction:reaction}):await supabase.rpc('react_to_team_shoutout',{p_shoutout_id:id,p_reaction:reaction});if(error)setMessage(error.message);await load();setBusy(false)}
 async function hideShoutout(id:string){if(!manager||busy)return;setBusy(true);const {error}=await supabase.rpc('hide_team_shoutout',{p_shoutout_id:id});setMessage(error?error.message:'Shout-out hidden from the team feed.');await load();setBusy(false)}
 if(!ready)return <main className={styles.page}>Loading team hub…</main>;if(!profile?.location_id)return <main className={styles.page}>No restaurant location is assigned.</main>;
 return <main className={styles.page}><div className={styles.top}><div><h1>Team Hub</h1><p>{manager?'Targeted announcements, read tracking and teammate recognition.':'Announcements and recognition for the El Molino team.'}</p></div><Link className={styles.back} href={manager?'/tools':'/employee'}>{manager?'Back to Tools':'Staff Home'}</Link></div>{message&&<div className={message.toLowerCase().includes('could not')?styles.error:styles.notice}>{message}</div>}
  <div className={styles.grid}><Metric label="Active announcements" value={String(activeAnnouncements.length)}/><Metric label="Unread for me" value={String(activeAnnouncements.filter(a=>{const r=recipient(a.id);return r&&!r.read_at}).length)}/><Metric label="Visible shout-outs" value={String(shoutouts.filter(s=>!s.hidden_at).length)}/><Metric label="Team members" value={String(employees.length)}/></div>
  {manager&&<section className={styles.section}><div className={styles.card}><h2>Send announcement</h2><form onSubmit={sendAnnouncement}><div className={styles.formGrid}><Field label="Title"><input maxLength={160} value={announcement.title} onChange={e=>setAnnouncement({...announcement,title:e.target.value})}/></Field><Field label="Priority"><select value={announcement.priority} onChange={e=>setAnnouncement({...announcement,priority:e.target.value})}><option value="normal">Normal</option><option value="important">Important</option><option value="urgent">Urgent</option></select></Field><Field label="Audience"><select value={announcement.target} onChange={e=>setAnnouncement({...announcement,target:e.target.value as Target,target_id:''})}><option value="all">Everyone</option><option value="employee">One employee</option><option value="role">Role</option><option value="department">Department</option></select></Field>{announcement.target!=='all'&&<Field label="Target"><select value={announcement.target_id} onChange={e=>setAnnouncement({...announcement,target_id:e.target.value})}><option value="">Choose target</option>{announcement.target==='employee'?employees.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>):announcement.target==='role'?roles.map(x=><option key={x.id} value={x.id}>{x.name}</option>):departments.map(x=><option key={x} value={x}>{label(x)}</option>)}</select></Field>}<Field label="Acknowledgment"><select value={announcement.requires_acknowledgment?'required':'read'} disabled={announcement.priority==='urgent'} onChange={e=>setAnnouncement({...announcement,requires_acknowledgment:e.target.value==='required'})}><option value="read">Read tracking only</option><option value="required">Require acknowledgment</option></select></Field><Field label="Expires (optional)"><input type="datetime-local" value={announcement.expires_at} onChange={e=>setAnnouncement({...announcement,expires_at:e.target.value})}/></Field><Field label="Message" wide><textarea maxLength={10000} value={announcement.body} onChange={e=>setAnnouncement({...announcement,body:e.target.value})}/></Field></div>{announcement.priority==='urgent'&&<p className={styles.muted}>Urgent announcements always require employee acknowledgment.</p>}<div className={styles.actions}><button className={styles.button} disabled={busy}>Send announcement</button></div></form></div></section>}
  <section className={styles.section}><h2>Announcements</h2><div className={styles.list}>{activeAnnouncements.map(a=>{const mine=recipient(a.id),all=recipients.filter(r=>r.announcement_id===a.id),read=all.filter(r=>r.read_at).length,acked=all.filter(r=>r.acknowledged_at).length;return <div className={styles.entry} key={a.id}><div className={styles.entryHead}><div><h3>{a.title}</h3><small>{new Date(a.sent_at).toLocaleString()}{a.expires_at?` · expires ${new Date(a.expires_at).toLocaleString()}`:''}{a.requires_acknowledgment?' · acknowledgment required':''}</small></div><span className={styles.pill}>{a.priority}</span></div><p>{a.body}</p>{manager&&<div className={styles.details}><Detail label="Recipients" value={String(all.length)}/><Detail label="Read" value={`${read}/${all.length}`}/>{a.requires_acknowledgment&&<Detail label="Acknowledged" value={`${acked}/${all.length}`}/>}<Detail label="Unread" value={String(all.length-read)}/></div>}<div className={styles.actions}>{mine&&!mine.read_at&&<button className={styles.button} disabled={busy} onClick={()=>markRead(a.id)}>Mark read</button>}{manager&&<><button className={`${styles.button} ${styles.secondary}`} disabled={busy||all.length===read} onClick={()=>remind(a.id)}>Remind unread</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>archive(a.id)}>Archive</button></>}</div></div>})}{!activeAnnouncements.length&&<div className={styles.empty}>No active announcements.</div>}</div></section>
  <section className={styles.section}><div className={styles.card}><h2>Give a shout-out</h2>{!me?<div className={styles.empty}>Your account must be linked to an employee record to post recognition.</div>:<form onSubmit={createShoutout}><div className={styles.formGrid}><Field label="Teammate"><select value={shoutout.to_employee_id} onChange={e=>setShoutout({...shoutout,to_employee_id:e.target.value})}><option value="">Choose teammate</option>{employees.filter(e=>e.id!==me).map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select></Field><Field label="Category"><select value={shoutout.category} onChange={e=>setShoutout({...shoutout,category:e.target.value})}>{categories.map(c=><option key={c} value={c}>{label(c)}</option>)}</select></Field><Field label="Message" wide><textarea maxLength={1000} value={shoutout.message} onChange={e=>setShoutout({...shoutout,message:e.target.value})}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy}>Post shout-out</button></div></form>}</div></section>
  <section className={styles.section}><h2>Recognition feed</h2><div className={styles.list}>{shoutouts.filter(s=>manager||!s.hidden_at).map(s=>{const counts=Object.fromEntries(reactions.map(k=>[k,reactionRows.filter(r=>r.shoutout_id===s.id&&r.reaction===k).length]));return <div className={styles.entry} key={s.id}><div className={styles.entryHead}><div><h3>{name(s.to_employee_id)}</h3><small>From {name(s.from_employee_id)} · {label(s.category)} · {new Date(s.created_at).toLocaleString()}</small></div><span className={styles.pill}>{s.hidden_at?'hidden':'visible'}</span></div><p>{s.message}</p>{!s.hidden_at&&<div className={styles.actions}>{reactions.map(r=><button key={r} className={`${styles.button} ${reactionRows.some(x=>x.shoutout_id===s.id&&x.employee_id===me&&x.reaction===r)?'':styles.secondary}`} disabled={busy||!me} onClick={()=>toggleReaction(s.id,r)}>{label(r)} {counts[r]}</button>)}</div>}{manager&&!s.hidden_at&&<div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>hideShoutout(s.id)}>Hide</button></div>}</div>})}{!shoutouts.length&&<div className={styles.empty}>No shout-outs yet.</div>}</div></section>
 </main>
}
function Metric({label,value}:{label:string;value:string}){return <div className={styles.metric}><span>{label}</span><strong>{value}</strong></div>}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={`${styles.field} ${wide?styles.wide:''}`}><span>{label}</span>{children}</label>}
function Detail({label,value}:{label:string;value:string}){return <div className={styles.detail}><b>{label}</b><span>{value}</span></div>}
