'use client';

import {FormEvent,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase';
import {useI18n} from '@/lib/i18n';
import styles from '../ops-tools.module.css';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Employee={id:string;full_name:string};
type DirectoryRow={employee_id:string;full_name:string};
type Role={id:string;name:string;department:string|null};
type Announcement={id:string;title:string;body:string;priority:'normal'|'important'|'urgent';expires_at:string|null;sent_at:string;archived_at:string|null;requires_acknowledgment:boolean};
type Recipient={announcement_id:string;employee_id:string;read_at:string|null;acknowledged_at:string|null;reminder_count:number;last_reminded_at:string|null};
type Shoutout={id:string;from_employee_id:string;to_employee_id:string;category:string;message:string;created_at:string;hidden_at:string|null};
type Reaction={shoutout_id:string;employee_id:string;reaction:'applause'|'heart'|'fire'|'thanks';created_at:string};
type Target='all'|'employee'|'role'|'department';
const categories=['great_job','teamwork','guest_service','leadership','hustle','growth','other'] as const;
const reactions=['applause','heart','fire','thanks'] as const;
const label=(s:string)=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const blankAnnouncement=()=>({title:'',body:'',priority:'normal',target:'all' as Target,target_id:'',expires_at:'',requires_acknowledgment:false});

export default function TeamPage(){
 const {locale}=useI18n();const t=(en:string,es:string)=>locale==='es'?es:en;const localeCode=locale==='es'?'es-US':'en-US';const systemLabel=(v:string)=>locale==='es'?({normal:'Normal',important:'Importante',urgent:'Urgente',great_job:'Gran trabajo',teamwork:'Trabajo en equipo',guest_service:'Servicio al cliente',leadership:'Liderazgo',hustle:'Esfuerzo',growth:'Crecimiento',other:'Otro',applause:'Aplausos',heart:'Corazón',fire:'Fuego',thanks:'Gracias'}[v]||label(v)):label(v);
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[profile,setProfile]=useState<Profile|null>(null),[me,setMe]=useState<string|null>(null),[employees,setEmployees]=useState<Employee[]>([]),[roles,setRoles]=useState<Role[]>([]),[announcements,setAnnouncements]=useState<Announcement[]>([]),[recipients,setRecipients]=useState<Recipient[]>([]),[shoutouts,setShoutouts]=useState<Shoutout[]>([]),[reactionRows,setReactionRows]=useState<Reaction[]>([]),[announcement,setAnnouncement]=useState(blankAnnouncement),[shoutout,setShoutout]=useState({to_employee_id:'',category:'great_job',message:''});
 const manager=profile?.app_role==='admin'||profile?.app_role==='manager';
 const departments=useMemo(()=>Array.from(new Set(roles.map(r=>r.department).filter((x):x is string=>Boolean(x)))).sort(),[roles]);
 const activeAnnouncements=useMemo(()=>announcements.filter(a=>!a.archived_at).sort((a,b)=>b.sent_at.localeCompare(a.sent_at)),[announcements]);
 useEffect(()=>{void load()},[]);
 async function load(){setBusy(true);const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}const p=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();if(p.error||!p.data?.location_id){setMessage(t('Could not load team access.','No se pudo cargar el acceso al equipo.'));setReady(true);setBusy(false);return}const pr=p.data as Profile;setProfile(pr);const [eid,e,r,a,ar,s,sr]=await Promise.all([supabase.rpc('time_clock_employee_id_for_user',{}),supabase.rpc('staff_directory',{}),supabase.from('employee_roles').select('id,name,department').eq('location_id',pr.location_id).order('name'),supabase.from('team_announcements').select('id,title,body,priority,expires_at,sent_at,archived_at,requires_acknowledgment').eq('location_id',pr.location_id).order('sent_at',{ascending:false}).limit(200),supabase.from('team_announcement_recipients').select('announcement_id,employee_id,read_at,acknowledged_at,reminder_count,last_reminded_at').eq('location_id',pr.location_id).limit(5000),supabase.from('team_shoutouts').select('id,from_employee_id,to_employee_id,category,message,created_at,hidden_at').eq('location_id',pr.location_id).order('created_at',{ascending:false}).limit(300),supabase.from('team_shoutout_reactions').select('shoutout_id,employee_id,reaction,created_at').eq('location_id',pr.location_id).limit(5000)]);if([eid,e,r,a,ar,s,sr].some(x=>x.error))setMessage(t('Some team data could not be loaded.','Algunos datos del equipo no se pudieron cargar.'));setMe((eid.data as string|null)||null);setEmployees(((e.data??[]) as DirectoryRow[]).map(x=>({id:x.employee_id,full_name:x.full_name})));setRoles((r.data??[]) as Role[]);setAnnouncements((a.data??[]) as Announcement[]);setRecipients((ar.data??[]) as Recipient[]);setShoutouts((s.data??[]) as Shoutout[]);setReactionRows((sr.data??[]) as Reaction[]);setReady(true);setBusy(false)}
 const name=(id:string)=>employees.find(e=>e.id===id)?.full_name||t('Team member','Miembro del equipo');
 const recipient=(announcementId:string)=>recipients.find(r=>r.announcement_id===announcementId&&r.employee_id===me);
 async function sendAnnouncement(e:FormEvent){e.preventDefault();if(!manager||busy||!announcement.title.trim()||!announcement.body.trim())return;if(announcement.target!=='all'&&!announcement.target_id)return setMessage(t('Choose an announcement audience.','Elige la audiencia del anuncio.'));setBusy(true);const roleIds=announcement.target==='role'?[announcement.target_id]:null,departmentsArg=announcement.target==='department'?[announcement.target_id]:null,employeeIds=announcement.target==='employee'?[announcement.target_id]:null;const {data,error}=await supabase.rpc('send_team_announcement',{p_title:announcement.title.trim(),p_body:announcement.body.trim(),p_priority:announcement.priority,p_role_ids:roleIds,p_departments:departmentsArg,p_employee_ids:employeeIds,p_expires_at:announcement.expires_at?new Date(announcement.expires_at).toISOString():null,p_requires_acknowledgment:announcement.requires_acknowledgment});if(error)setMessage(error.message);else{setAnnouncement(blankAnnouncement());setMessage(`${t('Announcement sent to','Anuncio enviado a')} ${Number((data as any)?.recipients||0)} ${Number((data as any)?.recipients||0)===1?t('teammate','compañero'):t('teammates','compañeros')}${(data as any)?.requires_acknowledgment?` · ${t('acknowledgment required','se requiere confirmación')}`:''}.`);await load()}setBusy(false)}
 async function markRead(id:string){if(busy)return;setBusy(true);const {error}=await supabase.rpc('mark_team_announcement_read',{p_announcement_id:id});setMessage(error?error.message:t('Announcement marked read.','Anuncio marcado como leído.'));await load();setBusy(false)}
 async function remind(id:string){if(!manager||busy)return;setBusy(true);const {data,error}=await supabase.rpc('remind_unread_team_announcement',{p_announcement_id:id});setMessage(error?error.message:`${t('Reminder recorded for','Recordatorio registrado para')} ${Number(data||0)} ${Number(data||0)===1?t('unread recipient','destinatario sin leer'):t('unread recipients','destinatarios sin leer')}.`);await load();setBusy(false)}
 async function archive(id:string){if(!manager||busy)return;setBusy(true);const {error}=await supabase.rpc('archive_team_announcement',{p_announcement_id:id});setMessage(error?error.message:t('Announcement archived.','Anuncio archivado.'));await load();setBusy(false)}
 async function createShoutout(e:FormEvent){e.preventDefault();if(!me||busy||!shoutout.to_employee_id||!shoutout.message.trim())return;setBusy(true);const {error}=await supabase.rpc('create_team_shoutout',{p_to_employee_id:shoutout.to_employee_id,p_category:shoutout.category,p_message:shoutout.message.trim()});if(!error)setShoutout({to_employee_id:'',category:'great_job',message:''});setMessage(error?error.message:t('Shout-out posted.','Reconocimiento publicado.'));await load();setBusy(false)}
 async function toggleReaction(id:string,reaction:Reaction['reaction']){if(!me||busy)return;setBusy(true);const exists=reactionRows.some(r=>r.shoutout_id===id&&r.employee_id===me&&r.reaction===reaction);const {error}=exists?await supabase.rpc('remove_team_shoutout_reaction',{p_shoutout_id:id,p_reaction:reaction}):await supabase.rpc('react_to_team_shoutout',{p_shoutout_id:id,p_reaction:reaction});if(error)setMessage(error.message);await load();setBusy(false)}
 async function hideShoutout(id:string){if(!manager||busy)return;setBusy(true);const {error}=await supabase.rpc('hide_team_shoutout',{p_shoutout_id:id});setMessage(error?error.message:t('Shout-out hidden from the team feed.','Reconocimiento ocultado del feed del equipo.'));await load();setBusy(false)}
 if(!ready)return <main className={styles.page}>{t('Loading team hub…','Cargando centro del equipo…')}</main>;if(!profile?.location_id)return <main className={styles.page}>{t('No restaurant location is assigned.','No hay una ubicación de restaurante asignada.')}</main>;
 return <main className={styles.page}><div className={styles.top}><div><h1>{t('Team Hub','Centro del Equipo')}</h1><p>{manager?t('Targeted announcements, read tracking and teammate recognition.','Anuncios dirigidos, seguimiento de lectura y reconocimiento del equipo.'):t('Announcements and recognition for the El Molino team.','Anuncios y reconocimiento para el equipo de El Molino.')}</p></div><Link className={styles.back} href={manager?'/tools':'/employee'}>{manager?t('Back to Tools','Volver a Herramientas'):t('Staff Home','Inicio del Personal')}</Link></div>{message&&<div className={message.toLowerCase().includes('could not')||message.toLowerCase().includes('no se pudo')?styles.error:styles.notice}>{message}</div>}
  <div className={styles.grid}><Metric label={t('Active announcements','Anuncios activos')} value={String(activeAnnouncements.length)}/><Metric label={t('Unread for me','Sin leer para mí')} value={String(activeAnnouncements.filter(a=>{const r=recipient(a.id);return r&&!r.read_at}).length)}/><Metric label={t('Visible shout-outs','Reconocimientos visibles')} value={String(shoutouts.filter(s=>!s.hidden_at).length)}/><Metric label={t('Team members','Miembros del equipo')} value={String(employees.length)}/></div>
  {manager&&<section className={styles.section}><div className={styles.card}><h2>{t('Send announcement','Enviar anuncio')}</h2><form onSubmit={sendAnnouncement}><div className={styles.formGrid}><Field label={t('Title','Título')}><input maxLength={160} value={announcement.title} onChange={e=>setAnnouncement({...announcement,title:e.target.value})}/></Field><Field label={t('Priority','Prioridad')}><select value={announcement.priority} onChange={e=>setAnnouncement({...announcement,priority:e.target.value})}><option value="normal">{t('Normal','Normal')}</option><option value="important">{t('Important','Importante')}</option><option value="urgent">{t('Urgent','Urgente')}</option></select></Field><Field label={t('Audience','Audiencia')}><select value={announcement.target} onChange={e=>setAnnouncement({...announcement,target:e.target.value as Target,target_id:''})}><option value="all">{t('Everyone','Todos')}</option><option value="employee">{t('One employee','Un empleado')}</option><option value="role">{t('Role','Puesto')}</option><option value="department">{t('Department','Departamento')}</option></select></Field>{announcement.target!=='all'&&<Field label={t('Target','Destino')}><select value={announcement.target_id} onChange={e=>setAnnouncement({...announcement,target_id:e.target.value})}><option value="">{t('Choose target','Elegir destino')}</option>{announcement.target==='employee'?employees.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>):announcement.target==='role'?roles.map(x=><option key={x.id} value={x.id}>{x.name}</option>):departments.map(x=><option key={x} value={x}>{label(x)}</option>)}</select></Field>}<Field label={t('Acknowledgment','Confirmación')}><select value={announcement.requires_acknowledgment?'required':'read'} disabled={announcement.priority==='urgent'} onChange={e=>setAnnouncement({...announcement,requires_acknowledgment:e.target.value==='required'})}><option value="read">{t('Read tracking only','Solo seguimiento de lectura')}</option><option value="required">{t('Require acknowledgment','Requerir confirmación')}</option></select></Field><Field label={t('Expires (optional)','Vence (opcional)')}><input type="datetime-local" value={announcement.expires_at} onChange={e=>setAnnouncement({...announcement,expires_at:e.target.value})}/></Field><Field label={t('Message','Mensaje')} wide><textarea maxLength={10000} value={announcement.body} onChange={e=>setAnnouncement({...announcement,body:e.target.value})}/></Field></div>{announcement.priority==='urgent'&&<p className={styles.muted}>{t('Urgent announcements always require employee acknowledgment.','Los anuncios urgentes siempre requieren confirmación del empleado.')}</p>}<div className={styles.actions}><button className={styles.button} disabled={busy}>{t('Send announcement','Enviar anuncio')}</button></div></form></div></section>}
  <section className={styles.section}><h2>{t('Announcements','Anuncios')}</h2><div className={styles.list}>{activeAnnouncements.map(a=>{const mine=recipient(a.id),all=recipients.filter(r=>r.announcement_id===a.id),read=all.filter(r=>r.read_at).length,acked=all.filter(r=>r.acknowledged_at).length;return <div className={styles.entry} key={a.id}><div className={styles.entryHead}><div><h3>{a.title}</h3><small>{new Date(a.sent_at).toLocaleString(localeCode)}{a.expires_at?` · ${t('expires','vence')} ${new Date(a.expires_at).toLocaleString(localeCode)}`:''}{a.requires_acknowledgment?` · ${t('acknowledgment required','se requiere confirmación')}`:''}</small></div><span className={styles.pill}>{systemLabel(a.priority)}</span></div><p>{a.body}</p>{manager&&<div className={styles.details}><Detail label={t('Recipients','Destinatarios')} value={String(all.length)}/><Detail label={t('Read','Leídos')} value={`${read}/${all.length}`}/>{a.requires_acknowledgment&&<Detail label={t('Acknowledged','Confirmados')} value={`${acked}/${all.length}`}/>}<Detail label={t('Unread','Sin leer')} value={String(all.length-read)}/></div>}<div className={styles.actions}>{mine&&!mine.read_at&&<button className={styles.button} disabled={busy} onClick={()=>markRead(a.id)}>{t('Mark read','Marcar leído')}</button>}{manager&&<><button className={`${styles.button} ${styles.secondary}`} disabled={busy||all.length===read} onClick={()=>remind(a.id)}>{t('Remind unread','Recordar a no lectores')}</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>archive(a.id)}>{t('Archive','Archivar')}</button></>}</div></div>})}{!activeAnnouncements.length&&<div className={styles.empty}>{t('No active announcements.','No hay anuncios activos.')}</div>}</div></section>
  <section className={styles.section}><div className={styles.card}><h2>{t('Give a shout-out','Dar un reconocimiento')}</h2>{!me?<div className={styles.empty}>{t('Your account must be linked to an employee record to post recognition.','Tu cuenta debe estar vinculada a un empleado para publicar reconocimientos.')}</div>:<form onSubmit={createShoutout}><div className={styles.formGrid}><Field label={t('Teammate','Compañero')}><select value={shoutout.to_employee_id} onChange={e=>setShoutout({...shoutout,to_employee_id:e.target.value})}><option value="">{t('Choose teammate','Elegir compañero')}</option>{employees.filter(e=>e.id!==me).map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select></Field><Field label={t('Category','Categoría')}><select value={shoutout.category} onChange={e=>setShoutout({...shoutout,category:e.target.value})}>{categories.map(c=><option key={c} value={c}>{systemLabel(c)}</option>)}</select></Field><Field label={t('Message','Mensaje')} wide><textarea maxLength={1000} value={shoutout.message} onChange={e=>setShoutout({...shoutout,message:e.target.value})}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy}>{t('Post shout-out','Publicar reconocimiento')}</button></div></form>}</div></section>
  <section className={styles.section}><h2>{t('Recognition feed','Feed de reconocimiento')}</h2><div className={styles.list}>{shoutouts.filter(s=>manager||!s.hidden_at).map(s=>{const counts=Object.fromEntries(reactions.map(k=>[k,reactionRows.filter(r=>r.shoutout_id===s.id&&r.reaction===k).length]));return <div className={styles.entry} key={s.id}><div className={styles.entryHead}><div><h3>{name(s.to_employee_id)}</h3><small>{t('From','De')} {name(s.from_employee_id)} · {systemLabel(s.category)} · {new Date(s.created_at).toLocaleString(localeCode)}</small></div><span className={styles.pill}>{s.hidden_at?t('hidden','oculto'):t('visible','visible')}</span></div><p>{s.message}</p>{!s.hidden_at&&<div className={styles.actions}>{reactions.map(r=><button key={r} className={`${styles.button} ${reactionRows.some(x=>x.shoutout_id===s.id&&x.employee_id===me&&x.reaction===r)?'':styles.secondary}`} disabled={busy||!me} onClick={()=>toggleReaction(s.id,r)}>{systemLabel(r)} {counts[r]}</button>)}</div>}{manager&&!s.hidden_at&&<div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>hideShoutout(s.id)}>{t('Hide','Ocultar')}</button></div>}</div>})}{!shoutouts.length&&<div className={styles.empty}>{t('No shout-outs yet.','Aún no hay reconocimientos.')}</div>}</div></section>
 </main>
}
function Metric({label,value}:{label:string;value:string}){return <div className={styles.metric}><span>{label}</span><strong>{value}</strong></div>}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={`${styles.field} ${wide?styles.wide:''}`}><span>{label}</span>{children}</label>}
function Detail({label,value}:{label:string;value:string}){return <div className={styles.detail}><b>{label}</b><span>{value}</span></div>}
