'use client';

import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase';
import styles from '../../ops-tools.module.css';
import {businessDateInZone} from '@/lib/intermediate-hardening';
import {suggestForecastWeek,projectedLaborHours,type HistoricalPerformance} from '@/lib/schedule-forecast';
import {addDateDays,dateDayOfWeek,generateSchedule,shiftNetHours,zonedLocalToIso,type AvailabilityRow,type CoverageRequirement,type DailyForecast,type ExistingShift,type OptimizationMode,type ScheduleProfile,type ScheduleGenerationResult} from '@/lib/scheduling-engine';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Employee={id:string;full_name:string;active:boolean};
type Role={id:string;name:string};
type Period={id:string;starts_on:string;ends_on:string;status:string;revision:number};
type TimeOff={employee_id:string;starts_on:string;ends_on:string;status:string};
type RoleAssignment={employee_id:string;role_id:string};
type Settings={timezone:string;overtime_after_hours:number;overtime_multiplier:number;auto_schedule_mode:'minimum'|'target';optimization_mode:OptimizationMode;sales_per_labor_hour_target:number|null;require_full_coverage_to_publish:boolean;open_shift_claim_requires_approval:boolean};
const DEFAULT:Settings={timezone:'America/New_York',overtime_after_hours:40,overtime_multiplier:1.5,auto_schedule_mode:'target',optimization_mode:'balanced',sales_per_labor_hour_target:null,require_full_coverage_to_publish:true,open_shift_claim_requires_approval:true};
const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const mondayOf=(d:string)=>addDateDays(d,-((dateDayOfWeek(d)+6)%7));
const n=(v:unknown,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const hh=(v:string)=>v.slice(0,5);
const money=(v:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v);
function normalizeProfile(x:any):ScheduleProfile{return {employee_id:x.employee_id,min_weekly_hours:n(x.min_weekly_hours),target_weekly_hours:x.target_weekly_hours===null?null:n(x.target_weekly_hours),max_weekly_hours:x.max_weekly_hours===null?null:n(x.max_weekly_hours),max_shift_hours:n(x.max_shift_hours,12),min_rest_hours:n(x.min_rest_hours,8),max_consecutive_days:n(x.max_consecutive_days,6),hourly_rate:x.hourly_rate===null?null:n(x.hourly_rate),avoid_overtime:x.avoid_overtime!==false,preferred_days_off:Array.isArray(x.preferred_days_off)?x.preferred_days_off.map(Number):[],preferred_start:x.preferred_start,preferred_end:x.preferred_end,allow_split_shifts:x.allow_split_shifts!==false,min_split_gap_hours:n(x.min_split_gap_hours,.5)}}

export default function ScheduleOptimizerPage(){
  const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const [profile,setProfile]=useState<Profile|null>(null),[weekStart,setWeekStart]=useState(()=>mondayOf(businessDateInZone())),[period,setPeriod]=useState<Period|null>(null),[settings,setSettings]=useState<Settings>(DEFAULT);
  const [employees,setEmployees]=useState<Employee[]>([]),[roles,setRoles]=useState<Role[]>([]),[roleAssignments,setRoleAssignments]=useState<RoleAssignment[]>([]),[availability,setAvailability]=useState<AvailabilityRow[]>([]),[timeOff,setTimeOff]=useState<TimeOff[]>([]),[profiles,setProfiles]=useState<ScheduleProfile[]>([]),[requirements,setRequirements]=useState<CoverageRequirement[]>([]),[shifts,setShifts]=useState<ExistingShift[]>([]),[history,setHistory]=useState<HistoricalPerformance[]>([]),[forecastDraft,setForecastDraft]=useState<Record<string,string>>({}),[preview,setPreview]=useState<ScheduleGenerationResult|null>(null);
  useEffect(()=>{void init()},[]);
  async function init(){setReady(false);const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}const {data:p,error}=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();if(error||!p||!p.location_id){setMessage('No restaurant location is assigned to this account.');setReady(true);return}const pr=p as Profile;if(pr.app_role!=='admin'&&pr.app_role!=='manager'){location.href='/schedule';return}setProfile(pr);const ws=mondayOf(businessDateInZone());setWeekStart(ws);await load(pr.location_id!,ws);setReady(true)}
  async function load(locationId=profile?.location_id||'',ws=weekStart){if(!locationId)return;setBusy(true);setPreview(null);try{
    const sRes=await supabase.from('schedule_settings').select('timezone,overtime_after_hours,overtime_multiplier,auto_schedule_mode,optimization_mode,sales_per_labor_hour_target,require_full_coverage_to_publish,open_shift_claim_requires_approval').eq('location_id',locationId).maybeSingle();if(sRes.error)throw sRes.error;
    const s:Settings=sRes.data?{timezone:sRes.data.timezone||DEFAULT.timezone,overtime_after_hours:n(sRes.data.overtime_after_hours,40),overtime_multiplier:n(sRes.data.overtime_multiplier,1.5),auto_schedule_mode:sRes.data.auto_schedule_mode==='minimum'?'minimum':'target',optimization_mode:(sRes.data.optimization_mode||'balanced') as OptimizationMode,sales_per_labor_hour_target:sRes.data.sales_per_labor_hour_target===null?null:n(sRes.data.sales_per_labor_hour_target),require_full_coverage_to_publish:sRes.data.require_full_coverage_to_publish!==false,open_shift_claim_requires_approval:sRes.data.open_shift_claim_requires_approval!==false}:DEFAULT;setSettings(s);
    const per=await supabase.rpc('ensure_schedule_period',{p_starts_on:ws});if(per.error)throw per.error;setPeriod(per.data as Period);
    const from=zonedLocalToIso(addDateDays(ws,-14),'00:00:00',s.timezone),to=zonedLocalToIso(addDateDays(ws,21),'00:00:00',s.timezone);
    const [e,r,ra,av,o,sp,cr,sh,fc,hist]=await Promise.all([
      supabase.from('employees').select('id,full_name,active').eq('location_id',locationId).is('deleted_at',null).eq('active',true).order('full_name'),
      supabase.from('employee_roles').select('id,name').eq('location_id',locationId).order('name'),
      supabase.from('employee_role_assignments').select('employee_id,role_id'),
      supabase.from('employee_availability').select('employee_id,day_of_week,available_from,available_to,unavailable').eq('location_id',locationId),
      supabase.from('time_off_requests').select('employee_id,starts_on,ends_on,status').eq('location_id',locationId).gte('ends_on',addDateDays(ws,-14)).lte('starts_on',addDateDays(ws,21)),
      supabase.from('employee_schedule_profiles').select('employee_id,min_weekly_hours,target_weekly_hours,max_weekly_hours,max_shift_hours,min_rest_hours,max_consecutive_days,hourly_rate,avoid_overtime,preferred_days_off,preferred_start,preferred_end,allow_split_shifts,min_split_gap_hours').eq('location_id',locationId),
      supabase.from('schedule_coverage_requirements').select('id,name,day_of_week,role_id,starts_at,ends_at,min_staff,target_staff,max_staff,break_minutes,priority,shift_type,active,effective_from,effective_to,demand_scalable').eq('location_id',locationId).order('day_of_week').order('starts_at'),
      supabase.from('schedule_shifts').select('id,employee_id,role_id,starts_at,ends_at,break_minutes,status,source,is_locked,coverage_requirement_id,schedule_period_id').eq('location_id',locationId).gte('starts_at',from).lt('starts_at',to).neq('status','cancelled').order('starts_at'),
      supabase.from('schedule_daily_forecasts').select('business_date,projected_sales,source,confidence').eq('location_id',locationId).gte('business_date',ws).lte('business_date',addDateDays(ws,6)),
      supabase.from('restaurant_daily_performance').select('business_date,net_sales,labor_hours').eq('location_id',locationId).gte('business_date',addDateDays(ws,-84)).lt('business_date',ws).order('business_date',{ascending:false})
    ]);
    if([e,r,ra,av,o,sp,cr,sh,fc,hist].some(x=>x.error))throw new Error('load');
    setEmployees((e.data??[]) as Employee[]);setRoles((r.data??[]) as Role[]);setRoleAssignments((ra.data??[]) as RoleAssignment[]);setAvailability((av.data??[]) as AvailabilityRow[]);setTimeOff((o.data??[]) as TimeOff[]);setProfiles((sp.data??[]).map(normalizeProfile));setRequirements((cr.data??[]).map((x:any)=>({...x,day_of_week:n(x.day_of_week),min_staff:n(x.min_staff),target_staff:n(x.target_staff),max_staff:x.max_staff===null?null:n(x.max_staff),break_minutes:n(x.break_minutes),priority:n(x.priority,50),demand_scalable:Boolean(x.demand_scalable)})) as CoverageRequirement[]);setShifts((sh.data??[]) as ExistingShift[]);setHistory((hist.data??[]).map((x:any)=>({business_date:x.business_date,net_sales:n(x.net_sales),labor_hours:x.labor_hours===null?null:n(x.labor_hours)})));const draft:Record<string,string>={};for(let i=0;i<7;i++)draft[addDateDays(ws,i)]='';for(const x of fc.data??[])draft[x.business_date]=String(x.projected_sales);setForecastDraft(draft);
  }catch{setMessage('Could not load the optimizer workspace.')}finally{setBusy(false)}}
  async function changeWeek(delta:number){if(!profile?.location_id||busy)return;const ws=addDateDays(weekStart,delta);setWeekStart(ws);await load(profile.location_id,ws)}
  const weekDates=useMemo(()=>Array.from({length:7},(_,i)=>addDateDays(weekStart,i)),[weekStart]);
  const roleName=(id:string)=>roles.find(x=>x.id===id)?.name||'Role';
  const forecasts:DailyForecast[]=useMemo(()=>weekDates.flatMap(d=>forecastDraft[d]!==''&&Number.isFinite(Number(forecastDraft[d]))?[{business_date:d,projected_sales:n(forecastDraft[d]),source:'manual'}]:[]),[weekDates,forecastDraft]);
  const totalForecast=forecasts.reduce((a,b)=>a+b.projected_sales,0),targetLabor=forecasts.reduce((a,b)=>a+(projectedLaborHours(b.projected_sales,settings.sales_per_labor_hour_target)||0),0),missingRates=employees.filter(e=>!profiles.find(p=>p.employee_id===e.id)?.hourly_rate).length;
  function input(){if(!period)throw new Error('period');return {period,employees,roles,roleAssignments,availability,timeOff,profiles,requirements,existingShifts:shifts,forecasts,settings:{timezone:settings.timezone,overtime_after_hours:settings.overtime_after_hours,overtime_multiplier:settings.overtime_multiplier,mode:settings.auto_schedule_mode,preserve_manual_shifts:true,optimization_mode:settings.optimization_mode,sales_per_labor_hour_target:settings.sales_per_labor_hour_target}}}
  function makePreview(){if(!period||period.status!=='draft'){setMessage('Reopen the schedule before optimizing it.');return}try{const x=generateSchedule(input());setPreview(x);setMessage(x.metrics.open_slots?`Optimizer created a safe draft with ${x.metrics.open_slots} unfilled slot${x.metrics.open_slots===1?'':'s'} left open.`:'Optimizer created a fully covered draft.')}catch{setMessage('The optimizer could not build this week. Review coverage rules and employee setup.')}}
  async function applyPreview(){if(!period||!preview||busy)return;setBusy(true);const {data,error}=await supabase.rpc('apply_schedule_generation',{p_period_id:period.id,p_expected_revision:period.revision,p_shifts:preview.shifts,p_client_issues:preview.issues,p_metrics:{...preview.metrics,objective_score:preview.objective_score},p_settings:{algorithm_version:preview.algorithm_version,mode:settings.auto_schedule_mode,optimization_mode:settings.optimization_mode,sales_per_labor_hour_target:settings.sales_per_labor_hour_target,forecasts}});if(error){setMessage(error.message.includes('reload')?'The schedule changed elsewhere, so the optimizer refused to overwrite it. Reloading now.':'The database rejected the generated schedule because a safety rule failed. Nothing was partially applied.')}else setMessage(`Optimized draft applied: ${data?.inserted_shifts??preview.shifts.length} generated shifts.`);setPreview(null);await load();setBusy(false)}
  async function saveSettings(){if(!profile?.location_id||busy)return;setBusy(true);const {error}=await supabase.from('schedule_settings').upsert({location_id:profile.location_id,timezone:settings.timezone,overtime_after_hours:settings.overtime_after_hours,overtime_multiplier:settings.overtime_multiplier,auto_schedule_mode:settings.auto_schedule_mode,optimization_mode:settings.optimization_mode,sales_per_labor_hour_target:settings.sales_per_labor_hour_target,require_full_coverage_to_publish:settings.require_full_coverage_to_publish,open_shift_claim_requires_approval:settings.open_shift_claim_requires_approval},{onConflict:'location_id'});setMessage(error?'Could not save optimizer rules.':'Optimizer rules saved.');setBusy(false)}
  async function saveForecasts(){if(!profile?.location_id||busy)return;for(const d of weekDates){const v=forecastDraft[d];if(v!==''&&n(v)<0){setMessage('Forecast sales cannot be negative.');return}}setBusy(true);try{for(const d of weekDates){const v=forecastDraft[d];if(v===''){const del=await supabase.from('schedule_daily_forecasts').delete().eq('location_id',profile.location_id).eq('business_date',d);if(del.error)throw del.error}else{const up=await supabase.from('schedule_daily_forecasts').upsert({location_id:profile.location_id,business_date:d,projected_sales:n(v),source:'manual',confidence:null},{onConflict:'location_id,business_date'});if(up.error)throw up.error}}setMessage('Sales forecast saved for this week.')}catch{setMessage('Could not save the sales forecast.')}finally{setBusy(false)}}
  function estimateFromHistory(){const suggestions=suggestForecastWeek(history,weekStart);if(!suggestions.length){setMessage('There is not enough saved sales history yet to estimate this week. Enter forecasts manually or import performance data first.');return}const next={...forecastDraft};for(const x of suggestions)next[x.business_date]=String(Math.round(x.projected_sales));setForecastDraft(next);setMessage(`Estimated ${suggestions.length} day${suggestions.length===1?'':'s'} from same-weekday sales history. Review the numbers before saving.`)}
  async function saveRequirement(r:CoverageRequirement){if(busy)return;setBusy(true);const {error}=await supabase.from('schedule_coverage_requirements').update({demand_scalable:Boolean(r.demand_scalable),max_staff:r.max_staff}).eq('id',r.id);setMessage(error?'Could not save that demand rule.':'Coverage demand rule saved.');setBusy(false)}
  function editRequirement(id:string,key:'demand_scalable'|'max_staff',value:any){setRequirements(xs=>xs.map(x=>x.id===id?{...x,[key]:value}:x))}
  async function copyPrevious(copyAssignments:boolean){if(!period||!profile?.location_id||busy)return;if(period.status!=='draft'){setMessage('The target week must be a draft before copying.');return}if(shifts.some(s=>s.schedule_period_id===period.id&&s.status!=='cancelled')){setMessage('This week already has shifts. Copy-week is intentionally blocked to prevent duplicates.');return}const prev=addDateDays(weekStart,-7);setBusy(true);try{const src=await supabase.from('schedule_periods').select('id').eq('location_id',profile.location_id).eq('starts_on',prev).eq('ends_on',addDateDays(prev,6)).maybeSingle();if(src.error)throw src.error;if(!src.data){setMessage('There is no previous Scheduling v2 week to copy yet.');return}if(copyAssignments&&!confirm('Copy last week with the same employees? Availability, approved time off, qualifications, rest and hour limits will still be enforced.'))return;const {data,error}=await supabase.rpc('copy_schedule_period',{p_source_period_id:src.data.id,p_target_period_id:period.id,p_expected_revision:period.revision,p_copy_assignments:copyAssignments});if(error)throw error;setMessage(`Copied ${data?.copied??0} shift${data?.copied===1?'':'s'} from last week ${copyAssignments?'with employee assignments':'as open structure'}.`);await load()}catch(e:any){setMessage(String(e?.message||'').includes('safety')?'Copy rejected by a scheduling safety rule.':'Could not copy last week. If copying assignments, a new availability, leave, rest, or hours conflict may be blocking it.')}finally{setBusy(false)}}

  if(!ready)return <main className={styles.page}>Loading optimizer…</main>;
  if(!profile?.location_id)return <main className={styles.page}>{message||'No location assigned.'}</main>;
  return <main className={styles.page}>
    <div className={styles.top}><div><h1>Schedule Optimizer</h1><p>Build coverage around demand, labor cost, fairness and employee constraints before publishing.</p></div><Link className={styles.back} href="/schedule">Back to Schedule</Link></div>
    {message&&<div className={message.startsWith('Could not')||message.includes('rejected')?styles.error:styles.notice}>{message}</div>}
    <section className={styles.section}><div className={styles.card}><div className={styles.entryHead}><div><h2>{weekStart} – {addDateDays(weekStart,6)}</h2><small>{period?.status.toUpperCase()} · revision {period?.revision??0}</small></div><div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>changeWeek(-7)}>Previous</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>changeWeek(7)}>Next</button></div></div><div className={styles.grid}><Metric label="Forecast sales" value={totalForecast?money(totalForecast):'Not set'}/><Metric label="Target labor hours" value={settings.sales_per_labor_hour_target&&totalForecast?targetLabor.toFixed(1):'Set SPLH target'}/><Metric label="Active employees" value={String(employees.length)}/><Metric label="Coverage blocks" value={String(requirements.filter(r=>r.active).length)}/><Metric label="Missing pay rates" value={String(missingRates)}/><Metric label="Optimization" value={settings.optimization_mode.replace('_',' ')}/></div></div></section>

    <section className={styles.section}><div className={styles.card}><h2>Optimization strategy</h2><div className={styles.formGrid}><Field label="Priority"><select value={settings.optimization_mode} onChange={e=>setSettings({...settings,optimization_mode:e.target.value as OptimizationMode})}><option value="balanced">Balanced</option><option value="lowest_cost">Lowest labor cost</option><option value="equal_hours">Equal hours / fairness</option><option value="preferences">Employee preferences</option></select></Field><Field label="Coverage mode"><select value={settings.auto_schedule_mode} onChange={e=>setSettings({...settings,auto_schedule_mode:e.target.value as 'minimum'|'target'})}><option value="target">Target coverage</option><option value="minimum">Minimum only</option></select></Field><Field label="Overtime starts after"><input type="number" min="1" max="168" step="0.5" value={settings.overtime_after_hours} onChange={e=>setSettings({...settings,overtime_after_hours:n(e.target.value,40)})}/></Field><Field label="Overtime multiplier"><input type="number" min="1" max="3" step="0.05" value={settings.overtime_multiplier} onChange={e=>setSettings({...settings,overtime_multiplier:n(e.target.value,1.5)})}/></Field><Field label="Sales per labor hour target"><input type="number" min="1" step="1" placeholder="e.g. 100" value={settings.sales_per_labor_hour_target??''} onChange={e=>setSettings({...settings,sales_per_labor_hour_target:e.target.value===''?null:n(e.target.value)})}/></Field></div><p>Balanced weighs coverage first, then overtime, fairness, preferences and cost. Lowest cost still cannot violate any hard employee rule.</p><div className={styles.actions}><button className={styles.button} disabled={busy} onClick={saveSettings}>Save Optimizer Rules</button></div></div></section>

    <section className={styles.section}><div className={styles.card}><h2>Sales forecast</h2><p>Forecasts are optional. When a coverage block is marked sales-driven and an SPLH target is set, the optimizer can scale that block between its minimum and maximum staffing.</p><div className={styles.formGrid}>{weekDates.map((d,i)=><Field key={d} label={`${DAYS[i]} ${d.slice(5)}`}><input type="number" min="0" step="1" placeholder="Projected sales" value={forecastDraft[d]??''} onChange={e=>setForecastDraft(x=>({...x,[d]:e.target.value}))}/></Field>)}</div><div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={estimateFromHistory}>Estimate From History</button><button className={styles.button} disabled={busy} onClick={saveForecasts}>Save Forecast Week</button></div></div></section>

    <section className={styles.section}><div className={styles.card}><h2>Demand-sensitive coverage</h2><p>Keep safety-critical or fixed positions non-scalable. For roles that should flex with business volume, set a maximum and enable sales-driven scaling.</p><div className={styles.list}>{requirements.map(r=><div className={styles.entry} key={r.id}><div className={styles.entryHead}><div><b>{DAYS[(r.day_of_week+6)%7]} · {roleName(r.role_id)} · {r.name}</b><small>{hh(r.starts_at)}–{hh(r.ends_at)} · min {r.min_staff} · target {r.target_staff}</small></div><span className={styles.pill}>{r.demand_scalable?'sales-driven':'fixed'}</span></div><div className={styles.formGrid}><label className={styles.field}><span>Scale with forecast</span><input type="checkbox" checked={Boolean(r.demand_scalable)} onChange={e=>editRequirement(r.id,'demand_scalable',e.target.checked)}/></label><Field label="Maximum staff"><input type="number" min={r.target_staff} max="50" value={r.max_staff??r.target_staff} onChange={e=>editRequirement(r.id,'max_staff',n(e.target.value,r.target_staff))}/></Field></div><div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>saveRequirement(r)}>Save Demand Rule</button></div></div>)}</div></div></section>

    <section className={styles.section}><div className={styles.card}><h2>Start from last week</h2><p>Copying is allowed only into an empty draft. Copying employees is transactional: if even one copied assignment conflicts with new availability, approved leave, qualifications, rest or hour limits, the database rejects the whole copy.</p><div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} disabled={busy||period?.status!=='draft'} onClick={()=>copyPrevious(false)}>Copy Shift Structure</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy||period?.status!=='draft'} onClick={()=>copyPrevious(true)}>Copy With Employees</button></div></div></section>

    <section className={styles.section}><div className={styles.card}><h2>Generate optimized draft</h2><p>The preview does not modify the schedule. Unfillable coverage remains open rather than forcing an illegal or unavailable assignment.</p><div className={styles.actions}><button className={styles.button} disabled={busy||period?.status!=='draft'} onClick={makePreview}>Build Preview</button></div>{preview&&<><div className={styles.grid}><Metric label="Coverage" value={`${preview.metrics.coverage_rate}%`}/><Metric label="Assigned slots" value={String(preview.metrics.assigned_slots)}/><Metric label="Open slots" value={String(preview.metrics.open_slots)}/><Metric label="Generated hours" value={preview.metrics.scheduled_hours.toFixed(1)}/><Metric label="Projected labor" value={money(preview.metrics.projected_labor_cost)}/><Metric label="Projected OT" value={`${preview.metrics.projected_overtime_hours.toFixed(1)} hrs`}/></div><div className={styles.list}>{preview.issues.slice(0,30).map((x,i)=><div className={styles.entry} key={`${x.code}-${i}`}><b>{x.severity.toUpperCase()} · {x.message}</b>{x.details&&<small>{Object.entries(x.details).map(([k,v])=>`${k}: ${String(v)}`).join(' · ')}</small>}</div>)}</div><div className={styles.actions}><button className={styles.button} disabled={busy} onClick={applyPreview}>Apply Optimized Draft</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>setPreview(null)}>Discard</button></div></>}</div></section>
  </main>
}
function Metric({label,value}:{label:string;value:string}){return <div className={styles.metric}><span>{label}</span><strong>{value}</strong></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className={styles.field}><span>{label}</span>{children}</label>}
