'use client';

import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase';
import {useI18n} from '@/lib/i18n';
import styles from '../../ops-tools.module.css';
import {businessDateInZone} from '@/lib/intermediate-hardening';
import {suggestForecastWeek,projectedLaborHours,type HistoricalPerformance} from '@/lib/schedule-forecast';
import {addDateDays,dateDayOfWeek,generateSchedule,shiftNetHours,zonedLocalToIso,type AvailabilityRow,type CoverageRequirement,type DailyForecast,type ExistingShift,type OptimizationMode,type ScheduleProfile,type ScheduleGenerationResult} from '@/lib/scheduling-engine';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Employee={id:string;full_name:string;active:boolean};
type Role={id:string;name:string};
type Period={id:string;starts_on:string;ends_on:string;status:string;revision:number};
type TimeOff={employee_id:string;starts_on:string;ends_on:string;status:string};
type RoleAssignment={employee_id:string;role_id:string};
type Settings={timezone:string;overtime_after_hours:number;overtime_multiplier:number;auto_schedule_mode:'minimum'|'target';optimization_mode:OptimizationMode;sales_per_labor_hour_target:number|null;require_full_coverage_to_publish:boolean;open_shift_claim_requires_approval:boolean};
const DEFAULT:Settings={timezone:'America/New_York',overtime_after_hours:40,overtime_multiplier:1.5,auto_schedule_mode:'target',optimization_mode:'balanced',sales_per_labor_hour_target:null,require_full_coverage_to_publish:true,open_shift_claim_requires_approval:true};
const DAYS=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const mondayOf=(d:string)=>addDateDays(d,-((dateDayOfWeek(d)+6)%7));
const n=(v:unknown,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const hh=(v:string)=>v.slice(0,5);
const money=(v:number,localeCode:string)=>new Intl.NumberFormat(localeCode,{style:'currency',currency:'USD',maximumFractionDigits:0}).format(v);
function normalizeProfile(x:any):ScheduleProfile{return {employee_id:x.employee_id,min_weekly_hours:n(x.min_weekly_hours),target_weekly_hours:x.target_weekly_hours===null?null:n(x.target_weekly_hours),max_weekly_hours:x.max_weekly_hours===null?null:n(x.max_weekly_hours),max_shift_hours:n(x.max_shift_hours,12),min_rest_hours:n(x.min_rest_hours,8),max_consecutive_days:n(x.max_consecutive_days,6),hourly_rate:x.hourly_rate===null?null:n(x.hourly_rate),avoid_overtime:x.avoid_overtime!==false,preferred_days_off:Array.isArray(x.preferred_days_off)?x.preferred_days_off.map(Number):[],preferred_start:x.preferred_start,preferred_end:x.preferred_end,allow_split_shifts:x.allow_split_shifts!==false,min_split_gap_hours:n(x.min_split_gap_hours,.5)}}

export default function ScheduleOptimizerPage(){
  const {locale}=useI18n();const t=(en:string,es:string)=>locale==='es'?es:en;const localeCode=locale==='es'?'es-US':'en-US';const days=locale==='es'?['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo']:DAYS;
  const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const [profile,setProfile]=useState<Profile|null>(null),[weekStart,setWeekStart]=useState(()=>mondayOf(businessDateInZone())),[period,setPeriod]=useState<Period|null>(null),[settings,setSettings]=useState<Settings>(DEFAULT);
  const [employees,setEmployees]=useState<Employee[]>([]),[roles,setRoles]=useState<Role[]>([]),[roleAssignments,setRoleAssignments]=useState<RoleAssignment[]>([]),[availability,setAvailability]=useState<AvailabilityRow[]>([]),[timeOff,setTimeOff]=useState<TimeOff[]>([]),[profiles,setProfiles]=useState<ScheduleProfile[]>([]),[requirements,setRequirements]=useState<CoverageRequirement[]>([]),[shifts,setShifts]=useState<ExistingShift[]>([]),[history,setHistory]=useState<HistoricalPerformance[]>([]),[forecastDraft,setForecastDraft]=useState<Record<string,string>>({}),[preview,setPreview]=useState<ScheduleGenerationResult|null>(null);
  useEffect(()=>{void init()},[]);
  async function init(){setReady(false);const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}const {data:p,error}=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();if(error||!p||!p.location_id){setMessage(t('No restaurant location is assigned to this account.','No hay una ubicación de restaurante asignada a esta cuenta.'));setReady(true);return}const pr=p as Profile;if(pr.app_role!=='admin'&&pr.app_role!=='manager'){location.href='/schedule';return}setProfile(pr);const ws=mondayOf(businessDateInZone());setWeekStart(ws);await load(pr.location_id!,ws);setReady(true)}
  async function load(locationId=profile?.location_id||'',ws=weekStart){if(!locationId)return;setBusy(true);setPreview(null);try{
    const sRes=await supabase.from('schedule_settings').select('timezone,overtime_after_hours,overtime_multiplier,auto_schedule_mode,optimization_mode,sales_per_labor_hour_target,require_full_coverage_to_publish,open_shift_claim_requires_approval').eq('location_id',locationId).maybeSingle();if(sRes.error)throw sRes.error;
    const s:Settings=sRes.data?{timezone:sRes.data.timezone||DEFAULT.timezone,overtime_after_hours:n(sRes.data.overtime_after_hours,40),overtime_multiplier:n(sRes.data.overtime_multiplier,1.5),auto_schedule_mode:sRes.data.auto_schedule_mode==='minimum'?'minimum':'target',optimization_mode:(sRes.data.optimization_mode||'balanced') as OptimizationMode,sales_per_labor_hour_target:sRes.data.sales_per_labor_hour_target===null?null:n(sRes.data.sales_per_labor_hour_target),require_full_coverage_to_publish:sRes.data.require_full_coverage_to_publish!==false,open_shift_claim_requires_approval:sRes.data.open_shift_claim_requires_approval!==false}:DEFAULT;setSettings(s);
    const per=await supabase.rpc('ensure_schedule_period',{p_starts_on:ws});if(per.error)throw per.error;setPeriod(per.data as Period);
    const from=zonedLocalToIso(addDateDays(ws,-14),'00:00:00',s.timezone),to=zonedLocalToIso(addDateDays(ws,21),'00:00:00',s.timezone);
    const [e,r,ra,av,o,sp,cr,sh,fc,hist]=await Promise.all([
      supabase.from('employees').select('id,full_name,active').eq('location_id',locationId).is('deleted_at',null).eq('active',true).order('full_name'),
      supabase.from('employee_roles').select('id,name').eq('location_id',locationId).order('name'),
      supabase.from('employee_role_assignments').select('employee_id,role_id'),
      supabase.from('employee_availability').select('employee_id,day_of_week,available_from,available_to,unavailable').eq('location_id',locationId),
      supabase.from('time_off_requests').select('employee_id,starts_on,ends_on,status').eq('location_id',locationId).gte('ends_on',addDateDays(ws,-14)).lte('starts_on',addDateDays(ws,21)),
      supabase.from('employee_schedule_profiles').select('employee_id,min_weekly_hours,target_weekly_hours,max_weekly_hours,max_shift_hours,min_rest_hours,max_consecutive_days,hourly_rate,avoid_overtime,preferred_days_off,preferred_start,preferred_end,allow_split_shifts,min_split_gap_hours').eq('location_id',locationId),
      supabase.from('schedule_coverage_requirements').select('id,name,day_of_week,role_id,starts_at,ends_at,min_staff,target_staff,max_staff,break_minutes,priority,shift_type,active,effective_from,effective_to,demand_scalable').eq('location_id',locationId).order('day_of_week').order('starts_at'),
      supabase.from('schedule_shifts').select('id,employee_id,role_id,starts_at,ends_at,break_minutes,status,source,is_locked,coverage_requirement_id,schedule_period_id').eq('location_id',locationId).gte('starts_at',from).lt('starts_at',to).neq('status','cancelled').order('starts_at'),
      supabase.from('schedule_daily_forecasts').select('business_date,projected_sales,source,confidence').eq('location_id',locationId).gte('business_date',ws).lte('business_date',addDateDays(ws,6)),
      supabase.from('restaurant_daily_performance').select('business_date,net_sales,labor_hours').eq('location_id',locationId).gte('business_date',addDateDays(ws,-84)).lt('business_date',ws).order('business_date',{ascending:false})
    ]);
    if([e,r,ra,av,o,sp,cr,sh,fc,hist].some(x=>x.error))throw new Error('load');
    setEmployees((e.data??[]) as Employee[]);setRoles((r.data??[]) as Role[]);setRoleAssignments((ra.data??[]) as RoleAssignment[]);setAvailability((av.data??[]) as AvailabilityRow[]);setTimeOff((o.data??[]) as TimeOff[]);setProfiles((sp.data??[]).map(normalizeProfile));setRequirements((cr.data??[]).map((x:any)=>({...x,day_of_week:n(x.day_of_week),min_staff:n(x.min_staff),target_staff:n(x.target_staff),max_staff:x.max_staff===null?null:n(x.max_staff),break_minutes:n(x.break_minutes),priority:n(x.priority,50),demand_scalable:Boolean(x.demand_scalable)})) as CoverageRequirement[]);setShifts((sh.data??[]) as ExistingShift[]);setHistory((hist.data??[]).map((x:any)=>({business_date:x.business_date,net_sales:n(x.net_sales),labor_hours:x.labor_hours===null?null:n(x.labor_hours)})));const draft:Record<string,string>={};for(let i=0;i<7;i++)draft[addDateDays(ws,i)]='';for(const x of fc.data??[])draft[x.business_date]=String(x.projected_sales);setForecastDraft(draft);
  }catch{setMessage(t('Could not load the optimizer workspace.','No se pudo cargar el espacio del optimizador.'))}finally{setBusy(false)}}
  async function changeWeek(delta:number){if(!profile?.location_id||busy)return;const ws=addDateDays(weekStart,delta);setWeekStart(ws);await load(profile.location_id,ws)}
  const weekDates=useMemo(()=>Array.from({length:7},(_,i)=>addDateDays(weekStart,i)),[weekStart]);
  const roleName=(id:string)=>roles.find(x=>x.id===id)?.name||t('Role','Puesto');
  const forecasts:DailyForecast[]=useMemo(()=>weekDates.flatMap(d=>forecastDraft[d]!==''&&Number.isFinite(Number(forecastDraft[d]))?[{business_date:d,projected_sales:n(forecastDraft[d]),source:'manual'}]:[]),[weekDates,forecastDraft]);
  const totalForecast=forecasts.reduce((a,b)=>a+b.projected_sales,0),targetLabor=forecasts.reduce((a,b)=>a+(projectedLaborHours(b.projected_sales,settings.sales_per_labor_hour_target)||0),0),missingRates=employees.filter(e=>!profiles.find(p=>p.employee_id===e.id)?.hourly_rate).length;
  function input(){if(!period)throw new Error('period');return {period,employees,roles,roleAssignments,availability,timeOff,profiles,requirements,existingShifts:shifts,forecasts,settings:{timezone:settings.timezone,overtime_after_hours:settings.overtime_after_hours,overtime_multiplier:settings.overtime_multiplier,mode:settings.auto_schedule_mode,preserve_manual_shifts:true,optimization_mode:settings.optimization_mode,sales_per_labor_hour_target:settings.sales_per_labor_hour_target}}}
  function makePreview(){if(!period||period.status!=='draft'){setMessage(t('Reopen the schedule before optimizing it.','Vuelve a abrir el horario antes de optimizarlo.'));return}try{const x=generateSchedule(input());setPreview(x);setMessage(x.metrics.open_slots?`${t('Optimizer created a safe draft with','El optimizador creó un borrador seguro con')} ${x.metrics.open_slots} ${x.metrics.open_slots===1?t('unfilled slot left open.','espacio sin cubrir abierto.'):t('unfilled slots left open.','espacios sin cubrir abiertos.')}`:t('Optimizer created a fully covered draft.','El optimizador creó un borrador con cobertura completa.'))}catch{setMessage(t('The optimizer could not build this week. Review coverage rules and employee setup.','El optimizador no pudo crear esta semana. Revisa las reglas de cobertura y la configuración de empleados.'))}}
  async function applyPreview(){if(!period||!preview||busy)return;setBusy(true);const {data,error}=await supabase.rpc('apply_schedule_generation',{p_period_id:period.id,p_expected_revision:period.revision,p_shifts:preview.shifts,p_client_issues:preview.issues,p_metrics:{...preview.metrics,objective_score:preview.objective_score},p_settings:{algorithm_version:preview.algorithm_version,mode:settings.auto_schedule_mode,optimization_mode:settings.optimization_mode,sales_per_labor_hour_target:settings.sales_per_labor_hour_target,forecasts}});if(error){setMessage(error.message.includes('reload')?t('The schedule changed elsewhere, so the optimizer refused to overwrite it. Reloading now.','El horario cambió en otro lugar; el optimizador se negó a sobrescribirlo. Recargando.'):t('The database rejected the generated schedule because a safety rule failed. Nothing was partially applied.','La base de datos rechazó el horario generado por una regla de seguridad. No se aplicó nada parcialmente.'))}else setMessage(`${t('Optimized draft applied:','Borrador optimizado aplicado:')} ${data?.inserted_shifts??preview.shifts.length} ${t('generated shifts.','turnos generados.')}`);setPreview(null);await load();setBusy(false)}
  async function saveSettings(){if(!profile?.location_id||busy)return;setBusy(true);const {error}=await supabase.from('schedule_settings').upsert({location_id:profile.location_id,timezone:settings.timezone,overtime_after_hours:settings.overtime_after_hours,overtime_multiplier:settings.overtime_multiplier,auto_schedule_mode:settings.auto_schedule_mode,optimization_mode:settings.optimization_mode,sales_per_labor_hour_target:settings.sales_per_labor_hour_target,require_full_coverage_to_publish:settings.require_full_coverage_to_publish,open_shift_claim_requires_approval:settings.open_shift_claim_requires_approval},{onConflict:'location_id'});setMessage(error?t('Could not save optimizer rules.','No se pudieron guardar las reglas del optimizador.'):t('Optimizer rules saved.','Reglas del optimizador guardadas.'));setBusy(false)}
  async function saveForecasts(){if(!profile?.location_id||busy)return;for(const d of weekDates){const v=forecastDraft[d];if(v!==''&&n(v)<0){setMessage(t('Forecast sales cannot be negative.','Las ventas proyectadas no pueden ser negativas.'));return}}setBusy(true);try{for(const d of weekDates){const v=forecastDraft[d];if(v===''){const del=await supabase.from('schedule_daily_forecasts').delete().eq('location_id',profile.location_id).eq('business_date',d);if(del.error)throw del.error}else{const up=await supabase.from('schedule_daily_forecasts').upsert({location_id:profile.location_id,business_date:d,projected_sales:n(v),source:'manual',confidence:null},{onConflict:'location_id,business_date'});if(up.error)throw up.error}}setMessage(t('Sales forecast saved for this week.','Pronóstico de ventas guardado para esta semana.'))}catch{setMessage(t('Could not save the sales forecast.','No se pudo guardar el pronóstico de ventas.'))}finally{setBusy(false)}}
  function estimateFromHistory(){const suggestions=suggestForecastWeek(history,weekStart);if(!suggestions.length){setMessage(t('There is not enough saved sales history yet to estimate this week. Enter forecasts manually or import performance data first.','Aún no hay suficiente historial de ventas para estimar esta semana. Ingresa pronósticos manualmente o importa datos de rendimiento.'));return}const next={...forecastDraft};for(const x of suggestions)next[x.business_date]=String(Math.round(x.projected_sales));setForecastDraft(next);setMessage(`${t('Estimated','Se estimaron')} ${suggestions.length} ${suggestions.length===1?t('day','día'):t('days','días')} ${t('from same-weekday sales history. Review the numbers before saving.','con el historial del mismo día de la semana. Revisa los números antes de guardar.')}`)}
  async function saveRequirement(r:CoverageRequirement){if(busy)return;setBusy(true);const {error}=await supabase.from('schedule_coverage_requirements').update({demand_scalable:Boolean(r.demand_scalable),max_staff:r.max_staff}).eq('id',r.id);setMessage(error?t('Could not save that demand rule.','No se pudo guardar esa regla de demanda.'):t('Coverage demand rule saved.','Regla de demanda de cobertura guardada.'));setBusy(false)}
  function editRequirement(id:string,key:'demand_scalable'|'max_staff',value:any){setRequirements(xs=>xs.map(x=>x.id===id?{...x,[key]:value}:x))}
  async function copyPrevious(copyAssignments:boolean){if(!period||!profile?.location_id||busy)return;if(period.status!=='draft'){setMessage(t('The target week must be a draft before copying.','La semana de destino debe ser un borrador antes de copiar.'));return}if(shifts.some(s=>s.schedule_period_id===period.id&&s.status!=='cancelled')){setMessage(t('This week already has shifts. Copy-week is intentionally blocked to prevent duplicates.','Esta semana ya tiene turnos. La copia está bloqueada para evitar duplicados.'));return}const prev=addDateDays(weekStart,-7);setBusy(true);try{const src=await supabase.from('schedule_periods').select('id').eq('location_id',profile.location_id).eq('starts_on',prev).eq('ends_on',addDateDays(prev,6)).maybeSingle();if(src.error)throw src.error;if(!src.data){setMessage(t('There is no previous Scheduling v2 week to copy yet.','Aún no hay una semana anterior de Programación v2 para copiar.'));return}if(copyAssignments&&!confirm(t('Copy last week with the same employees? Availability, approved time off, qualifications, rest and hour limits will still be enforced.','¿Copiar la semana pasada con los mismos empleados? Se seguirán aplicando disponibilidad, ausencias aprobadas, calificaciones, descanso y límites de horas.')))return;const {data,error}=await supabase.rpc('copy_schedule_period',{p_source_period_id:src.data.id,p_target_period_id:period.id,p_expected_revision:period.revision,p_copy_assignments:copyAssignments});if(error)throw error;setMessage(`${t('Copied','Se copiaron')} ${data?.copied??0} ${data?.copied===1?t('shift','turno'):t('shifts','turnos')} ${t('from last week','de la semana pasada')} ${copyAssignments?t('with employee assignments','con asignaciones de empleados'):t('as open structure','como estructura abierta')}.`);await load()}catch(e:any){setMessage(String(e?.message||'').includes('safety')?t('Copy rejected by a scheduling safety rule.','Copia rechazada por una regla de seguridad de programación.'):t('Could not copy last week. If copying assignments, a new availability, leave, rest, or hours conflict may be blocking it.','No se pudo copiar la semana pasada. Un conflicto nuevo de disponibilidad, ausencia, descanso u horas puede estar bloqueándolo.'))}finally{setBusy(false)}}

  if(!ready)return <main className={styles.page}>{t('Loading optimizer…','Cargando optimizador…')}</main>;
  if(!profile?.location_id)return <main className={styles.page}>{message||t('No location assigned.','No hay ubicación asignada.')}</main>;
  return <main className={styles.page}>
    <div className={styles.top}><div><h1>{t('Schedule Optimizer','Optimizador de Horarios')}</h1><p>{t('Build coverage around demand, labor cost, fairness and employee constraints before publishing.','Crea cobertura según demanda, costo laboral, equidad y restricciones de empleados antes de publicar.')}</p></div><Link className={styles.back} href="/schedule">{t('Back to Schedule','Volver al Horario')}</Link></div>
    {message&&<div className={message.startsWith('Could not')||message.startsWith('No se pudo')||message.includes('rejected')||message.includes('rechazada')?styles.error:styles.notice}>{message}</div>}
    <section className={styles.section}><div className={styles.card}><div className={styles.entryHead}><div><h2>{weekStart} – {addDateDays(weekStart,6)}</h2><small>{period?.status.toUpperCase()} · {t('revision','revisión')} {period?.revision??0}</small></div><div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>changeWeek(-7)}>{t('Previous','Anterior')}</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>changeWeek(7)}>{t('Next','Siguiente')}</button></div></div><div className={styles.grid}><Metric label={t('Forecast sales','Ventas proyectadas')} value={totalForecast?money(totalForecast,localeCode):t('Not set','Sin definir')}/><Metric label={t('Target labor hours','Horas laborales objetivo')} value={settings.sales_per_labor_hour_target&&totalForecast?targetLabor.toFixed(1):t('Set SPLH target','Define objetivo SPLH')}/><Metric label={t('Active employees','Empleados activos')} value={String(employees.length)}/><Metric label={t('Coverage blocks','Bloques de cobertura')} value={String(requirements.filter(r=>r.active).length)}/><Metric label={t('Missing pay rates','Tarifas faltantes')} value={String(missingRates)}/><Metric label={t('Optimization','Optimización')} value={settings.optimization_mode.replace('_',' ')}/></div></div></section>

    <section className={styles.section}><div className={styles.card}><h2>{t('Optimization strategy','Estrategia de optimización')}</h2><div className={styles.formGrid}><Field label={t('Priority','Prioridad')}><select value={settings.optimization_mode} onChange={e=>setSettings({...settings,optimization_mode:e.target.value as OptimizationMode})}><option value="balanced">{t('Balanced','Equilibrado')}</option><option value="lowest_cost">{t('Lowest labor cost','Menor costo laboral')}</option><option value="equal_hours">{t('Equal hours / fairness','Horas iguales / equidad')}</option><option value="preferences">{t('Employee preferences','Preferencias de empleados')}</option></select></Field><Field label={t('Coverage mode','Modo de cobertura')}><select value={settings.auto_schedule_mode} onChange={e=>setSettings({...settings,auto_schedule_mode:e.target.value as 'minimum'|'target'})}><option value="target">{t('Target coverage','Cobertura objetivo')}</option><option value="minimum">{t('Minimum only','Solo mínimo')}</option></select></Field><Field label={t('Overtime starts after','Horas extra después de')}><input type="number" min="1" max="168" step="0.5" value={settings.overtime_after_hours} onChange={e=>setSettings({...settings,overtime_after_hours:n(e.target.value,40)})}/></Field><Field label={t('Overtime multiplier','Multiplicador de horas extra')}><input type="number" min="1" max="3" step="0.05" value={settings.overtime_multiplier} onChange={e=>setSettings({...settings,overtime_multiplier:n(e.target.value,1.5)})}/></Field><Field label={t('Sales per labor hour target','Ventas objetivo por hora laboral')}><input type="number" min="1" step="1" placeholder={t('e.g. 100','p. ej. 100')} value={settings.sales_per_labor_hour_target??''} onChange={e=>setSettings({...settings,sales_per_labor_hour_target:e.target.value===''?null:n(e.target.value)})}/></Field></div><p>{t('Balanced weighs coverage first, then overtime, fairness, preferences and cost. Lowest cost still cannot violate any hard employee rule.','Equilibrado prioriza cobertura y luego horas extra, equidad, preferencias y costo. El menor costo nunca puede infringir reglas obligatorias.')}</p><div className={styles.actions}><button className={styles.button} disabled={busy} onClick={saveSettings}>{t('Save Optimizer Rules','Guardar Reglas del Optimizador')}</button></div></div></section>

    <section className={styles.section}><div className={styles.card}><h2>{t('Sales forecast','Pronóstico de ventas')}</h2><p>{t('Forecasts are optional. When a coverage block is marked sales-driven and an SPLH target is set, the optimizer can scale that block between its minimum and maximum staffing.','Los pronósticos son opcionales. Con cobertura según ventas y un objetivo SPLH, el optimizador ajusta el bloque entre personal mínimo y máximo.')}</p><div className={styles.formGrid}>{weekDates.map((d,i)=><Field key={d} label={`${days[i]} ${d.slice(5)}`}><input type="number" min="0" step="1" placeholder={t('Projected sales','Ventas proyectadas')} value={forecastDraft[d]??''} onChange={e=>setForecastDraft(x=>({...x,[d]:e.target.value}))}/></Field>)}</div><div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={estimateFromHistory}>{t('Estimate From History','Estimar del Historial')}</button><button className={styles.button} disabled={busy} onClick={saveForecasts}>{t('Save Forecast Week','Guardar Pronóstico Semanal')}</button></div></div></section>

    <section className={styles.section}><div className={styles.card}><h2>{t('Demand-sensitive coverage','Cobertura sensible a la demanda')}</h2><p>{t('Keep safety-critical or fixed positions non-scalable. For roles that should flex with business volume, set a maximum and enable sales-driven scaling.','Mantén fijos los puestos críticos. Para puestos que varían con el volumen, define un máximo y activa el ajuste según ventas.')}</p><div className={styles.list}>{requirements.map(r=><div className={styles.entry} key={r.id}><div className={styles.entryHead}><div><b>{days[(r.day_of_week+6)%7]} · {roleName(r.role_id)} · {r.name}</b><small>{hh(r.starts_at)}–{hh(r.ends_at)} · {t('min','mín')} {r.min_staff} · {t('target','objetivo')} {r.target_staff}</small></div><span className={styles.pill}>{r.demand_scalable?t('sales-driven','según ventas'):t('fixed','fijo')}</span></div><div className={styles.formGrid}><label className={styles.field}><span>{t('Scale with forecast','Ajustar con pronóstico')}</span><input type="checkbox" checked={Boolean(r.demand_scalable)} onChange={e=>editRequirement(r.id,'demand_scalable',e.target.checked)}/></label><Field label={t('Maximum staff','Personal máximo')}><input type="number" min={r.target_staff} max="50" value={r.max_staff??r.target_staff} onChange={e=>editRequirement(r.id,'max_staff',n(e.target.value,r.target_staff))}/></Field></div><div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>saveRequirement(r)}>{t('Save Demand Rule','Guardar Regla de Demanda')}</button></div></div>)}</div></div></section>

    <section className={styles.section}><div className={styles.card}><h2>{t('Start from last week','Comenzar desde la semana pasada')}</h2><p>{t('Copying is allowed only into an empty draft. Copying employees is transactional: if even one copied assignment conflicts with new availability, approved leave, qualifications, rest or hour limits, the database rejects the whole copy.','Solo se puede copiar a un borrador vacío. Copiar empleados es transaccional: si una asignación entra en conflicto con disponibilidad, ausencia, calificaciones, descanso u horas, se rechaza toda la copia.')}</p><div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} disabled={busy||period?.status!=='draft'} onClick={()=>copyPrevious(false)}>{t('Copy Shift Structure','Copiar Estructura de Turnos')}</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy||period?.status!=='draft'} onClick={()=>copyPrevious(true)}>{t('Copy With Employees','Copiar con Empleados')}</button></div></div></section>

    <section className={styles.section}><div className={styles.card}><h2>{t('Generate optimized draft','Generar borrador optimizado')}</h2><p>{t('The preview does not modify the schedule. Unfillable coverage remains open rather than forcing an illegal or unavailable assignment.','La vista previa no modifica el horario. La cobertura imposible queda abierta en vez de forzar una asignación ilegal o no disponible.')}</p><div className={styles.actions}><button className={styles.button} disabled={busy||period?.status!=='draft'} onClick={makePreview}>{t('Build Preview','Crear Vista Previa')}</button></div>{preview&&<><div className={styles.grid}><Metric label={t('Coverage','Cobertura')} value={`${preview.metrics.coverage_rate}%`}/><Metric label={t('Assigned slots','Espacios asignados')} value={String(preview.metrics.assigned_slots)}/><Metric label={t('Open slots','Espacios abiertos')} value={String(preview.metrics.open_slots)}/><Metric label={t('Generated hours','Horas generadas')} value={preview.metrics.scheduled_hours.toFixed(1)}/><Metric label={t('Projected labor','Trabajo proyectado')} value={money(preview.metrics.projected_labor_cost,localeCode)}/><Metric label={t('Projected OT','Horas extra proyectadas')} value={`${preview.metrics.projected_overtime_hours.toFixed(1)} hrs`}/></div><div className={styles.list}>{preview.issues.slice(0,30).map((x,i)=><div className={styles.entry} key={`${x.code}-${i}`}><b>{x.severity.toUpperCase()} · {x.message}</b>{x.details&&<small>{Object.entries(x.details).map(([k,v])=>`${k}: ${String(v)}`).join(' · ')}</small>}</div>)}</div><div className={styles.actions}><button className={styles.button} disabled={busy} onClick={applyPreview}>{t('Apply Optimized Draft','Aplicar Borrador Optimizado')}</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>setPreview(null)}>{t('Discard','Descartar')}</button></div></>}</div></section>
  </main>
}
function Metric({label,value}:{label:string;value:string}){return <div className={styles.metric}><span>{label}</span><strong>{value}</strong></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className={styles.field}><span>{label}</span>{children}</label>}
