'use client';

import {useEffect,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase';
import {addDateDays,dateDayOfWeek} from '@/lib/scheduling-engine';
import {businessDateInZone} from '@/lib/intermediate-hardening';
import styles from '../../ops-tools.module.css';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};type Period={id:string;starts_on:string;ends_on:string;status:string;revision:number};type DeptPub={department:string;status:string;revision:number;published_at:string|null;notification_mode:string|null};type Issue={severity:string;code:string;date?:string;name?:string;required?:number;target?:number;assigned?:number;count?:number};type Mode='everyone'|'changed_only'|'none';
const DEPTS=[{id:'foh',name:'Front of House'},{id:'boh',name:'Back of House'},{id:'management',name:'Management'},{id:'other',name:'Other'}] as const;
const mondayOf=(date:string)=>addDateDays(date,-((dateDayOfWeek(date)+6)%7));
export default function PublishCenter(){
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[profile,setProfile]=useState<Profile|null>(null),[week,setWeek]=useState(mondayOf(businessDateInZone())),[period,setPeriod]=useState<Period|null>(null),[pubs,setPubs]=useState<DeptPub[]>([]),[issues,setIssues]=useState<Record<string,Issue[]>>({}),[mode,setMode]=useState<Mode>('everyone');const canManage=profile?.app_role==='admin'||profile?.app_role==='manager';
 useEffect(()=>{void init()},[]);
 async function init(){const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}const p=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();if(p.error||!p.data?.location_id){setMessage('Could not load publish controls.');setReady(true);return}const pr=p.data as Profile;setProfile(pr);await loadWeek(week,pr);setReady(true)}
 async function loadWeek(ws=week,pr=profile){if(!pr?.location_id)return;setBusy(true);const res=canRole(pr)?await supabase.rpc('ensure_schedule_period',{p_starts_on:ws}):await supabase.from('schedule_periods').select('id,starts_on,ends_on,status,revision').eq('location_id',pr.location_id).eq('starts_on',ws).maybeSingle();if(res.error){setMessage(res.error.message);setBusy(false);return}const row=res.data as Period|null;setPeriod(row);if(row){const dp=await supabase.from('schedule_department_publications').select('department,status,revision,published_at,notification_mode').eq('schedule_period_id',row.id);setPubs((dp.data??[]) as DeptPub[]);await validateAll(row.id)}else{setPubs([]);setIssues({})}setBusy(false)}
 async function validateAll(id=period?.id){if(!id)return;const next:Record<string,Issue[]>={};for(const d of DEPTS){const r=await supabase.rpc('schedule_department_validation',{p_period_id:id,p_department:d.id});next[d.id]=(Array.isArray(r.data)?r.data:[]) as Issue[]}const all=await supabase.rpc('schedule_period_validation',{p_period_id:id});next.all=(Array.isArray(all.data)?all.data:[]) as Issue[];setIssues(next)}
 function canRole(p:Profile|null){return p?.app_role==='admin'||p?.app_role==='manager'}
 async function changeWeek(delta:number){const ws=addDateDays(week,delta*7);setWeek(ws);await loadWeek(ws)}
 function overrideFor(xs:Issue[]){const errors=xs.filter(x=>x.severity==='error');if(!errors.length)return null;return prompt(`${errors.length} coverage error${errors.length===1?'':'s'} remain. Enter a manager override reason (minimum 5 characters), or Cancel to fix the schedule first.`)}
 async function publishDepartment(department:string){if(!period||!canManage||busy)return;if(period.status==='published'){setMessage('The entire schedule is already published. Reopen the full schedule before using department publishing.');return}const over=overrideFor(issues[department]||[]);if((issues[department]||[]).some(x=>x.severity==='error')&&(!over||over.trim().length<5))return;setBusy(true);const {error}=await supabase.rpc('publish_schedule_department',{p_period_id:period.id,p_department:department,p_expected_period_revision:period.revision,p_override_reason:over,p_notification_mode:mode});setMessage(error?error.message:`${DEPTS.find(x=>x.id===department)?.name||department} published.`);await loadWeek();setBusy(false)}
 async function reopenDepartment(department:string){if(!period||!canManage||busy)return;if(!confirm(`Reopen ${department.toUpperCase()} for editing? Employees in that department will stop seeing this department draft until it is republished.`))return;setBusy(true);const {error}=await supabase.rpc('reopen_schedule_department',{p_period_id:period.id,p_department:department});setMessage(error?error.message:`${department.toUpperCase()} reopened for editing.`);await loadWeek();setBusy(false)}
 async function publishAll(){if(!period||!canManage||busy)return;const over=overrideFor(issues.all||[]);if((issues.all||[]).some(x=>x.severity==='error')&&(!over||over.trim().length<5))return;setBusy(true);const {error}=await supabase.rpc('publish_schedule_period_with_notifications',{p_period_id:period.id,p_expected_revision:period.revision,p_override_reason:over,p_notification_mode:mode});setMessage(error?error.message:'Entire restaurant schedule published.');await loadWeek();setBusy(false)}
 async function reopenAll(){if(!period||!canManage||busy)return;if(!confirm('Reopen the entire restaurant schedule? Published shifts will temporarily stop being visible until republished.'))return;setBusy(true);const {error}=await supabase.rpc('reopen_schedule_period',{p_period_id:period.id});setMessage(error?error.message:'Entire schedule reopened.');await loadWeek();setBusy(false)}
 const pub=(d:string)=>pubs.find(x=>x.department===d);
 if(!ready)return <div className="full-loader"><span>Opening Publish Center…</span></div>;
 return <main className={styles.page}><div className={styles.top}><div><h1>Publish Center</h1><p>Publish the full restaurant or FOH/BOH independently, with control over who gets notified.</p></div><Link className={styles.back} href="/schedule">Back to Schedule</Link></div>{message&&<div className={styles.notice}>{message}</div>}{!canManage?<div className={styles.error}>Manager access is required.</div>:<>
 <section className={styles.section}><div className={styles.card}><div className={styles.entryHead}><div><h2>{week} – {addDateDays(week,6)}</h2><small>{period?`Period ${period.status} · revision ${period.revision}`:'No schedule period'}</small></div><div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>changeWeek(-1)}>Previous</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>changeWeek(1)}>Next</button></div></div><label className={styles.field} style={{marginTop:12}}><span>When publishing, notify</span><select value={mode} onChange={e=>setMode(e.target.value as Mode)}><option value="everyone">Everyone scheduled</option><option value="changed_only">Only employees whose shifts changed</option><option value="none">No one — publish silently</option></select></label><p>“Changed only” is available after that schedule or department has been published at least once.</p></div></section>
 <section className={styles.section}><h2>Departments</h2><div className={styles.list}>{DEPTS.map(d=>{const p=pub(d.id),xs=issues[d.id]||[],errs=xs.filter(x=>x.severity==='error').length,warns=xs.filter(x=>x.severity==='warning').length;return <div className={styles.entry} key={d.id}><div className={styles.entryHead}><div><h3>{d.name}</h3><small>{errs} error(s) · {warns} warning(s){p?.published_at?` · last published ${new Date(p.published_at).toLocaleString()}`:''}</small></div><span className={styles.pill}>{p?.status||'draft'}</span></div>{xs.slice(0,5).map((x,i)=><div className={styles.detail} key={i}><b>{x.severity} · {String(x.name||x.code).replaceAll('_',' ')}</b><span>{x.date?`${x.date} · `:''}{x.required!==undefined?`${x.assigned??0}/${x.required} minimum`:x.target!==undefined?`${x.assigned??0}/${x.target} target`:x.count!==undefined?`${x.count} item(s)`:''}</span></div>)}<div className={styles.actions}>{p?.status==='published'?<button className={`${styles.button} ${styles.secondary}`} disabled={busy||period?.status==='published'} onClick={()=>reopenDepartment(d.id)}>Reopen {d.id.toUpperCase()}</button>:<button className={styles.button} disabled={busy||period?.status==='published'} onClick={()=>publishDepartment(d.id)}>Publish {d.id.toUpperCase()}</button>}</div></div>})}</div></section>
 <section className={styles.section}><div className={styles.card}><h2>Entire restaurant</h2><p>Use this when FOH and BOH are both ready. Full publication supersedes department-only visibility.</p><div className={styles.actions}>{period?.status==='published'?<button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={reopenAll}>Reopen Entire Schedule</button>:<button className={styles.button} disabled={busy||!period} onClick={publishAll}>Publish Entire Restaurant</button>}<button className={`${styles.button} ${styles.secondary}`} disabled={busy||!period} onClick={()=>validateAll()}>Recheck Coverage</button></div></div></section></>}
 </main>
}
