'use client';

import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase';
import styles from '../../ops-tools.module.css';

type Profile={id?:string;full_name?:string;app_role:'admin'|'manager'|'employee';location_id:string|null};
type Employee={id:string;full_name:string};
type Activity={id:string;at:string;kind:string;title:string;detail:string;actor_id:string|null};
export default function ScheduleActivityPage(){
 const [ready,setReady]=useState(false),[message,setMessage]=useState(''),[profile,setProfile]=useState<Profile|null>(null),[employees,setEmployees]=useState<Employee[]>([]),[people,setPeople]=useState<Record<string,string>>({}),[items,setItems]=useState<Activity[]>([]),[filter,setFilter]=useState('all');
 const canManage=profile?.app_role==='admin'||profile?.app_role==='manager';
 useEffect(()=>{void load()},[]);
 async function load(){const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}const p=await supabase.from('profiles').select('id,full_name,app_role,location_id').eq('id',u.user.id).single();if(p.error||!p.data?.location_id){setMessage('Could not load schedule activity.');setReady(true);return}const pr=p.data as Profile;setProfile(pr);if(!(pr.app_role==='admin'||pr.app_role==='manager')){setReady(true);return}try{const [emps,profiles,changes,pubs,deptPubs,offers,bids,av,timeoff,changesReq,claims]=await Promise.all([
 supabase.from('employees').select('id,full_name').eq('location_id',pr.location_id),
 supabase.from('profiles').select('id,full_name').eq('location_id',pr.location_id),
 supabase.from('schedule_shift_change_log').select('id,change_type,old_employee_id,new_employee_id,old_role_id,new_role_id,changed_by,changed_at').eq('location_id',pr.location_id).order('changed_at',{ascending:false}).limit(200),
 supabase.from('schedule_publication_events').select('id,schedule_period_id,revision,notification_mode,published_by,published_at').eq('location_id',pr.location_id).order('published_at',{ascending:false}).limit(100),
 supabase.from('schedule_department_publications').select('schedule_period_id,department,status,revision,published_by,published_at,notification_mode,updated_at').eq('location_id',pr.location_id).order('updated_at',{ascending:false}).limit(100),
 supabase.from('shift_pool_offers').select('id,offer_type,status,offered_by_employee_id,assigned_to_employee_id,created_by,resolved_by,created_at,resolved_at').eq('location_id',pr.location_id).order('created_at',{ascending:false}).limit(100),
 supabase.from('shift_pool_bids').select('id,offer_id,employee_id,status,created_by,reviewed_by,created_at,reviewed_at').eq('location_id',pr.location_id).order('created_at',{ascending:false}).limit(100),
 supabase.from('availability_change_requests').select('id,employee_id,request_kind,status,requested_by,reviewed_by,created_at,reviewed_at').eq('location_id',pr.location_id).order('created_at',{ascending:false}).limit(100),
 supabase.from('time_off_requests').select('id,employee_id,starts_on,ends_on,status,category,requested_by,reviewed_by,created_at,reviewed_at').eq('location_id',pr.location_id).order('created_at',{ascending:false}).limit(100),
 supabase.from('shift_change_requests').select('id,request_type,requested_by_employee_id,target_employee_id,status,requested_by,reviewed_by,created_at,reviewed_at').eq('location_id',pr.location_id).order('created_at',{ascending:false}).limit(100),
 supabase.from('shift_claims').select('id,employee_id,status,requested_by,reviewed_by,created_at,reviewed_at').eq('location_id',pr.location_id).order('created_at',{ascending:false}).limit(100)
 ]);const all=[emps,profiles,changes,pubs,deptPubs,offers,bids,av,timeoff,changesReq,claims];for(const x of all)if(x.error)throw x.error;const es=(emps.data??[]) as Employee[];setEmployees(es);const pm:Record<string,string>={};for(const x of profiles.data??[])pm[x.id]=x.full_name||'User';setPeople(pm);const en=(id:string|null|undefined)=>es.find(x=>x.id===id)?.full_name||'Employee';const out:Activity[]=[];
 for(const x of changes.data??[])out.push({id:`shift-${x.id}`,at:x.changed_at,kind:'shift',title:`Shift ${x.change_type}`,detail:`${en(x.old_employee_id)} → ${en(x.new_employee_id)}`,actor_id:x.changed_by});
 for(const x of pubs.data??[])out.push({id:`pub-${x.id}`,at:x.published_at,kind:'publish',title:`Schedule published · revision ${x.revision}`,detail:`Notifications: ${x.notification_mode}`,actor_id:x.published_by});
 for(const x of deptPubs.data??[])out.push({id:`dept-${x.schedule_period_id}-${x.department}-${x.revision}`,at:x.updated_at||x.published_at,kind:'publish',title:`${String(x.department).toUpperCase()} ${x.status}`,detail:`Department revision ${x.revision} · notifications ${x.notification_mode||'—'}`,actor_id:x.published_by});
 for(const x of offers.data??[]){out.push({id:`offer-open-${x.id}`,at:x.created_at,kind:'pool',title:`Shift Pool ${String(x.offer_type).replaceAll('_',' ')} opened`,detail:`${en(x.offered_by_employee_id)} · ${x.status}`,actor_id:x.created_by});if(x.resolved_at)out.push({id:`offer-close-${x.id}`,at:x.resolved_at,kind:'pool',title:`Shift Pool offer ${x.status}`,detail:x.assigned_to_employee_id?`Assigned to ${en(x.assigned_to_employee_id)}`:'No replacement assigned',actor_id:x.resolved_by})}
 for(const x of bids.data??[]){out.push({id:`bid-open-${x.id}`,at:x.created_at,kind:'pool',title:'Shift Pool bid submitted',detail:`${en(x.employee_id)} · ${x.status}`,actor_id:x.created_by});if(x.reviewed_at)out.push({id:`bid-review-${x.id}`,at:x.reviewed_at,kind:'pool',title:`Shift Pool bid ${x.status}`,detail:en(x.employee_id),actor_id:x.reviewed_by})}
 for(const x of av.data??[]){out.push({id:`av-open-${x.id}`,at:x.created_at,kind:'request',title:`Availability request · ${x.request_kind}`,detail:`${en(x.employee_id)} · ${x.status}`,actor_id:x.requested_by});if(x.reviewed_at)out.push({id:`av-review-${x.id}`,at:x.reviewed_at,kind:'request',title:`Availability ${x.status}`,detail:en(x.employee_id),actor_id:x.reviewed_by})}
 for(const x of timeoff.data??[]){out.push({id:`to-open-${x.id}`,at:x.created_at,kind:'request',title:`Time off requested · ${x.category||'unpaid'}`,detail:`${en(x.employee_id)} · ${x.starts_on}–${x.ends_on} · ${x.status}`,actor_id:x.requested_by});if(x.reviewed_at)out.push({id:`to-review-${x.id}`,at:x.reviewed_at,kind:'request',title:`Time off ${x.status}`,detail:en(x.employee_id),actor_id:x.reviewed_by})}
 for(const x of changesReq.data??[]){out.push({id:`cr-open-${x.id}`,at:x.created_at,kind:'request',title:`Shift ${String(x.request_type).replaceAll('_',' ')} requested`,detail:`${en(x.requested_by_employee_id)} · ${x.status}`,actor_id:x.requested_by});if(x.reviewed_at)out.push({id:`cr-review-${x.id}`,at:x.reviewed_at,kind:'request',title:`Shift request ${x.status}`,detail:`${en(x.requested_by_employee_id)}${x.target_employee_id?` → ${en(x.target_employee_id)}`:''}`,actor_id:x.reviewed_by})}
 for(const x of claims.data??[]){out.push({id:`claim-open-${x.id}`,at:x.created_at,kind:'request',title:'Open shift claimed',detail:`${en(x.employee_id)} · ${x.status}`,actor_id:x.requested_by});if(x.reviewed_at)out.push({id:`claim-review-${x.id}`,at:x.reviewed_at,kind:'request',title:`Open shift claim ${x.status}`,detail:en(x.employee_id),actor_id:x.reviewed_by})}
 out.sort((a,b)=>new Date(b.at).getTime()-new Date(a.at).getTime());setItems(out.slice(0,400))}catch(e:any){setMessage(e?.message||'Could not load schedule activity.')}finally{setReady(true)}}
 const shown=useMemo(()=>filter==='all'?items:items.filter(x=>x.kind===filter),[items,filter]);const actor=(id:string|null)=>id?(people[id]||id.slice(0,8)):'System';
 if(!ready)return <div className="full-loader"><span>Opening schedule activity…</span></div>;
 return <main className={styles.page}><div className={styles.top}><div><h1>Schedule Activity</h1><p>One timeline for schedule edits, publications, requests and Shift Pool decisions.</p></div><Link className={styles.back} href="/schedule">Back to Schedule</Link></div>{message&&<div className={styles.error}>{message}</div>}{!canManage?<div className={styles.error}>Manager access is required.</div>:<><section className={styles.section}><div className={styles.card}><div className={styles.actions}>{['all','shift','publish','pool','request'].map(x=><button key={x} className={`${styles.button} ${filter===x?'':styles.secondary}`} onClick={()=>setFilter(x)}>{x==='all'?'All':x[0].toUpperCase()+x.slice(1)}</button>)}</div></div></section><section className={styles.section}><div className={styles.list}>{shown.map(x=><div className={styles.entry} key={x.id}><div className={styles.entryHead}><div><h3>{x.title}</h3><small>{new Date(x.at).toLocaleString()} · by {actor(x.actor_id)}</small></div><span className={styles.pill}>{x.kind}</span></div><div className={styles.details}><div className={styles.detail}><span>{x.detail}</span></div></div></div>)}{shown.length===0&&<div className={styles.card}><b>No matching activity.</b></div>}</div></section></>}</main>
}
