'use client';

import {FormEvent,useEffect,useMemo,useState} from 'react';
import {ArrowLeft,CalendarClock,CalendarOff,CheckCircle2,Clock3,RefreshCw,XCircle} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import styles from '../employee.module.css';

type AvailabilityMode='any'|'custom'|'unavailable';
type AvailabilityDraft={mode:AvailabilityMode;from:string;to:string};
type Tab='availability'|'timeoff'|'history';
type Center={weekly_availability:any[];temporary_availability:any[];availability_requests:any[];time_off_requests:any[];shift_changes:any[];shift_claims:any[];blocked_days:any[];time_off_min_notice_days:number};
const DAYS=[{d:1,n:'Monday'},{d:2,n:'Tuesday'},{d:3,n:'Wednesday'},{d:4,n:'Thursday'},{d:5,n:'Friday'},{d:6,n:'Saturday'},{d:0,n:'Sunday'}];
const blank=():Record<number,AvailabilityDraft>=>Object.fromEntries(DAYS.map(x=>[x.d,{mode:'any',from:'10:00',to:'22:00'}]));
const today=()=>new Date().toISOString().slice(0,10);
const plusDays=(date:string,n:number)=>{const d=new Date(`${date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};
const labelStatus=(s:string)=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());

export default function EmployeeRequests(){
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[tab,setTab]=useState<Tab>('availability'),[center,setCenter]=useState<Center|null>(null),[weekly,setWeekly]=useState<Record<number,AvailabilityDraft>>(blank()),[temp,setTemp]=useState({from:plusDays(today(),7),to:plusDays(today(),14),reason:'',rows:blank()}),[off,setOff]=useState({starts_on:plusDays(today(),7),ends_on:plusDays(today(),7),category:'',reason:'',partial:false,start_time:'15:00',end_time:'18:00'});
 useEffect(()=>{void load()},[]);
 async function load(){setBusy(true);setMessage('');const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}const p=await supabase.from('profiles').select('app_role').eq('id',u.user.id).single();if(p.error||p.data?.app_role!=='employee'){location.href=p.data?'/manager':'/';return}const st=await supabase.rpc('employee_self_setup_status',{});if(st.error||st.data?.status!=='approved'||st.data?.employment_status!=='active'){location.href=st.data?.status==='approved'?'/employee/access':'/employee/setup';return}const r=await supabase.rpc('my_employee_request_center',{});if(r.error){setMessage(r.error.message);setReady(true);setBusy(false);return}const c=r.data as Center;setCenter(c);const d=blank();for(const row of c.weekly_availability||[]){const day=Number(row.day_of_week);d[day]=row.unavailable?{mode:'unavailable',from:'10:00',to:'22:00'}:{mode:'custom',from:String(row.available_from||'10:00').slice(0,5),to:String(row.available_to||'22:00').slice(0,5)}}setWeekly(d);setReady(true);setBusy(false)}
 function rowsFor(draft:Record<number,AvailabilityDraft>){return DAYS.flatMap(({d})=>{const x=draft[d];if(!x||x.mode==='any')return[];return[{day_of_week:d,unavailable:x.mode==='unavailable',available_from:x.mode==='custom'?x.from:null,available_to:x.mode==='custom'?x.to:null}]})}
 function validRows(draft:Record<number,AvailabilityDraft>){return Object.values(draft).every(x=>x.mode!=='custom'||(x.from&&x.to&&x.to>x.from))}
 async function saveWeekly(){if(busy)return;if(!validRows(weekly))return setMessage('Every custom availability window needs an end time after its start time.');setBusy(true);const {data,error}=await supabase.rpc('set_my_weekly_availability',{p_rows:rowsFor(weekly)});setMessage(error?error.message:data===-1?'Weekly availability change sent for manager approval.':'Weekly availability saved.');if(!error)await load();setBusy(false)}
 async function submitTemporary(e:FormEvent){e.preventDefault();if(busy)return;if(temp.to<temp.from)return setMessage('Temporary availability end date must be on or after the start date.');if(!validRows(temp.rows))return setMessage('Every custom availability window needs an end time after its start time.');setBusy(true);const {error}=await supabase.rpc('submit_availability_request',{p_rows:rowsFor(temp.rows),p_effective_from:temp.from,p_effective_to:temp.to,p_reason:temp.reason.trim()||null});setMessage(error?error.message:'Temporary availability request sent to management.');if(!error){setTemp(x=>({...x,reason:'',rows:blank()}));await load()}setBusy(false)}
 async function submitTimeOff(e:FormEvent){e.preventDefault();if(busy)return;if(off.ends_on<off.starts_on)return setMessage('Last day must be on or after the first day.');setBusy(true);const {error}=await supabase.rpc('submit_my_time_off_request',{p_starts_on:off.starts_on,p_ends_on:off.partial?off.starts_on:off.ends_on,p_reason:off.reason.trim()||null,p_category:off.category.trim()||null,p_partial_day:off.partial,p_start_time:off.partial?off.start_time:null,p_end_time:off.partial?off.end_time:null});setMessage(error?error.message:'Time-off request sent to management.');if(!error){setOff(x=>({...x,reason:'',category:''}));await load()}setBusy(false)}
 async function cancel(kind:'timeoff'|'availability',id:string){if(busy||!confirm('Cancel this pending request?'))return;setBusy(true);const {data,error}=await supabase.rpc(kind==='timeoff'?'cancel_my_time_off_request':'cancel_my_availability_request',{p_request_id:id});setMessage(error?error.message:data?'Request cancelled.':'That request is no longer pending.');if(!error)await load();setBusy(false)}
 const pending=useMemo(()=>[...(center?.availability_requests||[]),...(center?.time_off_requests||[]),...(center?.shift_changes||[]),...(center?.shift_claims||[])].filter((x:any)=>x.status==='pending').length,[center]);
 const blocked=new Set((center?.blocked_days||[]).map((x:any)=>x.blocked_on));
 if(!ready)return <main className={styles.page}>Opening your requests…</main>;
 return <main className={styles.page}>
  <header className={styles.header}><a className={styles.iconButton} href="/employee" aria-label="Back to staff home"><ArrowLeft size={20}/></a><div className={styles.brand}><small>El Molino Staff</small><strong>Requests</strong></div><button className={styles.iconButton} disabled={busy} aria-label="Refresh requests" onClick={load}><RefreshCw size={18}/></button></header>
  {message&&<div className={message.toLowerCase().includes('could not')||message.toLowerCase().includes('invalid')||message.toLowerCase().includes('blocked')?styles.error:styles.notice}>{message}</div>}
  <section className={styles.setupCard}><div className={styles.sectionHead}><h2>My scheduling requests</h2><span>{pending} pending</span></div><p className={styles.muted}>Availability tells management when you can work. Time off is for specific dates you cannot work. Your current approved settings stay in effect until a change is approved.</p><div className={styles.filterBar}><button className={`${styles.filterChip} ${tab==='availability'?styles.filterChipActive:''}`} onClick={()=>setTab('availability')}><CalendarClock size={14}/> Availability</button><button className={`${styles.filterChip} ${tab==='timeoff'?styles.filterChipActive:''}`} onClick={()=>setTab('timeoff')}><CalendarOff size={14}/> Time Off</button><button className={`${styles.filterChip} ${tab==='history'?styles.filterChipActive:''}`} onClick={()=>setTab('history')}><Clock3 size={14}/> History</button></div></section>
  {tab==='availability'&&<><section className={styles.section}><div className={styles.setupCard}><h2>Recurring weekly availability</h2><p className={styles.muted}>“Any time” adds no restriction. Custom hours limit scheduling to that window. Unavailable blocks the entire day.</p><AvailabilityEditor value={weekly} onChange={setWeekly}/><div className={styles.actions}><button className={styles.button} disabled={busy} onClick={saveWeekly}>Save weekly availability</button></div></div></section><section className={styles.section}><div className={styles.setupCard}><h2>Temporary availability</h2><p className={styles.muted}>Use this for school breaks, a temporary second-job schedule, travel windows or other date-limited changes. Your recurring availability returns automatically after the end date.</p><form onSubmit={submitTemporary}><div className={styles.two}><label className={styles.field}><span>Effective from</span><input type="date" min={today()} value={temp.from} onChange={e=>setTemp({...temp,from:e.target.value,to:e.target.value>temp.to?e.target.value:temp.to})}/></label><label className={styles.field}><span>Effective through</span><input type="date" min={temp.from} value={temp.to} onChange={e=>setTemp({...temp,to:e.target.value})}/></label></div><AvailabilityEditor value={temp.rows} onChange={rows=>setTemp({...temp,rows})}/><label className={styles.field}><span>Reason (optional)</span><input maxLength={2000} value={temp.reason} onChange={e=>setTemp({...temp,reason:e.target.value})}/></label><div className={styles.actions}><button className={styles.button} disabled={busy}>Submit temporary availability</button></div></form></div></section></>}
  {tab==='timeoff'&&<section className={styles.section}><div className={styles.setupCard}><h2>Request time off</h2><p className={styles.muted}>{center?.time_off_min_notice_days?`Requests require at least ${center.time_off_min_notice_days} day${center.time_off_min_notice_days===1?'':'s'} notice. `:''}Blocked dates cannot be submitted.</p><form onSubmit={submitTimeOff}><div className={styles.two}><label className={styles.field}><span>First day</span><input type="date" min={today()} value={off.starts_on} onChange={e=>setOff({...off,starts_on:e.target.value,ends_on:e.target.value>off.ends_on?e.target.value:off.ends_on})}/></label>{!off.partial&&<label className={styles.field}><span>Last day</span><input type="date" min={off.starts_on} value={off.ends_on} onChange={e=>setOff({...off,ends_on:e.target.value})}/></label>}</div><label className={styles.role}><input type="checkbox" checked={off.partial} onChange={e=>setOff({...off,partial:e.target.checked,ends_on:off.starts_on})}/>Partial day only</label>{off.partial&&<div className={styles.two}><label className={styles.field}><span>From</span><input type="time" value={off.start_time} onChange={e=>setOff({...off,start_time:e.target.value})}/></label><label className={styles.field}><span>To</span><input type="time" value={off.end_time} onChange={e=>setOff({...off,end_time:e.target.value})}/></label></div>}<label className={styles.field}><span>Category (optional)</span><input maxLength={80} placeholder="Vacation, appointment, personal…" value={off.category} onChange={e=>setOff({...off,category:e.target.value})}/></label><label className={styles.field}><span>Reason / note (optional)</span><input maxLength={2000} value={off.reason} onChange={e=>setOff({...off,reason:e.target.value})}/></label>{blocked.has(off.starts_on)&&<div className={styles.error}>This date is currently blocked for time-off requests.</div>}<div className={styles.actions}><button className={styles.button} disabled={busy||blocked.has(off.starts_on)}>Submit time off</button></div></form></div></section>}
  {tab==='history'&&<RequestHistory center={center} busy={busy} cancel={cancel}/>} 
 </main>
}

function AvailabilityEditor({value,onChange}:{value:Record<number,AvailabilityDraft>;onChange:(x:Record<number,AvailabilityDraft>)=>void}){return <div className={styles.list}>{DAYS.map(({d,n})=>{const a=value[d]||{mode:'any',from:'10:00',to:'22:00'};return <div className={styles.preferenceRow} key={d}><div className={styles.two}><label className={styles.field}><span>{n}</span><select value={a.mode} onChange={e=>onChange({...value,[d]:{...a,mode:e.target.value as AvailabilityMode}})}><option value="any">Any time</option><option value="custom">Custom hours</option><option value="unavailable">Unavailable</option></select></label>{a.mode==='custom'&&<label className={styles.field}><span>Hours</span><span className={styles.two}><input type="time" value={a.from} onChange={e=>onChange({...value,[d]:{...a,from:e.target.value}})}/><input type="time" value={a.to} onChange={e=>onChange({...value,[d]:{...a,to:e.target.value}})}/></span></label>}</div></div>})}</div>}

function RequestHistory({center,busy,cancel}:{center:Center|null;busy:boolean;cancel:(kind:'timeoff'|'availability',id:string)=>void}){
 const rows=[...(center?.time_off_requests||[]).map((x:any)=>({...x,_kind:'timeoff',_title:x.partial_day?'Partial-day time off':'Time off',_when:x.partial_day?`${x.starts_on} · ${String(x.start_time||'').slice(0,5)}–${String(x.end_time||'').slice(0,5)}`:`${x.starts_on}${x.ends_on!==x.starts_on?` – ${x.ends_on}`:''}`})),...(center?.availability_requests||[]).map((x:any)=>({...x,_kind:'availability',_title:x.effective_from?'Temporary availability':'Availability change',_when:x.effective_from?`${x.effective_from} – ${x.effective_to}`:'Recurring weekly availability'})),...(center?.shift_changes||[]).map((x:any)=>({...x,_kind:'shift',_title:labelStatus(x.request_type||'shift change'),_when:'Shift request'})),...(center?.shift_claims||[]).map((x:any)=>({...x,_kind:'claim',_title:'Open shift request',_when:'Shift Pool'}))].sort((a:any,b:any)=>String(b.created_at||b.submitted_at||'').localeCompare(String(a.created_at||a.submitted_at||'')));
 return <section className={styles.section}><div className={styles.sectionHead}><h2>Request history</h2><span>Newest first</span></div><div className={styles.list}>{rows.map((x:any)=><article className={styles.preferenceRow} key={`${x._kind}-${x.id}`}><div className={styles.sectionHead}><div><h2>{x._title}</h2><span>{x._when}</span></div><span className={styles.pill}>{labelStatus(x.status||'pending')}</span></div>{(x.reason||x.employee_note||x.manager_note)&&<p className={styles.muted}>{x.reason||x.employee_note}{x.manager_note?` · Manager: ${x.manager_note}`:''}</p>}<div className={styles.notificationMeta}><span>{x.status==='approved'?<CheckCircle2 size={13}/>:x.status==='denied'||x.status==='rejected'?<XCircle size={13}/>:<Clock3 size={13}/>} {labelStatus(x.status||'pending')}</span>{(x.created_at||x.submitted_at)&&<span>{new Date(x.created_at||x.submitted_at).toLocaleString()}</span>}</div>{x.status==='pending'&&(x._kind==='timeoff'||x._kind==='availability')&&<div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>cancel(x._kind,x.id)}>Cancel request</button></div>}</article>)}{!rows.length&&<div className={styles.empty}>You have no scheduling requests yet.</div>}</div></section>
}
