'use client';

import {FormEvent,useEffect,useMemo,useState} from 'react';
import {ArrowLeft,CalendarClock,CalendarOff,CheckCircle2,Clock3,RefreshCw,XCircle} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import {useI18n} from '@/lib/i18n';
import {requestsI18n} from '@/lib/i18n-requests';
import styles from '../employee.module.css';

type AvailabilityMode='any'|'custom'|'unavailable';
type AvailabilityDraft={mode:AvailabilityMode;from:string;to:string};
type Tab='availability'|'timeoff'|'history';
type Center={weekly_availability:any[];temporary_availability:any[];availability_requests:any[];time_off_requests:any[];shift_changes:any[];shift_claims:any[];blocked_days:any[];time_off_min_notice_days:number};
const DAY_IDS=[1,2,3,4,5,6,0];
const blank=():Record<number,AvailabilityDraft>=>Object.fromEntries(DAY_IDS.map(d=>[d,{mode:'any',from:'10:00',to:'22:00'}]));
const today=()=>new Date().toISOString().slice(0,10);
const plusDays=(date:string,n:number)=>{const d=new Date(`${date}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)};

export default function EmployeeRequests(){
 const {locale}=useI18n(),tx=requestsI18n(locale),dateLocale=locale==='es'?'es-US':'en-US';
 const statusLabel=(s:string)=>((tx.status as Record<string,string>)[s]||s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase()));
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[tab,setTab]=useState<Tab>('availability'),[center,setCenter]=useState<Center|null>(null),[weekly,setWeekly]=useState<Record<number,AvailabilityDraft>>(blank()),[temp,setTemp]=useState({from:plusDays(today(),7),to:plusDays(today(),14),reason:'',rows:blank()}),[off,setOff]=useState({starts_on:plusDays(today(),7),ends_on:plusDays(today(),7),category:'',reason:'',partial:false,start_time:'15:00',end_time:'18:00'});
 useEffect(()=>{void load()},[]);
 async function load(){setBusy(true);setMessage('');const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}const p=await supabase.from('profiles').select('app_role').eq('id',u.user.id).single();if(p.error||p.data?.app_role!=='employee'){location.href=p.data?'/manager':'/';return}const st=await supabase.rpc('employee_self_setup_status',{});if(st.error||st.data?.status!=='approved'||st.data?.employment_status!=='active'){location.href=st.data?.status==='approved'?'/employee/access':'/employee/setup';return}const r=await supabase.rpc('my_employee_request_center',{});if(r.error){setMessage(r.error.message);setReady(true);setBusy(false);return}const c=r.data as Center;setCenter(c);const d=blank();for(const row of c.weekly_availability||[]){const day=Number(row.day_of_week);d[day]=row.unavailable?{mode:'unavailable',from:'10:00',to:'22:00'}:{mode:'custom',from:String(row.available_from||'10:00').slice(0,5),to:String(row.available_to||'22:00').slice(0,5)}}setWeekly(d);setReady(true);setBusy(false)}
 function rowsFor(draft:Record<number,AvailabilityDraft>){return DAY_IDS.flatMap(d=>{const x=draft[d];if(!x||x.mode==='any')return[];return[{day_of_week:d,unavailable:x.mode==='unavailable',available_from:x.mode==='custom'?x.from:null,available_to:x.mode==='custom'?x.to:null}]})}
 function validRows(draft:Record<number,AvailabilityDraft>){return Object.values(draft).every(x=>x.mode!=='custom'||(x.from&&x.to&&x.to>x.from))}
 async function saveWeekly(){if(busy)return;if(!validRows(weekly))return setMessage(tx.customWindowError);setBusy(true);const {data,error}=await supabase.rpc('set_my_weekly_availability',{p_rows:rowsFor(weekly)});setMessage(error?error.message:data===-1?tx.weeklyApproval:tx.weeklySaved);if(!error)await load();setBusy(false)}
 async function submitTemporary(e:FormEvent){e.preventDefault();if(busy)return;if(temp.to<temp.from)return setMessage(tx.tempDateError);if(!validRows(temp.rows))return setMessage(tx.customWindowError);setBusy(true);const {error}=await supabase.rpc('submit_availability_request',{p_rows:rowsFor(temp.rows),p_effective_from:temp.from,p_effective_to:temp.to,p_reason:temp.reason.trim()||null});setMessage(error?error.message:tx.tempSent);if(!error){setTemp(x=>({...x,reason:'',rows:blank()}));await load()}setBusy(false)}
 async function submitTimeOff(e:FormEvent){e.preventDefault();if(busy)return;if(off.ends_on<off.starts_on)return setMessage(tx.lastDayError);setBusy(true);const {error}=await supabase.rpc('submit_my_time_off_request',{p_starts_on:off.starts_on,p_ends_on:off.partial?off.starts_on:off.ends_on,p_reason:off.reason.trim()||null,p_category:off.category.trim()||null,p_partial_day:off.partial,p_start_time:off.partial?off.start_time:null,p_end_time:off.partial?off.end_time:null});setMessage(error?error.message:tx.timeOffSent);if(!error){setOff(x=>({...x,reason:'',category:''}));await load()}setBusy(false)}
 async function cancel(kind:'timeoff'|'availability',id:string){if(busy||!confirm(tx.cancelConfirm))return;setBusy(true);const {data,error}=await supabase.rpc(kind==='timeoff'?'cancel_my_time_off_request':'cancel_my_availability_request',{p_request_id:id});setMessage(error?error.message:data?tx.cancelled:tx.notPending);if(!error)await load();setBusy(false)}
 const pending=useMemo(()=>[...(center?.availability_requests||[]),...(center?.time_off_requests||[]),...(center?.shift_changes||[]),...(center?.shift_claims||[])].filter((x:any)=>x.status==='pending').length,[center]);
 const blocked=new Set((center?.blocked_days||[]).map((x:any)=>x.blocked_on));
 if(!ready)return <main className={styles.page}>{tx.opening}</main>;
 return <main className={styles.page}>
  <header className={styles.header}><a className={styles.iconButton} href="/employee" aria-label={tx.back}><ArrowLeft size={20}/></a><div className={styles.brand}><small>{tx.staff}</small><strong>{tx.title}</strong></div><button className={styles.iconButton} disabled={busy} aria-label={tx.refresh} onClick={load}><RefreshCw size={18}/></button></header>
  {message&&<div className={message.toLowerCase().includes('could not')||message.toLowerCase().includes('invalid')||message.toLowerCase().includes('blocked')?styles.error:styles.notice}>{message}</div>}
  <section className={styles.setupCard}><div className={styles.sectionHead}><h2>{tx.heading}</h2><span>{pending} {tx.pending}</span></div><p className={styles.muted}>{tx.intro}</p><div className={styles.filterBar}><button className={`${styles.filterChip} ${tab==='availability'?styles.filterChipActive:''}`} onClick={()=>setTab('availability')}><CalendarClock size={14}/> {tx.availability}</button><button className={`${styles.filterChip} ${tab==='timeoff'?styles.filterChipActive:''}`} onClick={()=>setTab('timeoff')}><CalendarOff size={14}/> {tx.timeOff}</button><button className={`${styles.filterChip} ${tab==='history'?styles.filterChipActive:''}`} onClick={()=>setTab('history')}><Clock3 size={14}/> {tx.history}</button></div></section>
  {tab==='availability'&&<><section className={styles.section}><div className={styles.setupCard}><h2>{tx.weekly}</h2><p className={styles.muted}>{tx.weeklyHelp}</p><AvailabilityEditor value={weekly} onChange={setWeekly} tx={tx}/><div className={styles.actions}><button className={styles.button} disabled={busy} onClick={saveWeekly}>{tx.saveWeekly}</button></div></div></section><section className={styles.section}><div className={styles.setupCard}><h2>{tx.temp}</h2><p className={styles.muted}>{tx.tempHelp}</p><form onSubmit={submitTemporary}><div className={styles.two}><label className={styles.field}><span>{tx.effectiveFrom}</span><input type="date" min={today()} value={temp.from} onChange={e=>setTemp({...temp,from:e.target.value,to:e.target.value>temp.to?e.target.value:temp.to})}/></label><label className={styles.field}><span>{tx.effectiveThrough}</span><input type="date" min={temp.from} value={temp.to} onChange={e=>setTemp({...temp,to:e.target.value})}/></label></div><AvailabilityEditor value={temp.rows} onChange={rows=>setTemp({...temp,rows})} tx={tx}/><label className={styles.field}><span>{tx.reasonOptional}</span><input maxLength={2000} value={temp.reason} onChange={e=>setTemp({...temp,reason:e.target.value})}/></label><div className={styles.actions}><button className={styles.button} disabled={busy}>{tx.submitTemp}</button></div></form></div></section></>}
  {tab==='timeoff'&&<section className={styles.section}><div className={styles.setupCard}><h2>{tx.requestTimeOff}</h2><p className={styles.muted}>{center?.time_off_min_notice_days?`${tx.noticePrefix} ${center.time_off_min_notice_days} ${tx.noticeSuffix} `:''}{tx.blockedDates}</p><form onSubmit={submitTimeOff}><div className={styles.two}><label className={styles.field}><span>{tx.firstDay}</span><input type="date" min={today()} value={off.starts_on} onChange={e=>setOff({...off,starts_on:e.target.value,ends_on:e.target.value>off.ends_on?e.target.value:off.ends_on})}/></label>{!off.partial&&<label className={styles.field}><span>{tx.lastDay}</span><input type="date" min={off.starts_on} value={off.ends_on} onChange={e=>setOff({...off,ends_on:e.target.value})}/></label>}</div><label className={styles.role}><input type="checkbox" checked={off.partial} onChange={e=>setOff({...off,partial:e.target.checked,ends_on:off.starts_on})}/>{tx.partialOnly}</label>{off.partial&&<div className={styles.two}><label className={styles.field}><span>{tx.from}</span><input type="time" value={off.start_time} onChange={e=>setOff({...off,start_time:e.target.value})}/></label><label className={styles.field}><span>{tx.to}</span><input type="time" value={off.end_time} onChange={e=>setOff({...off,end_time:e.target.value})}/></label></div>}<label className={styles.field}><span>{tx.categoryOptional}</span><input maxLength={80} placeholder={tx.categoryPlaceholder} value={off.category} onChange={e=>setOff({...off,category:e.target.value})}/></label><label className={styles.field}><span>{tx.reasonNote}</span><input maxLength={2000} value={off.reason} onChange={e=>setOff({...off,reason:e.target.value})}/></label>{blocked.has(off.starts_on)&&<div className={styles.error}>{tx.blocked}</div>}<div className={styles.actions}><button className={styles.button} disabled={busy||blocked.has(off.starts_on)}>{tx.submitTimeOff}</button></div></form></div></section>}
  {tab==='history'&&<RequestHistory center={center} busy={busy} cancel={cancel} tx={tx} dateLocale={dateLocale} statusLabel={statusLabel}/>} 
 </main>
}

function AvailabilityEditor({value,onChange,tx}:{value:Record<number,AvailabilityDraft>;onChange:(x:Record<number,AvailabilityDraft>)=>void;tx:ReturnType<typeof requestsI18n>}){return <div className={styles.list}>{DAY_IDS.map((d,i)=>{const a=value[d]||{mode:'any',from:'10:00',to:'22:00'};return <div className={styles.preferenceRow} key={d}><div className={styles.two}><label className={styles.field}><span>{tx.days[i]}</span><select value={a.mode} onChange={e=>onChange({...value,[d]:{...a,mode:e.target.value as AvailabilityMode}})}><option value="any">{tx.anyTime}</option><option value="custom">{tx.customHours}</option><option value="unavailable">{tx.unavailable}</option></select></label>{a.mode==='custom'&&<label className={styles.field}><span>{tx.hours}</span><span className={styles.two}><input type="time" value={a.from} onChange={e=>onChange({...value,[d]:{...a,from:e.target.value}})}/><input type="time" value={a.to} onChange={e=>onChange({...value,[d]:{...a,to:e.target.value}})}/></span></label>}</div></div>})}</div>}

function RequestHistory({center,busy,cancel,tx,dateLocale,statusLabel}:{center:Center|null;busy:boolean;cancel:(kind:'timeoff'|'availability',id:string)=>void;tx:ReturnType<typeof requestsI18n>;dateLocale:string;statusLabel:(s:string)=>string}){
 const rows=[...(center?.time_off_requests||[]).map((x:any)=>({...x,_kind:'timeoff',_title:x.partial_day?tx.partialTimeOff:tx.timeOffTitle,_when:x.partial_day?`${x.starts_on} · ${String(x.start_time||'').slice(0,5)}–${String(x.end_time||'').slice(0,5)}`:`${x.starts_on}${x.ends_on!==x.starts_on?` – ${x.ends_on}`:''}`})),...(center?.availability_requests||[]).map((x:any)=>({...x,_kind:'availability',_title:x.effective_from?tx.tempAvailability:tx.availabilityChange,_when:x.effective_from?`${x.effective_from} – ${x.effective_to}`:tx.weeklyAvailability})),...(center?.shift_changes||[]).map((x:any)=>({...x,_kind:'shift',_title:statusLabel(x.request_type||'shift_change'),_when:tx.shiftRequest})),...(center?.shift_claims||[]).map((x:any)=>({...x,_kind:'claim',_title:tx.openShiftRequest,_when:tx.shiftPool}))].sort((a:any,b:any)=>String(b.created_at||b.submitted_at||'').localeCompare(String(a.created_at||a.submitted_at||'')));
 return <section className={styles.section}><div className={styles.sectionHead}><h2>{tx.requestHistory}</h2><span>{tx.newest}</span></div><div className={styles.list}>{rows.map((x:any)=><article className={styles.preferenceRow} key={`${x._kind}-${x.id}`}><div className={styles.sectionHead}><div><h2>{x._title}</h2><span>{x._when}</span></div><span className={styles.pill}>{statusLabel(x.status||'pending')}</span></div>{(x.reason||x.employee_note||x.manager_note)&&<p className={styles.muted}>{x.reason||x.employee_note}{x.manager_note?` · ${tx.manager}: ${x.manager_note}`:''}</p>}<div className={styles.notificationMeta}><span>{x.status==='approved'?<CheckCircle2 size={13}/>:x.status==='denied'||x.status==='rejected'?<XCircle size={13}/>:<Clock3 size={13}/>} {statusLabel(x.status||'pending')}</span>{(x.created_at||x.submitted_at)&&<span>{new Date(x.created_at||x.submitted_at).toLocaleString(dateLocale)}</span>}</div>{x.status==='pending'&&(x._kind==='timeoff'||x._kind==='availability')&&<div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>cancel(x._kind,x.id)}>{tx.cancelRequest}</button></div>}</article>)}{!rows.length&&<div className={styles.empty}>{tx.none}</div>}</div></section>
}
