'use client';

import {FormEvent,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase';
import {validEmail} from '@/lib/app-hardening';
import styles from '../../ops-tools.module.css';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Claim={id:string;user_id:string;first_name:string;last_name:string;phone:string|null;status:'pending'|'approved'|'changes_requested'|'rejected';employee_id:string|null;manager_note:string|null;submitted_at:string;reviewed_at:string|null};
type Role={id:string;name:string;department:string};
type RoleClaim={claim_id:string;role_id:string};
type Employee={id:string;full_name:string;user_id:string|null;active:boolean;employment_status:'active'|'suspended'|'inactive';status_reason:string|null;status_changed_at:string};
type Invite={id:string;email:string;status:string;expires_at:string|null;created_at:string};
type RoleChange={id:string;employee_id:string;user_id:string;status:'pending'|'approved'|'changes_requested'|'rejected'|'cancelled';employee_note:string|null;manager_note:string|null;submitted_at:string;reviewed_at:string|null};
type RoleChangeRole={request_id:string;role_id:string};

export default function TeamSetupPage(){
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[profile,setProfile]=useState<Profile|null>(null),[claims,setClaims]=useState<Claim[]>([]),[roles,setRoles]=useState<Role[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[invites,setInvites]=useState<Invite[]>([]),[roleChanges,setRoleChanges]=useState<RoleChange[]>([]),[selectedRoles,setSelectedRoles]=useState<Record<string,string[]>>({}),[selectedRoleChanges,setSelectedRoleChanges]=useState<Record<string,string[]>>({}),[existing,setExisting]=useState<Record<string,string>>({}),[inviteEmail,setInviteEmail]=useState('');
 useEffect(()=>{void load()},[]);
 async function load(){
  setBusy(true);setMessage('');const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}
  const p=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();if(!p.data||!['admin','manager'].includes(p.data.app_role)){location.href='/employee';return}
  const pr=p.data as Profile;if(!pr.location_id){setProfile(pr);setMessage('No restaurant location is assigned.');setBusy(false);setReady(true);return}setProfile(pr);
  const [c,r,rc,e,i,rq,rr]=await Promise.all([
   supabase.from('employee_self_setup_claims').select('id,user_id,first_name,last_name,phone,status,employee_id,manager_note,submitted_at,reviewed_at').eq('location_id',pr.location_id).order('submitted_at',{ascending:true}),
   supabase.from('employee_roles').select('id,name,department').eq('location_id',pr.location_id).neq('department','management').order('department').order('name'),
   supabase.from('employee_self_setup_role_claims').select('claim_id,role_id'),
   supabase.from('employees').select('id,full_name,user_id,active,employment_status,status_reason,status_changed_at').eq('location_id',pr.location_id).is('deleted_at',null).order('full_name'),
   supabase.from('user_invitations').select('id,email,status,expires_at,created_at').eq('location_id',pr.location_id).eq('app_role','employee').order('created_at',{ascending:false}).limit(100),
   supabase.from('employee_role_change_requests').select('id,employee_id,user_id,status,employee_note,manager_note,submitted_at,reviewed_at').eq('location_id',pr.location_id).order('submitted_at',{ascending:false}).limit(200),
   supabase.from('employee_role_change_request_roles').select('request_id,role_id')
  ]);
  const failed=[c,r,rc,e,i,rq,rr].find(x=>x.error);if(failed?.error)setMessage(failed.error.message||'Could not load team setup.');
  const cs=(c.data??[]) as Claim[],claimRoles=(rc.data??[]) as RoleClaim[],requests=(rq.data??[]) as RoleChange[],requestRoles=(rr.data??[]) as RoleChangeRole[];
  setClaims(cs);setRoles((r.data??[]) as Role[]);setEmployees((e.data??[]) as Employee[]);setInvites((i.data??[]) as Invite[]);setRoleChanges(requests);
  const map:Record<string,string[]>={};for(const claim of cs)map[claim.id]=claimRoles.filter(x=>x.claim_id===claim.id).map(x=>x.role_id);setSelectedRoles(map);
  const changeMap:Record<string,string[]>={};for(const req of requests)changeMap[req.id]=requestRoles.filter(x=>x.request_id===req.id).map(x=>x.role_id);setSelectedRoleChanges(changeMap);
  setBusy(false);setReady(true)
 }
 async function invite(e:FormEvent){e.preventDefault();if(busy||!profile?.location_id)return;const email=inviteEmail.trim().toLowerCase();if(!validEmail(email))return setMessage('Enter a valid employee email address.');if(invites.some(x=>x.email.toLowerCase()===email&&x.status==='pending'&&(!x.expires_at||new Date(x.expires_at)>new Date())))return setMessage('That employee already has an active invitation.');setBusy(true);const {data:u}=await supabase.auth.getUser();if(!u.user){setBusy(false);return}const {error}=await supabase.from('user_invitations').insert({location_id:profile.location_id,email,app_role:'employee',invited_by:u.user.id,expires_at:new Date(Date.now()+7*86400000).toISOString()});setMessage(error?.code==='23505'?'That employee already has an active invitation.':error?error.message:'Employee invitation created. They can create their account with this email from the El Molino app sign-in screen.');if(!error){setInviteEmail('');await load()}setBusy(false)}
 async function revokeInvite(id:string){if(busy)return;setBusy(true);const {error}=await supabase.from('user_invitations').update({status:'revoked'}).eq('id',id).eq('status','pending');setMessage(error?error.message:'Invitation revoked.');await load();setBusy(false)}
 function toggle(claimId:string,roleId:string){setSelectedRoles(m=>{const now=m[claimId]||[];return {...m,[claimId]:now.includes(roleId)?now.filter(x=>x!==roleId):[...now,roleId]}})}
 function toggleRoleChange(requestId:string,roleId:string){setSelectedRoleChanges(m=>{const now=m[requestId]||[];return {...m,[requestId]:now.includes(roleId)?now.filter(x=>x!==roleId):[...now,roleId]}})}
 async function review(c:Claim,decision:'approved'|'changes_requested'|'rejected'){
  if(busy)return;let note:string|null=null;if(decision!=='approved'){note=prompt(decision==='changes_requested'?'What should this employee correct?':'Reason / note for this employee:')?.trim()||null;if(decision==='changes_requested'&&!note)return}
  if(decision==='rejected'&&!confirm(`Reject ${c.first_name} ${c.last_name}'s staff profile?`))return;
  const roleIds=selectedRoles[c.id]||[];if(decision==='approved'&&!roleIds.length){setMessage('Choose at least one verified job role before approving.');return}
  setBusy(true);const {error}=await supabase.rpc('review_employee_self_setup',{p_claim_id:c.id,p_decision:decision,p_role_ids:decision==='approved'?roleIds:null,p_existing_employee_id:decision==='approved'?(existing[c.id]||null):null,p_manager_note:note});setMessage(error?error.message:decision==='approved'?`${c.first_name} ${c.last_name} is approved and scheduling-ready.`:decision==='changes_requested'?'Update request sent to the employee.':'Employee setup rejected.');await load();setBusy(false)
 }
 async function reviewRoleChange(req:RoleChange,decision:'approved'|'changes_requested'|'rejected',override=false){
  if(busy)return;let note:string|null=null;if(decision!=='approved'){note=prompt(decision==='changes_requested'?'What should the employee change in this position request?':'Reason / note for this request:')?.trim()||null;if(decision==='changes_requested'&&!note)return}
  const approved=selectedRoleChanges[req.id]||[];if(decision==='approved'&&!approved.length)return setMessage('Keep at least one verified position before approving.');
  setBusy(true);const {data,error}=await supabase.rpc('review_employee_role_change_request',{p_request_id:req.id,p_decision:decision,p_approved_role_ids:decision==='approved'?approved:null,p_manager_note:note,p_override_future_shifts:override});
  if(error&&decision==='approved'&&!override&&error.message.includes('future scheduled shifts')){setBusy(false);if(confirm('This role removal conflicts with future scheduled shifts. Approve anyway and review those shifts immediately?'))return reviewRoleChange(req,decision,true)}
  setMessage(error?error.message:decision==='approved'?`Verified positions updated${data?.future_shift_conflicts?` with ${data.future_shift_conflicts} future shift conflict(s) to review`:''}.`:decision==='changes_requested'?'Position request returned for changes.':'Position request rejected.');await load();setBusy(false)
 }
 async function changeStatus(emp:Employee,next:'active'|'suspended'|'inactive',override=false){
  if(busy||emp.employment_status===next)return;let reason:string|null=null;if(next!=='active'){reason=prompt(next==='suspended'?'Reason for suspending staff access:':'Reason for marking this employee inactive:')?.trim()||null;if(!reason)return}else reason=prompt('Optional note for reactivating this employee:')?.trim()||null;
  setBusy(true);const {data,error}=await supabase.rpc('set_employee_employment_status',{p_employee_id:emp.id,p_status:next,p_reason:reason,p_override_future_shifts:override});
  if(error&&!override&&error.message.includes('future scheduled shifts')){setBusy(false);if(confirm('This employee still has future scheduled shifts. Change their access anyway and review schedule coverage immediately?'))return changeStatus(emp,next,true)}
  setMessage(error?error.message:`${emp.full_name} is now ${next}.${data?.future_shift_count?` Review ${data.future_shift_count} future scheduled shift(s).`:''}`);await load();setBusy(false)
 }
 const pending=claims.filter(c=>c.status==='pending').length,changes=claims.filter(c=>c.status==='changes_requested').length,approved=claims.filter(c=>c.status==='approved').length,rejected=claims.filter(c=>c.status==='rejected').length,pendingRoleChanges=roleChanges.filter(x=>x.status==='pending');
 const unlinked=useMemo(()=>employees.filter(e=>e.active&&!e.user_id).length,[employees]);
 const empName=(id:string)=>employees.find(e=>e.id===id)?.full_name||'Employee';
 if(!ready)return <main className={styles.page}>Loading team setup…</main>;
 if(!profile?.location_id)return <main className={styles.page}>{message||'No restaurant location is assigned.'}</main>;
 return <main className={styles.page}>
  <div className={styles.top}><div><h1>Employee App Setup</h1><p>Invite staff, verify identity and positions, then control the employee lifecycle without losing history.</p></div><Link className={styles.back} href="/manager">Back to Manager</Link></div>
  {message&&<div className={message.toLowerCase().includes('could not')||message.toLowerCase().includes('choose at least')||message.toLowerCase().includes('valid employee')?styles.error:styles.notice}>{message}</div>}
  <div className={styles.grid}><Metric label="Active staff" value={employees.filter(e=>e.employment_status==='active').length}/><Metric label="Waiting profile review" value={pending}/><Metric label="Position changes" value={pendingRoleChanges.length}/><Metric label="Existing unlinked roster" value={unlinked}/></div>
  <section className={styles.section}><div className={styles.card}><h2>Invite employees</h2><p>Create an employee invitation for each staff email. They use that email to create their account, submit their identity and job positions, and wait for manager verification.</p><form onSubmit={invite}><div className={styles.formGrid}><label className={styles.field}><span>Employee email</span><input type="email" maxLength={254} value={inviteEmail} onChange={e=>setInviteEmail(e.target.value)} placeholder="employee@example.com" required/></label></div><div className={styles.actions}><button className={styles.button} disabled={busy}>Create Employee Invitation</button></div></form>{invites.length>0&&<div className={styles.list} style={{marginTop:12}}>{invites.slice(0,12).map(i=><div className={styles.entry} key={i.id}><div className={styles.entryHead}><div><b>{i.email}</b><small>{i.expires_at?`Expires ${new Date(i.expires_at).toLocaleString()}`:'No expiration'}</small></div><span className={styles.pill}>{i.status}</span></div>{i.status==='pending'&&<div className={styles.actions}><button type="button" className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>revokeInvite(i.id)}>Revoke</button></div>}</div>)}</div>}</div></section>
  <section className={styles.section}><h2>Waiting for profile review</h2><div className={styles.list}>{claims.filter(c=>c.status!=='approved').map(c=><div className={styles.entry} key={c.id}><div className={styles.entryHead}><div><h3>{c.first_name} {c.last_name}</h3><small>{c.phone||'No phone'} · submitted {new Date(c.submitted_at).toLocaleString()}</small></div><span className={styles.pill}>{c.status.replaceAll('_',' ')}</span></div>{c.manager_note&&<div className={styles.notice} style={{marginTop:10}}>{c.manager_note}</div>}<div className={styles.formGrid} style={{marginTop:12}}><label className={styles.field}><span>Link to existing roster record (optional)</span><select value={existing[c.id]||''} onChange={e=>setExisting(m=>({...m,[c.id]:e.target.value}))}><option value="">Auto-match same name or create new</option>{employees.filter(e=>!e.user_id||e.user_id===c.user_id).map(e=><option value={e.id} key={e.id}>{e.full_name}{e.user_id?' · already linked':''}</option>)}</select></label></div><div className={styles.details}>{roles.map(r=><label className={styles.checkbox} key={r.id}><input type="checkbox" checked={(selectedRoles[c.id]||[]).includes(r.id)} onChange={()=>toggle(c.id,r.id)}/>{r.name}</label>)}</div><div className={styles.actions}><button className={styles.button} disabled={busy} onClick={()=>review(c,'approved')}>Approve Profile</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>review(c,'changes_requested')}>Request Changes</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>review(c,'rejected')}>Reject</button></div></div>)}{!claims.some(c=>c.status!=='approved')&&<div className={styles.empty}>No employee profiles are waiting for review.</div>}</div></section>
  <section className={styles.section}><h2>Position change requests</h2><div className={styles.list}>{pendingRoleChanges.map(req=><div className={styles.entry} key={req.id}><div className={styles.entryHead}><div><h3>{empName(req.employee_id)}</h3><small>Submitted {new Date(req.submitted_at).toLocaleString()}{req.employee_note?` · ${req.employee_note}`:''}</small></div><span className={styles.pill}>pending</span></div><p>Requested verified positions:</p><div className={styles.details}>{roles.map(r=><label className={styles.checkbox} key={r.id}><input type="checkbox" checked={(selectedRoleChanges[req.id]||[]).includes(r.id)} onChange={()=>toggleRoleChange(req.id,r.id)}/>{r.name}</label>)}</div><div className={styles.actions}><button className={styles.button} disabled={busy} onClick={()=>reviewRoleChange(req,'approved')}>Approve Positions</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>reviewRoleChange(req,'changes_requested')}>Request Changes</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>reviewRoleChange(req,'rejected')}>Reject</button></div></div>)}{!pendingRoleChanges.length&&<div className={styles.empty}>No position changes are waiting for review.</div>}</div></section>
  <section className={styles.section}><h2>Staff lifecycle</h2><div className={styles.list}>{employees.filter(e=>Boolean(e.user_id)).map(e=><div className={styles.entry} key={e.id}><div className={styles.entryHead}><div><h3>{e.full_name}</h3><small>{e.status_reason||`Status updated ${new Date(e.status_changed_at).toLocaleString()}`}</small></div><span className={styles.pill}>{e.employment_status}</span></div><div className={styles.actions}>{e.employment_status!=='active'&&<button className={styles.button} disabled={busy} onClick={()=>changeStatus(e,'active')}>Reactivate</button>}{e.employment_status==='active'&&<button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>changeStatus(e,'suspended')}>Suspend Access</button>}{e.employment_status!=='inactive'&&<button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>changeStatus(e,'inactive')}>Mark Inactive</button>}</div></div>)}{!employees.some(e=>e.user_id)&&<div className={styles.empty}>Linked staff accounts will appear here after profile approval.</div>}</div></section>
  <section className={styles.section}><h2>Approved profiles</h2><div className={styles.list}>{claims.filter(c=>c.status==='approved').map(c=><div className={styles.entry} key={c.id}><div className={styles.entryHead}><div><h3>{c.first_name} {c.last_name}</h3><small>{(selectedRoles[c.id]||[]).map(id=>roles.find(r=>r.id===id)?.name).filter(Boolean).join(' · ')||'No role labels loaded'}</small></div><span className={styles.pill}>verified</span></div></div>)}{!approved&&<div className={styles.empty}>Approved staff will appear here.</div>}</div></section>
  {(changes>0||rejected>0)&&<section className={styles.section}><div className={styles.card}><b>{changes} profile update request{changes===1?'':'s'} · {rejected} rejected setup request{rejected===1?'':'s'}</b><p>Employees can correct and resubmit setup details until a profile is approved.</p></div></section>}
 </main>
}
function Metric({label,value}:{label:string;value:number}){return <div className={styles.metric}><span>{label}</span><strong>{value}</strong></div>}
