'use client';

import { FormEvent, useEffect, useState } from 'react';
import { ArrowLeft, KeyRound, Loader2, Mail, ShieldCheck, Trash2, UserRound } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type Profile={full_name:string|null;app_role:string;location_id:string|null};

export default function AccountPage(){
  const [profile,setProfile]=useState<Profile|null>(null),[email,setEmail]=useState(''),[newEmail,setNewEmail]=useState(''),[password,setPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(true);
  useEffect(()=>{void load()},[]);
  async function load(){const {data:u}=await supabase.auth.getUser();if(!u.user){window.location.href='/';return;}setEmail(u.user.email||'');setNewEmail(u.user.email||'');const {data}=await supabase.from('profiles').select('full_name,app_role,location_id').eq('id',u.user.id).single();setProfile(data as Profile);setLoading(false);}
  function flash(v:string){setMessage(v);setTimeout(()=>setMessage(''),4500)}
  async function changeName(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const full_name=String(fd.get('name')||'').trim();if(!full_name)return;const {data:u}=await supabase.auth.getUser();if(!u.user)return;const {error}=await supabase.from('profiles').update({full_name}).eq('id',u.user.id);if(error)return flash(error.message);await load();flash('Name updated.');}
  async function changeEmail(e:FormEvent){e.preventDefault();if(!newEmail.trim())return;const {error}=await supabase.auth.updateUser({email:newEmail.trim()},{emailRedirectTo:`${location.origin}/account`});flash(error?error.message:'Confirmation links were sent as required. Your email changes after confirmation.');}
  async function changePassword(e:FormEvent){e.preventDefault();if(password.length<8)return flash('Use at least 8 characters.');if(password!==confirmPassword)return flash('Passwords do not match.');const {error}=await supabase.auth.updateUser({password});if(!error){setPassword('');setConfirmPassword('')}flash(error?error.message:'Password changed.');}
  async function resendVerification(){const {error}=await supabase.auth.resend({type:'signup',email});flash(error?error.message:'Verification email sent.');}
  async function deleteAccount(){if(!confirm('This requests permanent deletion of your app account. Continue?'))return;if(!profile?.location_id)return;const {data:u}=await supabase.auth.getUser();if(!u.user)return;await supabase.from('activity_log').insert({location_id:profile.location_id,actor_user_id:u.user.id,action:'account_deletion_requested',entity_type:'profile',entity_id:u.user.id,summary:'User requested account deletion'});flash('Deletion request recorded. An administrator must complete deletion because deleting the authentication identity requires server-level authority.');}
  if(loading)return <div className="full-loader"><Loader2 className="spin"/><span>Loading account…</span></div>;
  return <div className="app-shell"><header className="topbar"><a className="round-button" href="/" aria-label="Back"><ArrowLeft/></a><div style={{flex:1}}><div className="brand-kicker">El Molino Ops</div><div className="brand-title">Account & Security</div></div></header><main className="page">{message&&<div className="toast-message">{message}</div>}<div className="page-heading"><h1>Your account</h1><p>Profile, email, password and account lifecycle.</p></div><div className="settings-card"><form className="setting-form" onSubmit={changeName}><div className="settings-icon"><UserRound/></div><div><b>Display name</b><small>Shown in activity and collaboration</small><input className="input" name="name" defaultValue={profile?.full_name||''}/></div><button className="btn secondary">Save</button></form><div className="setting-form"><div className="settings-icon"><ShieldCheck/></div><div><b>Role</b><small>Your access level is managed by an administrator</small><span className="status">{profile?.app_role}</span></div></div></div><div className="section-title"><h2>Email</h2><span>{email}</span></div><div className="card"><form className="form" onSubmit={changeEmail}><div className="field"><label>New email</label><input className="input" type="email" value={newEmail} onChange={e=>setNewEmail(e.target.value)} required/></div><button className="btn"><Mail size={16}/> Change email</button></form><button className="btn ghost" style={{width:'100%',marginTop:10}} onClick={resendVerification}>Resend verification email</button></div><div className="section-title"><h2>Password</h2><span>security</span></div><div className="card"><form className="form" onSubmit={changePassword}><div className="field"><label>New password</label><input className="input" type="password" autoComplete="new-password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required/></div><div className="field"><label>Confirm password</label><input className="input" type="password" autoComplete="new-password" minLength={8} value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} required/></div><button className="btn"><KeyRound size={16}/> Change password</button></form></div><div className="section-title"><h2>Account lifecycle</h2><span>danger zone</span></div><div className="card"><p style={{marginTop:0}}>Account deletion requires an administrator/server action so restaurant audit history is not silently destroyed.</p><button className="btn" style={{background:'var(--danger)'}} onClick={deleteAccount}><Trash2 size={16}/> Request account deletion</button></div></main></div>;
}
