'use client';

import {FormEvent,useEffect,useMemo,useState} from 'react';
import {ArrowLeft,Bell,Clock3,Coins,KeyRound,Loader2,Mail,ShieldCheck,Trash2,UserRound} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import {normalizedText,strongEnoughPassword,validEmail} from '@/lib/app-hardening';
import {useI18n} from '@/lib/i18n';

type Profile={full_name:string|null;app_role:'admin'|'manager'|'employee';location_id:string|null};
type Setup={status:string;employee_id?:string|null;employment_status?:'active'|'suspended'|'inactive'|null;status_reason?:string|null};
type Role={id:string;name:string;department?:string|null};
type CurrentRole={role_id:string;name:string;department:string|null;skill_level:number};
type RoleRequest={id:string;status:string;employee_note:string|null;manager_note:string|null;submitted_at:string;reviewed_at:string|null;requested_role_ids:string[]};
type RoleProfile={employee_id:string;current_roles:CurrentRole[];latest_request:RoleRequest|null};

export default function AccountPage(){
 const {locale,t}=useI18n();
 const c=locale==='es'?{
  loadError:'No se pudo cargar el perfil de tu cuenta.',nameRequired:'Ingresa un nombre visible.',nameError:'No se pudo actualizar tu nombre.',nameUpdated:'Nombre actualizado.',validEmail:'Ingresa una dirección de correo válida.',sameEmail:'Ese ya es el correo de tu cuenta.',emailError:'No se pudo iniciar el cambio de correo.',emailSent:'Se enviaron los enlaces de confirmación requeridos.',passwordRule:'Usa al menos 10 caracteres con letras y un número.',passwordMismatch:'Las contraseñas no coinciden.',passwordError:'No se pudo cambiar la contraseña.',passwordChanged:'Contraseña cambiada.',emailUnavailable:'El correo actual de tu cuenta no está disponible.',verificationError:'No se pudo reenviar la verificación en este momento.',verificationSent:'Correo de verificación enviado.',deleteConfirm:'¿Registrar una solicitud permanente para eliminar la cuenta?',locationUnavailable:'El perfil de tu ubicación no está disponible.',deleteDuplicate:'Ya existe una solicitud de eliminación registrada.',deleteError:'No se pudo registrar la solicitud de eliminación.',deleteRecorded:'Solicitud de eliminación registrada. Un administrador debe completar la eliminación.',keepRole:'Mantén seleccionado al menos un puesto de trabajo.',rolesSame:'Esos puestos ya coinciden con tus puestos verificados.',roleSent:'Solicitud de cambio de puesto enviada a gerencia.',cancelRole:'¿Cancelar tu solicitud pendiente de cambio de puesto?',roleCancelled:'Solicitud de cambio de puesto cancelada.',staffHelp:'Tus puestos verificados determinan qué funciones pueden usar el horario, la Bolsa de Turnos y los intercambios.',pendingSetup:'configuración pendiente',noRoles:'Aún no hay puestos verificados',chooseJobs:'Elige los trabajos que realmente realizas. Tus puestos verificados actuales siguen siendo los autorizados hasta que gerencia apruebe la solicitud.',changesRequested:'Gerencia solicitó cambios.',lastRejected:'Tu última solicitud de puesto no fue aprobada.',employee:'Empleado',unknown:'desconocido',resend:'Reenviar correo de verificación',deleteAccount:'Solicitar eliminación de la cuenta'
 }:{
  loadError:'Could not load your account profile.',nameRequired:'Enter a display name.',nameError:'Could not update your name.',nameUpdated:'Name updated.',validEmail:'Enter a valid email address.',sameEmail:'That is already your account email.',emailError:'Could not start the email change.',emailSent:'Confirmation links were sent as required.',passwordRule:'Use at least 10 characters with letters and a number.',passwordMismatch:'Passwords do not match.',passwordError:'Could not change the password.',passwordChanged:'Password changed.',emailUnavailable:'Your current account email is unavailable.',verificationError:'Could not resend verification right now.',verificationSent:'Verification email sent.',deleteConfirm:'Record a permanent account deletion request?',locationUnavailable:'Your location profile is unavailable.',deleteDuplicate:'A deletion request is already recorded.',deleteError:'Could not record the deletion request.',deleteRecorded:'Deletion request recorded. An administrator must complete deletion.',keepRole:'Keep at least one job position selected.',rolesSame:'Those positions already match your verified roles.',roleSent:'Position change request sent to management.',cancelRole:'Cancel your pending position change request?',roleCancelled:'Position change request cancelled.',staffHelp:'Your verified positions determine which roles scheduling, Shift Pool and trade matching can use.',pendingSetup:'pending setup',noRoles:'No verified positions yet',chooseJobs:'Choose the jobs you actually work. Your current verified positions stay authoritative until management approves the request.',changesRequested:'Management requested changes.',lastRejected:'Your last position request was not approved.',employee:'Employee',unknown:'unknown',resend:'Resend verification email',deleteAccount:'Request account deletion'
 };
 const [profile,setProfile]=useState<Profile|null>(null),[setup,setSetup]=useState<Setup|null>(null),[email,setEmail]=useState(''),[newEmail,setNewEmail]=useState(''),[password,setPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[roles,setRoles]=useState<Role[]>([]),[roleProfile,setRoleProfile]=useState<RoleProfile|null>(null),[selectedRoles,setSelectedRoles]=useState<string[]>([]),[roleNote,setRoleNote]=useState('');
 useEffect(()=>{void load()},[]);
 async function load(){
  const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}
  setEmail(u.user.email||'');setNewEmail(u.user.email||'');
  const {data,error}=await supabase.from('profiles').select('full_name,app_role,location_id').eq('id',u.user.id).single();
  if(error||!data){setMessage(c.loadError);setLoading(false);return}
  const pr=data as Profile;setProfile(pr);
  if(pr.app_role==='employee'){
   const [st,r,rp]=await Promise.all([supabase.rpc('employee_self_setup_status',{}),supabase.from('employee_roles').select('id,name,department').neq('department','management').order('department').order('name'),supabase.rpc('my_employee_role_profile',{})]);
   const ss=(st.data||{}) as Setup;setSetup(ss);
   if(!r.error)setRoles((r.data??[]) as Role[]);
   if(!rp.error&&rp.data){const value=rp.data as RoleProfile;setRoleProfile(value);const requested=value.latest_request?.status==='pending'?value.latest_request.requested_role_ids:null;setSelectedRoles(requested?.length?requested:value.current_roles.map(x=>x.role_id));setRoleNote(value.latest_request?.status==='pending'?value.latest_request.employee_note||'':'')}
  }
  setLoading(false)
 }
 function flash(v:string){setMessage(v);setTimeout(()=>setMessage(''),4500)}
 async function changeName(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const full_name=normalizedText(new FormData(e.currentTarget).get('name'),120);if(!full_name)return flash(c.nameRequired);setBusy(true);const {data:u}=await supabase.auth.getUser();if(!u.user){setBusy(false);return}const {error}=await supabase.from('profiles').update({full_name}).eq('id',u.user.id);setBusy(false);if(error)return flash(c.nameError);await load();flash(c.nameUpdated)}
 async function changeEmail(e:FormEvent){e.preventDefault();if(busy)return;const next=newEmail.trim().toLowerCase();if(!validEmail(next))return flash(c.validEmail);if(next===email.trim().toLowerCase())return flash(c.sameEmail);setBusy(true);const {error}=await supabase.auth.updateUser({email:next},{emailRedirectTo:`${location.origin}/account`});setBusy(false);flash(error?c.emailError:c.emailSent)}
 async function changePassword(e:FormEvent){e.preventDefault();if(busy)return;if(!strongEnoughPassword(password))return flash(c.passwordRule);if(password!==confirmPassword)return flash(c.passwordMismatch);setBusy(true);const {error}=await supabase.auth.updateUser({password});setBusy(false);if(!error){setPassword('');setConfirmPassword('')}flash(error?c.passwordError:c.passwordChanged)}
 async function resendVerification(){if(busy)return;if(!validEmail(email))return flash(c.emailUnavailable);setBusy(true);const {error}=await supabase.auth.resend({type:'signup',email});setBusy(false);flash(error?c.verificationError:c.verificationSent)}
 async function deleteAccount(){if(busy||!confirm(c.deleteConfirm))return;if(!profile?.location_id)return flash(c.locationUnavailable);const {data:u}=await supabase.auth.getUser();if(!u.user)return;setBusy(true);const {error}=await supabase.from('activity_log').insert({location_id:profile.location_id,actor_user_id:u.user.id,action:'account_deletion_requested',entity_type:'profile',entity_id:u.user.id,summary:'User requested account deletion'});setBusy(false);if(error?.code==='23505')return flash(c.deleteDuplicate);flash(error?c.deleteError:c.deleteRecorded)}
 function toggleRole(id:string){if(roleProfile?.latest_request?.status==='pending'||setup?.employment_status!=='active')return;setSelectedRoles(x=>x.includes(id)?x.filter(v=>v!==id):[...x,id])}
 async function submitRoleChange(){if(busy||setup?.employment_status!=='active')return;if(!selectedRoles.length)return flash(c.keepRole);const current=new Set(roleProfile?.current_roles.map(x=>x.role_id)||[]),next=new Set(selectedRoles);if(current.size===next.size&&[...current].every(x=>next.has(x)))return flash(c.rolesSame);setBusy(true);const {error}=await supabase.rpc('submit_employee_role_change_request',{p_role_ids:selectedRoles,p_employee_note:roleNote.trim()||null});setBusy(false);if(error)return flash(error.message);await load();flash(c.roleSent)}
 async function cancelRoleChange(){const req=roleProfile?.latest_request;if(!req||req.status!=='pending'||busy)return;if(!confirm(c.cancelRole))return;setBusy(true);const {error}=await supabase.rpc('cancel_my_employee_role_change_request',{p_request_id:req.id});setBusy(false);if(error)return flash(error.message);await load();flash(c.roleCancelled)}
 const employee=profile?.app_role==='employee',verifiedRoles=roleProfile?.current_roles||[],pendingRoleRequest=roleProfile?.latest_request?.status==='pending',roleChanges=useMemo(()=>{const current=new Set(verifiedRoles.map(x=>x.role_id)),next=new Set(selectedRoles);return current.size!==next.size||[...current].some(x=>!next.has(x))},[verifiedRoles,selectedRoles]);
 if(loading)return <div className="full-loader"><Loader2 className="spin"/></div>;
 return <div className="app-shell"><header className="topbar"><a className="round-button" href={employee&&setup?.employment_status!=='active'?'/employee/access':employee?'/employee':'/'}><ArrowLeft/></a><div className="brand-title">{t('account.title')}</div></header><main className="page">{message&&<div className="toast-message">{message}</div>}
  {employee&&<div className="card"><h2>{t('account.staffAccount')}</h2><p className="muted">{c.staffHelp}</p><div className="settings-card"><div className="setting-form"><ShieldCheck/><div><b>{t('account.employmentStatus')}</b><span className="status">{setup?.employment_status||c.pendingSetup}{setup?.status_reason?` · ${setup.status_reason}`:''}</span></div></div><div className="setting-form"><ShieldCheck/><div><b>{t('account.verifiedPositions')}</b><span className="status">{verifiedRoles.length?verifiedRoles.map(x=>x.name).join(' · '):c.noRoles}</span></div></div></div>{roles.length>0&&<div style={{marginTop:14}}><h3>{t('account.positionChange')}</h3><p className="muted">{c.chooseJobs}</p><div className="form-grid">{roles.map(r=><label className="checkbox" key={r.id}><input type="checkbox" checked={selectedRoles.includes(r.id)} disabled={Boolean(pendingRoleRequest)||setup?.employment_status!=='active'} onChange={()=>toggleRole(r.id)}/>{r.name}</label>)}</div><label className="form"><span>{t('account.noteForManagement')}</span><textarea className="input" maxLength={2000} disabled={Boolean(pendingRoleRequest)||setup?.employment_status!=='active'} value={roleNote} onChange={e=>setRoleNote(e.target.value)}/></label>{pendingRoleRequest?<div className="notice"><b>{t('account.waitingReview')}</b>{roleProfile?.latest_request?.employee_note?` ${roleProfile.latest_request.employee_note}`:''}<div className="actions"><button className="btn secondary" disabled={busy} onClick={cancelRoleChange}>{t('account.cancelRequest')}</button></div></div>:roleProfile?.latest_request?.status==='changes_requested'?<div className="notice"><b>{c.changesRequested}</b>{roleProfile.latest_request.manager_note?` ${roleProfile.latest_request.manager_note}`:''}</div>:roleProfile?.latest_request?.status==='rejected'?<div className="notice"><b>{c.lastRejected}</b>{roleProfile.latest_request.manager_note?` ${roleProfile.latest_request.manager_note}`:''}</div>:null}<div className="actions"><button className="btn" disabled={busy||Boolean(pendingRoleRequest)||!roleChanges||setup?.employment_status!=='active'} onClick={submitRoleChange}>{t('account.submitPositionChange')}</button></div></div>}<div className="actions"><a className="btn secondary" href="/employee/notifications/preferences"><Bell/> {t('account.notificationPreferences')}</a>{setup?.employment_status==='active'&&<><a className="btn secondary" href="/employee/time-clock"><Clock3/> {t('account.myTimeClock')}</a><a className="btn secondary" href="/employee/tips"><Coins/> {t('account.myTips')}</a></>}</div></div>}
  <div className="settings-card"><form className="setting-form" onSubmit={changeName}><div className="settings-icon"><UserRound/></div><div><b>{t('account.displayName')}</b><input className="input" name="name" maxLength={120} defaultValue={profile?.full_name||''}/></div><button disabled={busy} className="btn secondary">{t('common.save')}</button></form><div className="setting-form"><ShieldCheck/><div><b>{t('account.accountAccess')}</b><span className="status">{employee?c.employee:profile?.app_role||c.unknown}</span></div></div></div>
  <div className="card"><form className="form" onSubmit={changeEmail}><label>{t('account.newEmail')}</label><input className="input" type="email" autoComplete="email" maxLength={254} value={newEmail} onChange={e=>setNewEmail(e.target.value)} required/><button disabled={busy} className="btn"><Mail/> {t('account.changeEmail')}</button></form><button disabled={busy} className="btn ghost" onClick={resendVerification}>{c.resend}</button></div>
  <div className="card"><form className="form" onSubmit={changePassword}><input className="input" aria-label={t('account.newPassword')} type="password" autoComplete="new-password" minLength={10} maxLength={256} value={password} onChange={e=>setPassword(e.target.value)} required/><input className="input" aria-label={t('account.confirmPassword')} type="password" autoComplete="new-password" minLength={10} maxLength={256} value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} required/><button disabled={busy} className="btn"><KeyRound/> {t('account.changePassword')}</button></form></div>
  <div className="card"><button disabled={busy} className="btn" style={{background:'var(--danger)'}} onClick={deleteAccount}><Trash2/> {c.deleteAccount}</button></div>
 </main></div>
}
