'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Clock3, Loader2, Star, StarOff } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type Favorite={entity_type:string;entity_id:string;created_at:string};
type Recent={entity_type:string;entity_id:string;title:string|null;href:string|null;viewed_at:string};
type Resolved={entity_type:string;entity_id:string;title:string;href:string;subtitle?:string};

const routeFor=(type:string,id:string)=>type==='ops_record'?`/ops?record=${id}`:type==='procedure'?`/procedures?record=${id}`:type==='file'?'/files':type==='task'?'/tasks':type==='knowledge'?'/':type==='menu_item'?'/menu':'/';

export default function SavedPage(){
 const [loading,setLoading]=useState(true),[message,setMessage]=useState(''),[favorites,setFavorites]=useState<Favorite[]>([]),[recent,setRecent]=useState<Recent[]>([]),[resolved,setResolved]=useState<Resolved[]>([]),[userId,setUserId]=useState('');
 useEffect(()=>{void load()},[]);
 async function load(){setLoading(true);const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return;}setUserId(u.user.id);const [f,r]=await Promise.all([supabase.from('favorites').select('entity_type,entity_id,created_at').eq('user_id',u.user.id).order('created_at',{ascending:false}),supabase.from('recent_views').select('entity_type,entity_id,title,href,viewed_at').eq('user_id',u.user.id).order('viewed_at',{ascending:false}).limit(100)]);setFavorites((f.data??[]) as Favorite[]);setRecent((r.data??[]) as Recent[]);const rows=(f.data??[]) as Favorite[];const grouped=new Map<string,string[]>();for(const row of rows){const list=grouped.get(row.entity_type)||[];list.push(row.entity_id);grouped.set(row.entity_type,list)}const out:Resolved[]=[];const specs:Record<string,{table:string;title:string;subtitle?:string}>={ops_record:{table:'ops_records',title:'title',subtitle:'kind'},procedure:{table:'procedures',title:'title',subtitle:'status'},file:{table:'files',title:'title',subtitle:'kind'},task:{table:'tasks',title:'title',subtitle:'status'},knowledge:{table:'knowledge_items',title:'title',subtitle:'category'},menu_item:{table:'menu_items',title:'name'}};for(const [type,ids] of grouped){const spec=specs[type];if(!spec)continue;const columns=['id',spec.title,spec.subtitle].filter(Boolean).join(',');const {data}=await supabase.from(spec.table).select(columns).in('id',ids);for(const row of data??[]){const anyRow=row as any;out.push({entity_type:type,entity_id:anyRow.id,title:String(anyRow[spec.title]||'Untitled'),href:routeFor(type,anyRow.id),subtitle:spec.subtitle?String(anyRow[spec.subtitle]||''):undefined})}}setResolved(out);setLoading(false)}
 const favoriteRows=useMemo(()=>favorites.map(f=>({meta:f,item:resolved.find(r=>r.entity_type===f.entity_type&&r.entity_id===f.entity_id)})).filter(x=>x.item),[favorites,resolved]);
 async function removeFavorite(type:string,id:string){const {error}=await supabase.from('favorites').delete().eq('user_id',userId).eq('entity_type',type).eq('entity_id',id);if(error)return setMessage(error.message);await load();setMessage('Removed from saved items.')}
 async function clearRecent(){if(!confirm('Clear your recent history?'))return;const {error}=await supabase.from('recent_views').delete().eq('user_id',userId);if(error)return setMessage(error.message);await load();setMessage('Recent history cleared.')}
 if(loading)return <div className="full-loader"><Loader2 className="spin"/><span>Loading saved items…</span></div>;
 return <div className="app-shell"><header className="topbar"><a className="round-button" href="/tools" aria-label="Back"><ArrowLeft/></a><div style={{flex:1}}><div className="brand-kicker">El Molino Ops</div><div className="brand-title">Saved & Recent</div></div></header><main className="page">{message&&<div className="toast-message">{message}</div>}<div className="page-heading"><h1>Your shortcuts</h1><p>Saved records and recently viewed work, kept out of the main dashboard.</p></div><div className="section-title"><h2>Saved</h2><span>{favoriteRows.length}</span></div>{favoriteRows.length?<div className="list">{favoriteRows.map(({meta,item})=><div className="list-item" key={`${meta.entity_type}-${meta.entity_id}`}><span className="settings-icon"><Star/></span><a className="list-main" href={item!.href}><b>{item!.title}</b><small>{meta.entity_type.replace(/_/g,' ')}{item!.subtitle?` · ${item!.subtitle}`:''}</small></a><button className="icon-action" onClick={()=>removeFavorite(meta.entity_type,meta.entity_id)} aria-label="Remove saved item"><StarOff size={16}/></button></div>)}</div>:<div className="empty-state"><Star/><b>No saved items yet</b><span>Star important records from supported screens to keep them here.</span></div>}<div className="section-title"><h2>Recent</h2><button className="mini-action" onClick={clearRecent}>Clear</button></div>{recent.length?<div className="list">{recent.map(r=><a className="list-item" href={r.href||routeFor(r.entity_type,r.entity_id)} key={`${r.entity_type}-${r.entity_id}`}><span className="settings-icon"><Clock3/></span><span className="list-main"><b>{r.title||r.entity_type.replace(/_/g,' ')}</b><small>{r.entity_type.replace(/_/g,' ')} · {new Date(r.viewed_at).toLocaleString()}</small></span></a>)}</div>:<div className="empty-state"><Clock3/><b>No recent items yet</b><span>Recently opened records will appear here.</span></div>}</main></div>;
}
