'use client';

import { FormEvent, ReactNode, useEffect, useMemo, useState } from 'react';
import {
  Activity, Bell, BookOpen, Bot, Camera, Check, ChevronRight, CircleUserRound,
  ClipboardCheck, FileText, FolderOpen, Globe2, Home, Loader2, Menu as MenuIcon,
  MoreHorizontal, Plus, RefreshCw, Search, Settings, Sparkles, Upload, Users,
  WifiOff, X, LogOut, ShieldCheck, History, CheckCircle2, Circle, Mic, Trash2,
  Download, UserPlus, KeyRound
} from 'lucide-react';
import { supabase } from '@/lib/supabase';

type Tab = 'home' | 'operations' | 'team' | 'ai' | 'more';
type MoreSection = 'root' | 'knowledge' | 'files' | 'activity' | 'settings' | 'admin';
type AIMode = 'auto' | 'internal' | 'web';
type Profile = { full_name: string | null; app_role: 'admin'|'manager'|'employee'; location_id: string | null };
type Area = { id:string; name:string };
type Station = { id:string; name:string; description:string|null; area_id:string };
type KnowledgeItem = { id:string; title:string; content:string; status:string; station_id:string|null; category:string|null; created_at?:string };
type Procedure = { id:string; title:string; description:string|null; status:string; station_id:string|null; created_at?:string };
type Role = { id:string; name:string };
type Employee = { id:string; full_name:string; phone:string|null; active:boolean; start_date?:string|null };
type Task = { id:string; title:string; description:string|null; status:string; priority:string; due_at:string|null; assigned_employee_id:string|null; created_at:string };
type Notice = { id:string; title:string; body:string|null; href:string|null; read_at:string|null; created_at:string; type:string };
type ActivityRow = { id:string; action:string; summary:string|null; entity_type:string|null; created_at:string };
type FileRow = { id:string; file_name:string; kind:string; title:string|null; mime_type:string|null; size_bytes:number|null; storage_path:string; created_at:string };
type Prefs = { remember_email:boolean; email_notifications:boolean; push_notifications:boolean; in_app_notifications:boolean; reduced_motion:boolean; compact_mode:boolean; theme:'system'|'light'|'dark'; locale:string };
type SearchResult = { entity_type:string; entity_id:string; title:string; subtitle:string; href:string; rank:number };
type AIConversation = { id:string; title:string; source_mode:AIMode; updated_at:string };
type AIMessage = { id:string; role:'user'|'assistant'; content:string; source_label:string|null; feedback:number|null; created_at:string };

const defaultPrefs: Prefs = { remember_email:true, email_notifications:true, push_notifications:true, in_app_notifications:true, reduced_motion:false, compact_mode:false, theme:'system', locale:'en-US' };

export default function AppPage() {
  const [ready,setReady]=useState(false);
  const [signedIn,setSignedIn]=useState(false);
  const [loading,setLoading]=useState(false);
  const [profile,setProfile]=useState<Profile|null>(null);
  const [userEmail,setUserEmail]=useState('');
  const [tab,setTab]=useState<Tab>('home');
  const [moreSection,setMoreSection]=useState<MoreSection>('root');
  const [message,setMessage]=useState('');
  const [online,setOnline]=useState(true);
  const [showOnboarding,setShowOnboarding]=useState(false);
  const [showAccount,setShowAccount]=useState(false);
  const [showSearch,setShowSearch]=useState(false);
  const [showNotices,setShowNotices]=useState(false);

  const [email,setEmail]=useState('');
  const [password,setPassword]=useState('');
  const [fullName,setFullName]=useState('');
  const [authMode,setAuthMode]=useState<'signin'|'signup'>('signin');
  const [authBusy,setAuthBusy]=useState(false);

  const [areas,setAreas]=useState<Area[]>([]);
  const [stations,setStations]=useState<Station[]>([]);
  const [knowledge,setKnowledge]=useState<KnowledgeItem[]>([]);
  const [procedures,setProcedures]=useState<Procedure[]>([]);
  const [roles,setRoles]=useState<Role[]>([]);
  const [employees,setEmployees]=useState<Employee[]>([]);
  const [tasks,setTasks]=useState<Task[]>([]);
  const [notices,setNotices]=useState<Notice[]>([]);
  const [activity,setActivity]=useState<ActivityRow[]>([]);
  const [files,setFiles]=useState<FileRow[]>([]);
  const [prefs,setPrefs]=useState<Prefs>(defaultPrefs);

  const [stationName,setStationName]=useState('');
  const [stationDescription,setStationDescription]=useState('');
  const [selectedStation,setSelectedStation]=useState('');
  const [knowledgeTitle,setKnowledgeTitle]=useState('');
  const [knowledgeContent,setKnowledgeContent]=useState('');
  const [procedureTitle,setProcedureTitle]=useState('');
  const [procedureDescription,setProcedureDescription]=useState('');
  const [employeeName,setEmployeeName]=useState('');
  const [employeePhone,setEmployeePhone]=useState('');
  const [taskTitle,setTaskTitle]=useState('');
  const [taskDue,setTaskDue]=useState('');

  const canManage=profile?.app_role==='admin'||profile?.app_role==='manager';
  const kitchenArea=useMemo(()=>areas.find(a=>a.name==='Kitchen'),[areas]);
  const unreadCount=notices.filter(n=>!n.read_at).length;
  const openTasks=tasks.filter(t=>!['done','cancelled'].includes(t.status));

  useEffect(()=>{
    const remembered=localStorage.getItem('elmolino_email');
    if(remembered)setEmail(remembered);
    setShowOnboarding(localStorage.getItem('elmolino_onboarded')!=='1');
    const qs=new URLSearchParams(window.location.search); const requested=qs.get('tab') as Tab|null;
    if(requested&&['home','operations','team','ai','more'].includes(requested))setTab(requested);
    const sync=()=>setOnline(navigator.onLine); sync();
    window.addEventListener('online',sync);window.addEventListener('offline',sync);
    supabase.auth.getSession().then(({data})=>{setSignedIn(Boolean(data.session));setReady(true);if(data.session)void loadAll();});
    const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>{setSignedIn(Boolean(s));if(s)void loadAll();else{setProfile(null);setUserEmail('');}});
    return()=>{l.subscription.unsubscribe();window.removeEventListener('online',sync);window.removeEventListener('offline',sync);};
  },[]);

  useEffect(()=>{
    if(!ready)return;
    const draft=localStorage.getItem('elmolino_knowledge_draft');
    if(draft&&!knowledgeContent){try{const d=JSON.parse(draft);setKnowledgeTitle(d.title||'');setKnowledgeContent(d.content||'');}catch{}}
  },[ready]);
  useEffect(()=>{if(knowledgeTitle||knowledgeContent)localStorage.setItem('elmolino_knowledge_draft',JSON.stringify({title:knowledgeTitle,content:knowledgeContent}));},[knowledgeTitle,knowledgeContent]);
  useEffect(()=>{document.documentElement.dataset.theme=prefs.theme;document.documentElement.dataset.compact=String(prefs.compact_mode);document.documentElement.dataset.motion=prefs.reduced_motion?'reduced':'normal';},[prefs]);

  async function loadAll(){
    setLoading(true);setMessage('');
    const {data:a}=await supabase.auth.getUser();if(!a.user){setLoading(false);return;}
    setUserEmail(a.user.email||'');
    const [p,ar,st,k,pr,r,e,t,n,ac,f,pref]=await Promise.all([
      supabase.from('profiles').select('full_name,app_role,location_id').eq('id',a.user.id).single(),
      supabase.from('areas').select('id,name').order('name'),
      supabase.from('stations').select('id,name,description,area_id').order('created_at',{ascending:false}),
      supabase.from('knowledge_items').select('id,title,content,status,station_id,category,created_at').is('deleted_at',null).order('created_at',{ascending:false}).limit(200),
      supabase.from('procedures').select('id,title,description,status,station_id,created_at').is('deleted_at',null).order('created_at',{ascending:false}).limit(100),
      supabase.from('employee_roles').select('id,name').order('name'),
      supabase.from('employees').select('id,full_name,phone,active,start_date').is('deleted_at',null).order('full_name'),
      supabase.from('tasks').select('id,title,description,status,priority,due_at,assigned_employee_id,created_at').is('deleted_at',null).order('created_at',{ascending:false}).limit(100),
      supabase.from('notifications').select('id,title,body,href,read_at,created_at,type').order('created_at',{ascending:false}).limit(50),
      supabase.from('activity_log').select('id,action,summary,entity_type,created_at').order('created_at',{ascending:false}).limit(80),
      supabase.from('files').select('id,file_name,kind,title,mime_type,size_bytes,storage_path,created_at').is('deleted_at',null).order('created_at',{ascending:false}).limit(100),
      supabase.from('user_preferences').select('remember_email,email_notifications,push_notifications,in_app_notifications,reduced_motion,compact_mode,theme,locale').eq('user_id',a.user.id).maybeSingle()
    ]);
    if(p.error)setMessage(p.error.message);
    if(p.data)setProfile(p.data as Profile);
    setAreas((ar.data??[]) as Area[]);setStations((st.data??[]) as Station[]);setKnowledge((k.data??[]) as KnowledgeItem[]);setProcedures((pr.data??[]) as Procedure[]);setRoles((r.data??[]) as Role[]);setEmployees((e.data??[]) as Employee[]);setTasks((t.data??[]) as Task[]);setNotices((n.data??[]) as Notice[]);setActivity((ac.data??[]) as ActivityRow[]);setFiles((f.data??[]) as FileRow[]);if(pref.data)setPrefs(pref.data as Prefs);
    setLoading(false);
  }

  async function logActivity(action:string,entityType:string,entityId:string|null,summary:string){
    const {data:u}=await supabase.auth.getUser();if(!u.user||!profile?.location_id)return;
    await supabase.from('activity_log').insert({location_id:profile.location_id,actor_user_id:u.user.id,action,entity_type:entityType,entity_id:entityId,summary});
  }
  function flash(text:string){setMessage(text);window.setTimeout(()=>setMessage(''),3500);}
  async function auth(e:FormEvent){
    e.preventDefault();setAuthBusy(true);setMessage('');
    try{
      if(authMode==='signup'){
        const {error}=await supabase.auth.signUp({email,password,options:{data:{full_name:fullName}}});if(error)throw error;
        flash('Account created. Confirm your email if prompted, then sign in.');
      }else{
        const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;
        if(prefs.remember_email!==false)localStorage.setItem('elmolino_email',email);
      }
    }catch(err){setMessage(err instanceof Error?err.message:'Could not sign in.');}finally{setAuthBusy(false);}
  }
  async function forgotPassword(){if(!email)return flash('Enter your email first.');const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/`});flash(error?error.message:'Password reset email sent.');}
  async function updateName(){if(!profile)return;const name=prompt('Your name',profile.full_name||'');if(!name?.trim())return;const {data:u}=await supabase.auth.getUser();if(!u.user)return;const {error}=await supabase.from('profiles').update({full_name:name.trim()}).eq('id',u.user.id);if(error)return flash(error.message);await loadAll();flash('Profile updated.');}
  async function updatePrefs(patch:Partial<Prefs>){const {data:u}=await supabase.auth.getUser();if(!u.user)return;const next={...prefs,...patch};setPrefs(next);const {error}=await supabase.from('user_preferences').upsert({user_id:u.user.id,...next,updated_at:new Date().toISOString()});if(error)flash(error.message);if(!next.remember_email)localStorage.removeItem('elmolino_email');else if(userEmail)localStorage.setItem('elmolino_email',userEmail);}

  async function createStation(e:FormEvent){e.preventDefault();if(!kitchenArea||!stationName.trim())return;const {data,error}=await supabase.from('stations').insert({area_id:kitchenArea.id,name:stationName.trim(),description:stationDescription.trim()||null}).select('id').single();if(error)return flash(error.message);setStationName('');setStationDescription('');await logActivity('created','station',data.id,`Created station ${stationName}`);await loadAll();flash('Station added.');}
  async function createKnowledge(e:FormEvent){e.preventDefault();if(!profile?.location_id||!knowledgeTitle.trim()||!knowledgeContent.trim())return;const st=stations.find(s=>s.id===selectedStation);const {data,error}=await supabase.from('knowledge_items').insert({location_id:profile.location_id,area_id:st?.area_id??kitchenArea?.id??null,station_id:selectedStation||null,title:knowledgeTitle.trim(),content:knowledgeContent.trim(),category:'operational_knowledge',status:'draft'}).select('id').single();if(error)return flash(error.message);await logActivity('created','knowledge',data.id,`Added knowledge: ${knowledgeTitle}`);setKnowledgeTitle('');setKnowledgeContent('');localStorage.removeItem('elmolino_knowledge_draft');await loadAll();flash('Knowledge draft saved.');}
  async function approveKnowledge(id:string){const {data:a}=await supabase.auth.getUser();if(!a.user)return;const item=knowledge.find(k=>k.id===id);const {error}=await supabase.from('knowledge_items').update({status:'approved',approved_by:a.user.id,approved_at:new Date().toISOString()}).eq('id',id);if(error)return flash(error.message);await logActivity('approved','knowledge',id,`Approved knowledge: ${item?.title||id}`);await loadAll();flash('Knowledge approved.');}
  async function softDeleteKnowledge(id:string){if(!confirm('Move this knowledge record to trash?'))return;const item=knowledge.find(k=>k.id===id);const {error}=await supabase.from('knowledge_items').update({deleted_at:new Date().toISOString()}).eq('id',id);if(error)return flash(error.message);await logActivity('deleted','knowledge',id,`Moved ${item?.title||'knowledge'} to trash`);await loadAll();flash('Moved to trash.');}
  async function createProcedure(e:FormEvent){e.preventDefault();if(!profile?.location_id||!procedureTitle.trim())return;const st=stations.find(s=>s.id===selectedStation);const {data,error}=await supabase.from('procedures').insert({location_id:profile.location_id,area_id:st?.area_id??kitchenArea?.id??null,station_id:selectedStation||null,title:procedureTitle.trim(),description:procedureDescription.trim()||null,status:'draft'}).select('id').single();if(error)return flash(error.message);await logActivity('created','procedure',data.id,`Created procedure ${procedureTitle}`);setProcedureTitle('');setProcedureDescription('');await loadAll();flash('Procedure draft created.');}
  async function createEmployee(e:FormEvent){e.preventDefault();if(!profile?.location_id||!employeeName.trim())return;const {data,error}=await supabase.from('employees').insert({location_id:profile.location_id,full_name:employeeName.trim(),phone:employeePhone.trim()||null}).select('id').single();if(error)return flash(error.message);await logActivity('created','employee',data.id,`Added ${employeeName}`);setEmployeeName('');setEmployeePhone('');await loadAll();flash('Team member added.');}
  async function createTask(e:FormEvent){e.preventDefault();if(!profile?.location_id||!taskTitle.trim())return;const {data:u}=await supabase.auth.getUser();if(!u.user)return;const {data,error}=await supabase.from('tasks').insert({location_id:profile.location_id,title:taskTitle.trim(),due_at:taskDue?new Date(taskDue).toISOString():null,created_by:u.user.id}).select('id').single();if(error)return flash(error.message);await logActivity('created','task',data.id,`Created task ${taskTitle}`);setTaskTitle('');setTaskDue('');await loadAll();flash('Task created.');}
  async function toggleTask(task:Task){const done=task.status!=='done';const {error}=await supabase.from('tasks').update({status:done?'done':'open',completed_at:done?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq('id',task.id);if(error)return flash(error.message);await logActivity(done?'completed':'reopened','task',task.id,`${done?'Completed':'Reopened'} task ${task.title}`);await loadAll();}
  async function uploadFile(file:File){if(!profile?.location_id)return;const {data:u}=await supabase.auth.getUser();if(!u.user)return;const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=`${profile.location_id}/${u.user.id}/${Date.now()}-${safe}`;flash(`Uploading ${file.name}…`);const up=await supabase.storage.from('el-molino-files').upload(path,file,{upsert:false});if(up.error)return flash(up.error.message);const kind=file.type.startsWith('image/')?'photo':file.type.startsWith('video/')?'video':file.type.startsWith('audio/')?'audio':file.type.includes('spreadsheet')||file.name.endsWith('.csv')?'spreadsheet':file.type==='application/pdf'?'document':'file';const {data,error}=await supabase.from('files').insert({location_id:profile.location_id,uploaded_by:u.user.id,file_name:file.name,mime_type:file.type,size_bytes:file.size,storage_path:path,kind,title:file.name}).select('id').single();if(error)return flash(error.message);await logActivity('uploaded','file',data.id,`Uploaded ${file.name}`);await loadAll();flash('Upload complete.');}
  async function openFile(row:FileRow){const {data,error}=await supabase.storage.from('el-molino-files').createSignedUrl(row.storage_path,300);if(error)return flash(error.message);window.open(data.signedUrl,'_blank','noopener,noreferrer');}
  async function markNotice(n:Notice){if(!n.read_at)await supabase.from('notifications').update({read_at:new Date().toISOString()}).eq('id',n.id);setShowNotices(false);if(n.href)window.location.href=n.href;else await loadAll();}

  if(!ready)return <FullLoader />;
  if(!signedIn)return <AuthScreen {...{email,setEmail,password,setPassword,fullName,setFullName,authMode,setAuthMode,authBusy,message,auth,forgotPassword}} />;

  return <div className="app-shell">
    {!online&&<div className="offline-banner"><WifiOff size={15}/> Offline — cached screens remain available; changes may need a connection.</div>}
    <header className="topbar">
      <div><div className="brand-kicker">El Molino Taqueria</div><div className="brand-title">Johns Island</div></div>
      <div className="top-actions">
        <button className="round-button" aria-label="Search" onClick={()=>setShowSearch(true)}><Search size={19}/></button>
        <button className="round-button badge-button" aria-label="Notifications" onClick={()=>setShowNotices(true)}><Bell size={19}/>{unreadCount>0&&<span className="badge-count">{unreadCount>9?'9+':unreadCount}</span>}</button>
        <button className="avatar" aria-label="Account" onClick={()=>setShowAccount(true)}>{(profile?.full_name||'D').slice(0,1).toUpperCase()}</button>
      </div>
    </header>
    <main className="page" aria-busy={loading}>
      {message&&<div className="toast-message">{message}</div>}
      {loading&&<div className="inline-loading"><Loader2 className="spin" size={16}/> Syncing…</div>}
      {tab==='home'&&<HomeView profile={profile} tasks={openTasks} activity={activity} setTab={setTab} toggleTask={toggleTask}/>} 
      {tab==='operations'&&<OperationsView canManage={canManage} stations={stations} selectedStation={selectedStation} setSelectedStation={setSelectedStation} procedureTitle={procedureTitle} setProcedureTitle={setProcedureTitle} procedureDescription={procedureDescription} setProcedureDescription={setProcedureDescription} procedures={procedures} createProcedure={createProcedure} tasks={tasks} taskTitle={taskTitle} setTaskTitle={setTaskTitle} taskDue={taskDue} setTaskDue={setTaskDue} createTask={createTask} toggleTask={toggleTask}/>} 
      {tab==='team'&&<TeamView canManage={canManage} employeeName={employeeName} setEmployeeName={setEmployeeName} employeePhone={employeePhone} setEmployeePhone={setEmployeePhone} employees={employees} roles={roles} createEmployee={createEmployee}/>} 
      {tab==='ai'&&<AIView profile={profile} knowledge={knowledge} procedures={procedures}/>} 
      {tab==='more'&&<MoreView section={moreSection} setSection={setMoreSection} canManage={canManage} stations={stations} stationName={stationName} setStationName={setStationName} stationDescription={stationDescription} setStationDescription={setStationDescription} selectedStation={selectedStation} setSelectedStation={setSelectedStation} knowledgeTitle={knowledgeTitle} setKnowledgeTitle={setKnowledgeTitle} knowledgeContent={knowledgeContent} setKnowledgeContent={setKnowledgeContent} knowledge={knowledge} createStation={createStation} createKnowledge={createKnowledge} approveKnowledge={approveKnowledge} softDeleteKnowledge={softDeleteKnowledge} files={files} uploadFile={uploadFile} openFile={openFile} activity={activity} prefs={prefs} updatePrefs={updatePrefs} profile={profile}/>} 
    </main>
    <nav className="tabs" aria-label="Primary navigation">
      <TabButton label="Today" active={tab==='home'} onClick={()=>setTab('home')} icon={<Home size={19}/>}/>
      <TabButton label="Work" active={tab==='operations'} onClick={()=>setTab('operations')} icon={<ClipboardCheck size={19}/>}/>
      <TabButton label="Team" active={tab==='team'} onClick={()=>setTab('team')} icon={<Users size={19}/>}/>
      <TabButton label="Ask AI" active={tab==='ai'} onClick={()=>setTab('ai')} icon={<Bot size={19}/>}/>
      <TabButton label="More" active={tab==='more'} onClick={()=>{setTab('more');setMoreSection('root')}} icon={<MoreHorizontal size={19}/>}/>
    </nav>
    {showSearch&&<SearchSheet onClose={()=>setShowSearch(false)}/>} 
    {showNotices&&<NotificationSheet notices={notices} onClose={()=>setShowNotices(false)} onOpen={markNotice}/>} 
    {showAccount&&<AccountSheet profile={profile} email={userEmail} onClose={()=>setShowAccount(false)} updateName={updateName} onSignOut={()=>supabase.auth.signOut()}/>} 
    {showOnboarding&&<Onboarding onDone={()=>{localStorage.setItem('elmolino_onboarded','1');setShowOnboarding(false)}}/>}
  </div>;
}

function AuthScreen(p:any){return <main className="auth-wrap"><div className="auth-card"><div className="brand-kicker">Johns Island</div><h1>El Molino Ops</h1><p>One private workspace for the restaurant. Your session stays signed in on this device until you sign out.</p><form className="form" onSubmit={p.auth}>{p.authMode==='signup'&&<div className="field"><label>Name</label><input className="input" autoComplete="name" value={p.fullName} onChange={(e:any)=>p.setFullName(e.target.value)} required/></div>}<div className="field"><label>Email</label><input className="input" type="email" autoComplete="email" value={p.email} onChange={(e:any)=>p.setEmail(e.target.value)} required/></div><div className="field"><label>Password</label><input className="input" type="password" autoComplete={p.authMode==='signin'?'current-password':'new-password'} minLength={8} value={p.password} onChange={(e:any)=>p.setPassword(e.target.value)} required/></div><div className="remember-row"><Check size={15}/><span>Remember me on this device</span></div><button className="btn" disabled={p.authBusy}>{p.authBusy?<><Loader2 className="spin" size={16}/> Working…</>:p.authMode==='signup'?'Create account':'Sign in'}</button></form>{p.message&&<div className="notice" style={{marginTop:12}}>{p.message}</div>}<div className="auth-links"><button onClick={()=>p.setAuthMode(p.authMode==='signup'?'signin':'signup')}>{p.authMode==='signup'?'I already have an account':'Create account'}</button>{p.authMode==='signin'&&<button onClick={p.forgotPassword}>Forgot password?</button>}</div></div></main>}

function HomeView({profile,tasks,activity,setTab,toggleTask}:{profile:Profile|null;tasks:Task[];activity:ActivityRow[];setTab:(t:Tab)=>void;toggleTask:(t:Task)=>void}){const hr=new Date().getHours();const greeting=hr<12?'Good morning':hr<17?'Good afternoon':'Good evening';return <><section className="hero home-hero"><div className="brand-kicker hero-kicker">{profile?.app_role||'member'}</div><h1>{greeting}.</h1><p>Your day at Johns Island — work first, system details stay out of the way.</p><button className="hero-action" onClick={()=>setTab('ai')}><Sparkles size={17}/> Ask El Molino</button></section><div className="section-title"><h2>Today</h2><span>{tasks.length} open</span></div>{tasks.length?<div className="list">{tasks.slice(0,5).map(t=><button className="list-item" key={t.id} onClick={()=>toggleTask(t)}><div className="icon-wrap">{t.status==='done'?<CheckCircle2 size={18}/>:<Circle size={18}/>}</div><div className="list-main"><b>{t.title}</b><small>{formatDue(t.due_at)} · {t.priority}</small></div><ChevronRight size={17} className="muted-icon"/></button>)}</div>:<EmptyState icon={<CheckCircle2 size={24}/>} title="Nothing assigned yet" body="Tasks, checklists and shift duties will appear here."/>}<div className="section-title"><h2>Quick actions</h2><span>run the shift</span></div><div className="quick-grid"><button className="quick-card" onClick={()=>setTab('operations')}><ClipboardCheck/><b>Work</b><small>Tasks & procedures</small></button><button className="quick-card" onClick={()=>setTab('team')}><Users/><b>Team</b><small>People & training</small></button><a className="quick-card" href="/menu"><MenuIcon/><b>Menu</b><small>Catalog</small></a><button className="quick-card" onClick={()=>setTab('ai')}><Bot/><b>Ask AI</b><small>Internal + El Molino web</small></button></div>{activity.length>0&&<><div className="section-title"><h2>Recent</h2><span>activity</span></div><div className="list">{activity.slice(0,4).map(a=><div className="list-item" key={a.id}><div className="icon-wrap"><History size={17}/></div><div className="list-main"><b>{a.summary||a.action}</b><small>{timeAgo(a.created_at)}</small></div></div>)}</div></>}</>}

function OperationsView(p:any){return <><PageHeading title="Work" subtitle="Tasks, procedures and repeatable shift execution"/><div className="segmented-summary"><div><strong>{p.tasks.filter((t:Task)=>!['done','cancelled'].includes(t.status)).length}</strong><span>Open tasks</span></div><div><strong>{p.procedures.length}</strong><span>Procedures</span></div></div>{p.canManage&&<div className="card" style={{marginBottom:12}}><h3>Quick task</h3><form className="form" onSubmit={p.createTask}><input className="input" placeholder="What needs to get done?" value={p.taskTitle} onChange={(e:any)=>p.setTaskTitle(e.target.value)} required/><input className="input" type="datetime-local" value={p.taskDue} onChange={(e:any)=>p.setTaskDue(e.target.value)}/><button className="btn"><Plus size={16}/> Add task</button></form></div>}<div className="section-title"><h2>Tasks</h2><span>tap to complete</span></div>{p.tasks.length?<div className="list">{p.tasks.map((t:Task)=><button className={`list-item ${t.status==='done'?'completed-row':''}`} key={t.id} onClick={()=>p.toggleTask(t)}><div className="icon-wrap">{t.status==='done'?<CheckCircle2 size={18}/>:<Circle size={18}/>}</div><div className="list-main"><b>{t.title}</b><small>{formatDue(t.due_at)} · {t.priority}</small></div><span className="status">{t.status.replaceAll('_',' ')}</span></button>)}</div>:<EmptyState icon={<ClipboardCheck/>} title="No tasks yet" body="Create a task or later generate duties from approved procedures."/>}{p.canManage&&<><div className="section-title"><h2>Procedure builder</h2><span>manager</span></div><div className="card"><form className="form" onSubmit={p.createProcedure}><select className="select" value={p.selectedStation} onChange={(e:any)=>p.setSelectedStation(e.target.value)}><option value="">General / no station</option>{p.stations.map((s:Station)=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input className="input" placeholder="Procedure title" value={p.procedureTitle} onChange={(e:any)=>p.setProcedureTitle(e.target.value)} required/><textarea className="textarea" placeholder="Describe the process" value={p.procedureDescription} onChange={(e:any)=>p.setProcedureDescription(e.target.value)}/><button className="btn">Save procedure draft</button></form></div></>}<div className="section-title"><h2>Procedures</h2><span>{p.procedures.length}</span></div>{p.procedures.length?<div className="list">{p.procedures.map((x:Procedure)=><div className="list-item" key={x.id}><div className="icon-wrap"><ClipboardCheck size={18}/></div><div className="list-main"><b>{x.title}</b><small>{x.description||'No description yet'}</small></div><span className="status">{x.status}</span></div>)}</div>:<EmptyState icon={<FileText/>} title="No procedures yet" body="Approved restaurant knowledge can be turned into procedures here."/>}</>}

function TeamView(p:any){return <><PageHeading title="Team" subtitle="People, roles and training records"/>{p.canManage&&<div className="card" style={{marginBottom:14}}><h3>Add team member</h3><form className="form" onSubmit={p.createEmployee}><input className="input" placeholder="Full name" value={p.employeeName} onChange={(e:any)=>p.setEmployeeName(e.target.value)} required/><input className="input" inputMode="tel" placeholder="Phone" value={p.employeePhone} onChange={(e:any)=>p.setEmployeePhone(e.target.value)}/><button className="btn"><UserPlus size={16}/> Add employee</button></form></div>}<div className="section-title"><h2>Roster</h2><span>{p.employees.length} people</span></div>{p.employees.length?<div className="list">{p.employees.map((e:Employee)=><div className="list-item" key={e.id}><div className="person-avatar">{e.full_name.slice(0,1).toUpperCase()}</div><div className="list-main"><b>{e.full_name}</b><small>{e.phone||'No phone added'}{e.start_date?` · Started ${new Date(e.start_date).toLocaleDateString()}`:''}</small></div><span className="status">{e.active?'Active':'Inactive'}</span></div>)}</div>:<EmptyState icon={<Users/>} title="No team added yet" body="Add the roster first; roles, training and assignments build on it."/>}</>}

function AIView({profile,knowledge,procedures}:{profile:Profile|null;knowledge:KnowledgeItem[];procedures:Procedure[]}){
  const [q,setQ]=useState(''),[busy,setBusy]=useState(false),[mode,setMode]=useState<AIMode>('auto');
  const [convos,setConvos]=useState<AIConversation[]>([]),[current,setCurrent]=useState<string|null>(null),[msgs,setMsgs]=useState<AIMessage[]>([]),[showHistory,setShowHistory]=useState(false);
  useEffect(()=>{void loadConvos()},[]);
  async function loadConvos(){const {data}=await supabase.from('ai_conversations').select('id,title,source_mode,updated_at').eq('archived',false).order('updated_at',{ascending:false}).limit(30);setConvos((data??[]) as AIConversation[]);}
  async function openConvo(id:string){setCurrent(id);setShowHistory(false);const {data}=await supabase.from('ai_messages').select('id,role,content,source_label,feedback,created_at').eq('conversation_id',id).in('role',['user','assistant']).order('created_at');setMsgs((data??[]) as AIMessage[]);const c=convos.find(x=>x.id===id);if(c)setMode(c.source_mode);}
  function newConvo(){setCurrent(null);setMsgs([]);setQ('');setShowHistory(false);}
  async function ask(e:FormEvent){e.preventDefault();const question=q.trim();if(!question||!profile?.location_id)return;setBusy(true);setQ('');try{const {data:u}=await supabase.auth.getUser();if(!u.user)return;let id=current;if(!id){const {data:c,error}=await supabase.from('ai_conversations').insert({location_id:profile.location_id,user_id:u.user.id,title:question.slice(0,60),source_mode:mode}).select('id').single();if(error)throw error;id=c.id;setCurrent(id);await loadConvos();}const optimistic:AIMessage={id:`local-${Date.now()}`,role:'user',content:question,source_label:null,feedback:null,created_at:new Date().toISOString()};setMsgs(m=>[...m,optimistic]);await supabase.from('ai_messages').insert({conversation_id:id,role:'user',content:question});const r=await fetch('/api/ask',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({question,mode,knowledge,procedures})});const j=await r.json();const text=j.answer||'I could not answer that.';const source=j.source||'Assistant';const {data:am}=await supabase.from('ai_messages').insert({conversation_id:id,role:'assistant',content:text,source_label:source}).select('id,role,content,source_label,feedback,created_at').single();await supabase.from('ai_conversations').update({source_mode:mode,updated_at:new Date().toISOString()}).eq('id',id);if(am)setMsgs(m=>[...m,am as AIMessage]);await loadConvos();}catch(err){setMsgs(m=>[...m,{id:`err-${Date.now()}`,role:'assistant',content:err instanceof Error?err.message:'The assistant could not connect.',source_label:'Assistant error',feedback:null,created_at:new Date().toISOString()}]);}finally{setBusy(false);}}
  async function feedback(m:AIMessage,val:1|-1){if(m.id.startsWith('local')||m.id.startsWith('err'))return;await supabase.from('ai_messages').update({feedback:val}).eq('id',m.id);setMsgs(rows=>rows.map(x=>x.id===m.id?{...x,feedback:val}:x));}
  return <><div className="ai-header"><div><h2>Ask El Molino</h2><p>Internal knowledge first. Web access is restricted to El Molino.</p></div><button className="round-button" aria-label="Conversation history" onClick={()=>setShowHistory(!showHistory)}><History size={19}/></button></div>{showHistory&&<div className="card history-card"><button className="btn secondary" onClick={newConvo}><Plus size={15}/> New conversation</button><div className="history-list">{convos.map(c=><button key={c.id} onClick={()=>openConvo(c.id)}><b>{c.title}</b><small>{c.source_mode} · {timeAgo(c.updated_at)}</small></button>)}{!convos.length&&<small>No previous conversations.</small>}</div></div>}<div className="source-switch">{(['auto','internal','web'] as AIMode[]).map(m=><button key={m} className={mode===m?'active':''} onClick={()=>setMode(m)}>{m==='auto'?'Auto':m==='internal'?'Internal':'El Molino Web'}</button>)}</div><div className="chat"><div className="assistant-intro"><Sparkles size={18}/><div><b>What do you need?</b><span>I can explain what I can do even before the restaurant has taught me a specific procedure.</span></div></div>{msgs.map(m=><div className={`chat-row ${m.role}`} key={m.id}><div className="bubble">{m.source_label&&m.role==='assistant'&&<small className="source-label">{m.source_label}</small>}<div>{m.content}</div>{m.role==='assistant'&&<div className="feedback-row"><button aria-label="Helpful" className={m.feedback===1?'selected':''} onClick={()=>feedback(m,1)}>Helpful</button><button aria-label="Not helpful" className={m.feedback===-1?'selected':''} onClick={()=>feedback(m,-1)}>Needs work</button></div>}</div></div>)}{busy&&<div className="chat-row assistant"><div className="bubble"><Loader2 className="spin" size={17}/> Thinking…</div></div>}</div><form className="ai-composer" onSubmit={ask}><textarea value={q} onChange={e=>setQ(e.target.value)} placeholder="Ask about El Molino…" aria-label="Ask El Molino AI"/><button disabled={busy||!q.trim()}><Sparkles size={18}/></button></form></>}

function MoreView(p:any){if(p.section!=='root')return <MoreDetail {...p}/>;return <><PageHeading title="More" subtitle="Tools and administration that stay out of your main workflow"/><div className="settings-list"><MoreLink icon={<BookOpen/>} title="Knowledge Studio" body="Stations, internal knowledge and public research" onClick={()=>p.setSection('knowledge')}/><a className="settings-row" href="/menu"><span className="settings-icon"><MenuIcon/></span><span><b>Menu Catalog</b><small>Structured products, categories and prices</small></span><ChevronRight/></a><MoreLink icon={<FolderOpen/>} title="Files & Media" body="Photos, documents, audio, video and spreadsheets" onClick={()=>p.setSection('files')}/><MoreLink icon={<Activity/>} title="Activity" body="Who changed what and when" onClick={()=>p.setSection('activity')}/><MoreLink icon={<Settings/>} title="Settings" body="Account, notifications, accessibility and app preferences" onClick={()=>p.setSection('settings')}/>{p.profile?.app_role==='admin'&&<MoreLink icon={<ShieldCheck/>} title="Admin Center" body="System data, users and app health" onClick={()=>p.setSection('admin')}/>}</div><div className="install-note"><Download size={18}/><div><b>Install as an app</b><small>On iPhone: Share → Add to Home Screen. Your login remains attached to the permanent app URL.</small></div></div></>}

function MoreDetail(p:any){return <><button className="back-link" onClick={()=>p.setSection('root')}>‹ More</button>{p.section==='knowledge'&&<KnowledgeSection {...p}/>} {p.section==='files'&&<FilesSection files={p.files} uploadFile={p.uploadFile} openFile={p.openFile}/>} {p.section==='activity'&&<ActivitySection rows={p.activity}/>} {p.section==='settings'&&<SettingsSection prefs={p.prefs} updatePrefs={p.updatePrefs}/>} {p.section==='admin'&&<AdminSection knowledge={p.knowledge} stations={p.stations} files={p.files} activity={p.activity}/>}</>}

function KnowledgeSection(p:any){return <><PageHeading title="Knowledge Studio" subtitle="Backend knowledge is managed here, not on the home screen"/>{p.canManage&&<><div className="card" style={{marginBottom:12}}><h3>Add kitchen station</h3><form className="form" onSubmit={p.createStation}><input className="input" placeholder="Station name" value={p.stationName} onChange={(e:any)=>p.setStationName(e.target.value)} required/><textarea className="textarea" placeholder="What happens here?" value={p.stationDescription} onChange={(e:any)=>p.setStationDescription(e.target.value)}/><button className="btn">Add station</button></form></div><div className="card" style={{marginBottom:12}}><div className="card-title-row"><h3>Add internal knowledge</h3><span className="autosave-label">Draft autosaves</span></div><form className="form" onSubmit={p.createKnowledge}><select className="select" value={p.selectedStation} onChange={(e:any)=>p.setSelectedStation(e.target.value)}><option value="">General</option>{p.stations.map((s:Station)=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input className="input" placeholder="Title" value={p.knowledgeTitle} onChange={(e:any)=>p.setKnowledgeTitle(e.target.value)} required/><textarea className="textarea" placeholder="Teach the system how El Molino actually does this" value={p.knowledgeContent} onChange={(e:any)=>p.setKnowledgeContent(e.target.value)} required/><button className="btn">Save draft</button></form></div></>}<div className="section-title"><h2>Knowledge records</h2><span>{p.knowledge.length}</span></div><div className="list">{p.knowledge.map((k:KnowledgeItem)=><div className="list-item" key={k.id}><div className="icon-wrap">{k.category?.includes('research')?<Globe2 size={18}/>:<BookOpen size={18}/>}</div><div className="list-main"><b>{k.title}</b><small>{k.category?.replaceAll('_',' ')||'internal'} · {k.status}</small></div><div className="row-actions">{p.canManage&&k.status!=='approved'&&!k.category?.includes('research')&&<button className="mini-action" onClick={()=>p.approveKnowledge(k.id)}>Approve</button>}{p.canManage&&<button className="icon-action danger-action" aria-label="Move to trash" onClick={()=>p.softDeleteKnowledge(k.id)}><Trash2 size={16}/></button>}</div></div>)}</div></>}

function FilesSection({files,uploadFile,openFile}:{files:FileRow[];uploadFile:(f:File)=>void;openFile:(f:FileRow)=>void}){const choose=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(f)void uploadFile(f);e.target.value=''};return <><PageHeading title="Files & Media" subtitle="Capture the restaurant with photos, documents, video, voice and spreadsheets"/><div className="upload-grid"><label className="upload-tile"><Camera/><b>Take photo</b><small>Camera or photo library</small><input hidden type="file" accept="image/*" capture="environment" onChange={choose}/></label><label className="upload-tile"><Mic/><b>Voice / audio</b><small>Upload a recording</small><input hidden type="file" accept="audio/*" onChange={choose}/></label><label className="upload-tile"><FileText/><b>Document</b><small>PDF, Word, CSV or spreadsheet</small><input hidden type="file" accept=".pdf,.doc,.docx,.csv,.xlsx,.txt" onChange={choose}/></label><label className="upload-tile"><Upload/><b>Any file</b><small>Up to 50 MB</small><input hidden type="file" onChange={choose}/></label></div><div className="section-title"><h2>Library</h2><span>{files.length}</span></div>{files.length?<div className="list">{files.map(f=><button className="list-item" key={f.id} onClick={()=>openFile(f)}><div className="icon-wrap"><FileText size={18}/></div><div className="list-main"><b>{f.title||f.file_name}</b><small>{f.kind} · {formatBytes(f.size_bytes)}</small></div><ChevronRight size={17}/></button>)}</div>:<EmptyState icon={<FolderOpen/>} title="No files yet" body="Photos, manuals, voice notes and restaurant documents will live here."/>}</>}

function ActivitySection({rows}:{rows:ActivityRow[]}){return <><PageHeading title="Activity" subtitle="An audit trail of important changes"/>{rows.length?<div className="timeline">{rows.map(r=><div className="timeline-row" key={r.id}><div className="timeline-dot"/><div><b>{r.summary||r.action}</b><small>{r.entity_type||'system'} · {new Date(r.created_at).toLocaleString()}</small></div></div>)}</div>:<EmptyState icon={<Activity/>} title="No recorded activity yet" body="New edits, approvals, uploads and assignments will appear here."/>}</>}

function SettingsSection({prefs,updatePrefs}:{prefs:Prefs;updatePrefs:(p:Partial<Prefs>)=>void}){return <><PageHeading title="Settings" subtitle="Personalize how the app behaves on this device"/><div className="settings-card"><SettingToggle title="Remember email" body="Keep your email filled in if you ever need to sign in again" value={prefs.remember_email} onChange={v=>updatePrefs({remember_email:v})}/><SettingToggle title="In-app notifications" body="Show operational notifications inside the app" value={prefs.in_app_notifications} onChange={v=>updatePrefs({in_app_notifications:v})}/><SettingToggle title="Email notifications" body="Allow email delivery when notification delivery is enabled" value={prefs.email_notifications} onChange={v=>updatePrefs({email_notifications:v})}/><SettingToggle title="Push notifications" body="Allow device push delivery when configured" value={prefs.push_notifications} onChange={v=>updatePrefs({push_notifications:v})}/><SettingToggle title="Reduced motion" body="Minimize animation and movement" value={prefs.reduced_motion} onChange={v=>updatePrefs({reduced_motion:v})}/><SettingToggle title="Compact mode" body="Fit more information on larger screens" value={prefs.compact_mode} onChange={v=>updatePrefs({compact_mode:v})}/><div className="setting-row"><div><b>Appearance</b><small>Use device setting, light or dark</small></div><select className="select compact-select" value={prefs.theme} onChange={e=>updatePrefs({theme:e.target.value as Prefs['theme']})}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></div></div></>}

function AdminSection({knowledge,stations,files,activity}:{knowledge:KnowledgeItem[];stations:Station[];files:FileRow[];activity:ActivityRow[]}){return <><PageHeading title="Admin Center" subtitle="System controls and health stay here"/><div className="metric-grid"><Metric label="Knowledge" value={knowledge.length}/><Metric label="Stations" value={stations.length}/><Metric label="Files" value={files.length}/><Metric label="Audit events" value={activity.length}/></div><div className="notice" style={{marginTop:14}}>User invitations, fine-grained permissions, backups, integrations, error telemetry and system exports are now backed by the platform schema and will surface here as their workflows are enabled.</div></>}

function SearchSheet({onClose}:{onClose:()=>void}){const [q,setQ]=useState(''),[rows,setRows]=useState<SearchResult[]>([]),[busy,setBusy]=useState(false);useEffect(()=>{const id=setTimeout(async()=>{if(q.trim().length<2){setRows([]);return;}setBusy(true);const {data}=await supabase.rpc('global_search',{search_text:q.trim(),result_limit:30});setRows((data??[]) as SearchResult[]);setBusy(false);},220);return()=>clearTimeout(id)},[q]);return <div className="sheet-backdrop" role="dialog" aria-modal="true"><div className="sheet full-sheet"><div className="sheet-head"><h2>Search everything</h2><button className="round-button" onClick={onClose}><X/></button></div><div className="search-field"><Search size={19}/><input autoFocus placeholder="People, procedures, menu, knowledge…" value={q} onChange={e=>setQ(e.target.value)}/>{busy&&<Loader2 className="spin" size={17}/>}</div><div className="list search-results">{rows.map(r=><a className="list-item" key={`${r.entity_type}-${r.entity_id}`} href={r.href}><div className="icon-wrap"><Search size={17}/></div><div className="list-main"><b>{r.title}</b><small>{r.entity_type.replaceAll('_',' ')} · {r.subtitle}</small></div><ChevronRight size={17}/></a>)}{q.length>=2&&!busy&&!rows.length&&<EmptyState icon={<Search/>} title="No matches" body="Try a shorter or different search."/>}</div></div></div>}

function NotificationSheet({notices,onClose,onOpen}:{notices:Notice[];onClose:()=>void;onOpen:(n:Notice)=>void}){return <div className="sheet-backdrop" role="dialog" aria-modal="true"><div className="sheet"><div className="sheet-head"><h2>Notifications</h2><button className="round-button" onClick={onClose}><X/></button></div>{notices.length?<div className="list">{notices.map(n=><button className={`list-item ${!n.read_at?'unread':''}`} key={n.id} onClick={()=>onOpen(n)}><div className="icon-wrap"><Bell size={17}/></div><div className="list-main"><b>{n.title}</b><small>{n.body||timeAgo(n.created_at)}</small></div>{!n.read_at&&<span className="unread-dot"/>}</button>)}</div>:<EmptyState icon={<Bell/>} title="You're caught up" body="New assignments and important updates will appear here."/>}</div></div>}

function AccountSheet({profile,email,onClose,updateName,onSignOut}:{profile:Profile|null;email:string;onClose:()=>void;updateName:()=>void;onSignOut:()=>void}){return <div className="sheet-backdrop" role="dialog" aria-modal="true"><div className="sheet"><div className="sheet-head"><h2>Account</h2><button className="round-button" onClick={onClose}><X/></button></div><div className="account-hero"><div className="large-avatar">{(profile?.full_name||'D').slice(0,1).toUpperCase()}</div><div><b>{profile?.full_name||'Account'}</b><small>{email}</small><span className="status">{profile?.app_role||'member'}</span></div></div><button className="settings-row button-row" onClick={updateName}><span className="settings-icon"><CircleUserRound/></span><span><b>Edit profile</b><small>Change your display name</small></span><ChevronRight/></button><button className="settings-row button-row" onClick={onSignOut}><span className="settings-icon"><LogOut/></span><span><b>Sign out</b><small>This is the action that ends your remembered session</small></span><ChevronRight/></button></div></div>}

function Onboarding({onDone}:{onDone:()=>void}){const [step,setStep]=useState(0);const slides=[{icon:<Home/>,title:'Your work, not the database',body:'Today stays focused on what you need to run the shift. Research and system records stay in More.'},{icon:<Bot/>,title:'Ask El Molino',body:'Auto uses internal knowledge first. El Molino Web is restricted to restaurant-related public information.'},{icon:<Camera/>,title:'Teach it over time',body:'Capture photos, documents and real procedures. Draft knowledge stays separate until a manager approves it.'}];const s=slides[step];return <div className="onboard-backdrop"><div className="onboard-card"><div className="onboard-icon">{s.icon}</div><h2>{s.title}</h2><p>{s.body}</p><div className="dots">{slides.map((_,i)=><span key={i} className={i===step?'active':''}/>)}</div><button className="btn" onClick={()=>step<slides.length-1?setStep(step+1):onDone()}>{step<slides.length-1?'Continue':'Start using the app'}</button></div></div>}

function PageHeading({title,subtitle}:{title:string;subtitle:string}){return <div className="page-heading"><h1>{title}</h1><p>{subtitle}</p></div>}
function EmptyState({icon,title,body}:{icon:ReactNode;title:string;body:string}){return <div className="empty-state"><div className="icon-wrap">{icon}</div><b>{title}</b><span>{body}</span></div>}
function TabButton({label,active,onClick,icon}:{label:string;active:boolean;onClick:()=>void;icon:ReactNode}){return <button className={`tab ${active?'active':''}`} onClick={onClick}>{icon}<span>{label}</span></button>}
function MoreLink({icon,title,body,onClick}:{icon:ReactNode;title:string;body:string;onClick:()=>void}){return <button className="settings-row button-row" onClick={onClick}><span className="settings-icon">{icon}</span><span><b>{title}</b><small>{body}</small></span><ChevronRight/></button>}
function SettingToggle({title,body,value,onChange}:{title:string;body:string;value:boolean;onChange:(v:boolean)=>void}){return <div className="setting-row"><div><b>{title}</b><small>{body}</small></div><button className={`switch ${value?'on':''}`} role="switch" aria-checked={value} onClick={()=>onChange(!value)}><span/></button></div>}
function Metric({label,value}:{label:string;value:number}){return <div className="metric"><strong>{value}</strong><span>{label}</span></div>}
function FullLoader(){return <div className="full-loader"><Loader2 className="spin"/><span>Opening El Molino Ops…</span></div>}
function formatDue(v:string|null){if(!v)return 'No due date';const d=new Date(v);const now=new Date();const same=d.toDateString()===now.toDateString();return same?`Today ${d.toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}`:d.toLocaleString([],{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});}
function timeAgo(v:string){const n=Date.now()-new Date(v).getTime();const m=Math.floor(n/60000);if(m<1)return 'just now';if(m<60)return `${m}m ago`;const h=Math.floor(m/60);if(h<24)return `${h}h ago`;return `${Math.floor(h/24)}d ago`;}
function formatBytes(v:number|null){if(v==null)return 'size unknown';if(v<1024)return `${v} B`;if(v<1048576)return `${(v/1024).toFixed(1)} KB`;return `${(v/1048576).toFixed(1)} MB`;}
