'use client';

import {useEffect,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase';
import styles from '../ops-tools.module.css';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Employee={id:string;full_name:string};
type Mapping={toast_employee_guid:string;employee_id:string|null;toast_name:string;toast_email:string|null;deleted:boolean};
type SyncState={last_completed_at:string|null;last_business_date:string|null;last_status:string;last_error:string|null;last_counts:Record<string,number>};
type PayrollRow={employee_id:string;full_name:string;regular_hours:number;overtime_hours:number;worked_hours:number;hourly_wages:number;declared_cash_tips:number;cash_order_tips:number;non_cash_tips:number;service_charges:number;tips_withheld:number;estimated_payroll_gross:number;total_reported_tips:number};
type Payroll={rows:PayrollRow[];summary:{employees:number;worked_hours:number;hourly_wages:number;declared_cash_tips:number;non_cash_tips:number;service_charges:number;tips_withheld:number;estimated_payroll_gross:number}};
type CashRow={business_date:string;cash_sales:number;cash_refunds:number;pay_outs:number;cash_out:number;cash_in:number;cash_collected:number;tip_outs:number;deposits:number};
const isoToday=()=>new Date().toISOString().slice(0,10);const monthStart=()=>`${isoToday().slice(0,8)}01`;const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n)||0);

export default function ToastPage(){
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[profile,setProfile]=useState<Profile|null>(null),[configured,setConfigured]=useState(false),[employees,setEmployees]=useState<Employee[]>([]),[mappings,setMappings]=useState<Mapping[]>([]),[syncState,setSyncState]=useState<SyncState|null>(null),[source,setSource]=useState<'internal'|'toast'>('internal'),[syncDate,setSyncDate]=useState(isoToday()),[range,setRange]=useState({start:monthStart(),end:isoToday()}),[payroll,setPayroll]=useState<Payroll|null>(null),[cash,setCash]=useState<CashRow[]>([]);
 useEffect(()=>{void load()},[]);
 async function load(){setBusy(true);const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}const p=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();const pr=(p.data||null) as Profile|null;setProfile(pr);if(!pr?.location_id||!['admin','manager'].includes(pr.app_role)){setReady(true);setBusy(false);return}
  const [em,mp,st,tc]=await Promise.all([supabase.from('employees').select('id,full_name').eq('location_id',pr.location_id).eq('active',true).is('deleted_at',null).order('full_name'),supabase.from('toast_employee_map').select('toast_employee_guid,employee_id,toast_name,toast_email,deleted').eq('location_id',pr.location_id).order('toast_name'),supabase.from('toast_sync_state').select('last_completed_at,last_business_date,last_status,last_error,last_counts').eq('location_id',pr.location_id).maybeSingle(),supabase.from('time_clock_settings').select('authoritative_source').eq('location_id',pr.location_id).maybeSingle()]);
  setEmployees((em.data??[]) as Employee[]);setMappings((mp.data??[]) as Mapping[]);setSyncState((st.data||null) as SyncState|null);setSource((tc.data?.authoritative_source==='toast'?'toast':'internal'));
  const {data:session}=await supabase.auth.getSession();const token=session.session?.access_token;if(token){const response=await fetch('/api/toast/status',{headers:{authorization:`Bearer ${token}`}});if(response.ok){const j=await response.json();setConfigured(Boolean(j.configured))}}
  setReady(true);setBusy(false);await refreshReports();
 }
 async function sync(){if(busy)return;setBusy(true);setMessage('');try{const {data:s}=await supabase.auth.getSession();const token=s.session?.access_token;if(!token)throw new Error('Sign in again.');const response=await fetch('/api/toast/sync',{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify({businessDate:syncDate})});const body=await response.json();if(!response.ok)throw new Error(body.error||'Toast sync failed.');setMessage(`Toast sync complete for ${syncDate}.`);await load()}catch(e:any){setMessage(e?.message||'Toast sync failed.')}finally{setBusy(false)}}
 async function mapEmployee(toastGuid:string,employeeId:string){if(busy)return;setBusy(true);const {error}=await supabase.rpc('map_toast_employee',{p_toast_employee_guid:toastGuid,p_employee_id:employeeId||null});setMessage(error?error.message:'Employee mapping saved. Sync this business date again to import any previously unmapped punches.');await load();setBusy(false)}
 async function setClockSource(next:'internal'|'toast'){if(busy)return;setBusy(true);const {error}=await supabase.rpc('set_time_clock_authoritative_source',{p_source:next});if(error)setMessage(error.message);else{setSource(next);setMessage(next==='toast'?'Toast POS is now the authoritative clock. Staff should clock only in Toast.':'El Molino Ops internal clock is active.')}setBusy(false)}
 async function refreshReports(){const [p,c]=await Promise.all([supabase.rpc('toast_payroll_summary',{p_starts_on:range.start,p_ends_on:range.end}),supabase.rpc('toast_cash_summary',{p_starts_on:range.start,p_ends_on:range.end})]);if(!p.error)setPayroll(p.data as Payroll);if(!c.error)setCash(((c.data as any)?.rows??[]) as CashRow[])}
 if(!ready)return <main className={styles.page}>Loading Toast integration…</main>;
 if(!profile?.location_id||!['admin','manager'].includes(profile.app_role))return <main className={styles.page}>Manager access is required.</main>;
 const unmapped=mappings.filter(x=>!x.employee_id&&!x.deleted).length;
 return <main className={styles.page}><div className={styles.top}><div><h1>Toast POS Integration</h1><p>One source for punches, payroll hours, tips, cash activity and deposits.</p></div><Link className={styles.back} href="/tools">Back to Tools</Link></div>{message&&<div className={message.toLowerCase().includes('fail')||message.toLowerCase().includes('required')||message.toLowerCase().includes('not configured')?styles.error:styles.notice}>{message}</div>}
  <div className={styles.grid}><Metric label="API credentials" value={configured?'Configured':'Not configured'}/><Metric label="Clock source" value={source==='toast'?'Toast POS':'El Molino Ops'}/><Metric label="Unmapped staff" value={String(unmapped)}/><Metric label="Last sync" value={syncState?.last_completed_at?new Date(syncState.last_completed_at).toLocaleString():'Never'}/></div>
  <section className={styles.section}><div className={styles.card}><h2>Sync Toast</h2><p className={styles.muted}>Imports Toast labor time entries and breaks, order payment tips, cash-management entries and deposits. Imported punches use the existing manager/employee approval controls.</p><div className={styles.actions}><input type="date" value={syncDate} onChange={e=>setSyncDate(e.target.value)}/><button className={styles.button} disabled={busy||!configured} onClick={sync}>Sync business date</button></div>{syncState?.last_error&&<div className={styles.error}>{syncState.last_error}</div>}</div></section>
  <section className={styles.section}><div className={styles.card}><h2>Clock authority</h2><p className={styles.muted}>When Toast is authoritative, employee web/mobile/kiosk punches are blocked so staff never clock twice. Toast punches and breaks flow into El Molino Ops as POS imports.</p><div className={styles.actions}><button className={source==='toast'?styles.button:`${styles.button} ${styles.secondary}`} disabled={busy||source==='toast'||!syncState?.last_completed_at} onClick={()=>setClockSource('toast')}>Use Toast as clock</button><button className={source==='internal'?styles.button:`${styles.button} ${styles.secondary}`} disabled={busy||source==='internal'} onClick={()=>setClockSource('internal')}>Use El Molino Ops clock</button></div></div></section>
  <section className={styles.section}><h2>Employee mapping</h2><div className={styles.list}>{mappings.filter(m=>!m.deleted).map(m=><div className={styles.entry} key={m.toast_employee_guid}><div className={styles.entryHead}><div><h3>{m.toast_name}</h3><small>{m.toast_email||'Toast employee'} </small></div><span className={styles.pill}>{m.employee_id?'mapped':'needs mapping'}</span></div><label className={styles.field}><span>El Molino employee</span><select value={m.employee_id||''} onChange={e=>void mapEmployee(m.toast_employee_guid,e.target.value)} disabled={busy}><option value="">Not mapped</option>{employees.map(e=><option value={e.id} key={e.id}>{e.full_name}</option>)}</select></label></div>)}{!mappings.length&&<div className={styles.empty}>Run the first Toast sync to load employees.</div>}</div></section>
  <section className={styles.section}><div className={styles.card}><h2>Payroll-ready Toast report</h2><div className={styles.actions}><input type="date" value={range.start} onChange={e=>setRange({...range,start:e.target.value})}/><input type="date" value={range.end} onChange={e=>setRange({...range,end:e.target.value})}/><button className={styles.button} disabled={busy} onClick={refreshReports}>Refresh</button></div></div><div className={styles.grid}><Metric label="Hours" value={Number(payroll?.summary?.worked_hours||0).toFixed(2)}/><Metric label="Hourly wages" value={money(payroll?.summary?.hourly_wages||0)}/><Metric label="Non-cash tips" value={money(payroll?.summary?.non_cash_tips||0)}/><Metric label="Estimated payroll gross" value={money(payroll?.summary?.estimated_payroll_gross||0)}/></div><div className={styles.tableWrap}>{payroll?.rows?.length?<table className={styles.table}><thead><tr><th>Employee</th><th>Regular</th><th>OT</th><th>Wages</th><th>Card / non-cash tips</th><th>Declared cash tips</th><th>Service charges</th><th>Withheld</th><th>Payroll gross</th></tr></thead><tbody>{payroll.rows.map(r=><tr key={r.employee_id}><td>{r.full_name}</td><td>{Number(r.regular_hours).toFixed(2)}</td><td>{Number(r.overtime_hours).toFixed(2)}</td><td>{money(r.hourly_wages)}</td><td>{money(r.non_cash_tips)}</td><td>{money(r.declared_cash_tips)}</td><td>{money(r.service_charges)}</td><td>{money(r.tips_withheld)}</td><td>{money(r.estimated_payroll_gross)}</td></tr>)}</tbody></table>:<div className={styles.empty}>No mapped Toast payroll data in this range.</div>}</div></section>
  <section className={styles.section}><h2>Toast cash by business date</h2><div className={styles.tableWrap}>{cash.length?<table className={styles.table}><thead><tr><th>Date</th><th>Cash sales</th><th>Refunds</th><th>Paid outs</th><th>Cash in</th><th>Cash out</th><th>Collected</th><th>Tip outs</th><th>Deposits</th></tr></thead><tbody>{cash.map(r=><tr key={r.business_date}><td>{r.business_date}</td><td>{money(r.cash_sales)}</td><td>{money(r.cash_refunds)}</td><td>{money(r.pay_outs)}</td><td>{money(r.cash_in)}</td><td>{money(r.cash_out)}</td><td>{money(r.cash_collected)}</td><td>{money(r.tip_outs)}</td><td>{money(r.deposits)}</td></tr>)}</tbody></table>:<div className={styles.empty}>No Toast cash data in this range.</div>}</div></section>
 </main>}
function Metric({label,value}:{label:string;value:string}){return <div className={styles.metric}><span>{label}</span><strong>{value}</strong></div>}
