import {OPS_MODULES,type OpsField,type OpsKind,type OpsModule} from './ops-modules';

type Locale='en'|'es';

const MODULE_ES:Record<OpsKind,[string,string]>={
 shift_handoff:['Entregas de Turno','Entregas estructuradas del gerente saliente al entrante.'],manager_log:['Bitácora Gerencial','Notas gerenciales diarias que se pueden buscar.'],daily_recap:['Resúmenes Diarios','Resumen de ventas, trabajo y operaciones al final del día.'],incident:['Informes de Incidentes','Documenta incidentes de clientes, empleados, seguridad y operaciones.'],maintenance_ticket:['Solicitudes de Mantenimiento','Da seguimiento a equipos dañados y problemas del local hasta terminarlos.'],equipment:['Registro de Equipos','Equipos del restaurante, números de serie, modelos y garantías.'],equipment_service:['Historial de Servicio','Reparaciones y mantenimiento preventivo de equipos.'],vendor:['Proveedores','Directorio de contactos de proveedores y servicios.'],temperature_log:['Registros de Temperatura','Registros de temperatura de alimentos y equipos.'],waste_log:['Registro de Desperdicio','Registra producto desperdiciado, cantidad, costo y causa.'],comp_void_log:['Registro de Cortesías / Anulaciones','Registro gerencial de cortesías, anulaciones y explicaciones.'],inventory_count:['Conteos de Inventario','Registros reutilizables de conteo manual.'],stock_flag:['Alertas de Existencias Bajas','Marca productos que requieren compra o atención.'],order_prep_note:['Notas de Pedido / Preparación','Notas de compras y planificación de preparación.'],menu_availability:['Tablero 86','Controla artículos del menú agotados o limitados.'],ingredient:['Ingredientes','Registros reutilizables de ingredientes y almacenamiento.'],recipe:['Recetas','Ingredientes, rendimientos e instrucciones de preparación.'],allergen:['Alérgenos','Notas estructuradas de alérgenos y contacto cruzado.'],emergency_contact:['Contactos de Emergencia','Registros protegidos de contactos de emergencia.'],training_module:['Módulos de Capacitación','Material de aprendizaje estructurado para puestos del equipo.'],training_progress:['Progreso de Capacitación','Seguimiento de finalización y competencia del empleado.'],training_quiz:['Cuestionarios de Capacitación','Preguntas de conocimiento y claves de respuestas.'],certification:['Certificaciones','Controla certificaciones requeridas y vencimientos.'],onboarding:['Incorporación de Nuevos Empleados','Estado paso a paso de incorporación de personal.'],acknowledgment:['Confirmaciones','Registra la confirmación de políticas o anuncios.'],announcement:['Anuncios','Avisos gerenciales para el equipo del restaurante.'],cleaning_schedule:['Horario de Limpieza','Responsabilidades y estándares recurrentes de limpieza.'],deep_clean:['Plan de Limpieza Profunda','Trabajo periódico más allá de la limpieza del turno.'],favorite_link:['Favoritos','Fija destinos internos o registros usados con frecuencia.'],saved_search:['Búsquedas Guardadas','Términos y filtros de búsqueda reutilizables.'],system_note:['Notas del Sistema','Metadatos operativos internos y notas administrativas.']
};

const CATEGORY_ES:Record<string,string>={Shift:'Turno',Safety:'Seguridad',Maintenance:'Mantenimiento','Food Safety':'Seguridad Alimentaria',Inventory:'Inventario',Menu:'Menú',People:'Personal',Communication:'Comunicación',Cleaning:'Limpieza',Personal:'Área Personal',System:'Sistema',All:'Todos'};

const FIELD_ES:Record<string,string>={
 summary:'Resumen del turno',open_items:'Asuntos abiertos',staffing:'Notas de personal',cash_notes:'Notas de efectivo / cierre',body:'Nota',follow_up:'Se necesita seguimiento',sales:'Ventas totales',labor_pct:'% laboral',guest_notes:'Notas de clientes / servicio',wins:'Logros',issues:'Problemas',incident_type:'Tipo de incidente',occurred_at_text:'Cuándo ocurrió',people:'Personas involucradas',details:'Qué ocurrió',action_taken:'Acción tomada',asset:'Equipo / área',problem:'Problema',vendor:'Proveedor / técnico',cost:'Costo',category:'Categoría',manufacturer:'Fabricante',model:'Modelo',serial:'Número de serie',location:'Ubicación física',purchase_date:'Fecha de compra',warranty_until:'Garantía hasta',equipment_name:'Equipo',service_date:'Fecha de servicio',provider:'Proveedor de servicio',work:'Trabajo realizado',company:'Empresa',contact:'Persona de contacto',phone:'Teléfono',email:'Correo electrónico',account:'Cuenta / cliente #',notes:'Notas',item:'Artículo',temperature:'Temperatura °F',limit:'Rango requerido',corrective_action:'Acción correctiva',quantity:'Cantidad',unit:'Unidad',estimated_cost:'Costo estimado',reason:'Motivo',check_number:'Cheque / pedido #',amount:'Monto',type:'Tipo',approved_by:'Aprobado por',count:'Conteo',par:'Par',on_hand:'Disponible',needed_by:'Necesario para',note:'Nota',items:'Artículos / preparación',owner:'Persona responsable',state:'Disponibilidad',expected_back:'Regreso esperado',name:'Nombre del ingrediente',storage:'Almacenamiento',shelf_life:'Vida útil',yield:'Rendimiento',ingredients:'Ingredientes + cantidades',steps:'Pasos de preparación',hold_time:'Tiempo de conservación',plating:'Montaje / emplatado',allergens:'Alérgenos',cross_contact:'Notas de contacto cruzado',substitution:'Sustitución posible',employee:'Empleado',contact_name:'Nombre del contacto',relationship:'Relación',role:'Puesto',content:'Contenido de capacitación',pass_score:'Calificación mínima %',module:'Módulo',score:'Calificación %',completed_on:'Completado el',questions:'Preguntas',answer_key:'Clave de respuestas',certification:'Certificación',issued:'Emitida',expires:'Vence',credential:'Credencial #',stage:'Etapa',next_step:'Próximo paso',target_date:'Fecha objetivo',document:'Política / anuncio',acknowledged_on:'Confirmado el',audience:'Audiencia',pinned:'Fijado',area:'Área',task:'Tarea de limpieza',frequency:'Frecuencia',standard:'Estándar de finalización',scope:'Alcance',last_done:'Última finalización',next_due:'Próximo vencimiento',href:'Ruta / referencia de la app',query:'Consulta de búsqueda',filters:'Filtros'
};

const OPTION_ES:Record<string,string>={Guest:'Cliente',Employee:'Empleado',Safety:'Seguridad',Security:'Protección',Property:'Propiedad',Other:'Otro',Spoilage:'Deterioro',Overproduction:'Sobreproducción',Mistake:'Error',Quality:'Calidad',Dropped:'Caído',Expired:'Vencido',Comp:'Cortesía',Void:'Anulación',Refund:'Reembolso','86d':'Agotado',Limited:'Limitado','Back soon':'Disponible pronto',Available:'Disponible','Not started':'Sin iniciar','In progress':'En progreso',Complete:'Completo','Needs retraining':'Necesita recapacitación',Paperwork:'Documentación',Orientation:'Orientación',Training:'Capacitación',Shadowing:'Acompañamiento',Certified:'Certificado',Everyone:'Todos',Managers:'Gerentes',Kitchen:'Cocina',FOH:'Salón','Each shift':'Cada turno',Daily:'Diario',Weekly:'Semanal',Monthly:'Mensual',Yes:'Sí',No:'No',low:'baja',normal:'normal',high:'alta',urgent:'urgente',complete:'completo',active:'activo',attention:'atención'};

export function opsModuleText(module:OpsModule,locale:Locale){const translated=MODULE_ES[module.kind];return locale==='es'&&translated?{title:translated[0],description:translated[1]}:{title:module.title,description:module.description}}
export function opsCategoryText(value:string,locale:Locale){return locale==='es'?(CATEGORY_ES[value]||value):value}
export function opsFieldText(field:OpsField,locale:Locale){return locale==='es'?(FIELD_ES[field.key]||field.label):field.label}
export function opsOptionText(value:string,locale:Locale){return locale==='es'?(OPTION_ES[value]||value):value}
export function opsStatusText(value:string,locale:Locale){return opsOptionText(value,locale)}
export function opsBooleanText(value:boolean,locale:Locale){return value?(locale==='es'?'Sí':'Yes'):(locale==='es'?'No':'No')}
export function opsValidationText(message:string,locale:Locale){
 if(locale!=='es')return message;
 if(message==='Unknown module.')return 'Módulo desconocido.';
 if(message==='Title is required.')return 'El título es obligatorio.';
 if(message==='Title must be 200 characters or fewer.')return 'El título debe tener 200 caracteres o menos.';
 const match=message.match(/^(.+?) (is required|must be a number|must be at least (.+)|must be at most (.+))\.$/);
 if(!match)return message;
 const field=OPS_MODULES.flatMap(module=>module.fields).find(candidate=>candidate.label===match[1]);
 const label=field?(FIELD_ES[field.key]||field.label):match[1];
 if(match[2]==='is required')return `${label} es obligatorio.`;
 if(match[2]==='must be a number')return `${label} debe ser un número.`;
 if(match[3])return `${label} debe ser al menos ${match[3]}.`;
 return `${label} debe ser como máximo ${match[4]}.`;
}
