export const BACKUP_FORMAT='el-molino-ops-backup-v3';
export const RESTORABLE_TABLES=['employee_roles','employee_role_assignments','employees','areas','stations','knowledge_sources','knowledge_items','procedures','procedure_steps','checklist_templates','checklist_template_items','menu_categories','menu_items','menu_item_aliases','menu_item_components','tasks','task_dependencies','comments','ops_records'] as const;
export type BackupCheck={ok:boolean;errors:string[];warnings:string[];rowCount:number;tables:string[]};
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export function validUuid(v:unknown){return uuid.test(String(v||''))}
export function validIsoDate(v:unknown){if(typeof v!=='string'||v.length>64)return false;const n=Date.parse(v);return Number.isFinite(n)}
export function validateBackup(value:unknown,expectedLocation?:string):BackupCheck{const errors:string[]=[],warnings:string[]=[];if(!value||typeof value!=='object'||Array.isArray(value))return{ok:false,errors:['Backup root must be an object.'],warnings,rowCount:0,tables:[]};const b=value as any;if(b.format!==BACKUP_FORMAT)errors.push('Unsupported backup format.');if(!validIsoDate(b.exported_at))errors.push('Backup export timestamp is invalid.');if(!validUuid(b.location_id))errors.push('Backup location is invalid.');if(expectedLocation&&b.location_id!==expectedLocation)errors.push('Backup belongs to a different location.');if('errors' in b&&!Array.isArray(b.errors))errors.push('Backup export status is malformed.');if(Array.isArray(b.errors)&&b.errors.length>0)errors.push('Backup export was incomplete and reported one or more table errors.');if(!b.tables||typeof b.tables!=='object'||Array.isArray(b.tables))errors.push('Backup tables are missing.');const tables=b.tables&&typeof b.tables==='object'&&!Array.isArray(b.tables)?Object.keys(b.tables):[];let rowCount=0;const seenGlobal=new Set<string>();for(const table of tables){const rows=b.tables[table];if(!Array.isArray(rows)){errors.push(`${table}: rows must be an array.`);continue}if(rows.length>100000)errors.push(`${table}: exceeds 100,000-row safety limit.`);rowCount+=rows.length;if(rowCount>300000)errors.push('Backup exceeds 300,000 total rows.');const ids=new Set<string>();for(const row of rows){if(!row||typeof row!=='object'||Array.isArray(row)){errors.push(`${table}: contains a non-object row.`);continue}if('id' in row&&row.id!=null){if(!validUuid(row.id))errors.push(`${table}: contains an invalid id.`);else if(ids.has(row.id))errors.push(`${table}: contains a duplicate id.`);else ids.add(row.id)}if('location_id' in row&&row.location_id!=null&&b.location_id&&row.location_id!==b.location_id)errors.push(`${table}: contains a row from another location.`);const signature=`${table}:${String(row.id||'')}`;if(row.id&&seenGlobal.has(signature))errors.push(`${table}: duplicate primary-key signature.`);seenGlobal.add(signature)}}for(const table of tables)if(!RESTORABLE_TABLES.includes(table as any)&&!['locations','profiles','files','entity_file_links','activity_log','client_events','notifications','favorites','recent_views','ai_conversations','ai_messages','user_preferences','user_invitations','content_versions','checklist_runs','checklist_run_items'].includes(table))warnings.push(`${table}: unknown table will not be restored.`);if(rowCount===0)warnings.push('Backup contains no rows.');return{ok:errors.length===0,errors:[...new Set(errors)].slice(0,100),warnings:[...new Set(warnings)].slice(0,100),rowCount,tables}}
export function parseBackupText(text:string,expectedLocation?:string){if(typeof text!=='string'||text.length===0)return{value:null,check:{ok:false,errors:['Backup file is empty.'],warnings:[],rowCount:0,tables:[]} as BackupCheck};if(text.length>50*1024*1024)return{value:null,check:{ok:false,errors:['Backup file exceeds 50 MB validation limit.'],warnings:[],rowCount:0,tables:[]} as BackupCheck};try{const value=JSON.parse(text);return{value,check:validateBackup(value,expectedLocation)}}catch{return{value:null,check:{ok:false,errors:['Backup JSON is malformed.'],warnings:[],rowCount:0,tables:[]} as BackupCheck}}}
export function optimisticConflict<T extends {updated_at?:string|null}>(snapshot:T,current:T){return Boolean(snapshot.updated_at&&current.updated_at&&snapshot.updated_at!==current.updated_at)}
export function boundedText(v:unknown,max=5000){return String(v??'').replace(/\u0000/g,'').trim().slice(0,Math.max(0,Math.min(max,50000)))}
export function safeAriaText(v:unknown,fallback='Item'){const x=boundedText(v,160).replace(/[\r\n]+/g,' ');return x||fallback}
export function safeTabIndex(index:number,count:number){if(!Number.isFinite(index)||count<=0)return-1;return Math.max(0,Math.min(Math.trunc(index),count-1))}
export function nextFocus(index:number,direction:1|-1,count:number){if(count<=0)return-1;const i=safeTabIndex(index,count);return(i+direction+count)%count}
export function shouldAcceptAsyncResult(requestId:number,currentId:number,stillRelevant=true){return stillRelevant&&requestId===currentId}
export function safeCacheName(v:unknown){const s=String(v??'').trim();return /^el-molino-[a-z0-9._-]{1,80}$/i.test(s)?s:null}
export function isRestaurantInternalPath(v:unknown){const s=String(v??'').trim();return s.startsWith('/')&&!s.startsWith('//')&&!s.includes('\\')&&!/[\u0000-\u001f]/.test(s)}
export function chunkRanges(total:number,size=1000){const n=Math.max(0,Math.min(Math.trunc(Number(total)||0),300000)),s=Math.max(1,Math.min(Math.trunc(Number(size)||1000),5000)),out:{from:number;to:number}[]=[];for(let from=0;from<n;from+=s)out.push({from,to:Math.min(n-1,from+s-1)});return out}
