'use client';

import { use, useEffect, useState } from 'react';
import { ArrowLeft, File, Loader2, Paperclip, Star, StarOff } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { useI18n } from '@/lib/i18n';

type Row={id:string;kind:string;title:string;status:string;priority:string;data:Record<string,unknown>;due_at:string|null;created_at:string;updated_at:string};
type Attachment={id:string;file_name:string;title:string|null;kind:string;storage_bucket:string;storage_path:string};
const pretty=(x:string)=>x.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());

export default function OpsRecordPage({params}:{params:Promise<{id:string}>}){
  const {id}=use(params);const {locale}=useI18n();const localeCode=locale==='es'?'es-US':'en-US';
  const c=locale==='es'?{removed:'Eliminado de guardados.',saved:'Guardado.',attachmentError:'No se pudo abrir el archivo adjunto.',opening:'Abriendo registro…',operations:'Operaciones',unavailable:'Registro no disponible',loadError:'No se pudo cargar este registro.',back:'Atrás',removeSaved:'Quitar de guardados',saveItem:'Guardar elemento',priority:'prioridad',due:'vence',yes:'Sí',no:'No',attach:'Adjuntar archivo',viewAll:'Ver todos',attachments:'Archivos adjuntos',none:'Aún no hay archivos adjuntos',noneBody:'Agrega una foto, documento, video o nota de voz a este registro.',status:{open:'abierto',active:'activo',resolved:'resuelto',closed:'cerrado',completed:'completado',draft:'borrador',pending:'pendiente'} as Record<string,string>,priorities:{low:'baja',normal:'normal',high:'alta',urgent:'urgente'} as Record<string,string>,kinds:{maintenance_ticket:'Ticket de mantenimiento',equipment:'Equipo',equipment_service:'Servicio de equipo',incident:'Incidente',manager_log:'Registro de gerencia',vendor:'Proveedor',shift_handoff:'Relevo de turno',daily_recap:'Resumen diario',temperature_log:'Registro de temperatura',stock_flag:'Alerta de inventario',menu_availability:'Disponibilidad de menú'} as Record<string,string>,keys:{equipment:'Equipo',issue:'Problema',location_detail:'Ubicación',resolution:'Resolución',model:'Modelo',serial:'Serie',vendor:'Proveedor',warranty:'Garantía / notas',summary:'Resumen',cost:'Costo',next_due:'Próximo servicio',incident_type:'Tipo de incidente',people:'Personas',witnesses:'Testigos',description:'Descripción',immediate_action:'Acción inmediata',police_report:'Policía / reporte',follow_up:'Seguimiento',manager_resolution:'Resolución de gerencia'} as Record<string,string>}:{removed:'Removed from saved.',saved:'Saved.',attachmentError:'Could not open attachment.',opening:'Opening record…',operations:'Operations',unavailable:'Record unavailable',loadError:'This record could not be loaded.',back:'Back',removeSaved:'Remove saved item',saveItem:'Save item',priority:'priority',due:'due',yes:'Yes',no:'No',attach:'Attach file',viewAll:'View all',attachments:'Attachments',none:'No attachments yet',noneBody:'Add a photo, document, video or voice note to this record.',status:{open:'open',active:'active',resolved:'resolved',closed:'closed',completed:'completed',draft:'draft',pending:'pending'} as Record<string,string>,priorities:{low:'low',normal:'normal',high:'high',urgent:'urgent'} as Record<string,string>,kinds:{} as Record<string,string>,keys:{} as Record<string,string>};
  const kindLabel=(x:string)=>c.kinds[x]||pretty(x),keyLabel=(x:string)=>c.keys[x]||pretty(x),statusLabel=(x:string)=>c.status[x]||x,priorityLabel=(x:string)=>c.priorities[x]||x;
  const [loading,setLoading]=useState(true),[message,setMessage]=useState(''),[row,setRow]=useState<Row|null>(null),[files,setFiles]=useState<Attachment[]>([]),[saved,setSaved]=useState(false);
  useEffect(()=>{void load()},[id]);
  async function load(){
    setLoading(true);const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return;}
    const [r,links,fav]=await Promise.all([
      supabase.from('ops_records').select('id,kind,title,status,priority,data,due_at,created_at,updated_at').eq('id',id).is('deleted_at',null).single(),
      supabase.from('entity_file_links').select('file_id').eq('entity_type','ops_record').eq('entity_id',id),
      supabase.from('favorites').select('entity_id').eq('user_id',u.user.id).eq('entity_type','ops_record').eq('entity_id',id).maybeSingle()
    ]);
    if(r.error){setMessage(r.error.message);setLoading(false);return;}const record=r.data as Row;setRow(record);setSaved(Boolean(fav.data));
    const ids=(links.data??[]).map((x:any)=>x.file_id).filter(Boolean);if(ids.length){const {data}=await supabase.from('files').select('id,file_name,title,kind,storage_bucket,storage_path').in('id',ids).is('deleted_at',null);setFiles((data??[]) as Attachment[]);}else setFiles([]);
    await supabase.from('recent_views').upsert({user_id:u.user.id,entity_type:'ops_record',entity_id:id,title:record.title,href:`/ops-record/${id}`,viewed_at:new Date().toISOString()},{onConflict:'user_id,entity_type,entity_id'});
    setLoading(false);
  }
  async function toggleSaved(){const {data:u}=await supabase.auth.getUser();if(!u.user)return;if(saved){const {error}=await supabase.from('favorites').delete().eq('user_id',u.user.id).eq('entity_type','ops_record').eq('entity_id',id);if(error)return setMessage(error.message);setSaved(false);setMessage(c.removed);}else{const {error}=await supabase.from('favorites').upsert({user_id:u.user.id,entity_type:'ops_record',entity_id:id},{onConflict:'user_id,entity_type,entity_id'});if(error)return setMessage(error.message);setSaved(true);setMessage(c.saved);}}
  async function openFile(file:Attachment){const {data,error}=await supabase.storage.from(file.storage_bucket).createSignedUrl(file.storage_path,120);if(error||!data?.signedUrl)return setMessage(error?.message||c.attachmentError);window.open(data.signedUrl,'_blank','noopener,noreferrer');}
  if(loading)return <div className="full-loader"><Loader2 className="spin"/><span>{c.opening}</span></div>;
  if(!row)return <main className="page"><a className="back-link" href="/ops">‹ {c.operations}</a><div className="empty-state"><b>{c.unavailable}</b><span>{message||c.loadError}</span></div></main>;
  return <div className="app-shell"><header className="topbar"><a className="round-button" href={`/ops?kind=${row.kind}`} aria-label={c.back}><ArrowLeft/></a><div style={{flex:1}}><div className="brand-kicker">{kindLabel(row.kind)}</div><div className="brand-title">{row.title}</div></div><button className="round-button" onClick={toggleSaved} aria-label={saved?c.removeSaved:c.saveItem}>{saved?<StarOff/>:<Star/>}</button></header><main className="page">{message&&<div className="toast-message">{message}</div>}<div className="card" style={{padding:18}}><div className="card-title-row"><h2>{row.title}</h2><span className="status">{statusLabel(row.status)}</span></div><p style={{color:'var(--muted)',marginTop:4}}>{kindLabel(row.kind)} · {priorityLabel(row.priority)} {c.priority}{row.due_at?` · ${c.due} ${new Date(row.due_at).toLocaleString(localeCode)}`:''}</p><dl className="ops-detail">{Object.entries(row.data||{}).map(([k,v])=><div key={k} style={{marginTop:10}}><dt style={{fontSize:11,color:'var(--muted)'}}>{keyLabel(k)}</dt><dd style={{margin:0,marginTop:3}}>{typeof v==='boolean'?(v?c.yes:c.no):String(v)}</dd></div>)}</dl><div className="row-actions" style={{marginTop:16}}><a className="mini-action" href={`/capture?entityType=ops_record&entityId=${id}`}><Paperclip size={14}/> {c.attach}</a><a className="mini-action" href={`/ops?kind=${row.kind}`}>{c.viewAll} {kindLabel(row.kind)}</a></div></div><div className="section-title"><h2>{c.attachments}</h2><span>{files.length}</span></div>{files.length?<div className="list">{files.map(f=><button key={f.id} className="list-item" onClick={()=>openFile(f)} style={{width:'100%',textAlign:'left'}}><span className="settings-icon"><File/></span><span className="list-main"><b>{f.title||f.file_name}</b><small>{f.kind}</small></span></button>)}</div>:<div className="empty-state"><Paperclip/><b>{c.none}</b><span>{c.noneBody}</span></div>}</main></div>;
}
