'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { supabase } from '@/lib/supabase';
import styles from '../ops-tools.module.css';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Vendor={id:string;name:string;contact_name:string|null;phone:string|null;email:string|null;account_number:string|null;delivery_notes:string|null;active:boolean};
type PO={id:string;vendor_id:string|null;order_date:string;expected_date:string|null;status:string;created_at:string};
type Rec={id:string;title:string;data:any;occurred_at:string|null;created_at:string};

export default function VendorsPage(){
  const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[profile,setProfile]=useState<Profile|null>(null),[vendors,setVendors]=useState<Vendor[]>([]),[orders,setOrders]=useState<PO[]>([]),[notes,setNotes]=useState<Rec[]>([]),[message,setMessage]=useState('');
  const [form,setForm]=useState({name:'',contact_name:'',phone:'',email:'',account_number:'',delivery_notes:''}),[noteForm,setNoteForm]=useState({vendor_id:'',note:''});
  useEffect(()=>{void init()},[]);
  async function init(){const {data:u}=await supabase.auth.getUser();if(!u.user){window.location.href='/';return;}const {data:p}=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();setProfile((p||null) as Profile|null);if(p?.location_id&&['admin','manager'].includes(p.app_role))await load(p.location_id);setReady(true);}
  async function load(locationId=profile?.location_id||''){if(!locationId)return;const [v,o,n]=await Promise.all([supabase.from('restaurant_vendors').select('id,name,contact_name,phone,email,account_number,delivery_notes,active').eq('location_id',locationId).eq('active',true).order('name'),supabase.from('purchase_orders').select('id,vendor_id,order_date,expected_date,status,created_at').eq('location_id',locationId).order('created_at',{ascending:false}).limit(100),supabase.from('ops_records').select('id,title,data,occurred_at,created_at').eq('location_id',locationId).eq('kind','vendor').is('deleted_at',null).order('created_at',{ascending:false}).limit(100)]);setVendors((v.data??[]) as Vendor[]);setOrders((o.data??[]) as PO[]);setNotes((n.data??[]) as Rec[]);if(v.error||o.error||n.error)setMessage('Some vendor data could not be loaded.');}
  const openOrders=useMemo(()=>orders.filter(o=>['draft','submitted'].includes(o.status)).length,[orders]);
  const vendorName=(id:string|null)=>vendors.find(v=>v.id===id)?.name||'Unassigned vendor';
  async function saveVendor(e:FormEvent){e.preventDefault();if(!profile?.location_id||busy||!form.name.trim())return;setBusy(true);try{const payload={location_id:profile.location_id,name:form.name.trim().slice(0,200),contact_name:form.contact_name.trim().slice(0,200)||null,phone:form.phone.trim().slice(0,100)||null,email:form.email.trim().slice(0,254)||null,account_number:form.account_number.trim().slice(0,200)||null,delivery_notes:form.delivery_notes.trim().slice(0,4000)||null};const {error}=await supabase.from('restaurant_vendors').upsert(payload,{onConflict:'location_id,name'});if(error)throw error;setForm({name:'',contact_name:'',phone:'',email:'',account_number:'',delivery_notes:''});await load();setMessage('Vendor saved.');}catch{setMessage('Could not save vendor.');}finally{setBusy(false)}}
  async function addNote(e:FormEvent){e.preventDefault();if(!profile?.location_id||busy||!noteForm.vendor_id||!noteForm.note.trim())return;const vendor=vendors.find(v=>v.id===noteForm.vendor_id);setBusy(true);try{const {data:u}=await supabase.auth.getUser();const {error}=await supabase.from('ops_records').insert({location_id:profile.location_id,kind:'vendor',title:`Vendor note · ${vendor?.name||'Vendor'}`,status:'active',priority:'normal',sensitivity:'manager',data:{vendor_id:noteForm.vendor_id,vendor_name:vendor?.name||'',note:noteForm.note.trim().slice(0,5000)},tags:['vendor','service-note'],occurred_at:new Date().toISOString(),created_by:u.user?.id||null,updated_by:u.user?.id||null});if(error)throw error;setNoteForm({vendor_id:'',note:''});await load();setMessage('Vendor note saved.');}catch{setMessage('Could not save vendor note.');}finally{setBusy(false)}}
  if(!ready)return <main className={styles.page}>Loading vendors…</main>;
  if(!profile?.location_id||!['admin','manager'].includes(profile.app_role))return <main className={styles.page}><div className={styles.top}><div><h1>Vendors</h1><p>Manager-only vendor accounts and service records.</p></div><Link className={styles.back} href="/">Back</Link></div><div className={styles.error}>Manager access is required.</div></main>;
  return <main className={styles.page}><div className={styles.top}><div><h1>Vendors</h1><p>Contacts, accounts, delivery notes, purchase orders and service history.</p></div><Link className={styles.back} href="/">Back to Ops</Link></div>{message&&<div className={message.startsWith('Could not')||message.startsWith('Some')?styles.error:styles.notice}>{message}</div>}
    <div className={styles.grid}><Metric label="Active vendors" value={String(vendors.length)}/><Metric label="Open purchase orders" value={String(openOrders)}/><Metric label="Submitted orders" value={String(orders.filter(o=>o.status==='submitted').length)}/><Metric label="Vendor notes" value={String(notes.length)}/></div>
    <section className={styles.section}><div className={styles.card}><h2>Add / update vendor</h2><form onSubmit={saveVendor}><div className={styles.formGrid}><Field label="Vendor name"><input required maxLength={200} value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Contact"><input maxLength={200} value={form.contact_name} onChange={e=>setForm({...form,contact_name:e.target.value})}/></Field><Field label="Phone"><input maxLength={100} value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></Field><Field label="Email"><input type="email" maxLength={254} value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="Account number"><input maxLength={200} value={form.account_number} onChange={e=>setForm({...form,account_number:e.target.value})}/></Field><Field label="Delivery / ordering notes" wide><textarea maxLength={4000} value={form.delivery_notes} onChange={e=>setForm({...form,delivery_notes:e.target.value})}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy}>Save vendor</button></div></form></div></section>
    <section className={styles.section}><h2>Vendor directory</h2><div className={styles.list}>{vendors.map(v=><div className={styles.entry} key={v.id}><div className={styles.entryHead}><div><h3>{v.name}</h3><small>{v.contact_name||'No contact'}{v.phone?` · ${v.phone}`:''}{v.email?` · ${v.email}`:''}</small></div><span className={styles.pill}>{orders.filter(o=>o.vendor_id===v.id&&['draft','submitted'].includes(o.status)).length} open orders</span></div><div className={styles.details}>{detail('Account',v.account_number)}{detail('Delivery / ordering',v.delivery_notes)}</div></div>)}</div></section>
    <div className={styles.split}><section className={styles.section}><div className={styles.card}><h2>Vendor service note</h2><form onSubmit={addNote}><div className={styles.formGrid}><Field label="Vendor"><select value={noteForm.vendor_id} onChange={e=>setNoteForm({...noteForm,vendor_id:e.target.value})}><option value="">Choose vendor</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></Field><Field label="Note" wide><textarea value={noteForm.note} onChange={e=>setNoteForm({...noteForm,note:e.target.value})}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy}>Save note</button></div></form></div></section><section className={styles.section}><div className={styles.card}><h2>Recent purchase orders</h2><div className={styles.list}>{orders.slice(0,12).map(o=><div className={styles.entry} key={o.id}><div className={styles.entryHead}><div><h3>{vendorName(o.vendor_id)}</h3><small>{o.order_date}{o.expected_date?` · expected ${o.expected_date}`:''}</small></div><span className={styles.pill}>{o.status}</span></div></div>)}</div></div></section></div>
    <section className={styles.section}><h2>Vendor history</h2><div className={styles.list}>{notes.length?notes.map(n=><div className={styles.entry} key={n.id}><div className={styles.entryHead}><div><h3>{n.data?.vendor_name||n.title}</h3><small>{new Date(n.occurred_at||n.created_at).toLocaleString()}</small></div></div><div className={styles.details}>{detail('Note',n.data?.note)}</div></div>):<div className={styles.empty}>No vendor service notes yet.</div>}</div></section>
  </main>}
function Metric({label,value}:{label:string;value:string}){return <div className={styles.metric}><span>{label}</span><strong>{value}</strong></div>}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={`${styles.field} ${wide?styles.wide:''}`}><span>{label}</span>{children}</label>}
function detail(label:string,value?:string|null){return value?.trim()?<div className={styles.detail}><b>{label}</b><span>{value}</span></div>:null}
