'use client';

import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase';
import {useI18n} from '@/lib/i18n';
import styles from '../../ops-tools.module.css';
import {businessDateInZone} from '@/lib/intermediate-hardening';
import {addDateDays,dateDayOfWeek} from '@/lib/scheduling-engine';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Period={id:string;starts_on:string;ends_on:string;revision:number};
type DayReport={business_date:string;projected_sales:number;scheduled_paid_hours:number;base_labor_cost:number;base_labor_percent:number|null;sales_per_labor_hour:number|null};
type Report={period_id:string;starts_on:string;ends_on:string;days:DayReport[];projected_sales:number;scheduled_paid_hours:number;base_labor_cost:number;overtime_hours:number;overtime_premium:number;scheduled_labor_cost:number;labor_percent:number|null;sales_per_labor_hour:number|null;labor_percent_target:number|null;sales_per_labor_hour_target:number|null;weekly_labor_cost_target:number|null};
type Targets={labor_percent_target:string;sales_per_labor_hour_target:string;weekly_labor_cost_target:string};

const num=(v:unknown)=>Number.isFinite(Number(v))?Number(v):0;
const mondayOf=(d:string)=>addDateDays(d,-((dateDayOfWeek(d)+6)%7));
export default function LaborBudgetPage(){
 const {locale}=useI18n();const t=(en:string,es:string)=>locale==='es'?es:en;const localeCode=locale==='es'?'es-US':'en-US';const money=(v:number|null|undefined)=>Number(v||0).toLocaleString(localeCode,{style:'currency',currency:'USD',maximumFractionDigits:2});
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[profile,setProfile]=useState<Profile|null>(null),[weekStart,setWeekStart]=useState(()=>mondayOf(businessDateInZone())),[period,setPeriod]=useState<Period|null>(null),[report,setReport]=useState<Report|null>(null),[targets,setTargets]=useState<Targets>({labor_percent_target:'',sales_per_labor_hour_target:'',weekly_labor_cost_target:''}),[forecasts,setForecasts]=useState<Record<string,string>>({});
 const canManage=profile?.app_role==='admin'||profile?.app_role==='manager';
 useEffect(()=>{void init()},[]);
 async function init(){const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}const p=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();if(p.error||!p.data?.location_id){setMessage(t('Could not load labor-budget access.','No se pudo cargar el acceso al presupuesto laboral.'));setReady(true);return}const pr=p.data as Profile;setProfile(pr);await load(pr,weekStart);setReady(true)}
 async function load(pr=profile,ws=weekStart){if(!pr?.location_id)return;setBusy(true);try{let per:any=null;if(pr.app_role==='admin'||pr.app_role==='manager'){const r=await supabase.rpc('ensure_schedule_period',{p_starts_on:ws});if(r.error)throw r.error;per=r.data}else{const r=await supabase.from('schedule_periods').select('id,starts_on,ends_on,revision').eq('location_id',pr.location_id).eq('starts_on',ws).maybeSingle();if(r.error)throw r.error;per=r.data}setPeriod(per as Period|null);const s=await supabase.from('schedule_settings').select('labor_percent_target,sales_per_labor_hour_target,weekly_labor_cost_target').eq('location_id',pr.location_id).maybeSingle();if(s.error)throw s.error;setTargets({labor_percent_target:s.data?.labor_percent_target==null?'':String(s.data.labor_percent_target),sales_per_labor_hour_target:s.data?.sales_per_labor_hour_target==null?'':String(s.data.sales_per_labor_hour_target),weekly_labor_cost_target:s.data?.weekly_labor_cost_target==null?'':String(s.data.weekly_labor_cost_target)});const f=await supabase.from('schedule_daily_forecasts').select('business_date,projected_sales').eq('location_id',pr.location_id).gte('business_date',ws).lte('business_date',addDateDays(ws,6));if(f.error)throw f.error;const map:Record<string,string>={};for(let i=0;i<7;i++)map[addDateDays(ws,i)]='';for(const x of f.data??[])map[x.business_date]=String(x.projected_sales);setForecasts(map);if(per){const rr=await supabase.rpc('schedule_labor_budget_report',{p_period_id:per.id});if(rr.error)throw rr.error;setReport(rr.data as Report)}else setReport(null)}catch(e:any){setMessage(e?.message||t('Could not load labor budget.','No se pudo cargar el presupuesto laboral.'))}finally{setBusy(false)}}
 async function changeWeek(days:number){if(busy)return;const ws=addDateDays(weekStart,days);setWeekStart(ws);await load(profile,ws)}
 async function saveTargets(){if(!canManage||!profile?.location_id||busy)return;const lp=targets.labor_percent_target===''?null:num(targets.labor_percent_target),splh=targets.sales_per_labor_hour_target===''?null:num(targets.sales_per_labor_hour_target),weekly=targets.weekly_labor_cost_target===''?null:num(targets.weekly_labor_cost_target);if(lp!==null&&(lp<0||lp>100)){setMessage(t('Labor percent target must be between 0 and 100.','El objetivo de porcentaje laboral debe estar entre 0 y 100.'));return}if((splh!==null&&splh<=0)||(weekly!==null&&weekly<0)){setMessage(t('Labor targets must be positive.','Los objetivos laborales deben ser positivos.'));return}setBusy(true);const {error}=await supabase.from('schedule_settings').upsert({location_id:profile.location_id,labor_percent_target:lp,sales_per_labor_hour_target:splh,weekly_labor_cost_target:weekly},{onConflict:'location_id'});setMessage(error?error.message:t('Labor targets saved.','Objetivos laborales guardados.'));await load();setBusy(false)}
 async function saveForecast(date:string){if(!canManage||!profile?.location_id||busy)return;const value=forecasts[date];if(value===''||num(value)<0){setMessage(t('Projected sales must be zero or greater.','Las ventas proyectadas deben ser cero o más.'));return}setBusy(true);const {error}=await supabase.from('schedule_daily_forecasts').upsert({location_id:profile.location_id,business_date:date,projected_sales:num(value),source:'manual',confidence:100},{onConflict:'location_id,business_date'});setMessage(error?error.message:`${t('Projected sales saved for','Ventas proyectadas guardadas para')} ${date}.`);await load();setBusy(false)}
 const dayMap=useMemo(()=>new Map((report?.days??[]).map(x=>[x.business_date,x])),[report]);
 const splhTarget=targets.sales_per_labor_hour_target===''?null:num(targets.sales_per_labor_hour_target);
 if(!ready)return <div className="full-loader"><span>{t('Opening labor budget…','Abriendo presupuesto laboral…')}</span></div>;
 return <main className={styles.page}><div className={styles.top}><div><h1>{t('Labor Budget','Presupuesto Laboral')}</h1><p>{t('Compare projected sales with paid scheduled hours and labor cost before the schedule is published.','Compara ventas proyectadas con horas pagadas y costo laboral antes de publicar el horario.')}</p></div><Link className={styles.back} href="/schedule">{t('Back to Schedule','Volver al Horario')}</Link></div>
 {message&&<div className={message.toLowerCase().includes('could not')||message.toLowerCase().includes('no se pudo')?styles.error:styles.notice}>{message}</div>}
 {!canManage?<div className={styles.error}>{t('Manager access is required for wage and labor-budget data.','Se requiere acceso gerencial para datos salariales y presupuesto laboral.')}</div>:<>
 <section className={styles.section}><div className={styles.card}><div className={styles.entryHead}><div><h2>{t('Week of','Semana del')} {weekStart}</h2><small>{period?t('Schedule period loaded','Período cargado'):t('No schedule period yet','Aún no hay período')}</small></div><div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>changeWeek(-7)}>{t('Previous','Anterior')}</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>changeWeek(7)}>{t('Next','Siguiente')}</button></div></div></div></section>
 <section className={styles.section}><div className={styles.card}><h2>{t('Weekly targets','Objetivos semanales')}</h2><div className={styles.formGrid}><label className={styles.field}><span>{t('Target labor %','% laboral objetivo')}</span><input type="number" min="0" max="100" step="0.1" value={targets.labor_percent_target} onChange={e=>setTargets({...targets,labor_percent_target:e.target.value})}/></label><label className={styles.field}><span>{t('Target sales per labor hour','Ventas objetivo por hora laboral')}</span><input type="number" min="0.01" step="0.01" value={targets.sales_per_labor_hour_target} onChange={e=>setTargets({...targets,sales_per_labor_hour_target:e.target.value})}/></label><label className={styles.field}><span>{t('Weekly labor-cost budget','Presupuesto laboral semanal')}</span><input type="number" min="0" step="0.01" value={targets.weekly_labor_cost_target} onChange={e=>setTargets({...targets,weekly_labor_cost_target:e.target.value})}/></label></div><div className={styles.actions}><button className={styles.button} disabled={busy} onClick={saveTargets}>{t('Save Labor Targets','Guardar Objetivos Laborales')}</button></div></div></section>
 {report&&<section className={styles.section}><div className={styles.card}><h2>{t('Week snapshot','Resumen semanal')}</h2><div className={styles.details}><Metric label={t('Projected sales','Ventas proyectadas')} value={money(report.projected_sales)}/><Metric label={t('Paid scheduled hours','Horas pagadas programadas')} value={`${num(report.scheduled_paid_hours).toFixed(1)} ${t('hrs','h')}`}/><Metric label={t('Base labor cost','Costo laboral base')} value={money(report.base_labor_cost)}/><Metric label={t('Overtime premium','Prima de horas extra')} value={`${money(report.overtime_premium)} · ${num(report.overtime_hours).toFixed(1)} OT ${t('hrs','h')}`}/><Metric label={t('Scheduled labor cost','Costo laboral programado')} value={money(report.scheduled_labor_cost)}/><Metric label={t('Labor %','% laboral')} value={report.labor_percent==null?'—':`${num(report.labor_percent).toFixed(1)}%${report.labor_percent_target!=null?` / ${num(report.labor_percent_target).toFixed(1)}% ${t('target','objetivo')}`:''}`}/><Metric label={t('Sales / labor hr','Ventas / hora laboral')} value={report.sales_per_labor_hour==null?'—':`${money(report.sales_per_labor_hour)}${report.sales_per_labor_hour_target!=null?` / ${money(report.sales_per_labor_hour_target)} ${t('target','objetivo')}`:''}`}/><Metric label={t('Weekly cost budget','Presupuesto semanal')} value={report.weekly_labor_cost_target==null?'—':money(report.weekly_labor_cost_target)}/></div></div></section>}
 <section className={styles.section}><h2>{t('Daily sales & labor','Ventas y trabajo diarios')}</h2><div className={styles.list}>{Array.from({length:7},(_,i)=>addDateDays(weekStart,i)).map(date=>{const d=dayMap.get(date);const projected=num(forecasts[date]);const recommended=splhTarget&&splhTarget>0?projected/splhTarget:null;return <div className={styles.entry} key={date}><div className={styles.entryHead}><div><h3>{date}</h3><small>{d?`${num(d.scheduled_paid_hours).toFixed(1)} ${t('paid hrs','h pagadas')} · ${money(d.base_labor_cost)} ${t('base cost','costo base')} · ${d.base_labor_percent==null?'—':`${num(d.base_labor_percent).toFixed(1)}% ${t('labor','laboral')}`}`:t('No scheduled labor yet','Aún no hay trabajo programado')}</small></div>{recommended!=null&&<span className={styles.pill}>{recommended.toFixed(1)} {t('target hrs','h objetivo')}</span>}</div><div className={styles.formGrid}><label className={styles.field}><span>{t('Projected sales','Ventas proyectadas')}</span><input type="number" min="0" step="1" value={forecasts[date]??''} onChange={e=>setForecasts({...forecasts,[date]:e.target.value})}/></label><label className={styles.field}><span>{t('Sales / scheduled hr','Ventas / hora programada')}</span><input readOnly value={d?.sales_per_labor_hour==null?'—':money(d.sales_per_labor_hour)}/></label></div><div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>saveForecast(date)}>{t('Save Sales Forecast','Guardar Pronóstico de Ventas')}</button></div></div>})}</div></section>
 <section className={styles.section}><div className={styles.notice}><b>{t('Recommended hours are deterministic.','Las horas recomendadas son deterministas.')}</b><small style={{display:'block',marginTop:6}}>{t('When a Sales per Labor Hour target is set, target hours = projected sales ÷ SPLH target. The app does not invent an “AI” labor recommendation when there is not enough restaurant history.','Cuando se define un objetivo de ventas por hora laboral, las horas objetivo = ventas proyectadas ÷ objetivo SPLH. La aplicación no inventa recomendaciones de “IA” sin suficiente historial del restaurante.')}</small></div></section>
 </>}
 </main>
}
function Metric({label,value}:{label:string;value:string}){return <div className={styles.detail}><b>{label}</b><span>{value}</span></div>}
