'use client';

import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase';
import styles from '../../ops-tools.module.css';
import {businessDateInZone} from '@/lib/intermediate-hardening';
import {addDateDays,dateDayOfWeek} from '@/lib/scheduling-engine';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Period={id:string;starts_on:string;ends_on:string;revision:number};
type DayReport={business_date:string;projected_sales:number;scheduled_paid_hours:number;base_labor_cost:number;base_labor_percent:number|null;sales_per_labor_hour:number|null};
type Report={period_id:string;starts_on:string;ends_on:string;days:DayReport[];projected_sales:number;scheduled_paid_hours:number;base_labor_cost:number;overtime_hours:number;overtime_premium:number;scheduled_labor_cost:number;labor_percent:number|null;sales_per_labor_hour:number|null;labor_percent_target:number|null;sales_per_labor_hour_target:number|null;weekly_labor_cost_target:number|null};
type Targets={labor_percent_target:string;sales_per_labor_hour_target:string;weekly_labor_cost_target:string};
const money=(v:number|null|undefined)=>Number(v||0).toLocaleString([],{style:'currency',currency:'USD',maximumFractionDigits:2});
const num=(v:unknown)=>Number.isFinite(Number(v))?Number(v):0;
const mondayOf=(d:string)=>addDateDays(d,-((dateDayOfWeek(d)+6)%7));
export default function LaborBudgetPage(){
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[profile,setProfile]=useState<Profile|null>(null),[weekStart,setWeekStart]=useState(()=>mondayOf(businessDateInZone())),[period,setPeriod]=useState<Period|null>(null),[report,setReport]=useState<Report|null>(null),[targets,setTargets]=useState<Targets>({labor_percent_target:'',sales_per_labor_hour_target:'',weekly_labor_cost_target:''}),[forecasts,setForecasts]=useState<Record<string,string>>({});
 const canManage=profile?.app_role==='admin'||profile?.app_role==='manager';
 useEffect(()=>{void init()},[]);
 async function init(){const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}const p=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();if(p.error||!p.data?.location_id){setMessage('Could not load labor-budget access.');setReady(true);return}const pr=p.data as Profile;setProfile(pr);await load(pr,weekStart);setReady(true)}
 async function load(pr=profile,ws=weekStart){if(!pr?.location_id)return;setBusy(true);try{let per:any=null;if(pr.app_role==='admin'||pr.app_role==='manager'){const r=await supabase.rpc('ensure_schedule_period',{p_starts_on:ws});if(r.error)throw r.error;per=r.data}else{const r=await supabase.from('schedule_periods').select('id,starts_on,ends_on,revision').eq('location_id',pr.location_id).eq('starts_on',ws).maybeSingle();if(r.error)throw r.error;per=r.data}setPeriod(per as Period|null);const s=await supabase.from('schedule_settings').select('labor_percent_target,sales_per_labor_hour_target,weekly_labor_cost_target').eq('location_id',pr.location_id).maybeSingle();if(s.error)throw s.error;setTargets({labor_percent_target:s.data?.labor_percent_target==null?'':String(s.data.labor_percent_target),sales_per_labor_hour_target:s.data?.sales_per_labor_hour_target==null?'':String(s.data.sales_per_labor_hour_target),weekly_labor_cost_target:s.data?.weekly_labor_cost_target==null?'':String(s.data.weekly_labor_cost_target)});const f=await supabase.from('schedule_daily_forecasts').select('business_date,projected_sales').eq('location_id',pr.location_id).gte('business_date',ws).lte('business_date',addDateDays(ws,6));if(f.error)throw f.error;const map:Record<string,string>={};for(let i=0;i<7;i++)map[addDateDays(ws,i)]='';for(const x of f.data??[])map[x.business_date]=String(x.projected_sales);setForecasts(map);if(per){const rr=await supabase.rpc('schedule_labor_budget_report',{p_period_id:per.id});if(rr.error)throw rr.error;setReport(rr.data as Report)}else setReport(null)}catch(e:any){setMessage(e?.message||'Could not load labor budget.')}finally{setBusy(false)}}
 async function changeWeek(days:number){if(busy)return;const ws=addDateDays(weekStart,days);setWeekStart(ws);await load(profile,ws)}
 async function saveTargets(){if(!canManage||!profile?.location_id||busy)return;const lp=targets.labor_percent_target===''?null:num(targets.labor_percent_target),splh=targets.sales_per_labor_hour_target===''?null:num(targets.sales_per_labor_hour_target),weekly=targets.weekly_labor_cost_target===''?null:num(targets.weekly_labor_cost_target);if(lp!==null&&(lp<0||lp>100)){setMessage('Labor percent target must be between 0 and 100.');return}if((splh!==null&&splh<=0)||(weekly!==null&&weekly<0)){setMessage('Labor targets must be positive.');return}setBusy(true);const {error}=await supabase.from('schedule_settings').upsert({location_id:profile.location_id,labor_percent_target:lp,sales_per_labor_hour_target:splh,weekly_labor_cost_target:weekly},{onConflict:'location_id'});setMessage(error?error.message:'Labor targets saved.');await load();setBusy(false)}
 async function saveForecast(date:string){if(!canManage||!profile?.location_id||busy)return;const value=forecasts[date];if(value===''||num(value)<0){setMessage('Projected sales must be zero or greater.');return}setBusy(true);const {error}=await supabase.from('schedule_daily_forecasts').upsert({location_id:profile.location_id,business_date:date,projected_sales:num(value),source:'manual',confidence:100},{onConflict:'location_id,business_date'});setMessage(error?error.message:`Projected sales saved for ${date}.`);await load();setBusy(false)}
 const dayMap=useMemo(()=>new Map((report?.days??[]).map(x=>[x.business_date,x])),[report]);
 const splhTarget=targets.sales_per_labor_hour_target===''?null:num(targets.sales_per_labor_hour_target);
 if(!ready)return <div className="full-loader"><span>Opening labor budget…</span></div>;
 return <main className={styles.page}><div className={styles.top}><div><h1>Labor Budget</h1><p>Compare projected sales with paid scheduled hours and labor cost before the schedule is published.</p></div><Link className={styles.back} href="/schedule">Back to Schedule</Link></div>
 {message&&<div className={message.toLowerCase().includes('could not')?styles.error:styles.notice}>{message}</div>}
 {!canManage?<div className={styles.error}>Manager access is required for wage and labor-budget data.</div>:<>
 <section className={styles.section}><div className={styles.card}><div className={styles.entryHead}><div><h2>Week of {weekStart}</h2><small>{period?'Schedule period loaded':'No schedule period yet'}</small></div><div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>changeWeek(-7)}>Previous</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>changeWeek(7)}>Next</button></div></div></div></section>
 <section className={styles.section}><div className={styles.card}><h2>Weekly targets</h2><div className={styles.formGrid}><label className={styles.field}><span>Target labor %</span><input type="number" min="0" max="100" step="0.1" value={targets.labor_percent_target} onChange={e=>setTargets({...targets,labor_percent_target:e.target.value})}/></label><label className={styles.field}><span>Target sales per labor hour</span><input type="number" min="0.01" step="0.01" value={targets.sales_per_labor_hour_target} onChange={e=>setTargets({...targets,sales_per_labor_hour_target:e.target.value})}/></label><label className={styles.field}><span>Weekly labor-cost budget</span><input type="number" min="0" step="0.01" value={targets.weekly_labor_cost_target} onChange={e=>setTargets({...targets,weekly_labor_cost_target:e.target.value})}/></label></div><div className={styles.actions}><button className={styles.button} disabled={busy} onClick={saveTargets}>Save Labor Targets</button></div></div></section>
 {report&&<section className={styles.section}><div className={styles.card}><h2>Week snapshot</h2><div className={styles.details}><Metric label="Projected sales" value={money(report.projected_sales)}/><Metric label="Paid scheduled hours" value={`${num(report.scheduled_paid_hours).toFixed(1)} hrs`}/><Metric label="Base labor cost" value={money(report.base_labor_cost)}/><Metric label="Overtime premium" value={`${money(report.overtime_premium)} · ${num(report.overtime_hours).toFixed(1)} OT hrs`}/><Metric label="Scheduled labor cost" value={money(report.scheduled_labor_cost)}/><Metric label="Labor %" value={report.labor_percent==null?'—':`${num(report.labor_percent).toFixed(1)}%${report.labor_percent_target!=null?` / ${num(report.labor_percent_target).toFixed(1)}% target`:''}`}/><Metric label="Sales / labor hr" value={report.sales_per_labor_hour==null?'—':`${money(report.sales_per_labor_hour)}${report.sales_per_labor_hour_target!=null?` / ${money(report.sales_per_labor_hour_target)} target`:''}`}/><Metric label="Weekly cost budget" value={report.weekly_labor_cost_target==null?'—':money(report.weekly_labor_cost_target)}/></div></div></section>}
 <section className={styles.section}><h2>Daily sales & labor</h2><div className={styles.list}>{Array.from({length:7},(_,i)=>addDateDays(weekStart,i)).map(date=>{const d=dayMap.get(date);const projected=num(forecasts[date]);const recommended=splhTarget&&splhTarget>0?projected/splhTarget:null;return <div className={styles.entry} key={date}><div className={styles.entryHead}><div><h3>{date}</h3><small>{d?`${num(d.scheduled_paid_hours).toFixed(1)} paid hrs · ${money(d.base_labor_cost)} base cost · ${d.base_labor_percent==null?'—':`${num(d.base_labor_percent).toFixed(1)}% labor`}`:'No scheduled labor yet'}</small></div>{recommended!=null&&<span className={styles.pill}>{recommended.toFixed(1)} target hrs</span>}</div><div className={styles.formGrid}><label className={styles.field}><span>Projected sales</span><input type="number" min="0" step="1" value={forecasts[date]??''} onChange={e=>setForecasts({...forecasts,[date]:e.target.value})}/></label><label className={styles.field}><span>Sales / scheduled hr</span><input readOnly value={d?.sales_per_labor_hour==null?'—':money(d.sales_per_labor_hour)}/></label></div><div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>saveForecast(date)}>Save Sales Forecast</button></div></div>})}</div></section>
 <section className={styles.section}><div className={styles.notice}><b>Recommended hours are deterministic.</b><small style={{display:'block',marginTop:6}}>When a Sales per Labor Hour target is set, target hours = projected sales ÷ SPLH target. The app does not invent an “AI” labor recommendation when there is not enough restaurant history.</small></div></section>
 </>}
 </main>
}
function Metric({label,value}:{label:string;value:string}){return <div className={styles.detail}><b>{label}</b><span>{value}</span></div>}
