'use client';

import { FormEvent, useEffect, useState } from 'react';
import { ArrowLeft, Check, ClipboardCheck, Loader2, Plus, Trash2 } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Procedure={id:string;title:string;description:string|null;status:string;approved_at:string|null;version:number};
type Step={id:string;procedure_id:string;step_number:number;instruction:string;requires_photo:boolean};

export default function ProceduresPage(){
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[profile,setProfile]=useState<Profile|null>(null),[procedures,setProcedures]=useState<Procedure[]>([]),[steps,setSteps]=useState<Step[]>([]),[title,setTitle]=useState(''),[description,setDescription]=useState('');
 const canManage=profile?.app_role==='admin'||profile?.app_role==='manager';
 useEffect(()=>{void load()},[]);
 async function load(){setLoading(true);const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return;}const [p,pr,st]=await Promise.all([supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single(),supabase.from('procedures').select('id,title,description,status,approved_at,version').is('deleted_at',null).order('updated_at',{ascending:false}),supabase.from('procedure_steps').select('id,procedure_id,step_number,instruction,requires_photo').order('step_number')]);setProfile(p.data as Profile);setProcedures((pr.data??[]) as Procedure[]);setSteps((st.data??[]) as Step[]);setLoading(false)}
 function flash(x:string){setMessage(x);setTimeout(()=>setMessage(''),3500)}
 async function create(e:FormEvent){e.preventDefault();if(!profile?.location_id||!canManage)return;setBusy(true);const {error}=await supabase.from('procedures').insert({location_id:profile.location_id,title:title.trim().slice(0,200),description:description.trim().slice(0,8000)||null,status:'draft'});setBusy(false);if(error)return flash(error.message);setTitle('');setDescription('');await load();flash('Procedure draft created.')}
 async function addStep(p:Procedure){if(!canManage)return;const instruction=prompt('Step instruction');if(!instruction?.trim())return;const n=steps.filter(s=>s.procedure_id===p.id).length+1;const {error}=await supabase.from('procedure_steps').insert({procedure_id:p.id,step_number:n,instruction:instruction.trim().slice(0,4000)});if(error)return flash(error.message);await load()}
 async function removeStep(s:Step){if(!canManage||!confirm('Delete this step?'))return;const {error}=await supabase.from('procedure_steps').delete().eq('id',s.id);if(error)return flash(error.message);await renumber(s.procedure_id,s.id);await load()}
 async function renumber(id:string,excludeId?:string){const list=steps.filter(s=>s.procedure_id===id&&s.id!==excludeId).sort((a,b)=>a.step_number-b.step_number);for(let i=0;i<list.length;i++){if(list[i].step_number!==i+1){const {error}=await supabase.from('procedure_steps').update({step_number:i+1}).eq('id',list[i].id);if(error)throw error}}}
 async function approve(p:Procedure){if(!canManage)return;const {data:u}=await supabase.auth.getUser();const next=p.status==='approved'?'draft':'approved';const {error}=await supabase.from('procedures').update({status:next,approved_by:next==='approved'?u.user?.id:null,approved_at:next==='approved'?new Date().toISOString():null}).eq('id',p.id);if(error)return flash(error.message);await load();flash(next==='approved'?'Procedure approved.':'Procedure returned to draft.')}
 async function convert(p:Procedure){if(!canManage)return;const period=(prompt('Checklist period: opening, mid_shift, closing, or other','other')||'other').trim();const {data,error}=await supabase.rpc('create_checklist_from_procedure',{p_procedure_id:p.id,p_title:null,p_period:period});if(error)return flash(error.message);flash(`Checklist created (${String(data).slice(0,8)}…).`)}
 if(loading)return <div className="full-loader"><Loader2 className="spin"/><span>Opening procedures…</span></div>;
 return <div className="app-shell"><header className="topbar"><a className="round-button" href="/" aria-label="Back"><ArrowLeft/></a><div style={{flex:1}}><div className="brand-kicker">El Molino Ops</div><div className="brand-title">Procedures</div></div></header><main className="page">{message&&<div className="toast-message">{message}</div>}<div className="page-heading"><h1>Procedure builder</h1><p>Draft, approve, version and convert operational standards into executable checklists.</p></div>{canManage&&<form className="card form" onSubmit={create}><h3>New procedure</h3><input className="input" value={title} onChange={e=>setTitle(e.target.value)} placeholder="Procedure title" required/><textarea className="textarea" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Purpose / expected outcome"/><button className="btn" disabled={busy}><Plus/> Create draft</button></form>}<div className="section-title"><h2>Procedures</h2><span>{procedures.length}</span></div><div className="list">{procedures.map(p=>{const ps=steps.filter(s=>s.procedure_id===p.id).sort((a,b)=>a.step_number-b.step_number);return <details className="list-item" key={p.id}><summary style={{display:'flex',alignItems:'center',gap:12}}><div className="list-main"><b>{p.title}</b><small>{p.status} · version {p.version} · {ps.length} steps</small></div><span className="status">{p.status}</span></summary><div className="ops-detail">{p.description&&<p>{p.description}</p>}<div className="list">{ps.map(s=><div className="list-item" key={s.id}><span className="status">{s.step_number}</span><div className="list-main"><b>{s.instruction}</b>{s.requires_photo&&<small>Photo required</small>}</div>{canManage&&<button className="icon-action danger-action" onClick={()=>removeStep(s)} aria-label="Delete step"><Trash2 size={14}/></button>}</div>)}</div>{canManage&&<div className="row-actions" style={{marginTop:12,flexWrap:'wrap'}}><button className="mini-action" onClick={()=>addStep(p)}><Plus/> Add step</button><button className="mini-action" onClick={()=>approve(p)}><Check/> {p.status==='approved'?'Return to draft':'Approve'}</button><button className="mini-action" onClick={()=>convert(p)} disabled={p.status!=='approved'}><ClipboardCheck/> Convert to checklist</button><a className="mini-action" href={`/capture?entityType=procedure&entityId=${p.id}`}>Attach file</a></div>}</div></details>})}{!procedures.length&&<div className="empty-state"><ClipboardCheck/><b>No procedures yet</b><span>Create a draft, add steps, approve it, then turn it into a checklist.</span></div>}</div></main></div>;
}
