'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { supabase } from '@/lib/supabase';
import { useI18n } from '@/lib/i18n';
import styles from '../ops-tools.module.css';
import { businessDateInZone } from '@/lib/intermediate-hardening';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Vendor={id:string;name:string;active:boolean};
type Item={id:string;vendor_id:string|null;name:string;category:string;unit:string;par_level:number;reorder_level:number;unit_cost:number;active:boolean};
type Count={id:string;counted_on:string;status:string};
type CountLine={item_id:string;quantity:number;unit_cost_snapshot:number};
type Waste={id:string;item_id:string;quantity:number;unit_cost_snapshot:number;reason:string;occurred_at:string};
type PO={id:string;vendor_id:string|null;order_date:string;expected_date:string|null;status:string;created_at:string};
type MenuItem={id:string;name:string;base_price:number|null};
type Recipe={id:string;menu_item_id:string;inventory_item_id:string;quantity:number};
const money=(n:number,localeCode:string)=>new Intl.NumberFormat(localeCode,{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(n)||0);
const today=()=>businessDateInZone();

export default function InventoryPage(){
  const {locale}=useI18n();const t=(en:string,es:string)=>locale==='es'?es:en;const localeCode=locale==='es'?'es-US':'en-US';const statusLabel=(v:string)=>locale==='es'?({draft:'borrador',final:'finalizado',submitted:'enviado',received:'recibido'}[v]||v):v;const categoryLabel=(v:string)=>locale==='es'?({food:'alimentos',beer:'cerveza',wine:'vino',liquor:'licor',non_alcoholic:'sin alcohol',paper:'papel',cleaning:'limpieza',other:'otro'}[v]||v):v.replaceAll('_',' ');
  const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[profile,setProfile]=useState<Profile|null>(null),[message,setMessage]=useState('');
  const [vendors,setVendors]=useState<Vendor[]>([]),[items,setItems]=useState<Item[]>([]),[count,setCount]=useState<Count|null>(null),[lines,setLines]=useState<CountLine[]>([]),[waste,setWaste]=useState<Waste[]>([]),[orders,setOrders]=useState<PO[]>([]),[menu,setMenu]=useState<MenuItem[]>([]),[recipes,setRecipes]=useState<Recipe[]>([]);
  const [vendorForm,setVendorForm]=useState({name:''});
  const [itemForm,setItemForm]=useState({name:'',category:'food',unit:'each',par_level:'0',reorder_level:'0',unit_cost:'0',vendor_id:''});
  const [countForm,setCountForm]=useState({item_id:'',quantity:'0'}),[wasteForm,setWasteForm]=useState({item_id:'',quantity:'1',reason:''}),[recipeForm,setRecipeForm]=useState({menu_item_id:'',inventory_item_id:'',quantity:'1'});
  useEffect(()=>{void init()},[]);
  async function init(){const {data:u}=await supabase.auth.getUser();if(!u.user){window.location.href='/';return;}const {data:p}=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();setProfile((p||null) as Profile|null);if(p?.location_id&&['admin','manager'].includes(p.app_role))await load(p.location_id);setReady(true);}
  async function load(locationId=profile?.location_id||''){if(!locationId)return;const [v,i,c,w,o,m,r]=await Promise.all([
    supabase.from('restaurant_vendors').select('id,name,active').eq('location_id',locationId).eq('active',true).order('name'),
    supabase.from('inventory_items').select('id,vendor_id,name,category,unit,par_level,reorder_level,unit_cost,active').eq('location_id',locationId).eq('active',true).order('name'),
    supabase.from('inventory_counts').select('id,counted_on,status').eq('location_id',locationId).order('counted_on',{ascending:false}).limit(1).maybeSingle(),
    supabase.from('waste_entries').select('id,item_id,quantity,unit_cost_snapshot,reason,occurred_at').eq('location_id',locationId).order('occurred_at',{ascending:false}).limit(30),
    supabase.from('purchase_orders').select('id,vendor_id,order_date,expected_date,status,created_at').eq('location_id',locationId).order('created_at',{ascending:false}).limit(30),
    supabase.from('menu_items').select('id,name,base_price').eq('location_id',locationId).eq('active',true).order('name'),
    supabase.from('recipe_cost_components').select('id,menu_item_id,inventory_item_id,quantity').eq('location_id',locationId)
  ]);setVendors((v.data??[]) as Vendor[]);setItems((i.data??[]) as Item[]);setWaste((w.data??[]) as Waste[]);setOrders((o.data??[]) as PO[]);setMenu((m.data??[]) as MenuItem[]);setRecipes((r.data??[]) as Recipe[]);const latest=(c.data||null) as Count|null;setCount(latest);if(latest){const q=await supabase.from('inventory_count_lines').select('item_id,quantity,unit_cost_snapshot').eq('count_id',latest.id);setLines((q.data??[]) as CountLine[]);}else setLines([]);if(v.error||i.error||c.error||w.error||o.error||m.error||r.error)setMessage(t('Some inventory data could not be loaded.','Algunos datos de inventario no se pudieron cargar.'));}
  const qtyMap=useMemo(()=>new Map(lines.map(x=>[x.item_id,Number(x.quantity)||0])),[lines]);
  const suggested=useMemo(()=>items.filter(i=>qtyMap.has(i.id)).map(i=>({item:i,qty:qtyMap.get(i.id)!,suggested:Math.max(0,Number(i.par_level)-Number(qtyMap.get(i.id)!))})).filter(x=>x.qty<=Number(x.item.reorder_level)&&x.suggested>0),[items,qtyMap]);
  const inventoryValue=useMemo(()=>lines.reduce((n,l)=>n+Number(l.quantity)*Number(l.unit_cost_snapshot),0),[lines]);
  const wasteCost=useMemo(()=>waste.reduce((n,w)=>n+Number(w.quantity)*Number(w.unit_cost_snapshot),0),[waste]);
  const menuCosts=useMemo(()=>menu.map(mi=>{const cost=recipes.filter(r=>r.menu_item_id===mi.id).reduce((n,r)=>n+Number(r.quantity)*Number(items.find(i=>i.id===r.inventory_item_id)?.unit_cost||0),0);const price=Number(mi.base_price||0);return {id:mi.id,name:mi.name,price,cost,pct:price>0?cost/price*100:0};}).filter(x=>x.cost>0).sort((a,b)=>b.pct-a.pct),[menu,recipes,items]);
  const itemName=(id:string)=>items.find(i=>i.id===id)?.name||t('Unknown item','Artículo desconocido'),vendorName=(id:string|null)=>vendors.find(v=>v.id===id)?.name||t('No vendor','Sin proveedor');
  async function addVendor(e:FormEvent){e.preventDefault();if(!profile?.location_id||busy||!vendorForm.name.trim())return;setBusy(true);try{const {error}=await supabase.from('restaurant_vendors').insert({location_id:profile.location_id,name:vendorForm.name.trim().slice(0,200)});if(error)throw error;setVendorForm({name:''});await load();setMessage(t('Vendor added.','Proveedor agregado.'));}catch{setMessage(t('Could not add vendor.','No se pudo agregar el proveedor.'));}finally{setBusy(false)}}
  async function addItem(e:FormEvent){e.preventDefault();if(!profile?.location_id||busy||!itemForm.name.trim())return;setBusy(true);try{const {error}=await supabase.from('inventory_items').insert({location_id:profile.location_id,name:itemForm.name.trim().slice(0,200),category:itemForm.category,unit:itemForm.unit.trim().slice(0,60)||'each',par_level:Math.max(0,Number(itemForm.par_level)||0),reorder_level:Math.max(0,Number(itemForm.reorder_level)||0),unit_cost:Math.max(0,Number(itemForm.unit_cost)||0),vendor_id:itemForm.vendor_id||null});if(error)throw error;setItemForm({...itemForm,name:''});await load();setMessage(t('Inventory item added.','Artículo de inventario agregado.'));}catch{setMessage(t('Could not add inventory item.','No se pudo agregar el artículo.'));}finally{setBusy(false)}}
  async function ensureTodayCount(){if(!profile?.location_id)return null;if(count?.counted_on===today()){if(count.status==='final')throw new Error(t("Today's inventory count is finalized",'El conteo de inventario de hoy está finalizado'));return count.id;}const {data,error}=await supabase.from('inventory_counts').upsert({location_id:profile.location_id,counted_on:today(),status:'draft'},{onConflict:'location_id,counted_on'}).select('id,status').single();if(error)throw error;if(data.status!=='draft')throw new Error(t("Today's inventory count is finalized",'El conteo de inventario de hoy está finalizado'));return data.id as string;}
  async function saveCount(e:FormEvent){e.preventDefault();if(!countForm.item_id||busy)return;const item=items.find(i=>i.id===countForm.item_id);if(!item)return;setBusy(true);try{const countId=await ensureTodayCount();if(!countId)return;const {error}=await supabase.from('inventory_count_lines').upsert({count_id:countId,item_id:item.id,quantity:Math.max(0,Number(countForm.quantity)||0)},{onConflict:'count_id,item_id'});if(error)throw error;setCountForm({...countForm,quantity:'0'});await load();setMessage(t('Count updated.','Conteo actualizado.'));}catch{setMessage(t('Could not save inventory count.','No se pudo guardar el conteo.'));}finally{setBusy(false)}}
  async function addWaste(e:FormEvent){e.preventDefault();if(!profile?.location_id||!wasteForm.item_id||!wasteForm.reason.trim()||busy)return;const item=items.find(i=>i.id===wasteForm.item_id);if(!item)return;setBusy(true);try{const {error}=await supabase.from('waste_entries').insert({location_id:profile.location_id,item_id:item.id,quantity:Math.max(.001,Number(wasteForm.quantity)||0),reason:wasteForm.reason.trim().slice(0,1000)});if(error)throw error;setWasteForm({...wasteForm,quantity:'1',reason:''});await load();setMessage(t('Waste recorded.','Desperdicio registrado.'));}catch{setMessage(t('Could not record waste.','No se pudo registrar el desperdicio.'));}finally{setBusy(false)}}
  async function addRecipe(e:FormEvent){e.preventDefault();if(!profile?.location_id||!recipeForm.menu_item_id||!recipeForm.inventory_item_id||busy)return;setBusy(true);try{const {error}=await supabase.from('recipe_cost_components').upsert({location_id:profile.location_id,menu_item_id:recipeForm.menu_item_id,inventory_item_id:recipeForm.inventory_item_id,quantity:Math.max(.0001,Number(recipeForm.quantity)||0)},{onConflict:'menu_item_id,inventory_item_id'});if(error)throw error;await load();setMessage(t('Recipe cost component saved.','Componente de costo de receta guardado.'));}catch{setMessage(t('Could not save recipe component.','No se pudo guardar el componente de receta.'));}finally{setBusy(false)}}
  async function finalizeCount(){if(!count||count.status!=='draft'||!lines.length||busy)return;setBusy(true);try{const {error}=await supabase.rpc('finalize_inventory_count',{p_count_id:count.id});if(error)throw error;await load();setMessage(t('Inventory count finalized. Cost snapshots are now locked.','Conteo finalizado. Las instantáneas de costo están bloqueadas.'));}catch{setMessage(t('Could not finalize inventory count.','No se pudo finalizar el conteo.'));}finally{setBusy(false)}}
  async function createSuggestedOrders(){if(!profile?.location_id||!count||count.status!=='final'||!suggested.length||busy)return;setBusy(true);try{const {data,error}=await supabase.rpc('create_suggested_purchase_orders',{p_count_id:count.id});if(error)throw error;const created=Number(data||0);await load();setMessage(created?`${t('Created','Se crearon')} ${created} ${created===1?t('draft order.','orden en borrador.'):t('draft orders.','órdenes en borrador.')}`:t('Draft orders already exist for this inventory count.','Ya existen órdenes en borrador para este conteo.'));}catch{setMessage(t('Could not create draft orders. No partial order was saved.','No se pudieron crear órdenes. No se guardó ninguna orden parcial.'));}finally{setBusy(false)}}
  async function setOrderStatus(id:string,status:'submitted'|'received'){if(busy)return;setBusy(true);try{const {error}=await supabase.from('purchase_orders').update({status}).eq('id',id);if(error)throw error;await load();setMessage(`${t('Order marked','Orden marcada como')} ${statusLabel(status)}.`);}catch{setMessage(t('Could not update order.','No se pudo actualizar la orden.'));}finally{setBusy(false)}}
  if(!ready)return <main className={styles.page}>{t('Loading inventory…','Cargando inventario…')}</main>;
  if(!profile?.location_id||!['admin','manager'].includes(profile.app_role))return <main className={styles.page}><div className={styles.top}><div><h1>{t('Inventory & Food Cost','Inventario y Costo de Alimentos')}</h1><p>{t('Manager-only cost and ordering data.','Datos de costos y pedidos solo para gerentes.')}</p></div><Link className={styles.back} href="/">{t('Back','Volver')}</Link></div><div className={styles.error}>{t('Manager access is required.','Se requiere acceso gerencial.')}</div></main>;
  return <main className={styles.page}>
    <div className={styles.top}><div><h1>{t('Inventory & Food Cost','Inventario y Costo de Alimentos')}</h1><p>{t('Pars, counts, ordering, waste and theoretical recipe cost.','Niveles par, conteos, pedidos, desperdicio y costo teórico de recetas.')}</p></div><Link className={styles.back} href="/">{t('Back to Ops','Volver a Operaciones')}</Link></div>
    {message&&<div className={message.startsWith('Could not')||message.startsWith('Some')||message.startsWith('No se pudo')||message.startsWith('Algunos')?styles.error:styles.notice}>{message}</div>}
    <div className={styles.grid}><Metric label={t('Active items','Artículos activos')} value={String(items.length)}/><Metric label={t('Latest counted inventory value','Valor del último inventario')} value={money(inventoryValue,localeCode)}/><Metric label={t('Below reorder (counted)','Bajo nivel de reorden')} value={String(suggested.length)}/><Metric label={t('Recent waste cost','Costo de desperdicio reciente')} value={money(wasteCost,localeCode)}/></div>
    <div className={styles.split}><section className={styles.section}><div className={styles.card}><h2>{t('Quick count','Conteo rápido')}</h2><p className={styles.muted}>{t('Latest count','Último conteo')}: {count?.counted_on||t('none yet','ninguno')}{count?` · ${statusLabel(count.status)}`:''}</p>{count?.counted_on===today()&&count.status==='final'&&<div className={styles.notice}>{t('Today’s count is finalized and locked. Start tomorrow’s count on the next business date.','El conteo de hoy está finalizado y bloqueado. Inicia el de mañana en la próxima fecha laboral.')}</div>}<form onSubmit={saveCount}><div className={styles.formGrid}><Field label={t('Item','Artículo')}><select value={countForm.item_id} onChange={e=>setCountForm({...countForm,item_id:e.target.value})}><option value="">{t('Choose item','Elegir artículo')}</option>{items.map(i=><option key={i.id} value={i.id}>{i.name} · {i.unit}</option>)}</select></Field><Field label={t('Quantity','Cantidad')}><input type="number" min="0" step="0.001" value={countForm.quantity} onChange={e=>setCountForm({...countForm,quantity:e.target.value})}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy||(count?.counted_on===today()&&count.status==='final')}>{t('Save count','Guardar conteo')}</button>{count?.status==='draft'&&lines.length>0&&<button type="button" className={styles.button} disabled={busy} onClick={finalizeCount}>{t('Finalize count','Finalizar conteo')}</button>}</div></form></div></section><section className={styles.section}><div className={styles.card}><h2>{t('Waste','Desperdicio')}</h2><form onSubmit={addWaste}><div className={styles.formGrid}><Field label={t('Item','Artículo')}><select value={wasteForm.item_id} onChange={e=>setWasteForm({...wasteForm,item_id:e.target.value})}><option value="">{t('Choose item','Elegir artículo')}</option>{items.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></Field><Field label={t('Quantity','Cantidad')}><input type="number" min="0.001" step="0.001" value={wasteForm.quantity} onChange={e=>setWasteForm({...wasteForm,quantity:e.target.value})}/></Field><Field label={t('Reason','Motivo')} wide><input maxLength={1000} value={wasteForm.reason} onChange={e=>setWasteForm({...wasteForm,reason:e.target.value})}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy}>{t('Record waste','Registrar desperdicio')}</button></div></form></div></section></div>
    <section className={styles.section}><div className={styles.card}><h2>{t('Low stock / order prep','Existencias bajas / preparación de pedidos')}</h2>{suggested.length?<><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>{t('Item','Artículo')}</th><th>{t('On hand','Disponible')}</th><th>{t('Par','Par')}</th><th>{t('Suggested','Sugerido')}</th><th>{t('Vendor','Proveedor')}</th></tr></thead><tbody>{suggested.map(x=><tr key={x.item.id}><td>{x.item.name}</td><td>{x.qty} {x.item.unit}</td><td>{x.item.par_level}</td><td>{x.suggested.toFixed(2)}</td><td>{vendorName(x.item.vendor_id)}</td></tr>)}</tbody></table></div><div className={styles.actions}><button className={styles.button} disabled={busy||count?.status!=='final'} onClick={createSuggestedOrders}>{count?.status==='final'?t('Create draft purchase orders','Crear órdenes en borrador'):t('Finalize count before ordering','Finaliza el conteo antes de pedir')}</button></div></>:<div className={styles.empty}>{t('Nothing is below its reorder point based on the latest count.','Nada está por debajo del punto de reorden según el último conteo.')}</div>}</div></section>
    <section className={styles.section}><div className={styles.card}><h2>{t('Inventory item setup','Configuración de artículos')}</h2><form onSubmit={addItem}><div className={styles.formGrid}><Field label={t('Item name','Nombre del artículo')}><input maxLength={200} value={itemForm.name} onChange={e=>setItemForm({...itemForm,name:e.target.value})}/></Field><Field label={t('Category','Categoría')}><select value={itemForm.category} onChange={e=>setItemForm({...itemForm,category:e.target.value})}>{['food','beer','wine','liquor','non_alcoholic','paper','cleaning','other'].map(x=><option key={x} value={x}>{categoryLabel(x)}</option>)}</select></Field><Field label={t('Unit','Unidad')}><input maxLength={60} value={itemForm.unit} onChange={e=>setItemForm({...itemForm,unit:e.target.value})}/></Field><Field label={t('Vendor','Proveedor')}><select value={itemForm.vendor_id} onChange={e=>setItemForm({...itemForm,vendor_id:e.target.value})}><option value="">{t('No vendor','Sin proveedor')}</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></Field><Field label="Par"><input type="number" min="0" step="0.001" value={itemForm.par_level} onChange={e=>setItemForm({...itemForm,par_level:e.target.value})}/></Field><Field label={t('Reorder at','Reordenar en')}><input type="number" min="0" step="0.001" value={itemForm.reorder_level} onChange={e=>setItemForm({...itemForm,reorder_level:e.target.value})}/></Field><Field label={t('Unit cost','Costo unitario')}><input type="number" min="0" step="0.0001" value={itemForm.unit_cost} onChange={e=>setItemForm({...itemForm,unit_cost:e.target.value})}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy}>{t('Add item','Agregar artículo')}</button></div></form><form onSubmit={addVendor} className={styles.actions}><Field label={t('New vendor','Nuevo proveedor')}><input maxLength={200} value={vendorForm.name} onChange={e=>setVendorForm({name:e.target.value})}/></Field><button className={`${styles.button} ${styles.secondary}`} disabled={busy}>{t('Add vendor','Agregar proveedor')}</button></form></div></section>
    <section className={styles.section}><div className={styles.card}><h2>{t('Recipe food cost','Costo de alimentos por receta')}</h2><p className={styles.muted}>{t("Link menu items to inventory quantities. Cost uses each inventory item's current unit cost.",'Vincula platos con cantidades de inventario. El costo usa el costo unitario actual de cada artículo.')}</p><form onSubmit={addRecipe}><div className={styles.formGrid}><Field label={t('Menu item','Plato')}><select value={recipeForm.menu_item_id} onChange={e=>setRecipeForm({...recipeForm,menu_item_id:e.target.value})}><option value="">{t('Choose menu item','Elegir plato')}</option>{menu.map(m=><option key={m.id} value={m.id}>{m.name} {m.base_price?`· ${money(m.base_price,localeCode)}`:''}</option>)}</select></Field><Field label={t('Inventory ingredient','Ingrediente de inventario')}><select value={recipeForm.inventory_item_id} onChange={e=>setRecipeForm({...recipeForm,inventory_item_id:e.target.value})}><option value="">{t('Choose ingredient','Elegir ingrediente')}</option>{items.map(i=><option key={i.id} value={i.id}>{i.name} · {i.unit}</option>)}</select></Field><Field label={t('Quantity per menu item','Cantidad por plato')}><input type="number" min="0.0001" step="0.0001" value={recipeForm.quantity} onChange={e=>setRecipeForm({...recipeForm,quantity:e.target.value})}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy}>{t('Save component','Guardar componente')}</button></div></form>{menuCosts.length>0&&<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>{t('Menu item','Plato')}</th><th>{t('Price','Precio')}</th><th>{t('Theoretical cost','Costo teórico')}</th><th>{t('Food cost %','% costo de alimentos')}</th></tr></thead><tbody>{menuCosts.slice(0,40).map(x=><tr key={x.id}><td>{x.name}</td><td>{money(x.price,localeCode)}</td><td>{money(x.cost,localeCode)}</td><td className={x.pct>35?styles.bad:x.pct>30?styles.warning:styles.good}>{x.pct.toFixed(1)}%</td></tr>)}</tbody></table></div>}</div></section>
    <section className={styles.section}><h2>{t('Purchase orders','Órdenes de compra')}</h2><div className={styles.list}>{orders.length?orders.map(o=><div className={styles.entry} key={o.id}><div className={styles.entryHead}><div><h3>{vendorName(o.vendor_id)}</h3><small>{o.order_date}{o.expected_date?` · ${t('expected','esperado')} ${o.expected_date}`:''}</small></div><span className={styles.pill}>{statusLabel(o.status)}</span></div>{o.status==='draft'&&<div className={styles.actions}><button className={styles.button} disabled={busy} onClick={()=>setOrderStatus(o.id,'submitted')}>{t('Mark submitted','Marcar enviada')}</button></div>}{o.status==='submitted'&&<div className={styles.actions}><button className={styles.button} disabled={busy} onClick={()=>setOrderStatus(o.id,'received')}>{t('Mark received','Marcar recibida')}</button></div>}</div>):<div className={styles.empty}>{t('No purchase orders yet.','Aún no hay órdenes de compra.')}</div>}</div></section>
  </main>;
}
function Metric({label,value}:{label:string;value:string}){return <div className={styles.metric}><span>{label}</span><strong>{value}</strong></div>}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={`${styles.field} ${wide?styles.wide:''}`}><span>{label}</span>{children}</label>}
