'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { supabase } from '@/lib/supabase';
import styles from '../ops-tools.module.css';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Vendor={id:string;name:string;active:boolean};
type Item={id:string;vendor_id:string|null;name:string;category:string;unit:string;par_level:number;reorder_level:number;unit_cost:number;active:boolean};
type Count={id:string;counted_on:string;status:string};
type CountLine={item_id:string;quantity:number;unit_cost_snapshot:number};
type Waste={id:string;item_id:string;quantity:number;unit_cost_snapshot:number;reason:string;occurred_at:string};
type PO={id:string;vendor_id:string|null;order_date:string;expected_date:string|null;status:string;created_at:string};
type MenuItem={id:string;name:string;base_price:number|null};
type Recipe={id:string;menu_item_id:string;inventory_item_id:string;quantity:number};
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(n)||0);
const today=()=>new Date().toISOString().slice(0,10);

export default function InventoryPage(){
  const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[profile,setProfile]=useState<Profile|null>(null),[message,setMessage]=useState('');
  const [vendors,setVendors]=useState<Vendor[]>([]),[items,setItems]=useState<Item[]>([]),[count,setCount]=useState<Count|null>(null),[lines,setLines]=useState<CountLine[]>([]),[waste,setWaste]=useState<Waste[]>([]),[orders,setOrders]=useState<PO[]>([]),[menu,setMenu]=useState<MenuItem[]>([]),[recipes,setRecipes]=useState<Recipe[]>([]);
  const [vendorForm,setVendorForm]=useState({name:''});
  const [itemForm,setItemForm]=useState({name:'',category:'food',unit:'each',par_level:'0',reorder_level:'0',unit_cost:'0',vendor_id:''});
  const [countForm,setCountForm]=useState({item_id:'',quantity:'0'}),[wasteForm,setWasteForm]=useState({item_id:'',quantity:'1',reason:''}),[recipeForm,setRecipeForm]=useState({menu_item_id:'',inventory_item_id:'',quantity:'1'});
  useEffect(()=>{void init()},[]);
  async function init(){const {data:u}=await supabase.auth.getUser();if(!u.user){window.location.href='/';return;}const {data:p}=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();setProfile((p||null) as Profile|null);if(p?.location_id&&['admin','manager'].includes(p.app_role))await load(p.location_id);setReady(true);}
  async function load(locationId=profile?.location_id||''){if(!locationId)return;const [v,i,c,w,o,m,r]=await Promise.all([
    supabase.from('restaurant_vendors').select('id,name,active').eq('location_id',locationId).eq('active',true).order('name'),
    supabase.from('inventory_items').select('id,vendor_id,name,category,unit,par_level,reorder_level,unit_cost,active').eq('location_id',locationId).eq('active',true).order('name'),
    supabase.from('inventory_counts').select('id,counted_on,status').eq('location_id',locationId).order('counted_on',{ascending:false}).limit(1).maybeSingle(),
    supabase.from('waste_entries').select('id,item_id,quantity,unit_cost_snapshot,reason,occurred_at').eq('location_id',locationId).order('occurred_at',{ascending:false}).limit(30),
    supabase.from('purchase_orders').select('id,vendor_id,order_date,expected_date,status,created_at').eq('location_id',locationId).order('created_at',{ascending:false}).limit(30),
    supabase.from('menu_items').select('id,name,base_price').eq('location_id',locationId).eq('active',true).order('name'),
    supabase.from('recipe_cost_components').select('id,menu_item_id,inventory_item_id,quantity').eq('location_id',locationId)
  ]);setVendors((v.data??[]) as Vendor[]);setItems((i.data??[]) as Item[]);setWaste((w.data??[]) as Waste[]);setOrders((o.data??[]) as PO[]);setMenu((m.data??[]) as MenuItem[]);setRecipes((r.data??[]) as Recipe[]);const latest=(c.data||null) as Count|null;setCount(latest);if(latest){const q=await supabase.from('inventory_count_lines').select('item_id,quantity,unit_cost_snapshot').eq('count_id',latest.id);setLines((q.data??[]) as CountLine[]);}else setLines([]);if(v.error||i.error||c.error||w.error||o.error||m.error||r.error)setMessage('Some inventory data could not be loaded.');}
  const qtyMap=useMemo(()=>new Map(lines.map(x=>[x.item_id,Number(x.quantity)||0])),[lines]);
  const suggested=useMemo(()=>items.map(i=>({item:i,qty:qtyMap.get(i.id)??0,suggested:Math.max(0,Number(i.par_level)-Number(qtyMap.get(i.id)??0))})).filter(x=>x.qty<=Number(x.item.reorder_level)&&x.suggested>0),[items,qtyMap]);
  const inventoryValue=useMemo(()=>items.reduce((n,i)=>n+(qtyMap.get(i.id)??0)*Number(i.unit_cost),0),[items,qtyMap]);
  const wasteCost=useMemo(()=>waste.reduce((n,w)=>n+Number(w.quantity)*Number(w.unit_cost_snapshot),0),[waste]);
  const menuCosts=useMemo(()=>menu.map(mi=>{const cost=recipes.filter(r=>r.menu_item_id===mi.id).reduce((n,r)=>n+Number(r.quantity)*Number(items.find(i=>i.id===r.inventory_item_id)?.unit_cost||0),0);const price=Number(mi.base_price||0);return {id:mi.id,name:mi.name,price,cost,pct:price>0?cost/price*100:0};}).filter(x=>x.cost>0).sort((a,b)=>b.pct-a.pct),[menu,recipes,items]);
  const itemName=(id:string)=>items.find(i=>i.id===id)?.name||'Unknown item',vendorName=(id:string|null)=>vendors.find(v=>v.id===id)?.name||'No vendor';
  async function addVendor(e:FormEvent){e.preventDefault();if(!profile?.location_id||busy||!vendorForm.name.trim())return;setBusy(true);try{const {error}=await supabase.from('restaurant_vendors').insert({location_id:profile.location_id,name:vendorForm.name.trim().slice(0,200)});if(error)throw error;setVendorForm({name:''});await load();setMessage('Vendor added.');}catch{setMessage('Could not add vendor.');}finally{setBusy(false)}}
  async function addItem(e:FormEvent){e.preventDefault();if(!profile?.location_id||busy||!itemForm.name.trim())return;setBusy(true);try{const {error}=await supabase.from('inventory_items').insert({location_id:profile.location_id,name:itemForm.name.trim().slice(0,200),category:itemForm.category,unit:itemForm.unit.trim().slice(0,60)||'each',par_level:Math.max(0,Number(itemForm.par_level)||0),reorder_level:Math.max(0,Number(itemForm.reorder_level)||0),unit_cost:Math.max(0,Number(itemForm.unit_cost)||0),vendor_id:itemForm.vendor_id||null});if(error)throw error;setItemForm({...itemForm,name:''});await load();setMessage('Inventory item added.');}catch{setMessage('Could not add inventory item.');}finally{setBusy(false)}}
  async function ensureTodayCount(){if(!profile?.location_id)return null;if(count?.counted_on===today())return count.id;const {data,error}=await supabase.from('inventory_counts').upsert({location_id:profile.location_id,counted_on:today(),status:'draft'},{onConflict:'location_id,counted_on'}).select('id').single();if(error)throw error;return data.id as string;}
  async function saveCount(e:FormEvent){e.preventDefault();if(!countForm.item_id||busy)return;const item=items.find(i=>i.id===countForm.item_id);if(!item)return;setBusy(true);try{const countId=await ensureTodayCount();if(!countId)return;const {error}=await supabase.from('inventory_count_lines').upsert({count_id:countId,item_id:item.id,quantity:Math.max(0,Number(countForm.quantity)||0),unit_cost_snapshot:Number(item.unit_cost)||0},{onConflict:'count_id,item_id'});if(error)throw error;setCountForm({...countForm,quantity:'0'});await load();setMessage('Count updated.');}catch{setMessage('Could not save inventory count.');}finally{setBusy(false)}}
  async function addWaste(e:FormEvent){e.preventDefault();if(!profile?.location_id||!wasteForm.item_id||!wasteForm.reason.trim()||busy)return;const item=items.find(i=>i.id===wasteForm.item_id);if(!item)return;setBusy(true);try{const {error}=await supabase.from('waste_entries').insert({location_id:profile.location_id,item_id:item.id,quantity:Math.max(.001,Number(wasteForm.quantity)||0),unit_cost_snapshot:Number(item.unit_cost)||0,reason:wasteForm.reason.trim().slice(0,1000)});if(error)throw error;setWasteForm({...wasteForm,quantity:'1',reason:''});await load();setMessage('Waste recorded.');}catch{setMessage('Could not record waste.');}finally{setBusy(false)}}
  async function addRecipe(e:FormEvent){e.preventDefault();if(!profile?.location_id||!recipeForm.menu_item_id||!recipeForm.inventory_item_id||busy)return;setBusy(true);try{const {error}=await supabase.from('recipe_cost_components').upsert({location_id:profile.location_id,menu_item_id:recipeForm.menu_item_id,inventory_item_id:recipeForm.inventory_item_id,quantity:Math.max(.0001,Number(recipeForm.quantity)||0)},{onConflict:'menu_item_id,inventory_item_id'});if(error)throw error;await load();setMessage('Recipe cost component saved.');}catch{setMessage('Could not save recipe component.');}finally{setBusy(false)}}
  async function createSuggestedOrders(){if(!profile?.location_id||!suggested.length||busy)return;setBusy(true);try{const groups=new Map<string,{vendor_id:string|null;rows:typeof suggested}>();for(const s of suggested){const k=s.item.vendor_id||'none';if(!groups.has(k))groups.set(k,{vendor_id:s.item.vendor_id,rows:[]});groups.get(k)!.rows.push(s);}for(const g of groups.values()){const {data:po,error}=await supabase.from('purchase_orders').insert({location_id:profile.location_id,vendor_id:g.vendor_id,status:'draft',notes:'Auto-prepared from latest count and par levels.'}).select('id').single();if(error)throw error;const payload=g.rows.map(x=>({purchase_order_id:po.id,item_id:x.item.id,quantity:x.suggested,unit_cost:Number(x.item.unit_cost)||0}));const l=await supabase.from('purchase_order_lines').insert(payload);if(l.error)throw l.error;}await load();setMessage(`Created ${groups.size} draft order${groups.size===1?'':'s'}.`);}catch{setMessage('Could not create draft orders.');}finally{setBusy(false)}}
  async function setOrderStatus(id:string,status:'submitted'|'received'){if(busy)return;setBusy(true);try{const patch=status==='submitted'?{status,submitted_at:new Date().toISOString()}:{status,received_at:new Date().toISOString()};const {error}=await supabase.from('purchase_orders').update(patch).eq('id',id);if(error)throw error;await load();setMessage(`Order marked ${status}.`);}catch{setMessage('Could not update order.');}finally{setBusy(false)}}
  if(!ready)return <main className={styles.page}>Loading inventory…</main>;
  if(!profile?.location_id||!['admin','manager'].includes(profile.app_role))return <main className={styles.page}><div className={styles.top}><div><h1>Inventory & Food Cost</h1><p>Manager-only cost and ordering data.</p></div><Link className={styles.back} href="/">Back</Link></div><div className={styles.error}>Manager access is required.</div></main>;
  return <main className={styles.page}>
    <div className={styles.top}><div><h1>Inventory & Food Cost</h1><p>Pars, counts, ordering, waste and theoretical recipe cost.</p></div><Link className={styles.back} href="/">Back to Ops</Link></div>
    {message&&<div className={message.startsWith('Could not')||message.startsWith('Some')?styles.error:styles.notice}>{message}</div>}
    <div className={styles.grid}><Metric label="Active items" value={String(items.length)}/><Metric label="Latest inventory value" value={money(inventoryValue)}/><Metric label="Below reorder" value={String(suggested.length)}/><Metric label="Recent waste cost" value={money(wasteCost)}/></div>
    <div className={styles.split}><section className={styles.section}><div className={styles.card}><h2>Quick count</h2><p className={styles.muted}>Latest count: {count?.counted_on||'none yet'}</p><form onSubmit={saveCount}><div className={styles.formGrid}><Field label="Item"><select value={countForm.item_id} onChange={e=>setCountForm({...countForm,item_id:e.target.value})}><option value="">Choose item</option>{items.map(i=><option key={i.id} value={i.id}>{i.name} · {i.unit}</option>)}</select></Field><Field label="Quantity"><input type="number" min="0" step="0.001" value={countForm.quantity} onChange={e=>setCountForm({...countForm,quantity:e.target.value})}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy}>Save count</button></div></form></div></section><section className={styles.section}><div className={styles.card}><h2>Waste</h2><form onSubmit={addWaste}><div className={styles.formGrid}><Field label="Item"><select value={wasteForm.item_id} onChange={e=>setWasteForm({...wasteForm,item_id:e.target.value})}><option value="">Choose item</option>{items.map(i=><option key={i.id} value={i.id}>{i.name}</option>)}</select></Field><Field label="Quantity"><input type="number" min="0.001" step="0.001" value={wasteForm.quantity} onChange={e=>setWasteForm({...wasteForm,quantity:e.target.value})}/></Field><Field label="Reason" wide><input maxLength={1000} value={wasteForm.reason} onChange={e=>setWasteForm({...wasteForm,reason:e.target.value})}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy}>Record waste</button></div></form></div></section></div>
    <section className={styles.section}><div className={styles.card}><h2>Low stock / order prep</h2>{suggested.length?<><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Item</th><th>On hand</th><th>Par</th><th>Suggested</th><th>Vendor</th></tr></thead><tbody>{suggested.map(x=><tr key={x.item.id}><td>{x.item.name}</td><td>{x.qty} {x.item.unit}</td><td>{x.item.par_level}</td><td>{x.suggested.toFixed(2)}</td><td>{vendorName(x.item.vendor_id)}</td></tr>)}</tbody></table></div><div className={styles.actions}><button className={styles.button} disabled={busy} onClick={createSuggestedOrders}>Create draft purchase orders</button></div></>:<div className={styles.empty}>Nothing is below its reorder point based on the latest count.</div>}</div></section>
    <section className={styles.section}><div className={styles.card}><h2>Inventory item setup</h2><form onSubmit={addItem}><div className={styles.formGrid}><Field label="Item name"><input maxLength={200} value={itemForm.name} onChange={e=>setItemForm({...itemForm,name:e.target.value})}/></Field><Field label="Category"><select value={itemForm.category} onChange={e=>setItemForm({...itemForm,category:e.target.value})}>{['food','beer','wine','liquor','non_alcoholic','paper','cleaning','other'].map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select></Field><Field label="Unit"><input maxLength={60} value={itemForm.unit} onChange={e=>setItemForm({...itemForm,unit:e.target.value})}/></Field><Field label="Vendor"><select value={itemForm.vendor_id} onChange={e=>setItemForm({...itemForm,vendor_id:e.target.value})}><option value="">No vendor</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select></Field><Field label="Par"><input type="number" min="0" step="0.001" value={itemForm.par_level} onChange={e=>setItemForm({...itemForm,par_level:e.target.value})}/></Field><Field label="Reorder at"><input type="number" min="0" step="0.001" value={itemForm.reorder_level} onChange={e=>setItemForm({...itemForm,reorder_level:e.target.value})}/></Field><Field label="Unit cost"><input type="number" min="0" step="0.0001" value={itemForm.unit_cost} onChange={e=>setItemForm({...itemForm,unit_cost:e.target.value})}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy}>Add item</button></div></form><form onSubmit={addVendor} className={styles.actions}><Field label="New vendor"><input maxLength={200} value={vendorForm.name} onChange={e=>setVendorForm({name:e.target.value})}/></Field><button className={`${styles.button} ${styles.secondary}`} disabled={busy}>Add vendor</button></form></div></section>
    <section className={styles.section}><div className={styles.card}><h2>Recipe food cost</h2><p className={styles.muted}>Link menu items to inventory quantities. Cost uses each inventory item's current unit cost.</p><form onSubmit={addRecipe}><div className={styles.formGrid}><Field label="Menu item"><select value={recipeForm.menu_item_id} onChange={e=>setRecipeForm({...recipeForm,menu_item_id:e.target.value})}><option value="">Choose menu item</option>{menu.map(m=><option key={m.id} value={m.id}>{m.name} {m.base_price?`· ${money(m.base_price)}`:''}</option>)}</select></Field><Field label="Inventory ingredient"><select value={recipeForm.inventory_item_id} onChange={e=>setRecipeForm({...recipeForm,inventory_item_id:e.target.value})}><option value="">Choose ingredient</option>{items.map(i=><option key={i.id} value={i.id}>{i.name} · {i.unit}</option>)}</select></Field><Field label="Quantity per menu item"><input type="number" min="0.0001" step="0.0001" value={recipeForm.quantity} onChange={e=>setRecipeForm({...recipeForm,quantity:e.target.value})}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy}>Save component</button></div></form>{menuCosts.length>0&&<div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Menu item</th><th>Price</th><th>Theoretical cost</th><th>Food cost %</th></tr></thead><tbody>{menuCosts.slice(0,40).map(x=><tr key={x.id}><td>{x.name}</td><td>{money(x.price)}</td><td>{money(x.cost)}</td><td className={x.pct>35?styles.bad:x.pct>30?styles.warning:styles.good}>{x.pct.toFixed(1)}%</td></tr>)}</tbody></table></div>}</div></section>
    <section className={styles.section}><h2>Purchase orders</h2><div className={styles.list}>{orders.length?orders.map(o=><div className={styles.entry} key={o.id}><div className={styles.entryHead}><div><h3>{vendorName(o.vendor_id)}</h3><small>{o.order_date}{o.expected_date?` · expected ${o.expected_date}`:''}</small></div><span className={styles.pill}>{o.status}</span></div>{o.status==='draft'&&<div className={styles.actions}><button className={styles.button} disabled={busy} onClick={()=>setOrderStatus(o.id,'submitted')}>Mark submitted</button></div>}{o.status==='submitted'&&<div className={styles.actions}><button className={styles.button} disabled={busy} onClick={()=>setOrderStatus(o.id,'received')}>Mark received</button></div>}</div>):<div className={styles.empty}>No purchase orders yet.</div>}</div></section>
  </main>;
}
function Metric({label,value}:{label:string;value:string}){return <div className={styles.metric}><span>{label}</span><strong>{value}</strong></div>}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={`${styles.field} ${wide?styles.wide:''}`}><span>{label}</span>{children}</label>}
