'use client';

import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase';
import styles from '../../ops-tools.module.css';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Employee={id:string;full_name:string};
type Working={punch_id:string;employee_id:string;employee_name:string;clock_in:string;source:string;on_break:boolean;break_started_at:string|null};

export default function TimeClockKioskPage(){
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[profile,setProfile]=useState<Profile|null>(null),[employees,setEmployees]=useState<Employee[]>([]),[working,setWorking]=useState<Working[]>([]),[employeeId,setEmployeeId]=useState(''),[pin,setPin]=useState('');
 const selectedWorking=useMemo(()=>working.find(w=>w.employee_id===employeeId)||null,[working,employeeId]);
 useEffect(()=>{void load()},[]);
 async function load(){const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}const p=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();if(p.error||!p.data?.location_id){setMessage('Could not open kiosk.');setReady(true);return}const pr=p.data as Profile;setProfile(pr);if(!['admin','manager'].includes(pr.app_role)){setReady(true);return}const [e,w]=await Promise.all([supabase.from('employees').select('id,full_name').eq('location_id',pr.location_id).eq('active',true).is('deleted_at',null).order('full_name'),supabase.rpc('time_clock_whos_working')]);setEmployees((e.data??[]) as Employee[]);setWorking((Array.isArray(w.data)?w.data:[]) as Working[]);setReady(true)}
 async function action(kind:'clock_in'|'clock_out'|'start_break'|'end_break'){if(!employeeId||!/^\d{4,8}$/.test(pin)||busy)return;setBusy(true);try{const {data,error}=await supabase.rpc('kiosk_time_clock_action',{p_employee_id:employeeId,p_pin:pin,p_action:kind,p_paid_break:false});if(error)throw error;const out=(data||{}) as any;if(!out.ok)throw new Error(out.error||'Kiosk action failed.');setMessage(kind==='clock_in'?'Clocked in.':kind==='clock_out'?'Clocked out.':kind==='start_break'?'Break started.':'Break ended.');setPin('');await load()}catch(error:any){setMessage(error?.message||'Kiosk action failed.');setPin('')}finally{setBusy(false)}}
 if(!ready)return <div className="full-loader"><span>Opening kiosk…</span></div>;
 if(!profile||!['admin','manager'].includes(profile.app_role))return <main className={styles.page}><div className={styles.error}>A manager must launch the time clock kiosk.</div><Link className={styles.back} href="/time-clock">Back</Link></main>;
 return <main className={styles.page}><div className={styles.top}><div><h1>Time Clock Kiosk</h1><p>Manager-launched shared punch station. Employee PINs are verified only by the server.</p></div><Link className={styles.back} href="/time-clock">Exit Kiosk</Link></div>{message&&<div className={message.toLowerCase().includes('failed')||message.toLowerCase().includes('invalid')||message.toLowerCase().includes('locked')?styles.error:styles.notice}>{message}</div>}
 <section className={styles.section}><div className={styles.card}><div className={styles.formGrid}><label className={styles.field}><span>Employee</span><select value={employeeId} onChange={e=>{setEmployeeId(e.target.value);setPin('')}}><option value="">Choose your name</option>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select></label><label className={styles.field}><span>PIN</span><input type="password" inputMode="numeric" autoComplete="off" minLength={4} maxLength={8} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,'').slice(0,8))} placeholder="4–8 digits"/></label></div>{employeeId&&<div className={styles.notice} style={{marginTop:12}}>{selectedWorking?(selectedWorking.on_break?'You are currently on break.':'You are currently clocked in.'):'You are currently clocked out.'}</div>}<div className={styles.actions} style={{marginTop:14}}>{!selectedWorking?<button className={styles.button} disabled={busy||!employeeId||pin.length<4} onClick={()=>action('clock_in')}>Clock In</button>:selectedWorking.on_break?<><button className={styles.button} disabled={busy||pin.length<4} onClick={()=>action('end_break')}>End Break</button></>:<><button className={styles.button} disabled={busy||pin.length<4} onClick={()=>action('clock_out')}>Clock Out</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy||pin.length<4} onClick={()=>action('start_break')}>Start Break</button></>}</div><p>Breaks started at the kiosk are recorded as unpaid by default. A manager can correct paid-break status from the Time Clock manager workspace with an audit reason.</p></div></section>
 </main>
}
