'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { supabase } from '@/lib/supabase';
import styles from '../ops-tools.module.css';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Session={id:string;business_date:string;shift:string;opening_cash:number;cash_sales:number;paid_outs:number;cash_refunds:number;expected_cash:number;actual_cash:number;deposit_amount:number;safe_count:number;petty_cash:number;notes:string|null;status:string;created_at:string};
const today=()=>new Date().toISOString().slice(0,10);
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n)||0);
const n=(v:string)=>Math.max(0,Number(v)||0);

export default function CashPage(){
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[profile,setProfile]=useState<Profile|null>(null),[rows,setRows]=useState<Session[]>([]),[message,setMessage]=useState('');
 const [form,setForm]=useState({business_date:today(),shift:'closing',opening_cash:'0',cash_sales:'0',paid_outs:'0',cash_refunds:'0',actual_cash:'0',deposit_amount:'0',safe_count:'0',petty_cash:'0',notes:''});
 useEffect(()=>{void init()},[]);
 async function init(){const {data:u}=await supabase.auth.getUser();if(!u.user){window.location.href='/';return;}const {data:p}=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();setProfile((p||null) as Profile|null);if(p?.location_id&&['admin','manager'].includes(p.app_role))await load(p.location_id);setReady(true)}
 async function load(locationId=profile?.location_id||''){if(!locationId)return;const {data,error}=await supabase.from('cash_control_sessions').select('*').eq('location_id',locationId).order('business_date',{ascending:false}).order('created_at',{ascending:false}).limit(90);setRows((data??[]) as Session[]);if(error)setMessage('Could not load cash-control records.')}
 const expected=n(form.opening_cash)+n(form.cash_sales)-n(form.paid_outs)-n(form.cash_refunds),variance=n(form.actual_cash)-expected;
 const unresolved=useMemo(()=>rows.filter(r=>r.status!=='verified').length,[rows]);
 async function save(e:FormEvent){e.preventDefault();if(!profile?.location_id||busy)return;setBusy(true);try{const {data:u}=await supabase.auth.getUser();if(!u.user)return;const payload={location_id:profile.location_id,business_date:form.business_date,shift:form.shift,opening_cash:n(form.opening_cash),cash_sales:n(form.cash_sales),paid_outs:n(form.paid_outs),cash_refunds:n(form.cash_refunds),expected_cash:expected,actual_cash:n(form.actual_cash),deposit_amount:n(form.deposit_amount),safe_count:n(form.safe_count),petty_cash:n(form.petty_cash),notes:form.notes.trim().slice(0,4000)||null,status:'submitted',created_by:u.user.id};const {error}=await supabase.from('cash_control_sessions').upsert(payload,{onConflict:'location_id,business_date,shift'});if(error)throw error;await load();setMessage('Cash control submitted.');}catch{setMessage('Could not save cash control.');}finally{setBusy(false)}}
 async function verify(row:Session){if(busy)return;setBusy(true);try{const {data:u}=await supabase.auth.getUser();const {error}=await supabase.from('cash_control_sessions').update({status:'verified',verified_by:u.user?.id||null,verified_at:new Date().toISOString()}).eq('id',row.id);if(error)throw error;await load();setMessage('Cash control verified.');}catch{setMessage('Could not verify cash control.');}finally{setBusy(false)}}
 if(!ready)return <main className={styles.page}>Loading cash controls…</main>;
 if(!profile?.location_id||!['admin','manager'].includes(profile.app_role))return <main className={styles.page}><div className={styles.top}><div><h1>Cash Controls</h1><p>Manager-only drawer, safe and deposit records.</p></div><Link className={styles.back} href="/">Back</Link></div><div className={styles.error}>Manager access is required.</div></main>;
 return <main className={styles.page}><div className={styles.top}><div><h1>Cash Controls</h1><p>Drawer reconciliation, paid-outs, deposits, safe count and over/short.</p></div><Link className={styles.back} href="/">Back to Ops</Link></div>{message&&<div className={message.startsWith('Could not')?styles.error:styles.notice}>{message}</div>}
 <div className={styles.grid}><Metric label="Expected cash" value={money(expected)}/><Metric label="Actual cash" value={money(n(form.actual_cash))}/><Metric label="Current variance" value={`${variance>=0?'+':''}${money(variance)}`}/><Metric label="Awaiting verification" value={String(unresolved)}/></div>
 <section className={styles.section}><div className={styles.card}><h2>Reconcile shift</h2><form onSubmit={save}><div className={styles.formGrid}><Field label="Business date"><input type="date" value={form.business_date} onChange={e=>setForm({...form,business_date:e.target.value})}/></Field><Field label="Shift"><select value={form.shift} onChange={e=>setForm({...form,shift:e.target.value})}><option value="opening">Opening</option><option value="mid">Mid</option><option value="closing">Closing</option><option value="other">Other</option></select></Field><Field label="Opening cash"><input type="number" min="0" step="0.01" value={form.opening_cash} onChange={e=>setForm({...form,opening_cash:e.target.value})}/></Field><Field label="Cash sales"><input type="number" min="0" step="0.01" value={form.cash_sales} onChange={e=>setForm({...form,cash_sales:e.target.value})}/></Field><Field label="Paid-outs"><input type="number" min="0" step="0.01" value={form.paid_outs} onChange={e=>setForm({...form,paid_outs:e.target.value})}/></Field><Field label="Cash refunds"><input type="number" min="0" step="0.01" value={form.cash_refunds} onChange={e=>setForm({...form,cash_refunds:e.target.value})}/></Field><Field label="Actual cash counted"><input type="number" min="0" step="0.01" value={form.actual_cash} onChange={e=>setForm({...form,actual_cash:e.target.value})}/></Field><Field label="Deposit amount"><input type="number" min="0" step="0.01" value={form.deposit_amount} onChange={e=>setForm({...form,deposit_amount:e.target.value})}/></Field><Field label="Safe count"><input type="number" min="0" step="0.01" value={form.safe_count} onChange={e=>setForm({...form,safe_count:e.target.value})}/></Field><Field label="Petty cash"><input type="number" min="0" step="0.01" value={form.petty_cash} onChange={e=>setForm({...form,petty_cash:e.target.value})}/></Field><Field label="Manager notes" wide><textarea maxLength={4000} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy}>Submit reconciliation</button></div></form></div></section>
 <section className={styles.section}><h2>Recent cash controls</h2><div className={styles.tableWrap}>{rows.length?<table className={styles.table}><thead><tr><th>Date</th><th>Shift</th><th>Expected</th><th>Actual</th><th>Over / short</th><th>Deposit</th><th>Safe</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(r=>{const v=Number(r.actual_cash)-Number(r.expected_cash);return <tr key={r.id}><td>{r.business_date}</td><td>{r.shift}</td><td>{money(r.expected_cash)}</td><td>{money(r.actual_cash)}</td><td className={Math.abs(v)>.01?styles.bad:styles.good}>{v>=0?'+':''}{money(v)}</td><td>{money(r.deposit_amount)}</td><td>{money(r.safe_count)}</td><td>{r.status}</td><td>{r.status!=='verified'&&<button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>verify(r)}>Verify</button>}</td></tr>})}</tbody></table>:<div className={styles.empty}>No cash-control sessions yet.</div>}</div></section>
 </main>}
function Metric({label,value}:{label:string;value:string}){return <div className={styles.metric}><span>{label}</span><strong>{value}</strong></div>}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={`${styles.field} ${wide?styles.wide:''}`}><span>{label}</span>{children}</label>}
