'use client';

import {useEffect,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase';
import styles from '../../ops-tools.module.css';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Settings={timezone:string;overtime_after_hours:number;overtime_multiplier:number;require_full_coverage_to_publish:boolean;open_shift_claim_requires_approval:boolean;auto_schedule_mode:'minimum'|'target';shift_pool_enabled:boolean;shift_pool_requires_approval:boolean;shift_pool_allow_trades:boolean;shift_pool_cross_location:boolean;availability_visible_to_employees:boolean;availability_approval_required:boolean;temporary_availability_enabled:boolean;allow_availability_for_published_weeks:boolean;paid_time_off_enabled:boolean;paid_sick_time_off_enabled:boolean;shift_reminders_enabled:boolean;shift_reminder_hours:number};
const DEFAULT:Settings={timezone:'America/New_York',overtime_after_hours:40,overtime_multiplier:1.5,require_full_coverage_to_publish:true,open_shift_claim_requires_approval:true,auto_schedule_mode:'target',shift_pool_enabled:true,shift_pool_requires_approval:true,shift_pool_allow_trades:true,shift_pool_cross_location:false,availability_visible_to_employees:true,availability_approval_required:true,temporary_availability_enabled:true,allow_availability_for_published_weeks:true,paid_time_off_enabled:false,paid_sick_time_off_enabled:false,shift_reminders_enabled:true,shift_reminder_hours:2};
export default function ScheduleSettingsPage(){
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[profile,setProfile]=useState<Profile|null>(null),[settings,setSettings]=useState<Settings>(DEFAULT);
 const canManage=profile?.app_role==='admin'||profile?.app_role==='manager';
 useEffect(()=>{void load()},[]);
 async function load(){const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}const p=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();if(p.error||!p.data?.location_id){setMessage('Could not load scheduling settings.');setReady(true);return}const pr=p.data as Profile;setProfile(pr);const r=await supabase.from('schedule_settings').select('timezone,overtime_after_hours,overtime_multiplier,require_full_coverage_to_publish,open_shift_claim_requires_approval,auto_schedule_mode,shift_pool_enabled,shift_pool_requires_approval,shift_pool_allow_trades,shift_pool_cross_location,availability_visible_to_employees,availability_approval_required,temporary_availability_enabled,allow_availability_for_published_weeks,paid_time_off_enabled,paid_sick_time_off_enabled,shift_reminders_enabled,shift_reminder_hours').eq('location_id',pr.location_id).maybeSingle();if(r.data)setSettings({...DEFAULT,...r.data} as Settings);if(r.error)setMessage(r.error.message);setReady(true)}
 async function save(){if(!canManage||!profile?.location_id||busy)return;setBusy(true);const {error}=await supabase.from('schedule_settings').upsert({location_id:profile.location_id,...settings},{onConflict:'location_id'});setMessage(error?error.message:'Scheduling settings saved.');setBusy(false)}
 const toggle=(key:keyof Settings)=><input type="checkbox" checked={Boolean(settings[key])} onChange={e=>setSettings({...settings,[key]:e.target.checked})}/>;
 if(!ready)return <div className="full-loader"><span>Opening scheduling settings…</span></div>;
 return <main className={styles.page}><div className={styles.top}><div><h1>Scheduling Settings</h1><p>Control how Auto Schedule, Shift Pool, availability, time off, reminders and publishing behave.</p></div><Link className={styles.back} href="/schedule">Back to Schedule</Link></div>{message&&<div className={styles.notice}>{message}</div>}{!canManage?<div className={styles.error}>Manager access is required.</div>:<>
 <section className={styles.section}><div className={styles.card}><h2>Auto Schedule & labor</h2><div className={styles.formGrid}><label className={styles.field}><span>Staffing level</span><select value={settings.auto_schedule_mode} onChange={e=>setSettings({...settings,auto_schedule_mode:e.target.value as any})}><option value="target">Target coverage</option><option value="minimum">Minimum coverage</option></select></label><label className={styles.field}><span>Overtime after hours</span><input type="number" min="1" max="168" step="0.5" value={settings.overtime_after_hours} onChange={e=>setSettings({...settings,overtime_after_hours:Number(e.target.value)})}/></label><label className={styles.field}><span>Overtime multiplier</span><input type="number" min="1" max="3" step="0.05" value={settings.overtime_multiplier} onChange={e=>setSettings({...settings,overtime_multiplier:Number(e.target.value)})}/></label><Bool label="Require full minimum coverage to publish">{toggle('require_full_coverage_to_publish')}</Bool></div></div></section>
 <section className={styles.section}><div className={styles.card}><h2>Shift Pool</h2><div className={styles.formGrid}><Bool label="Enable Shift Pool">{toggle('shift_pool_enabled')}</Bool><Bool label="Manager approval for offered-shift bids">{toggle('shift_pool_requires_approval')}</Bool><Bool label="Allow direct shift trades">{toggle('shift_pool_allow_trades')}</Bool><Bool label="Manager approval for manager-posted open shifts">{toggle('open_shift_claim_requires_approval')}</Bool><Bool label="Allow cross-location pool">{toggle('shift_pool_cross_location')}</Bool></div><div className={styles.notice} style={{marginTop:12}}>Partial-shift offers stay disabled until segmented-shift coverage is fully enabled and validated. Full-shift offers, bids, take-backs, open shifts, and trades are active.</div></div></section>
 <section className={styles.section}><div className={styles.card}><h2>Availability & time off</h2><div className={styles.formGrid}><Bool label="Employees can view availability">{toggle('availability_visible_to_employees')}</Bool><Bool label="Availability changes require manager approval">{toggle('availability_approval_required')}</Bool><Bool label="Allow temporary availability">{toggle('temporary_availability_enabled')}</Bool><Bool label="Allow availability requests for published weeks">{toggle('allow_availability_for_published_weeks')}</Bool><Bool label="Enable Paid time off category">{toggle('paid_time_off_enabled')}</Bool><Bool label="Enable Paid Sick category">{toggle('paid_sick_time_off_enabled')}</Bool></div></div></section>
 <section className={styles.section}><div className={styles.card}><h2>Shift reminders</h2><div className={styles.formGrid}><Bool label="Send upcoming-shift reminders">{toggle('shift_reminders_enabled')}</Bool><label className={styles.field}><span>Hours before shift</span><input type="number" min="0.25" max="168" step="0.25" value={settings.shift_reminder_hours} onChange={e=>setSettings({...settings,shift_reminder_hours:Number(e.target.value)})}/></label></div><p>Reminders are deduplicated per employee and shift version. If a shift is reassigned, the new employee becomes eligible for the reminder instead.</p></div></section>
 <div className={styles.actions}><button className={styles.button} disabled={busy} onClick={save}>Save Scheduling Settings</button></div></>}
 </main>
}
function Bool({label,children}:{label:string;children:React.ReactNode}){return <label className={styles.field}><span>{label}</span>{children}</label>}
