'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Check, CheckCircle2, Circle, ClipboardCheck, Loader2, Plus } from 'lucide-react';
import { supabase } from '@/lib/supabase';

type Period='opening'|'mid_shift'|'closing';
type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Template={id:string;title:string;period:Period;active:boolean};
type Run={id:string;checklist_template_id:string;business_date:string;started_at:string|null;completed_at:string|null;created_at:string};
type Item={id:string;checklist_run_id:string;template_item_id:string;completed:boolean;completed_at:string|null;note:string|null;checklist_template_items?:{label:string;item_number:number;requires_photo:boolean}|null};

const labels:Record<Period,string>={opening:'Opening',mid_shift:'Mid Shift',closing:'Closing'};
const dateKey=()=>new Date().toLocaleDateString('en-CA');

export default function ShiftPage(){
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const [profile,setProfile]=useState<Profile|null>(null),[period,setPeriod]=useState<Period>('opening'),[templates,setTemplates]=useState<Template[]>([]),[runs,setRuns]=useState<Run[]>([]),[items,setItems]=useState<Item[]>([]);
  const canManage=profile?.app_role==='admin'||profile?.app_role==='manager';
  const todaysRuns=useMemo(()=>runs.filter(r=>r.business_date===dateKey()),[runs]);
  const periodTemplates=templates.filter(t=>t.period===period&&t.active);
  useEffect(()=>{void load()},[]);
  async function load(){setLoading(true);const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return;}const [p,t,r]=await Promise.all([supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single(),supabase.from('checklist_templates').select('id,title,period,active').eq('active',true).order('title'),supabase.from('checklist_runs').select('id,checklist_template_id,business_date,started_at,completed_at,created_at').gte('business_date',new Date(Date.now()-7*86400000).toISOString().slice(0,10)).order('created_at',{ascending:false})]);if(p.data)setProfile(p.data as Profile);setTemplates((t.data??[]) as Template[]);setRuns((r.data??[]) as Run[]);const ids=(r.data??[]).map((x:any)=>x.id);if(ids.length){const it=await supabase.from('checklist_run_items').select('id,checklist_run_id,template_item_id,completed,completed_at,note,checklist_template_items(label,item_number,requires_photo)').in('checklist_run_id',ids).order('created_at');setItems((it.data??[]) as unknown as Item[]);if(it.error)setMessage(it.error.message)}setLoading(false)}
  function flash(x:string){setMessage(x);setTimeout(()=>setMessage(''),3500)}
  async function start(template:Template){if(!canManage)return flash('A manager must start a checklist run.');setBusy(true);const {data:u}=await supabase.auth.getUser();const {error}=await supabase.from('checklist_runs').insert({checklist_template_id:template.id,business_date:dateKey(),started_at:new Date().toISOString(),created_by:u.user?.id??null});setBusy(false);if(error)return flash(error.message);await load();flash(`${template.title} started.`)}
  async function toggle(item:Item){const next=!item.completed;setItems(list=>list.map(x=>x.id===item.id?{...x,completed:next,completed_at:next?new Date().toISOString():null}:x));const {data:u}=await supabase.auth.getUser();const {error}=await supabase.from('checklist_run_items').update({completed:next,completed_by:next?u.user?.id:null,completed_at:next?new Date().toISOString():null}).eq('id',item.id);if(error){await load();flash(error.message);return;}const runItems=items.filter(x=>x.checklist_run_id===item.checklist_run_id);const willComplete=runItems.every(x=>x.id===item.id?next:x.completed);if(willComplete&&canManage)await supabase.from('checklist_runs').update({completed_at:new Date().toISOString()}).eq('id',item.checklist_run_id)}
  async function finish(run:Run){if(!canManage)return;const runItems=items.filter(x=>x.checklist_run_id===run.id);if(!runItems.length||runItems.some(x=>!x.completed))return flash('Complete every item first.');const {error}=await supabase.from('checklist_runs').update({completed_at:new Date().toISOString()}).eq('id',run.id);if(error)return flash(error.message);await load();flash('Checklist completed.')}
  if(loading)return <div className="full-loader"><Loader2 className="spin"/><span>Opening shift workspace…</span></div>;
  return <div className="app-shell"><header className="topbar"><a className="round-button" href="/" aria-label="Back"><ArrowLeft/></a><div style={{flex:1}}><div className="brand-kicker">El Molino Ops</div><div className="brand-title">Run the Shift</div></div></header><main className="page">{message&&<div className="toast-message">{message}</div>}<div className="page-heading"><h1>{labels[period]}</h1><p>Execute today’s assigned checklist work and hand off what remains.</p></div><div className="source-switch" style={{display:'grid!important'} as any}>{(['opening','mid_shift','closing'] as Period[]).map(p=><button key={p} className={period===p?'active':''} onClick={()=>setPeriod(p)}>{labels[p]}</button>)}</div><div className="list">{periodTemplates.map(template=>{const run=todaysRuns.find(r=>r.checklist_template_id===template.id);const runItems=run?items.filter(i=>i.checklist_run_id===run.id).sort((a,b)=>(a.checklist_template_items?.item_number??0)-(b.checklist_template_items?.item_number??0)):[];const done=runItems.filter(x=>x.completed).length;return <div className="card" key={template.id}><div className="card-title-row"><div><h3>{template.title}</h3><small style={{color:'var(--muted)'}}>{run?`${done}/${runItems.length} complete`:'Not started today'}</small></div>{run?.completed_at?<span className="status">Complete</span>:!run&&canManage?<button className="btn" disabled={busy} onClick={()=>start(template)}><Plus/> Start</button>:null}</div>{run&&<div className="list" style={{marginTop:12}}>{runItems.map(item=><button className={`list-item ${item.completed?'completed-row':''}`} key={item.id} onClick={()=>toggle(item)}><span className="task-check">{item.completed?<CheckCircle2/>:<Circle/>}</span><span className="list-main"><b>{item.checklist_template_items?.label||'Checklist item'}</b>{item.checklist_template_items?.requires_photo&&<small>Photo required</small>}</span></button>)}{!runItems.length&&<div className="empty-state"><b>No checklist items</b><span>This template needs items before it can be used.</span></div>}{canManage&&!run.completed_at&&runItems.length>0&&<button className="btn" onClick={()=>finish(run)}><Check/> Finish checklist</button>}</div>}</div>})}{!periodTemplates.length&&<div className="empty-state"><ClipboardCheck/><b>No {labels[period].toLowerCase()} templates</b><span>Managers can create checklist templates from approved procedures.</span></div>}</div><div className="section-title"><h2>Shift records</h2><span>handoff & recap</span></div><div className="quick-grid"><a className="quick-card" href="/ops?kind=shift_handoff&new=1"><ClipboardCheck/><b>Shift handoff</b><small>Pass open work to the next manager.</small></a><a className="quick-card" href="/ops?kind=daily_recap&new=1"><CheckCircle2/><b>Daily recap</b><small>Record the day’s operational summary.</small></a></div></main></div>;
}
