'use client';

import {FormEvent,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase';
import {useI18n} from '@/lib/i18n';
import styles from '../../ops-tools.module.css';
import {businessDateInZone} from '@/lib/intermediate-hardening';
import {addDateDays,dateDayOfWeek,zonedLocalToIso} from '@/lib/scheduling-engine';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Employee={id:string;full_name:string};type Shift={id:string;employee_id:string|null;role_id:string|null;starts_at:string;ends_at:string;status:string;notes:string|null};type Role={id:string;name:string};type FlagType={flag_key:string;label:string;active:boolean;system_type:boolean};type Flag={id:string;shift_id:string;employee_id:string;flag_key:string;note:string|null;created_at:string};
const mondayOf=(d:string)=>addDateDays(d,-((dateDayOfWeek(d)+6)%7));
export default function AttendancePage(){
 const {locale}=useI18n();const localeCode=locale==='es'?'es-US':'en-US';const c=locale==='es'?{access:'No se pudo cargar el acceso de asistencia.',load:'No se pudieron cargar las marcas de asistencia.',notePrompt:(x:string)=>`Nota opcional para ${x}:`,saved:'Marca de asistencia guardada.',removeConfirm:'¿Quitar esta marca de asistencia? La eliminación permanece en el registro de auditoría.',removed:'Marca de asistencia eliminada.',customError:'La marca personalizada necesita una etiqueta y una clave corta.',customAdded:'Marca de asistencia personalizada agregada.',unassigned:'Sin asignar',role:'Puesto',opening:'Abriendo asistencia…',title:'Marcas de Asistencia',body:'Registra lo que ocurrió en un turno programado sin reescribir el historial del horario.',back:'Volver al Horario',manager:'Se requiere acceso de gerente.',week:'Semana del',times:'Las horas se muestran en',previous:'Anterior',next:'Siguiente',custom:'Marca de asistencia personalizada',customBody:'Las marcas estándar Enfermo, Ausente sin aviso, Tarde, Llamó para faltar y Llamado a trabajar son tipos permanentes del sistema. Agrega marcas específicas del restaurante aquí cuando sea necesario.',label:'Etiqueta',labelPlaceholder:'Salió temprano',key:'Clave',keyPlaceholder:'left_early',addType:'Agregar Tipo de Marca',assigned:'Turnos asignados',flags:(n:number)=>`${n} marca${n===1?'':'s'}`,noNote:'Sin nota',remove:'Quitar',none:'No hay turnos asignados esta semana.',system:{sick:'Enfermo',no_show:'Ausente sin aviso',late:'Tarde',called_off:'Llamó para faltar',called_in:'Llamado a trabajar'} as Record<string,string>,status:{draft:'borrador',published:'publicado',open:'abierto',assigned:'asignado'} as Record<string,string>}:{access:'Could not load attendance access.',load:'Could not load attendance flags.',notePrompt:(x:string)=>`Optional note for ${x}:`,saved:'Attendance flag saved.',removeConfirm:'Remove this attendance flag? The removal remains in the audit record.',removed:'Attendance flag removed.',customError:'Custom flag needs a label and a short key.',customAdded:'Custom attendance flag added.',unassigned:'Unassigned',role:'Role',opening:'Opening attendance…',title:'Attendance Flags',body:'Record what happened on a scheduled shift without rewriting the schedule history.',back:'Back to Schedule',manager:'Manager access is required.',week:'Week of',times:'Times display in',previous:'Previous',next:'Next',custom:'Custom attendance flag',customBody:'The standard Sick, No-show, Late, Called off and Called in flags are permanent system types. Add restaurant-specific flags here when needed.',label:'Label',labelPlaceholder:'Left early',key:'Key',keyPlaceholder:'left_early',addType:'Add Flag Type',assigned:'Assigned shifts',flags:(n:number)=>`${n} flag${n===1?'':'s'}`,noNote:'No note',remove:'Remove',none:'No assigned shifts this week.',system:{} as Record<string,string>,status:{draft:'draft',published:'published',open:'open',assigned:'assigned'} as Record<string,string>};
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[profile,setProfile]=useState<Profile|null>(null),[weekStart,setWeekStart]=useState(()=>mondayOf(businessDateInZone())),[timezone,setTimezone]=useState('America/New_York'),[employees,setEmployees]=useState<Employee[]>([]),[roles,setRoles]=useState<Role[]>([]),[shifts,setShifts]=useState<Shift[]>([]),[types,setTypes]=useState<FlagType[]>([]),[flags,setFlags]=useState<Flag[]>([]),[newType,setNewType]=useState({key:'',label:''});
 const canManage=profile?.app_role==='admin'||profile?.app_role==='manager';const flagLabel=(t:FlagType|undefined,key:string)=>t?.system_type?(c.system[key]||t.label):(t?.label||key.replaceAll('_',' '));
 useEffect(()=>{void init()},[]);
 async function init(){const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}const p=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();if(p.error||!p.data?.location_id){setMessage(c.access);setReady(true);return}const pr=p.data as Profile;setProfile(pr);await load(pr,weekStart);setReady(true)}
 async function load(pr=profile,ws=weekStart){if(!pr?.location_id)return;setBusy(true);try{const sr=await supabase.from('schedule_settings').select('timezone').eq('location_id',pr.location_id).maybeSingle();const tz=sr.data?.timezone||'America/New_York';setTimezone(tz);const from=zonedLocalToIso(ws,'00:00:00',tz),to=zonedLocalToIso(addDateDays(ws,7),'00:00:00',tz);const [e,r,s,t,f]=await Promise.all([supabase.from('employees').select('id,full_name').eq('location_id',pr.location_id).eq('active',true).is('deleted_at',null),supabase.from('employee_roles').select('id,name').eq('location_id',pr.location_id),supabase.from('schedule_shifts').select('id,employee_id,role_id,starts_at,ends_at,status,notes').eq('location_id',pr.location_id).gte('starts_at',from).lt('starts_at',to).neq('status','cancelled').order('starts_at'),supabase.from('schedule_attendance_flag_types').select('flag_key,label,active,system_type').eq('location_id',pr.location_id).order('system_type',{ascending:false}).order('label'),supabase.from('schedule_attendance_flags').select('id,shift_id,employee_id,flag_key,note,created_at').eq('location_id',pr.location_id).is('deleted_at',null).order('created_at',{ascending:false})]);for(const x of [e,r,s,t,f])if(x.error)throw x.error;setEmployees((e.data??[]) as Employee[]);setRoles((r.data??[]) as Role[]);setShifts((s.data??[]) as Shift[]);setTypes((t.data??[]) as FlagType[]);setFlags((f.data??[]) as Flag[])}catch(e:any){setMessage(e?.message||c.load)}finally{setBusy(false)}}
 async function changeWeek(days:number){if(busy)return;const ws=addDateDays(weekStart,days);setWeekStart(ws);await load(profile,ws)}
 async function addFlag(shift:Shift,key:string){if(!canManage||busy)return;const type=types.find(x=>x.flag_key===key),note=window.prompt(c.notePrompt(flagLabel(type,key)))||'';setBusy(true);const {error}=await supabase.rpc('record_schedule_attendance_flag',{p_shift_id:shift.id,p_flag_key:key,p_note:note.trim()||null});setMessage(error?error.message:c.saved);await load();setBusy(false)}
 async function removeFlag(id:string){if(!canManage||busy||!window.confirm(c.removeConfirm))return;setBusy(true);const {error}=await supabase.rpc('remove_schedule_attendance_flag',{p_flag_id:id});setMessage(error?error.message:c.removed);await load();setBusy(false)}
 async function createType(e:FormEvent){e.preventDefault();if(!canManage||busy)return;const key=newType.key.trim().toLowerCase().replace(/[^a-z0-9_]+/g,'_').replace(/^_+|_+$/g,'');if(key.length<2||!newType.label.trim()){setMessage(c.customError);return}setBusy(true);const {error}=await supabase.rpc('upsert_schedule_attendance_flag_type',{p_flag_key:key,p_label:newType.label.trim(),p_active:true});setMessage(error?error.message:c.customAdded);if(!error)setNewType({key:'',label:''});await load();setBusy(false)}
 const empName=(id:string|null)=>employees.find(x=>x.id===id)?.full_name||c.unassigned,roleName=(id:string|null)=>roles.find(x=>x.id===id)?.name||c.role,fmt=(iso:string)=>new Date(iso).toLocaleString(localeCode,{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
 const flagMap=useMemo(()=>{const m=new Map<string,Flag[]>();for(const f of flags){const a=m.get(f.shift_id)||[];a.push(f);m.set(f.shift_id,a)}return m},[flags]);
 if(!ready)return <div className="full-loader"><span>{c.opening}</span></div>;
 return <main className={styles.page}><div className={styles.top}><div><h1>{c.title}</h1><p>{c.body}</p></div><Link className={styles.back} href="/schedule">{c.back}</Link></div>{message&&<div className={(message===c.access||message===c.load)?styles.error:styles.notice}>{message}</div>}{!canManage?<div className={styles.error}>{c.manager}</div>:<>
 <section className={styles.section}><div className={styles.card}><div className={styles.entryHead}><div><h2>{c.week} {new Date(`${weekStart}T12:00:00`).toLocaleDateString(localeCode)}</h2><small>{c.times} {timezone}.</small></div><div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>changeWeek(-7)}>{c.previous}</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>changeWeek(7)}>{c.next}</button></div></div></div></section>
 <section className={styles.section}><div className={styles.card}><h2>{c.custom}</h2><p>{c.customBody}</p><form onSubmit={createType}><div className={styles.formGrid}><label className={styles.field}><span>{c.label}</span><input maxLength={80} value={newType.label} onChange={e=>setNewType({...newType,label:e.target.value})} placeholder={c.labelPlaceholder}/></label><label className={styles.field}><span>{c.key}</span><input maxLength={40} value={newType.key} onChange={e=>setNewType({...newType,key:e.target.value})} placeholder={c.keyPlaceholder}/></label></div><div className={styles.actions}><button className={styles.button} disabled={busy}>{c.addType}</button></div></form></div></section>
 <section className={styles.section}><h2>{c.assigned}</h2><div className={styles.list}>{shifts.filter(s=>s.employee_id).map(s=>{const existing=flagMap.get(s.id)||[];return <div className={styles.entry} key={s.id}><div className={styles.entryHead}><div><h3>{empName(s.employee_id)} · {roleName(s.role_id)}</h3><small>{fmt(s.starts_at)} – {new Date(s.ends_at).toLocaleTimeString(localeCode,{hour:'numeric',minute:'2-digit'})} · {c.status[s.status]||s.status}</small></div><span className={styles.pill}>{c.flags(existing.length)}</span></div>{existing.length>0&&<div className={styles.details}>{existing.map(f=>{const type=types.find(t=>t.flag_key===f.flag_key);return <div className={styles.detail} key={f.id}><b>{flagLabel(type,f.flag_key)}</b><span>{f.note||c.noNote} · {new Date(f.created_at).toLocaleString(localeCode)}</span><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>removeFlag(f.id)}>{c.remove}</button></div>})}</div>}<div className={styles.actions}>{types.filter(t=>t.active&&!existing.some(f=>f.flag_key===t.flag_key)).map(t=><button key={t.flag_key} className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>addFlag(s,t.flag_key)}>{flagLabel(t,t.flag_key)}</button>)}</div></div>})}{!shifts.some(s=>s.employee_id)&&<div className={styles.card}><b>{c.none}</b></div>}</div></section>
 </>}</main>
}
