'use client';

import {FormEvent,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase';
import styles from '../../ops-tools.module.css';
import {businessDateInZone} from '@/lib/intermediate-hardening';
import {addDateDays,dateDayOfWeek,zonedLocalToIso} from '@/lib/scheduling-engine';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Employee={id:string;full_name:string};
type Shift={id:string;employee_id:string|null;role_id:string|null;starts_at:string;ends_at:string;status:string;notes:string|null};
type Role={id:string;name:string};
type FlagType={flag_key:string;label:string;active:boolean;system_type:boolean};
type Flag={id:string;shift_id:string;employee_id:string;flag_key:string;note:string|null;created_at:string};
const mondayOf=(d:string)=>addDateDays(d,-((dateDayOfWeek(d)+6)%7));
const fmt=(iso:string)=>new Date(iso).toLocaleString([],{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'});
export default function AttendancePage(){
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[profile,setProfile]=useState<Profile|null>(null),[weekStart,setWeekStart]=useState(()=>mondayOf(businessDateInZone())),[timezone,setTimezone]=useState('America/New_York'),[employees,setEmployees]=useState<Employee[]>([]),[roles,setRoles]=useState<Role[]>([]),[shifts,setShifts]=useState<Shift[]>([]),[types,setTypes]=useState<FlagType[]>([]),[flags,setFlags]=useState<Flag[]>([]),[newType,setNewType]=useState({key:'',label:''});
 const canManage=profile?.app_role==='admin'||profile?.app_role==='manager';
 useEffect(()=>{void init()},[]);
 async function init(){const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}const p=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();if(p.error||!p.data?.location_id){setMessage('Could not load attendance access.');setReady(true);return}const pr=p.data as Profile;setProfile(pr);await load(pr,weekStart);setReady(true)}
 async function load(pr=profile,ws=weekStart){if(!pr?.location_id)return;setBusy(true);try{const sr=await supabase.from('schedule_settings').select('timezone').eq('location_id',pr.location_id).maybeSingle();const tz=sr.data?.timezone||'America/New_York';setTimezone(tz);const from=zonedLocalToIso(ws,'00:00:00',tz),to=zonedLocalToIso(addDateDays(ws,7),'00:00:00',tz);const [e,r,s,t,f]=await Promise.all([supabase.from('employees').select('id,full_name').eq('location_id',pr.location_id).eq('active',true).is('deleted_at',null),supabase.from('employee_roles').select('id,name').eq('location_id',pr.location_id),supabase.from('schedule_shifts').select('id,employee_id,role_id,starts_at,ends_at,status,notes').eq('location_id',pr.location_id).gte('starts_at',from).lt('starts_at',to).neq('status','cancelled').order('starts_at'),supabase.from('schedule_attendance_flag_types').select('flag_key,label,active,system_type').eq('location_id',pr.location_id).order('system_type',{ascending:false}).order('label'),supabase.from('schedule_attendance_flags').select('id,shift_id,employee_id,flag_key,note,created_at').eq('location_id',pr.location_id).is('deleted_at',null).order('created_at',{ascending:false})]);for(const x of [e,r,s,t,f])if(x.error)throw x.error;setEmployees((e.data??[]) as Employee[]);setRoles((r.data??[]) as Role[]);setShifts((s.data??[]) as Shift[]);setTypes((t.data??[]) as FlagType[]);setFlags((f.data??[]) as Flag[])}catch(e:any){setMessage(e?.message||'Could not load attendance flags.')}finally{setBusy(false)}}
 async function changeWeek(days:number){if(busy)return;const ws=addDateDays(weekStart,days);setWeekStart(ws);await load(profile,ws)}
 async function addFlag(shift:Shift,key:string){if(!canManage||busy)return;const note=window.prompt(`Optional note for ${types.find(x=>x.flag_key===key)?.label||key}:`)||'';setBusy(true);const {error}=await supabase.rpc('record_schedule_attendance_flag',{p_shift_id:shift.id,p_flag_key:key,p_note:note.trim()||null});setMessage(error?error.message:'Attendance flag saved.');await load();setBusy(false)}
 async function removeFlag(id:string){if(!canManage||busy||!window.confirm('Remove this attendance flag? The removal remains in the audit record.'))return;setBusy(true);const {error}=await supabase.rpc('remove_schedule_attendance_flag',{p_flag_id:id});setMessage(error?error.message:'Attendance flag removed.');await load();setBusy(false)}
 async function createType(e:FormEvent){e.preventDefault();if(!canManage||busy)return;const key=newType.key.trim().toLowerCase().replace(/[^a-z0-9_]+/g,'_').replace(/^_+|_+$/g,'');if(key.length<2||!newType.label.trim()){setMessage('Custom flag needs a label and a short key.');return}setBusy(true);const {error}=await supabase.rpc('upsert_schedule_attendance_flag_type',{p_flag_key:key,p_label:newType.label.trim(),p_active:true});setMessage(error?error.message:'Custom attendance flag added.');if(!error)setNewType({key:'',label:''});await load();setBusy(false)}
 const empName=(id:string|null)=>employees.find(x=>x.id===id)?.full_name||'Unassigned';const roleName=(id:string|null)=>roles.find(x=>x.id===id)?.name||'Role';
 const flagMap=useMemo(()=>{const m=new Map<string,Flag[]>();for(const f of flags){const a=m.get(f.shift_id)||[];a.push(f);m.set(f.shift_id,a)}return m},[flags]);
 if(!ready)return <div className="full-loader"><span>Opening attendance…</span></div>;
 return <main className={styles.page}><div className={styles.top}><div><h1>Attendance Flags</h1><p>Record what happened on a scheduled shift without rewriting the schedule history.</p></div><Link className={styles.back} href="/schedule">Back to Schedule</Link></div>{message&&<div className={message.toLowerCase().includes('could not')?styles.error:styles.notice}>{message}</div>}{!canManage?<div className={styles.error}>Manager access is required.</div>:<>
 <section className={styles.section}><div className={styles.card}><div className={styles.entryHead}><div><h2>Week of {weekStart}</h2><small>Times display in {timezone}.</small></div><div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>changeWeek(-7)}>Previous</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>changeWeek(7)}>Next</button></div></div></div></section>
 <section className={styles.section}><div className={styles.card}><h2>Custom attendance flag</h2><p>The standard Sick, No-show, Late, Called off and Called in flags are permanent system types. Add restaurant-specific flags here when needed.</p><form onSubmit={createType}><div className={styles.formGrid}><label className={styles.field}><span>Label</span><input maxLength={80} value={newType.label} onChange={e=>setNewType({...newType,label:e.target.value})} placeholder="Left early"/></label><label className={styles.field}><span>Key</span><input maxLength={40} value={newType.key} onChange={e=>setNewType({...newType,key:e.target.value})} placeholder="left_early"/></label></div><div className={styles.actions}><button className={styles.button} disabled={busy}>Add Flag Type</button></div></form></div></section>
 <section className={styles.section}><h2>Assigned shifts</h2><div className={styles.list}>{shifts.filter(s=>s.employee_id).map(s=>{const existing=flagMap.get(s.id)||[];return <div className={styles.entry} key={s.id}><div className={styles.entryHead}><div><h3>{empName(s.employee_id)} · {roleName(s.role_id)}</h3><small>{fmt(s.starts_at)} – {new Date(s.ends_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})} · {s.status}</small></div><span className={styles.pill}>{existing.length} flag{existing.length===1?'':'s'}</span></div>{existing.length>0&&<div className={styles.details}>{existing.map(f=><div className={styles.detail} key={f.id}><b>{types.find(t=>t.flag_key===f.flag_key)?.label||f.flag_key.replaceAll('_',' ')}</b><span>{f.note||'No note'} · {new Date(f.created_at).toLocaleString()}</span><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>removeFlag(f.id)}>Remove</button></div>)}</div>}<div className={styles.actions}>{types.filter(t=>t.active&&!existing.some(f=>f.flag_key===t.flag_key)).map(t=><button key={t.flag_key} className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>addFlag(s,t.flag_key)}>{t.label}</button>)}</div></div>})}{!shifts.some(s=>s.employee_id)&&<div className={styles.card}><b>No assigned shifts this week.</b></div>}</div></section>
 </>}</main>
}
