create or replace function public.shift_pool_candidate_warnings(p_offer_id uuid,p_employee_id uuid default null)
returns jsonb language plpgsql security definer set search_path='pg_catalog','public' as $$
declare loc uuid:=public.current_location_id();emp uuid:=coalesce(p_employee_id,public.current_schedule_employee_id());o public.shift_pool_offers%rowtype;s public.schedule_shifts%rowtype;tz text;local_start timestamp;local_end timestamp;dow integer;av public.employee_availability%rowtype;prof public.employee_schedule_profiles%rowtype;issues jsonb:='[]'::jsonb;week_start date;existing_hours numeric:=0;offered_hours numeric:=0;ot numeric:=40;
begin
 if auth.uid() is null or loc is null or emp is null then raise exception 'employee required';end if;if p_employee_id is not null and public.current_app_role() not in('admin','manager') and p_employee_id<>public.current_schedule_employee_id() then raise exception 'manager access required';end if;select * into o from public.shift_pool_offers where id=p_offer_id and location_id=loc;if not found then raise exception 'offer not found';end if;select * into s from public.schedule_shifts where id=o.shift_id and location_id=loc;if not found then raise exception 'shift not found';end if;
 if emp=o.offered_by_employee_id then issues:=issues||jsonb_build_array(jsonb_build_object('code','same_employee','severity','error','message','You already own this shift.'));end if;if not exists(select 1 from public.employees e where e.id=emp and e.location_id=loc and e.active and e.deleted_at is null and coalesce(e.employment_status,'active')='active') then issues:=issues||jsonb_build_array(jsonb_build_object('code','inactive','severity','error','message','Employee is not active at this location.'));end if;if s.role_id is not null and not exists(select 1 from public.employee_role_assignments a where a.employee_id=emp and a.role_id=s.role_id) then issues:=issues||jsonb_build_array(jsonb_build_object('code','role','severity','error','message','You are not qualified for this role.'));end if;if exists(select 1 from public.schedule_shifts x where x.employee_id=emp and x.id<>s.id and x.status in('scheduled','covered') and tstzrange(x.starts_at,x.ends_at,'[)')&&tstzrange(o.offered_starts_at,o.offered_ends_at,'[)')) then issues:=issues||jsonb_build_array(jsonb_build_object('code','overlap','severity','error','message','You already have an overlapping shift.'));end if;if public.time_off_conflicts_shift(emp,loc,o.offered_starts_at,o.offered_ends_at,'approved') then issues:=issues||jsonb_build_array(jsonb_build_object('code','time_off','severity','error','message','You have approved time off during this shift.'));end if;
 tz:=public.schedule_timezone(loc);local_start:=o.offered_starts_at at time zone tz;local_end:=o.offered_ends_at at time zone tz;dow:=extract(dow from local_start)::integer;select * into av from public.employee_availability where employee_id=emp and location_id=loc and day_of_week=dow;if found and(av.unavailable or(av.available_from is not null and local_start::time<av.available_from) or(av.available_to is not null and local_end::time>av.available_to)) then issues:=issues||jsonb_build_array(jsonb_build_object('code','availability','severity','error','message','This shift falls outside your availability.'));end if;
 select * into prof from public.employee_schedule_profiles where employee_id=emp and location_id=loc;offered_hours:=extract(epoch from(o.offered_ends_at-o.offered_starts_at))/3600.0;if prof.employee_id is not null and prof.max_shift_hours is not null and offered_hours>prof.max_shift_hours then issues:=issues||jsonb_build_array(jsonb_build_object('code','max_shift','severity','error','message','This shift exceeds your maximum shift length.'));end if;if prof.employee_id is not null and prof.min_rest_hours is not null and exists(select 1 from public.schedule_shifts x where x.employee_id=emp and x.id<>s.id and x.status in('scheduled','covered') and((x.ends_at<=o.offered_starts_at and extract(epoch from(o.offered_starts_at-x.ends_at))/3600.0<prof.min_rest_hours) or(x.starts_at>=o.offered_ends_at and extract(epoch from(x.starts_at-o.offered_ends_at))/3600.0<prof.min_rest_hours))) then issues:=issues||jsonb_build_array(jsonb_build_object('code','rest','severity','error','message','This shift would violate your minimum rest period.'));end if;
 week_start:=date_trunc('week',local_start)::date;select coalesce(sum(public.schedule_net_hours(x.starts_at,x.ends_at,x.break_minutes)),0) into existing_hours from public.schedule_shifts x where x.employee_id=emp and x.id<>s.id and x.status in('scheduled','covered') and(x.starts_at at time zone tz)::date>=week_start and(x.starts_at at time zone tz)::date<week_start+7;if prof.employee_id is not null and prof.max_weekly_hours is not null and existing_hours+offered_hours>prof.max_weekly_hours then issues:=issues||jsonb_build_array(jsonb_build_object('code','max_hours','severity','error','message','This shift would exceed your maximum weekly hours.','projected_hours',round(existing_hours+offered_hours,2)));end if;select coalesce(overtime_after_hours,40) into ot from public.schedule_settings where location_id=loc;ot:=coalesce(ot,40);if existing_hours+offered_hours>ot then issues:=issues||jsonb_build_array(jsonb_build_object('code','overtime','severity','warning','message','This shift would create overtime and still needs manager approval.','projected_hours',round(existing_hours+offered_hours,2)));end if;return issues;
end$$;

create or replace function public.open_shift_candidate_warnings(p_shift_id uuid,p_employee_id uuid default null)
returns jsonb language plpgsql security definer set search_path='pg_catalog','public' as $$
declare loc uuid:=public.current_location_id();emp uuid:=coalesce(p_employee_id,public.current_schedule_employee_id());s public.schedule_shifts%rowtype;tz text;local_start timestamp;local_end timestamp;dow integer;av public.employee_availability%rowtype;prof public.employee_schedule_profiles%rowtype;issues jsonb:='[]'::jsonb;week_start date;existing_hours numeric:=0;candidate_hours numeric:=0;ot numeric:=40;
begin
 if auth.uid() is null or loc is null or emp is null then raise exception 'employee required';end if;if p_employee_id is not null and public.current_app_role() not in('admin','manager') and p_employee_id<>public.current_schedule_employee_id() then raise exception 'manager access required';end if;select * into s from public.schedule_shifts where id=p_shift_id and location_id=loc;if not found then raise exception 'shift not found';end if;if s.status<>'open' or s.employee_id is not null or s.ends_at<=now() then issues:=issues||jsonb_build_array(jsonb_build_object('code','unavailable','severity','error','message','This open shift is no longer available.'));return issues;end if;if s.schedule_period_id is not null and not public.is_schedule_department_published(s.schedule_period_id,s.role_id) then issues:=issues||jsonb_build_array(jsonb_build_object('code','unpublished','severity','error','message','This shift is not published.'));end if;if not exists(select 1 from public.employees e where e.id=emp and e.location_id=loc and e.active and e.deleted_at is null and coalesce(e.employment_status,'active')='active') then issues:=issues||jsonb_build_array(jsonb_build_object('code','inactive','severity','error','message','Employee is not active at this location.'));end if;if s.role_id is not null and not exists(select 1 from public.employee_role_assignments a where a.employee_id=emp and a.role_id=s.role_id) then issues:=issues||jsonb_build_array(jsonb_build_object('code','role','severity','error','message','You are not qualified for this role.'));end if;if exists(select 1 from public.schedule_shifts x where x.employee_id=emp and x.id<>s.id and x.status in('scheduled','covered') and tstzrange(x.starts_at,x.ends_at,'[)')&&tstzrange(s.starts_at,s.ends_at,'[)')) then issues:=issues||jsonb_build_array(jsonb_build_object('code','overlap','severity','error','message','You already have an overlapping shift.'));end if;if public.time_off_conflicts_shift(emp,loc,s.starts_at,s.ends_at,'approved') then issues:=issues||jsonb_build_array(jsonb_build_object('code','time_off','severity','error','message','You have approved time off during this shift.'));end if;
 tz:=public.schedule_timezone(loc);local_start:=s.starts_at at time zone tz;local_end:=s.ends_at at time zone tz;dow:=extract(dow from local_start)::integer;select * into av from public.employee_availability where employee_id=emp and location_id=loc and day_of_week=dow;if found and(av.unavailable or(av.available_from is not null and local_start::time<av.available_from) or(av.available_to is not null and local_end::time>av.available_to)) then issues:=issues||jsonb_build_array(jsonb_build_object('code','availability','severity','error','message','This shift falls outside your availability.'));end if;select * into prof from public.employee_schedule_profiles where employee_id=emp and location_id=loc;candidate_hours:=public.schedule_net_hours(s.starts_at,s.ends_at,s.break_minutes);if prof.employee_id is not null and prof.max_shift_hours is not null and candidate_hours>prof.max_shift_hours then issues:=issues||jsonb_build_array(jsonb_build_object('code','max_shift','severity','error','message','This shift exceeds your maximum shift length.'));end if;if prof.employee_id is not null and prof.min_rest_hours is not null and exists(select 1 from public.schedule_shifts x where x.employee_id=emp and x.id<>s.id and x.status in('scheduled','covered') and((x.ends_at<=s.starts_at and extract(epoch from(s.starts_at-x.ends_at))/3600.0<prof.min_rest_hours) or(x.starts_at>=s.ends_at and extract(epoch from(x.starts_at-s.ends_at))/3600.0<prof.min_rest_hours))) then issues:=issues||jsonb_build_array(jsonb_build_object('code','rest','severity','error','message','This shift would violate your minimum rest period.'));end if;week_start:=date_trunc('week',local_start)::date;select coalesce(sum(public.schedule_net_hours(x.starts_at,x.ends_at,x.break_minutes)),0) into existing_hours from public.schedule_shifts x where x.employee_id=emp and x.id<>s.id and x.status in('scheduled','covered') and(x.starts_at at time zone tz)::date>=week_start and(x.starts_at at time zone tz)::date<week_start+7;if prof.employee_id is not null and prof.max_weekly_hours is not null and existing_hours+candidate_hours>prof.max_weekly_hours then issues:=issues||jsonb_build_array(jsonb_build_object('code','max_hours','severity','error','message','This shift would exceed your maximum weekly hours.','projected_hours',round(existing_hours+candidate_hours,2)));end if;select coalesce(overtime_after_hours,40) into ot from public.schedule_settings where location_id=loc;ot:=coalesce(ot,40);if existing_hours+candidate_hours>ot then issues:=issues||jsonb_build_array(jsonb_build_object('code','overtime','severity','warning','message','This shift would create overtime and still needs manager approval.','projected_hours',round(existing_hours+candidate_hours,2)));end if;return issues;
end$$;
grant execute on function public.open_shift_candidate_warnings(uuid,uuid) to authenticated;revoke execute on function public.open_shift_candidate_warnings(uuid,uuid) from anon,public;

create or replace function public.claim_open_shift(p_shift_id uuid)
returns text language plpgsql security definer set search_path='pg_catalog','public' as $$
declare s public.schedule_shifts%rowtype;emp_id uuid;loc uuid:=public.current_location_id();needs_approval boolean:=true;claim_id uuid;warnings jsonb;
begin if auth.uid() is null or loc is null then raise exception 'authentication required';end if;emp_id:=public.current_schedule_employee_id();if emp_id is null then raise exception 'active employee record required';end if;select * into s from public.schedule_shifts where id=p_shift_id and location_id=loc for update;if not found then raise exception 'open shift is no longer available';end if;warnings:=public.open_shift_candidate_warnings(s.id,emp_id);if exists(select 1 from jsonb_array_elements(warnings) x where x->>'severity'='error') then raise exception 'this shift conflicts with your schedule, availability, time off, role, rest, or hour limits';end if;select coalesce(x.open_shift_claim_requires_approval,true) into needs_approval from public.schedule_settings x where x.location_id=loc;needs_approval:=coalesce(needs_approval,true);insert into public.shift_claims(location_id,shift_id,employee_id,status,requested_by) values(loc,s.id,emp_id,case when needs_approval then 'pending' else 'approved' end,auth.uid()) returning id into claim_id;if needs_approval then perform public.notify_location_managers(loc,'staffing','Open shift claim needs review','An employee requested an open shift.','/schedule',jsonb_build_object('shift_id',s.id,'claim_id',claim_id));return 'pending';end if;perform set_config('el_molino.published_schedule_rpc','1',true);update public.schedule_shifts set employee_id=emp_id,status='covered',source='claim' where id=s.id;update public.shift_claims set reviewed_by=auth.uid(),reviewed_at=now() where id=claim_id;return 'approved';end$$;

create or replace function public.review_shift_claim(p_claim_id uuid,p_decision text)
returns boolean language plpgsql security definer set search_path='pg_catalog','public' as $$
declare c public.shift_claims%rowtype;s public.schedule_shifts%rowtype;loc uuid:=public.current_location_id();warnings jsonb;
begin if auth.uid() is null or public.current_app_role() not in('admin','manager') then raise exception 'manager access required';end if;if p_decision not in('approved','denied') then raise exception 'invalid decision';end if;select * into c from public.shift_claims where id=p_claim_id and location_id=loc and status='pending' for update;if not found then return false;end if;select * into s from public.schedule_shifts where id=c.shift_id and location_id=loc for update;if not found then raise exception 'shift not found';end if;if p_decision='approved' then warnings:=public.open_shift_candidate_warnings(s.id,c.employee_id);if exists(select 1 from jsonb_array_elements(warnings) x where x->>'severity'='error') then raise exception 'claim can no longer be approved because the employee now conflicts with this shift';end if;perform set_config('el_molino.published_schedule_rpc','1',true);update public.schedule_shifts set employee_id=c.employee_id,status='covered',source='claim' where id=s.id;update public.shift_claims set status='denied',reviewed_by=auth.uid(),reviewed_at=now() where shift_id=s.id and status='pending' and id<>c.id;end if;update public.shift_claims set status=p_decision,reviewed_by=auth.uid(),reviewed_at=now() where id=c.id;perform public.notify_schedule_employee(loc,c.employee_id,'schedule','Open-shift claim '||p_decision,'Your open-shift request was '||p_decision||'.','/schedule/pool',jsonb_build_object('shift_id',s.id,'claim_id',c.id,'decision',p_decision));return true;end$$;
