create or replace function public.employee_trade_candidate_warnings(p_employee_id uuid,p_remove_shift_id uuid,p_add_shift_id uuid)
returns jsonb language plpgsql stable security definer set search_path='pg_catalog','public' as $$
declare loc uuid:=public.current_location_id();add_shift public.schedule_shifts%rowtype;remove_shift public.schedule_shifts%rowtype;prof public.employee_schedule_profiles%rowtype;av public.employee_availability%rowtype;issues jsonb:='[]'::jsonb;tz text;local_start timestamp;local_end timestamp;dow int;week_start date;existing_hours numeric:=0;add_hours numeric:=0;ot numeric:=40;
begin
 if auth.uid() is null or loc is null or p_employee_id is null then raise exception 'authentication required';end if;select * into add_shift from public.schedule_shifts where id=p_add_shift_id and location_id=loc;if not found then raise exception 'trade add shift not found';end if;select * into remove_shift from public.schedule_shifts where id=p_remove_shift_id and location_id=loc;if not found then raise exception 'trade remove shift not found';end if;
 if not exists(select 1 from public.employees e where e.id=p_employee_id and e.location_id=loc and e.active and e.deleted_at is null and coalesce(e.employment_status,'active')='active') then issues:=issues||jsonb_build_array(jsonb_build_object('code','inactive','severity','error','message','Employee is not active.'));end if;if add_shift.role_id is not null and not exists(select 1 from public.employee_role_assignments a where a.employee_id=p_employee_id and a.role_id=add_shift.role_id) then issues:=issues||jsonb_build_array(jsonb_build_object('code','role','severity','error','message','Employee is not qualified for the incoming role.'));end if;if public.time_off_conflicts_shift(p_employee_id,loc,add_shift.starts_at,add_shift.ends_at,'approved') then issues:=issues||jsonb_build_array(jsonb_build_object('code','time_off','severity','error','message','Incoming shift conflicts with approved time off.'));end if;if exists(select 1 from public.schedule_shifts x where x.location_id=loc and x.employee_id=p_employee_id and x.id not in(p_remove_shift_id,p_add_shift_id) and x.status in('scheduled','covered') and tstzrange(x.starts_at,x.ends_at,'[)')&&tstzrange(add_shift.starts_at,add_shift.ends_at,'[)')) then issues:=issues||jsonb_build_array(jsonb_build_object('code','overlap','severity','error','message','Incoming shift overlaps another scheduled shift.'));end if;
 tz:=public.schedule_timezone(loc);local_start:=add_shift.starts_at at time zone tz;local_end:=add_shift.ends_at at time zone tz;dow:=extract(dow from local_start)::int;select * into av from public.employee_availability where employee_id=p_employee_id and location_id=loc and day_of_week=dow;if found and(av.unavailable or(av.available_from is not null and local_start::time<av.available_from) or(av.available_to is not null and local_end::time>av.available_to)) then issues:=issues||jsonb_build_array(jsonb_build_object('code','availability','severity','error','message','Incoming shift falls outside employee availability.'));end if;select * into prof from public.employee_schedule_profiles where employee_id=p_employee_id and location_id=loc;add_hours:=public.schedule_net_hours(add_shift.starts_at,add_shift.ends_at,add_shift.break_minutes);if prof.employee_id is not null and prof.max_shift_hours is not null and add_hours>prof.max_shift_hours then issues:=issues||jsonb_build_array(jsonb_build_object('code','max_shift','severity','error','message','Incoming shift exceeds maximum shift length.'));end if;if prof.employee_id is not null and prof.min_rest_hours is not null and exists(select 1 from public.schedule_shifts x where x.location_id=loc and x.employee_id=p_employee_id and x.id not in(p_remove_shift_id,p_add_shift_id) and x.status in('scheduled','covered') and((x.ends_at<=add_shift.starts_at and extract(epoch from(add_shift.starts_at-x.ends_at))/3600.0<prof.min_rest_hours) or(x.starts_at>=add_shift.ends_at and extract(epoch from(x.starts_at-add_shift.ends_at))/3600.0<prof.min_rest_hours))) then issues:=issues||jsonb_build_array(jsonb_build_object('code','rest','severity','error','message','Incoming shift violates minimum rest.'));end if;week_start:=date_trunc('week',local_start)::date;select coalesce(sum(public.schedule_net_hours(x.starts_at,x.ends_at,x.break_minutes)),0) into existing_hours from public.schedule_shifts x where x.location_id=loc and x.employee_id=p_employee_id and x.id not in(p_remove_shift_id,p_add_shift_id) and x.status in('scheduled','covered') and(x.starts_at at time zone tz)::date>=week_start and(x.starts_at at time zone tz)::date<week_start+7;if prof.employee_id is not null and prof.max_weekly_hours is not null and existing_hours+add_hours>prof.max_weekly_hours then issues:=issues||jsonb_build_array(jsonb_build_object('code','max_hours','severity','error','message','Incoming shift would exceed maximum weekly hours.','projected_hours',round(existing_hours+add_hours,2)));end if;select coalesce(overtime_after_hours,40) into ot from public.schedule_settings where location_id=loc;ot:=coalesce(ot,40);if existing_hours+add_hours>ot then issues:=issues||jsonb_build_array(jsonb_build_object('code','overtime','severity','warning','message','Trade would create overtime.','projected_hours',round(existing_hours+add_hours,2)));end if;return issues;
end$$;

create or replace function public.staff_trade_candidates(p_shift_id uuid)
returns table(shift_id uuid,employee_id uuid,employee_name text,role_id uuid,role_name text,starts_at timestamptz,ends_at timestamptz)
language plpgsql stable security definer set search_path='pg_catalog','public','auth' as $$
declare loc uuid:=public.current_location_id();eid uuid:=public.current_schedule_employee_id();src public.schedule_shifts%rowtype;
begin if auth.uid() is null or loc is null or eid is null then return;end if;select s.* into src from public.schedule_shifts s where s.id=p_shift_id and s.location_id=loc and s.employee_id=eid and s.status in('scheduled','covered');if not found or src.role_id is null then return;end if;if src.schedule_period_id is not null and not public.is_schedule_department_published(src.schedule_period_id,src.role_id) then return;end if;return query select t.id,t.employee_id,e.full_name,t.role_id,r.name,t.starts_at,t.ends_at from public.schedule_shifts t join public.employees e on e.id=t.employee_id and e.location_id=loc and e.active and e.deleted_at is null join public.employee_roles r on r.id=t.role_id and r.location_id=loc where t.location_id=loc and t.id<>src.id and t.employee_id is not null and t.employee_id<>eid and t.role_id is not null and t.status in('scheduled','covered') and t.ends_at>now() and(t.schedule_period_id is null or public.is_schedule_department_published(t.schedule_period_id,t.role_id)) and not exists(select 1 from jsonb_array_elements(public.employee_trade_candidate_warnings(eid,src.id,t.id)) w where w->>'severity'='error') and not exists(select 1 from jsonb_array_elements(public.employee_trade_candidate_warnings(t.employee_id,t.id,src.id)) w where w->>'severity'='error') order by t.starts_at,e.full_name,t.id;end$$;

-- review_shift_change_request was also hardened in production to rerun employee_trade_candidate_warnings for both employees immediately before a swap and to abort if either side has a new error.
revoke execute on function public.employee_trade_candidate_warnings(uuid,uuid,uuid) from authenticated,anon,public;
