alter table public.team_announcements add column if not exists requires_acknowledgment boolean not null default false;
alter table public.team_announcement_recipients add column if not exists acknowledged_at timestamptz;

create table if not exists public.team_channels (
 id uuid primary key default gen_random_uuid(),location_id uuid not null,channel_kind text not null default 'direct' check(channel_kind in('direct','group')),title text,direct_key text,created_by_user_id uuid,created_at timestamptz not null default now(),archived_at timestamptz,check(char_length(coalesce(title,''))<=160)
);
create unique index if not exists team_channels_direct_key_uq on public.team_channels(location_id,direct_key) where direct_key is not null;
create index if not exists team_channels_location_idx on public.team_channels(location_id,created_at desc);
create table if not exists public.team_channel_members (
 channel_id uuid not null references public.team_channels(id) on delete cascade,location_id uuid not null,employee_id uuid not null references public.employees(id) on delete cascade,joined_at timestamptz not null default now(),last_read_at timestamptz,primary key(channel_id,employee_id)
);
create index if not exists team_channel_members_employee_idx on public.team_channel_members(employee_id,channel_id);
create table if not exists public.team_channel_messages (
 id uuid primary key default gen_random_uuid(),channel_id uuid not null references public.team_channels(id) on delete cascade,location_id uuid not null,author_employee_id uuid not null references public.employees(id),body text not null check(char_length(body) between 1 and 2000),created_at timestamptz not null default now(),deleted_at timestamptz
);
create index if not exists team_channel_messages_channel_idx on public.team_channel_messages(channel_id,created_at desc);
alter table public.team_channels enable row level security;alter table public.team_channel_members enable row level security;alter table public.team_channel_messages enable row level security;
revoke all on public.team_channels,public.team_channel_members,public.team_channel_messages from anon,authenticated;

create or replace function public.resolve_manager_on_duty_employee_id() returns uuid language plpgsql stable security definer set search_path='pg_catalog','public' as $$
declare loc uuid:=public.current_location_id();out_id uuid;
begin
 if auth.uid() is null or loc is null then return null;end if;
 select e.id into out_id from public.employees e join public.profiles p on p.id=e.user_id join public.schedule_shifts s on s.employee_id=e.id and s.location_id=loc where e.location_id=loc and e.active and e.deleted_at is null and coalesce(e.employment_status,'active')='active' and p.app_role in('admin','manager') and s.status in('scheduled','covered') and s.starts_at<=now() and s.ends_at>now() order by s.starts_at,e.full_name limit 1;if out_id is not null then return out_id;end if;
 select e.id into out_id from public.employees e join public.profiles p on p.id=e.user_id join public.schedule_shifts s on s.employee_id=e.id and s.location_id=loc where e.location_id=loc and e.active and e.deleted_at is null and coalesce(e.employment_status,'active')='active' and p.app_role in('admin','manager') and s.status in('scheduled','covered') and s.starts_at>now() order by s.starts_at,e.full_name limit 1;if out_id is not null then return out_id;end if;
 select e.id into out_id from public.employees e join public.profiles p on p.id=e.user_id where e.location_id=loc and e.active and e.deleted_at is null and coalesce(e.employment_status,'active')='active' and p.app_role in('admin','manager') order by case p.app_role when 'manager' then 0 else 1 end,e.full_name limit 1;return out_id;
end$$;

create or replace function public.staff_manager_on_duty() returns jsonb language plpgsql stable security definer set search_path='pg_catalog','public' as $$
declare loc uuid:=public.current_location_id();mid uuid;nm text;st text:='fallback';shift_start timestamptz;shift_end timestamptz;
begin
 if auth.uid() is null or loc is null then raise exception 'authentication required';end if;mid:=public.resolve_manager_on_duty_employee_id();if mid is null then return jsonb_build_object('available',false);end if;select e.full_name into nm from public.employees e where e.id=mid and e.location_id=loc;
 select s.starts_at,s.ends_at into shift_start,shift_end from public.schedule_shifts s where s.employee_id=mid and s.location_id=loc and s.status in('scheduled','covered') and s.starts_at<=now() and s.ends_at>now() order by s.starts_at limit 1;if shift_start is not null then st:='on_duty';else select s.starts_at,s.ends_at into shift_start,shift_end from public.schedule_shifts s where s.employee_id=mid and s.location_id=loc and s.status in('scheduled','covered') and s.starts_at>now() order by s.starts_at limit 1;if shift_start is not null then st:='next_manager';end if;end if;
 return jsonb_build_object('available',true,'employee_id',mid,'full_name',nm,'state',st,'shift_starts_at',shift_start,'shift_ends_at',shift_end);
end$$;

create or replace function public.start_direct_team_channel(p_other_employee_id uuid) returns uuid language plpgsql security definer set search_path='pg_catalog','public' as $$
declare loc uuid:=public.current_location_id();me uuid:=public.current_schedule_employee_id();cid uuid;dkey text;
begin
 if auth.uid() is null or loc is null or me is null then raise exception 'active employee login required';end if;if p_other_employee_id is null or p_other_employee_id=me then raise exception 'choose another active teammate';end if;if not exists(select 1 from public.employees e where e.id=p_other_employee_id and e.location_id=loc and e.active and e.deleted_at is null and coalesce(e.employment_status,'active')='active') then raise exception 'teammate is not available';end if;
 dkey:=case when me::text<p_other_employee_id::text then me::text||':'||p_other_employee_id::text else p_other_employee_id::text||':'||me::text end;insert into public.team_channels(location_id,channel_kind,direct_key,created_by_user_id) values(loc,'direct',dkey,auth.uid()) on conflict(location_id,direct_key) where direct_key is not null do update set archived_at=null returning id into cid;insert into public.team_channel_members(channel_id,location_id,employee_id,last_read_at) values(cid,loc,me,now()),(cid,loc,p_other_employee_id,null) on conflict(channel_id,employee_id) do update set location_id=excluded.location_id;return cid;
end$$;

create or replace function public.start_manager_on_duty_channel() returns jsonb language plpgsql security definer set search_path='pg_catalog','public' as $$
declare mid uuid;cid uuid;info jsonb;
begin if auth.uid() is null or public.current_schedule_employee_id() is null then raise exception 'active employee login required';end if;info:=public.staff_manager_on_duty();if coalesce((info->>'available')::boolean,false)=false then raise exception 'no manager account is available';end if;mid:=(info->>'employee_id')::uuid;if mid=public.current_schedule_employee_id() then raise exception 'you are the manager on duty';end if;cid:=public.start_direct_team_channel(mid);return info||jsonb_build_object('channel_id',cid);end$$;

create or replace function public.my_team_channels() returns jsonb language sql stable security definer set search_path='pg_catalog','public' as $$with me as(select public.current_schedule_employee_id() eid,public.current_location_id() loc),base as(select c.id,c.channel_kind,c.title,m.last_read_at,case when c.channel_kind='direct' then coalesce((select e.full_name from public.team_channel_members om join public.employees e on e.id=om.employee_id where om.channel_id=c.id and om.employee_id<>me.eid limit 1),c.title,'Conversation') else coalesce(c.title,'Team conversation') end display_name,(select max(x.created_at) from public.team_channel_messages x where x.channel_id=c.id and x.deleted_at is null) last_message_at,(select count(*)::int from public.team_channel_messages x where x.channel_id=c.id and x.deleted_at is null and x.author_employee_id<>me.eid and x.created_at>coalesce(m.last_read_at,'epoch'::timestamptz)) unread_count,(select left(x.body,160) from public.team_channel_messages x where x.channel_id=c.id and x.deleted_at is null order by x.created_at desc limit 1) last_message from me join public.team_channel_members m on m.employee_id=me.eid and m.location_id=me.loc join public.team_channels c on c.id=m.channel_id and c.location_id=me.loc and c.archived_at is null)select coalesce(jsonb_agg(to_jsonb(base) order by coalesce(last_message_at,'epoch'::timestamptz) desc,display_name),'[]'::jsonb) from base$$;
create or replace function public.team_channel_messages_for_me(p_channel_id uuid,p_limit integer default 100) returns jsonb language sql stable security definer set search_path='pg_catalog','public' as $$with me as(select public.current_schedule_employee_id() eid,public.current_location_id() loc),allowed as(select 1 from me join public.team_channel_members m on m.employee_id=me.eid and m.location_id=me.loc and m.channel_id=p_channel_id),rows as(select x.id,x.channel_id,x.author_employee_id,e.full_name author_name,x.body,x.created_at,(x.author_employee_id=me.eid) mine from me,allowed,public.team_channel_messages x join public.employees e on e.id=x.author_employee_id where x.channel_id=p_channel_id and x.location_id=me.loc and x.deleted_at is null order by x.created_at desc limit greatest(1,least(coalesce(p_limit,100),200)))select coalesce(jsonb_agg(to_jsonb(rows) order by created_at),'[]'::jsonb) from rows$$;
create or replace function public.mark_team_channel_read(p_channel_id uuid) returns boolean language plpgsql security definer set search_path='pg_catalog','public' as $$declare loc uuid:=public.current_location_id();me uuid:=public.current_schedule_employee_id();begin if auth.uid() is null or loc is null or me is null then raise exception 'active employee login required';end if;update public.team_channel_members set last_read_at=now() where channel_id=p_channel_id and employee_id=me and location_id=loc;if not found then raise exception 'conversation not available';end if;return true;end$$;
create or replace function public.send_team_channel_message(p_channel_id uuid,p_body text) returns uuid language plpgsql security definer set search_path='pg_catalog','public' as $$declare loc uuid:=public.current_location_id();me uuid:=public.current_schedule_employee_id();mid uuid;sender text;begin if auth.uid() is null or loc is null or me is null then raise exception 'active employee login required';end if;if char_length(trim(coalesce(p_body,''))) not between 1 and 2000 then raise exception 'message must be 1-2000 characters';end if;if not exists(select 1 from public.team_channel_members m join public.team_channels c on c.id=m.channel_id where m.channel_id=p_channel_id and m.employee_id=me and m.location_id=loc and c.location_id=loc and c.archived_at is null) then raise exception 'conversation not available';end if;select e.full_name into sender from public.employees e where e.id=me;insert into public.team_channel_messages(channel_id,location_id,author_employee_id,body) values(p_channel_id,loc,me,trim(p_body)) returning id into mid;update public.team_channel_members set last_read_at=now() where channel_id=p_channel_id and employee_id=me;insert into public.notifications(location_id,user_id,type,title,body,href,data,category,event_key,dedupe_key,priority) select loc,e.user_id,'team','New message from '||coalesce(sender,'Teammate'),left(trim(p_body),160),'/employee/team?channel='||p_channel_id::text,jsonb_build_object('channel_id',p_channel_id,'message_id',mid),'team','team.message','team.message:'||mid::text||':'||e.user_id::text,'normal' from public.team_channel_members m join public.employees e on e.id=m.employee_id where m.channel_id=p_channel_id and m.location_id=loc and m.employee_id<>me and e.user_id is not null and e.active and e.deleted_at is null on conflict do nothing;return mid;end$$;
create or replace function public.acknowledge_team_announcement(p_announcement_id uuid) returns boolean language plpgsql security definer set search_path='pg_catalog','public' as $$declare eid uuid:=public.current_schedule_employee_id();loc uuid:=public.current_location_id();begin if auth.uid() is null or eid is null or loc is null then raise exception 'active employee login required';end if;update public.team_announcement_recipients r set read_at=coalesce(r.read_at,now()),acknowledged_at=coalesce(r.acknowledged_at,now()) where r.announcement_id=p_announcement_id and r.employee_id=eid and r.location_id=loc and exists(select 1 from public.team_announcements a where a.id=r.announcement_id and a.location_id=loc and a.requires_acknowledgment);if not found then raise exception 'acknowledgment is not required or announcement is not addressed to you';end if;return true;end$$;

create or replace function public.employee_home_priority_snapshot() returns jsonb language plpgsql stable security definer set search_path='pg_catalog','public' as $$declare loc uuid:=public.current_location_id();eid uuid:=public.current_schedule_employee_id();unread_ann int:=0;required_ack int:=0;urgent_ann int:=0;unread_msg int:=0;training_open int:=0;training_overdue int:=0;pending_requests int:=0;begin if auth.uid() is null or loc is null or eid is null then raise exception 'active employee login required';end if;select count(*)::int,count(*) filter(where a.requires_acknowledgment and r.acknowledged_at is null)::int,count(*) filter(where a.priority='urgent')::int into unread_ann,required_ack,urgent_ann from public.team_announcement_recipients r join public.team_announcements a on a.id=r.announcement_id where r.location_id=loc and r.employee_id=eid and a.archived_at is null and(a.expires_at is null or a.expires_at>now()) and r.read_at is null;select count(*)::int into unread_msg from public.team_channel_members m join public.team_channel_messages x on x.channel_id=m.channel_id and x.location_id=loc and x.deleted_at is null where m.employee_id=eid and m.location_id=loc and x.author_employee_id<>eid and x.created_at>coalesce(m.last_read_at,'epoch'::timestamptz);select count(*) filter(where a.status in('assigned','in_progress'))::int,count(*) filter(where a.status in('assigned','in_progress') and a.due_at is not null and a.due_at<now())::int into training_open,training_overdue from public.training_course_assignments a where a.location_id=loc and a.employee_id=eid;select(select count(*) from public.time_off_requests x where x.location_id=loc and x.employee_id=eid and x.status='pending')+(select count(*) from public.availability_change_requests x where x.location_id=loc and x.employee_id=eid and x.status='pending')+(select count(*) from public.shift_change_requests x where x.location_id=loc and x.requested_by_employee_id=eid and x.status='pending')+(select count(*) from public.shift_claims x where x.location_id=loc and x.employee_id=eid and x.status='pending') into pending_requests;return jsonb_build_object('unread_announcements',unread_ann,'required_acknowledgments',required_ack,'urgent_announcements',urgent_ann,'unread_messages',unread_msg,'training_open',training_open,'training_overdue',training_overdue,'pending_requests',pending_requests,'top_priority',case when required_ack>0 then 'announcement_ack' when urgent_ann>0 then 'urgent_announcement' when training_overdue>0 then 'training_overdue' when unread_msg>0 then 'team_message' when pending_requests>0 then 'pending_request' else 'none' end);end$$;

grant execute on function public.resolve_manager_on_duty_employee_id(),public.staff_manager_on_duty(),public.start_manager_on_duty_channel(),public.my_team_channels(),public.employee_home_priority_snapshot() to authenticated;
grant execute on function public.start_direct_team_channel(uuid),public.team_channel_messages_for_me(uuid,integer),public.mark_team_channel_read(uuid),public.send_team_channel_message(uuid,text),public.acknowledge_team_announcement(uuid) to authenticated;
revoke execute on function public.resolve_manager_on_duty_employee_id(),public.staff_manager_on_duty(),public.start_manager_on_duty_channel(),public.my_team_channels(),public.employee_home_priority_snapshot() from anon,public;
revoke execute on function public.start_direct_team_channel(uuid),public.team_channel_messages_for_me(uuid,integer),public.mark_team_channel_read(uuid),public.send_team_channel_message(uuid,text),public.acknowledge_team_announcement(uuid) from anon,public;
