create or replace function public.employee_shift_pool_snapshot()
returns jsonb language plpgsql stable security definer set search_path='pg_catalog','public' as $$
declare loc uuid:=public.current_location_id();eid uuid:=public.current_schedule_employee_id();offers jsonb;opens jsonb;mine_offers jsonb;mine_bids jsonb;mine_claims jsonb;my_trades jsonb;
begin
 if auth.uid() is null or loc is null or eid is null then raise exception 'active employee login required';end if;
 if not exists(select 1 from public.employees e where e.id=eid and e.location_id=loc and e.active and e.deleted_at is null and coalesce(e.employment_status,'active')='active') then raise exception 'active employee login required';end if;
 select coalesce(jsonb_agg(jsonb_build_object('id',o.id,'shift_id',o.shift_id,'offered_by_employee_id',o.offered_by_employee_id,'offered_by_name',coalesce(owner.full_name,'Team member'),'offer_type',o.offer_type,'offered_starts_at',o.offered_starts_at,'offered_ends_at',o.offered_ends_at,'audience',o.audience,'comment',o.comment,'status',o.status,'role_id',s.role_id,'role_name',coalesce(r.name,'Shift'),'warnings',case when o.offered_by_employee_id=eid then '[]'::jsonb else public.shift_pool_candidate_warnings(o.id,eid) end) order by o.offered_starts_at,o.id),'[]'::jsonb) into offers from public.shift_pool_offers o join public.schedule_shifts s on s.id=o.shift_id and s.location_id=loc left join public.employees owner on owner.id=o.offered_by_employee_id and owner.location_id=loc left join public.employee_roles r on r.id=s.role_id and r.location_id=loc where o.location_id=loc and o.status='open' and public.can_view_shift_pool_offer(o.id);
 select coalesce(jsonb_agg(jsonb_build_object('id',s.id,'role_id',s.role_id,'role_name',coalesce(r.name,'Shift'),'starts_at',s.starts_at,'ends_at',s.ends_at,'status',s.status,'schedule_period_id',s.schedule_period_id,'warnings',public.open_shift_candidate_warnings(s.id,eid)) order by s.starts_at,s.id),'[]'::jsonb) into opens from public.staff_shift_pool_shifts() s left join public.employee_roles r on r.id=s.role_id and r.location_id=loc where s.employee_id is null and s.status='open';
 select coalesce(jsonb_agg(jsonb_build_object('id',o.id,'shift_id',o.shift_id,'offer_type',o.offer_type,'offered_starts_at',o.offered_starts_at,'offered_ends_at',o.offered_ends_at,'comment',o.comment,'status',o.status,'assigned_to_employee_id',o.assigned_to_employee_id,'role_name',coalesce(r.name,'Shift'),'pending_bid_count',(select count(*)::int from public.shift_pool_bids b where b.offer_id=o.id and b.status='pending')) order by o.created_at desc),'[]'::jsonb) into mine_offers from public.shift_pool_offers o join public.schedule_shifts s on s.id=o.shift_id and s.location_id=loc left join public.employee_roles r on r.id=s.role_id and r.location_id=loc where o.location_id=loc and o.offered_by_employee_id=eid;
 select coalesce(jsonb_agg(jsonb_build_object('id',b.id,'offer_id',b.offer_id,'status',b.status,'comment',b.comment,'created_at',b.created_at,'offered_starts_at',o.offered_starts_at,'offered_ends_at',o.offered_ends_at,'role_name',coalesce(r.name,'Shift')) order by b.created_at desc),'[]'::jsonb) into mine_bids from public.shift_pool_bids b join public.shift_pool_offers o on o.id=b.offer_id and o.location_id=loc join public.schedule_shifts s on s.id=o.shift_id and s.location_id=loc left join public.employee_roles r on r.id=s.role_id and r.location_id=loc where b.location_id=loc and b.employee_id=eid;
 select coalesce(jsonb_agg(jsonb_build_object('id',c.id,'shift_id',c.shift_id,'status',c.status,'created_at',c.created_at,'starts_at',s.starts_at,'ends_at',s.ends_at,'role_name',coalesce(r.name,'Shift')) order by c.created_at desc),'[]'::jsonb) into mine_claims from public.shift_claims c join public.schedule_shifts s on s.id=c.shift_id and s.location_id=loc left join public.employee_roles r on r.id=s.role_id and r.location_id=loc where c.location_id=loc and c.employee_id=eid;
 select coalesce(jsonb_agg(jsonb_build_object('id',q.id,'request_type',q.request_type,'status',q.status,'target_response',q.target_response,'target_responded_at',q.target_responded_at,'reason',q.reason,'created_at',q.created_at,'requested_by_employee_id',q.requested_by_employee_id,'requested_by_name',coalesce(req.full_name,'Team member'),'target_employee_id',q.target_employee_id,'target_employee_name',coalesce(trg.full_name,'Team member'),'source_shift_id',q.shift_id,'source_starts_at',src.starts_at,'source_ends_at',src.ends_at,'source_role_name',coalesce(sr.name,'Shift'),'target_shift_id',q.target_shift_id,'target_starts_at',tgt.starts_at,'target_ends_at',tgt.ends_at,'target_role_name',coalesce(tr.name,'Shift')) order by q.created_at desc),'[]'::jsonb) into my_trades from public.shift_change_requests q join public.schedule_shifts src on src.id=q.shift_id and src.location_id=loc left join public.schedule_shifts tgt on tgt.id=q.target_shift_id and tgt.location_id=loc left join public.employees req on req.id=q.requested_by_employee_id and req.location_id=loc left join public.employees trg on trg.id=q.target_employee_id and trg.location_id=loc left join public.employee_roles sr on sr.id=src.role_id and sr.location_id=loc left join public.employee_roles tr on tr.id=tgt.role_id and tr.location_id=loc where q.location_id=loc and q.request_type='swap' and(q.requested_by_employee_id=eid or q.target_employee_id=eid);
 return jsonb_build_object('employee_id',eid,'visible_offers',offers,'open_shifts',opens,'my_offers',mine_offers,'my_bids',mine_bids,'my_claims',mine_claims,'my_trades',my_trades,'up_for_grabs_count',jsonb_array_length(offers)+jsonb_array_length(opens));
end$$;
