create or replace function public.employee_home_priority_snapshot()
returns jsonb
language plpgsql
stable security definer
set search_path='pg_catalog','public'
as $$
declare loc uuid:=public.current_location_id();eid uuid:=public.current_schedule_employee_id();unread_ann int:=0;required_ack int:=0;urgent_ann int:=0;unread_msg int:=0;training_open int:=0;training_overdue int:=0;pending_requests int:=0;
begin
 if auth.uid() is null or loc is null or eid is null then raise exception 'active employee login required';end if;
 select count(*) filter(where r.read_at is null)::int,count(*) filter(where a.requires_acknowledgment and r.acknowledged_at is null)::int,count(*) filter(where a.priority='urgent' and r.read_at is null)::int into unread_ann,required_ack,urgent_ann from public.team_announcement_recipients r join public.team_announcements a on a.id=r.announcement_id where r.location_id=loc and r.employee_id=eid and a.archived_at is null and(a.expires_at is null or a.expires_at>now());
 select count(*)::int into unread_msg from public.team_channel_members m join public.team_channel_messages x on x.channel_id=m.channel_id and x.location_id=loc and x.deleted_at is null where m.employee_id=eid and m.location_id=loc and x.author_employee_id<>eid and x.created_at>coalesce(m.last_read_at,'epoch'::timestamptz);
 select count(*) filter(where a.status in('assigned','in_progress'))::int,count(*) filter(where a.status in('assigned','in_progress') and a.due_at is not null and a.due_at<now())::int into training_open,training_overdue from public.training_course_assignments a where a.location_id=loc and a.employee_id=eid;
 select(select count(*) from public.time_off_requests x where x.location_id=loc and x.employee_id=eid and x.status='pending')+(select count(*) from public.availability_change_requests x where x.location_id=loc and x.employee_id=eid and x.status='pending')+(select count(*) from public.shift_change_requests x where x.location_id=loc and x.requested_by_employee_id=eid and x.status='pending')+(select count(*) from public.shift_claims x where x.location_id=loc and x.employee_id=eid and x.status='pending') into pending_requests;
 return jsonb_build_object('unread_announcements',unread_ann,'required_acknowledgments',required_ack,'urgent_announcements',urgent_ann,'unread_messages',unread_msg,'training_open',training_open,'training_overdue',training_overdue,'pending_requests',pending_requests,'top_priority',case when required_ack>0 then 'announcement_ack' when urgent_ann>0 then 'urgent_announcement' when training_overdue>0 then 'training_overdue' when unread_msg>0 then 'team_message' when pending_requests>0 then 'pending_request' else 'none' end);
end$$;
grant execute on function public.employee_home_priority_snapshot() to authenticated;revoke execute on function public.employee_home_priority_snapshot() from anon,public;

create or replace function public.employee_shift_pool_snapshot()
returns jsonb
language plpgsql
stable security definer
set search_path='pg_catalog','public'
as $$
declare loc uuid:=public.current_location_id();eid uuid:=public.current_schedule_employee_id();offers jsonb;opens jsonb;mine_offers jsonb;mine_bids jsonb;mine_claims jsonb;my_trades jsonb;
begin
 if auth.uid() is null or loc is null or eid is null then raise exception 'active employee login required';end if;if not exists(select 1 from public.employees e where e.id=eid and e.location_id=loc and e.active and e.deleted_at is null and coalesce(e.employment_status,'active')='active') then raise exception 'active employee login required';end if;
 select coalesce(jsonb_agg(jsonb_build_object('id',o.id,'shift_id',o.shift_id,'offered_by_employee_id',o.offered_by_employee_id,'offered_by_name',coalesce(owner.full_name,'Team member'),'offer_type',o.offer_type,'offered_starts_at',o.offered_starts_at,'offered_ends_at',o.offered_ends_at,'audience',o.audience,'comment',o.comment,'status',o.status,'role_id',s.role_id,'role_name',coalesce(r.name,'Shift'),'warnings',case when o.offered_by_employee_id=eid then '[]'::jsonb else public.shift_pool_candidate_warnings(o.id,eid) end) order by o.offered_starts_at,o.id),'[]'::jsonb) into offers from public.shift_pool_offers o join public.schedule_shifts s on s.id=o.shift_id and s.location_id=loc left join public.employees owner on owner.id=o.offered_by_employee_id and owner.location_id=loc left join public.employee_roles r on r.id=s.role_id and r.location_id=loc where o.location_id=loc and o.status='open' and public.can_view_shift_pool_offer(o.id);
 select coalesce(jsonb_agg(jsonb_build_object('id',s.id,'role_id',s.role_id,'role_name',coalesce(r.name,'Shift'),'starts_at',s.starts_at,'ends_at',s.ends_at,'status',s.status,'schedule_period_id',s.schedule_period_id,'warnings',public.open_shift_candidate_warnings(s.id,eid)) order by s.starts_at,s.id),'[]'::jsonb) into opens from public.staff_shift_pool_shifts() s left join public.employee_roles r on r.id=s.role_id and r.location_id=loc where s.employee_id is null and s.status='open';
 select coalesce(jsonb_agg(jsonb_build_object('id',o.id,'shift_id',o.shift_id,'offer_type',o.offer_type,'offered_starts_at',o.offered_starts_at,'offered_ends_at',o.offered_ends_at,'comment',o.comment,'status',o.status,'assigned_to_employee_id',o.assigned_to_employee_id,'role_name',coalesce(r.name,'Shift'),'pending_bid_count',(select count(*)::int from public.shift_pool_bids b where b.offer_id=o.id and b.status='pending')) order by o.created_at desc),'[]'::jsonb) into mine_offers from public.shift_pool_offers o join public.schedule_shifts s on s.id=o.shift_id and s.location_id=loc left join public.employee_roles r on r.id=s.role_id and r.location_id=loc where o.location_id=loc and o.offered_by_employee_id=eid;
 select coalesce(jsonb_agg(jsonb_build_object('id',b.id,'offer_id',b.offer_id,'status',b.status,'comment',b.comment,'created_at',b.created_at,'offered_starts_at',o.offered_starts_at,'offered_ends_at',o.offered_ends_at,'role_name',coalesce(r.name,'Shift')) order by b.created_at desc),'[]'::jsonb) into mine_bids from public.shift_pool_bids b join public.shift_pool_offers o on o.id=b.offer_id and o.location_id=loc join public.schedule_shifts s on s.id=o.shift_id and s.location_id=loc left join public.employee_roles r on r.id=s.role_id and r.location_id=loc where b.location_id=loc and b.employee_id=eid;
 select coalesce(jsonb_agg(jsonb_build_object('id',c.id,'shift_id',c.shift_id,'status',c.status,'created_at',c.created_at,'starts_at',s.starts_at,'ends_at',s.ends_at,'role_name',coalesce(r.name,'Shift')) order by c.created_at desc),'[]'::jsonb) into mine_claims from public.shift_claims c join public.schedule_shifts s on s.id=c.shift_id and s.location_id=loc left join public.employee_roles r on r.id=s.role_id and r.location_id=loc where c.location_id=loc and c.employee_id=eid;
 select coalesce(jsonb_agg(jsonb_build_object('id',q.id,'request_type',q.request_type,'status',q.status,'reason',q.reason,'created_at',q.created_at,'requested_by_employee_id',q.requested_by_employee_id,'requested_by_name',coalesce(req.full_name,'Team member'),'target_employee_id',q.target_employee_id,'target_employee_name',coalesce(trg.full_name,'Team member'),'source_shift_id',q.shift_id,'source_starts_at',src.starts_at,'source_ends_at',src.ends_at,'source_role_name',coalesce(sr.name,'Shift'),'target_shift_id',q.target_shift_id,'target_starts_at',tgt.starts_at,'target_ends_at',tgt.ends_at,'target_role_name',coalesce(tr.name,'Shift')) order by q.created_at desc),'[]'::jsonb) into my_trades from public.shift_change_requests q join public.schedule_shifts src on src.id=q.shift_id and src.location_id=loc left join public.schedule_shifts tgt on tgt.id=q.target_shift_id and tgt.location_id=loc left join public.employees req on req.id=q.requested_by_employee_id and req.location_id=loc left join public.employees trg on trg.id=q.target_employee_id and trg.location_id=loc left join public.employee_roles sr on sr.id=src.role_id and sr.location_id=loc left join public.employee_roles tr on tr.id=tgt.role_id and tr.location_id=loc where q.location_id=loc and q.request_type='swap' and(q.requested_by_employee_id=eid or q.target_employee_id=eid);
 return jsonb_build_object('employee_id',eid,'visible_offers',offers,'open_shifts',opens,'my_offers',mine_offers,'my_bids',mine_bids,'my_claims',mine_claims,'my_trades',my_trades,'up_for_grabs_count',jsonb_array_length(offers)+jsonb_array_length(opens));
end$$;
grant execute on function public.employee_shift_pool_snapshot() to authenticated;revoke execute on function public.employee_shift_pool_snapshot() from anon,public;

create or replace function public.normalize_notification_event()
returns trigger language plpgsql set search_path='pg_catalog','public' as $$
declare target_role public.app_role;
begin new.type:=left(coalesce(nullif(trim(new.type),''),'info'),80);new.category:=left(coalesce(nullif(trim(new.category),''),case when new.type='schedule' then 'schedule' when new.type='staffing' then 'requests' when new.type='employee_setup' then 'account' when new.type='training' then 'training' when new.type in('team','announcement') then 'team' when new.type='time_clock' then 'time_clock' when new.type='tips' then 'tips' else 'general' end),80);new.event_key:=left(coalesce(nullif(trim(new.event_key),''),nullif(new.data->>'event_key',''),new.type,'info'),120);new.priority:=coalesce(nullif(trim(new.priority),''),'normal');if new.priority not in('low','normal','high','critical') then new.priority:='normal';end if;select p.app_role into target_role from public.profiles p where p.id=new.user_id;if target_role='employee' and new.href is not null then if new.href='/schedule' then new.href:='/employee/schedule';elsif new.href like '/schedule?%' then new.href:='/employee/schedule'||substring(new.href from 10);elsif new.href='/schedule/requests' then new.href:='/employee/requests';elsif new.href like '/schedule/requests?%' then new.href:='/employee/requests'||substring(new.href from 19);elsif new.href='/schedule/pool' then new.href:='/employee/shift-pool';elsif new.href like '/schedule/pool?%' then new.href:='/employee/shift-pool'||substring(new.href from 15);elsif new.href='/team' then new.href:='/employee/team';elsif new.href like '/team?%' then new.href:='/employee/team'||substring(new.href from 6);elsif new.href='/training/courses' then new.href:='/employee/training';elsif new.href like '/training/courses?%' then new.href:='/employee/training'||substring(new.href from 18);elsif new.href='/time-clock' then new.href:='/employee/time-clock';elsif new.href like '/time-clock?%' then new.href:='/employee/time-clock'||substring(new.href from 12);elsif new.href='/tips' then new.href:='/employee/tips';elsif new.href like '/tips?%' then new.href:='/employee/tips'||substring(new.href from 6);end if;end if;return new;end$$;
