-- Pilot authoritative event ledger v1
-- Records consequential mutations at the database boundary without free-form notes or financial data.
create table if not exists public.pilot_operation_events(id bigint generated always as identity primary key,occurred_at timestamptz not null default now(),location_id uuid not null,actor_user_id uuid,operation text not null,entity_type text not null,entity_id text,outcome text not null,reason_code text,source text not null default 'database',constraint pilot_operation_events_outcome_check check(outcome in('success','policy_rejection','failure')),constraint pilot_operation_events_source_check check(source in('database','server')),constraint pilot_operation_events_operation_check check(operation ~ '^[a-z0-9_]{3,80}$'),constraint pilot_operation_events_entity_type_check check(entity_type ~ '^[a-z0-9_]{2,80}$'));
create index if not exists pilot_operation_events_location_time_idx on public.pilot_operation_events(location_id,occurred_at desc);
create index if not exists pilot_operation_events_operation_outcome_idx on public.pilot_operation_events(operation,outcome,occurred_at desc);
alter table public.pilot_operation_events enable row level security;
revoke all on public.pilot_operation_events from anon,authenticated;
create or replace function public.record_pilot_operation_event(p_operation text,p_entity_type text,p_entity_id text,p_outcome text,p_reason_code text default null) returns bigint language plpgsql security definer set search_path='pg_catalog','public','auth' as $$declare loc uuid:=public.current_location_id();event_id bigint;begin if auth.uid() is null or loc is null then raise exception 'authenticated location required';end if;if p_operation is null or p_operation !~ '^[a-z0-9_]{3,80}$' or p_entity_type is null or p_entity_type !~ '^[a-z0-9_]{2,80}$' or p_outcome not in('success','policy_rejection','failure') then raise exception 'invalid pilot event';end if;insert into public.pilot_operation_events(location_id,actor_user_id,operation,entity_type,entity_id,outcome,reason_code) values(loc,auth.uid(),p_operation,p_entity_type,left(p_entity_id,120),p_outcome,left(p_reason_code,80)) returning id into event_id;return event_id;end$$;
revoke all on function public.record_pilot_operation_event(text,text,text,text,text) from public,anon;grant execute on function public.record_pilot_operation_event(text,text,text,text,text) to authenticated;
create or replace function public.capture_pilot_critical_mutation() returns trigger language plpgsql security definer set search_path='pg_catalog','public','auth' as $$declare op text;eid text;loc uuid;begin loc:=coalesce((to_jsonb(new)->>'location_id')::uuid,(to_jsonb(old)->>'location_id')::uuid,public.current_location_id());eid:=coalesce(to_jsonb(new)->>'id',to_jsonb(old)->>'id');op:=tg_table_name||'_'||lower(tg_op);insert into public.pilot_operation_events(location_id,actor_user_id,operation,entity_type,entity_id,outcome) values(loc,auth.uid(),op,tg_table_name,eid,'success');return coalesce(new,old);end$$;
revoke all on function public.capture_pilot_critical_mutation() from public,anon,authenticated;
do $$declare t text;begin foreach t in array array['availability_change_requests','time_off_requests','shift_change_requests','shift_claims','schedule_shifts','schedule_department_publications','time_clock_punches','time_clock_breaks','time_clock_pay_periods','tip_pool_runs','tip_distributions'] loop if to_regclass('public.'||t) is not null then execute format('drop trigger if exists pilot_capture_mutation on public.%I',t);execute format('create trigger pilot_capture_mutation after insert or update or delete on public.%I for each row execute function public.capture_pilot_critical_mutation()',t);end if;end loop;end$$;
create or replace function public.pilot_scorecard_snapshot(p_since timestamptz default now()-interval '7 days') returns jsonb language plpgsql stable security definer set search_path='pg_catalog','public','auth' as $$declare loc uuid:=public.current_location_id();result jsonb;begin if auth.uid() is null or loc is null or public.current_app_role() not in('admin','manager') then raise exception 'manager access required';end if;select jsonb_build_object('since',p_since,'critical_mutations',count(*) filter(where outcome in('success','failure')),'successful_critical_mutations',count(*) filter(where outcome='success'),'failed_critical_mutations',count(*) filter(where outcome='failure'),'policy_rejections',count(*) filter(where outcome='policy_rejection'),'critical_mutation_success_rate',case when count(*) filter(where outcome in('success','failure'))=0 then null else round(100.0*count(*) filter(where outcome='success')/count(*) filter(where outcome in('success','failure')),2) end) into result from public.pilot_operation_events where location_id=loc and occurred_at>=p_since;return result;end$$;
revoke all on function public.pilot_scorecard_snapshot(timestamptz) from public,anon;grant execute on function public.pilot_scorecard_snapshot(timestamptz) to authenticated;
