'use client';

import {FormEvent,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase';
import styles from '../ops-tools.module.css';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Settings={enabled:boolean;mobile_punch_enabled:boolean;kiosk_punch_enabled:boolean;require_scheduled_shift:boolean;employee_approval_enabled:boolean;geofence_enabled:boolean;geofence_latitude:number|null;geofence_longitude:number|null;geofence_radius_meters:number;early_clock_in_minutes:number;late_clock_out_minutes:number;auto_punch_out_hours:number;pay_period_frequency:'weekly'|'biweekly';pay_period_anchor:string;workweek_starts_on:number};
type Punch={id:string;employee_id:string;clock_in:string;clock_out:string|null;source:string;note:string|null;manager_approved_at:string|null;employee_approval_status:'pending'|'approved'|'disputed';employee_dispute_note:string|null};
type BreakRow={id:string;punch_id:string;started_at:string;ended_at:string|null;paid:boolean;deleted_at:string|null};
type Period={id:string;starts_on:string;ends_on:string;status:'open'|'closed';closed_at:string|null};
type Employee={id:string;full_name:string};
type Working={punch_id:string;employee_id:string;employee_name:string;clock_in:string;source:string;on_break:boolean;break_started_at:string|null};
type WageRow={employee_id:string;full_name:string;worked_hours:number;hourly_rate:number;base_wages:number;overtime_hours:number;overtime_premium:number;estimated_wages:number;punches:number};
type WageReport={pay_period:{id:string;starts_on:string;ends_on:string;status:string};rows:WageRow[];summary:{employees:number;worked_hours:number;base_wages:number;overtime_hours:number;overtime_premium:number;estimated_wages:number}};
const DEFAULT:Settings={enabled:true,mobile_punch_enabled:true,kiosk_punch_enabled:true,require_scheduled_shift:false,employee_approval_enabled:true,geofence_enabled:false,geofence_latitude:null,geofence_longitude:null,geofence_radius_meters:250,early_clock_in_minutes:30,late_clock_out_minutes:120,auto_punch_out_hours:16,pay_period_frequency:'biweekly',pay_period_anchor:'2026-01-05',workweek_starts_on:1};
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(n)||0);
const localInput=(d:Date)=>{const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,16)};

export default function TimeClockPage(){
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[profile,setProfile]=useState<Profile|null>(null),[settings,setSettings]=useState<Settings>(DEFAULT),[employeeId,setEmployeeId]=useState<string|null>(null),[punches,setPunches]=useState<Punch[]>([]),[breaks,setBreaks]=useState<BreakRow[]>([]),[periods,setPeriods]=useState<Period[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[working,setWorking]=useState<Working[]>([]),[wages,setWages]=useState<WageReport|null>(null),[periodId,setPeriodId]=useState(''),[pin,setPin]=useState(''),[manual,setManual]=useState({employee_id:'',clock_in:'',clock_out:'',note:'',reason:''});
 const manager=profile?.app_role==='admin'||profile?.app_role==='manager';
 const myOpen=useMemo(()=>punches.find(p=>p.employee_id===employeeId&&!p.clock_out)||null,[punches,employeeId]);
 const myBreak=useMemo(()=>myOpen?breaks.find(b=>b.punch_id===myOpen.id&&!b.ended_at&&!b.deleted_at)||null:null,[breaks,myOpen]);
 useEffect(()=>{void load()},[]);
 async function load(){
  setBusy(true);setMessage('');
  const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}
  const p=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();if(p.error||!p.data?.location_id){setMessage('Could not load time clock access.');setBusy(false);setReady(true);return}
  const pr=p.data as Profile;setProfile(pr);
  const [s,id,pu,br,pp,wk,emps]=await Promise.all([
    supabase.from('time_clock_settings').select('enabled,mobile_punch_enabled,kiosk_punch_enabled,require_scheduled_shift,employee_approval_enabled,geofence_enabled,geofence_latitude,geofence_longitude,geofence_radius_meters,early_clock_in_minutes,late_clock_out_minutes,auto_punch_out_hours,pay_period_frequency,pay_period_anchor,workweek_starts_on').eq('location_id',pr.location_id).maybeSingle(),
    supabase.rpc('time_clock_employee_id_for_user',{}),
    supabase.from('time_clock_punches').select('id,employee_id,clock_in,clock_out,source,note,manager_approved_at,employee_approval_status,employee_dispute_note').eq('location_id',pr.location_id).order('clock_in',{ascending:false}).limit(200),
    supabase.from('time_clock_breaks').select('id,punch_id,started_at,ended_at,paid,deleted_at').eq('location_id',pr.location_id).order('started_at',{ascending:false}).limit(500),
    supabase.from('time_clock_pay_periods').select('id,starts_on,ends_on,status,closed_at').eq('location_id',pr.location_id).order('starts_on',{ascending:false}).limit(30),
    supabase.rpc('time_clock_whos_working',{}),
    ['admin','manager'].includes(pr.app_role)?supabase.from('employees').select('id,full_name').eq('location_id',pr.location_id).eq('active',true).is('deleted_at',null).order('full_name'):Promise.resolve({data:[],error:null}) as any
  ]);
  if([s,id,pu,br,pp,wk,emps].some((x:any)=>x.error))setMessage('Some time clock data could not be loaded.');
  setSettings({...DEFAULT,...(s.data||{})} as Settings);setEmployeeId((id.data as string|null)||null);setPunches((pu.data??[]) as Punch[]);setBreaks((br.data??[]) as BreakRow[]);setPeriods((pp.data??[]) as Period[]);setWorking(((wk.data??[]) as Working[]));setEmployees((emps.data??[]) as Employee[]);
  const selected=periodId||(pp.data?.[0]?.id||'');if(selected)setPeriodId(selected);
  if(['admin','manager'].includes(pr.app_role)&&selected){const wr=await supabase.rpc('time_clock_worked_hours_wages',{p_pay_period_id:selected,p_approved_only:true});if(!wr.error)setWages(wr.data as WageReport)}
  setBusy(false);setReady(true);
 }
 async function coords(){if(!settings.geofence_enabled)return {lat:null,lng:null};if(!navigator.geolocation)throw new Error('Location access is required for punching.');return new Promise<{lat:number;lng:number}>((resolve,reject)=>navigator.geolocation.getCurrentPosition(p=>resolve({lat:p.coords.latitude,lng:p.coords.longitude}),()=>reject(new Error('Allow location access to use the time clock.')),{enableHighAccuracy:true,timeout:10000,maximumAge:30000}))}
 async function act(kind:'in'|'out'){if(busy||!settings.enabled)return;setBusy(true);try{const c=await coords();const name=kind==='in'?'clock_in':'clock_out';const {error}=await supabase.rpc(name,{p_source:'web',p_latitude:c.lat,p_longitude:c.lng});if(error)throw error;setMessage(kind==='in'?'Clocked in.':'Clocked out.');await load()}catch(e:any){setMessage(e?.message||'Could not update the time clock.')}finally{setBusy(false)}}
 async function breakAct(kind:'start'|'end'){if(busy)return;setBusy(true);const r=kind==='start'?await supabase.rpc('start_time_clock_break',{p_paid:false,p_source:'web'}):await supabase.rpc('end_time_clock_break',{p_source:'web'});setMessage(r.error?r.error.message:kind==='start'?'Break started.':'Break ended.');await load();setBusy(false)}
 async function attest(p:Punch,approved:boolean){if(busy)return;let note:string|null=null;if(!approved){note=prompt('What needs to be corrected?')?.trim()||null;if(!note)return}setBusy(true);const {error}=await supabase.rpc('employee_attest_time_clock_punch',{p_punch_id:p.id,p_approved:approved,p_dispute_note:note});setMessage(error?error.message:approved?'Punch approved.':'Correction requested.');await load();setBusy(false)}
 async function setMyPin(e:FormEvent){e.preventDefault();if(busy||!/^\d{4,8}$/.test(pin))return setMessage('PIN must be 4 to 8 digits.');setBusy(true);const {error}=await supabase.rpc('set_time_clock_pin',{p_pin:pin});setPin('');setMessage(error?error.message:'Kiosk PIN saved.');setBusy(false)}
 async function saveSettings(){if(!manager||!profile?.location_id||busy)return;if(settings.geofence_enabled&&(settings.geofence_latitude===null||settings.geofence_longitude===null))return setMessage('Set geofence latitude and longitude before enabling geofencing.');setBusy(true);const {error}=await supabase.from('time_clock_settings').upsert({location_id:profile.location_id,...settings},{onConflict:'location_id'});setMessage(error?error.message:'Time clock settings saved.');setBusy(false)}
 async function approve(p:Punch){if(!manager||busy)return;setBusy(true);const {error}=await supabase.rpc('manager_approve_time_clock_punch',{p_punch_id:p.id});setMessage(error?error.message:'Punch approved by manager.');await load();setBusy(false)}
 async function editPunch(p:Punch){if(!manager||busy)return;const start=prompt('Clock in (ISO timestamp)',p.clock_in);if(!start)return;const end=prompt('Clock out (ISO timestamp)',p.clock_out||'');if(!end)return;const reason=prompt('Reason for correction');if(!reason?.trim())return setMessage('A correction reason is required.');setBusy(true);const {error}=await supabase.rpc('manager_upsert_time_clock_punch',{p_punch_id:p.id,p_employee_id:p.employee_id,p_clock_in:start,p_clock_out:end,p_note:p.note,p_reason:reason.trim()});setMessage(error?error.message:'Punch corrected; approvals were reset.');await load();setBusy(false)}
 async function addManual(e:FormEvent){e.preventDefault();if(!manager||busy||!manual.employee_id||!manual.clock_in||!manual.clock_out||!manual.reason.trim())return;setBusy(true);const {error}=await supabase.rpc('manager_upsert_time_clock_punch',{p_punch_id:null,p_employee_id:manual.employee_id,p_clock_in:new Date(manual.clock_in).toISOString(),p_clock_out:new Date(manual.clock_out).toISOString(),p_note:manual.note.trim()||null,p_reason:manual.reason.trim()});if(!error)setManual({employee_id:'',clock_in:'',clock_out:'',note:'',reason:''});setMessage(error?error.message:'Missed punch added.');await load();setBusy(false)}
 async function periodAction(p:Period,action:'approve'|'close'|'reopen'){if(!manager||busy)return;setBusy(true);const rpc=action==='approve'?'manager_approve_all_time_clock_punches':action==='close'?'close_time_clock_pay_period':'reopen_time_clock_pay_period';const arg=action==='approve'?{p_pay_period_id:p.id}:{p_pay_period_id:p.id};const {error}=await supabase.rpc(rpc,arg);setMessage(error?error.message:action==='approve'?'All closed punches approved.':action==='close'?'Pay period closed.':'Pay period reopened.');await load();setBusy(false)}
 async function selectPeriod(id:string){setPeriodId(id);if(!manager||!id)return;const {data,error}=await supabase.rpc('time_clock_worked_hours_wages',{p_pay_period_id:id,p_approved_only:true});if(error)setMessage(error.message);else setWages(data as WageReport)}
 if(!ready)return <main className={styles.page}>Loading time clock…</main>;
 if(!profile?.location_id)return <main className={styles.page}>No restaurant location is assigned.</main>;
 return <main className={styles.page}>
  <div className={styles.top}><div><h1>Time Clock</h1><p>Punches, breaks, approvals, pay periods and wage-ready hours.</p></div><Link className={styles.back} href="/tools">Back to Tools</Link></div>
  {message&&<div className={message.toLowerCase().includes('could not')||message.toLowerCase().includes('required')?styles.error:styles.notice}>{message}</div>}
  <div className={styles.grid}><Metric label="Working now" value={String(working.length)}/><Metric label="Open punch" value={myOpen?'Yes':'No'}/><Metric label="Active break" value={myBreak?'Yes':'No'}/><Metric label="Latest period" value={periods[0]?.status||'—'}/></div>
  <section className={styles.section}><div className={styles.card}><h2>My clock</h2>{!employeeId?<div className={styles.empty}>Your account is not linked to an active employee record.</div>:<><div className={styles.actions}>{!myOpen?<button className={styles.button} disabled={busy||!settings.enabled} onClick={()=>act('in')}>Clock in</button>:<button className={styles.button} disabled={busy||Boolean(myBreak)} onClick={()=>act('out')}>Clock out</button>}{myOpen&&!myBreak&&<button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>breakAct('start')}>Start break</button>}{myBreak&&<button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>breakAct('end')}>End break</button>}</div><form onSubmit={setMyPin} className={styles.actions}><input aria-label="Kiosk PIN" inputMode="numeric" pattern="\d{4,8}" maxLength={8} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,''))} placeholder="4–8 digit kiosk PIN"/><button className={`${styles.button} ${styles.secondary}`} disabled={busy||!/^\d{4,8}$/.test(pin)}>Save PIN</button></form></>}</div></section>
  <section className={styles.section}><h2>My recent punches</h2><div className={styles.list}>{punches.filter(p=>p.employee_id===employeeId).slice(0,20).map(p=><div className={styles.entry} key={p.id}><div className={styles.entryHead}><div><h3>{new Date(p.clock_in).toLocaleString()}</h3><small>{p.clock_out?`Out ${new Date(p.clock_out).toLocaleString()}`:'Currently clocked in'} · {p.source}</small></div><span className={styles.pill}>{p.employee_approval_status}</span></div>{p.clock_out&&settings.employee_approval_enabled&&p.employee_approval_status!=='approved'&&<div className={styles.actions}><button className={styles.button} disabled={busy} onClick={()=>attest(p,true)}>Approve</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>attest(p,false)}>Dispute</button></div>}</div>)}{!punches.some(p=>p.employee_id===employeeId)&&<div className={styles.empty}>No punches yet.</div>}</div></section>
  {manager&&<>
   <section className={styles.section}><h2>Who’s working</h2><div className={styles.list}>{working.map(w=><div className={styles.entry} key={w.punch_id}><div className={styles.entryHead}><div><h3>{w.employee_name}</h3><small>Since {new Date(w.clock_in).toLocaleTimeString()} · {w.source}</small></div><span className={styles.pill}>{w.on_break?'on break':'working'}</span></div></div>)}{!working.length&&<div className={styles.empty}>Nobody is clocked in.</div>}</div></section>
   <section className={styles.section}><div className={styles.card}><h2>Add a missed punch</h2><form onSubmit={addManual}><div className={styles.formGrid}><label className={styles.field}><span>Employee</span><select value={manual.employee_id} onChange={e=>setManual({...manual,employee_id:e.target.value})}><option value="">Choose employee</option>{employees.map(e=><option key={e.id} value={e.id}>{e.full_name}</option>)}</select></label><label className={styles.field}><span>Clock in</span><input type="datetime-local" value={manual.clock_in} onChange={e=>setManual({...manual,clock_in:e.target.value})}/></label><label className={styles.field}><span>Clock out</span><input type="datetime-local" min={manual.clock_in||undefined} value={manual.clock_out} onChange={e=>setManual({...manual,clock_out:e.target.value})}/></label><label className={styles.field}><span>Reason</span><input maxLength={2000} value={manual.reason} onChange={e=>setManual({...manual,reason:e.target.value})}/></label><label className={`${styles.field} ${styles.wide}`}><span>Note</span><input maxLength={2000} value={manual.note} onChange={e=>setManual({...manual,note:e.target.value})}/></label></div><div className={styles.actions}><button className={styles.button} disabled={busy}>Add missed punch</button></div></form></div></section>
   <section className={styles.section}><h2>Manager punch review</h2><div className={styles.list}>{punches.slice(0,50).map(p=><div className={styles.entry} key={p.id}><div className={styles.entryHead}><div><h3>{employees.find(e=>e.id===p.employee_id)?.full_name||'Employee'}</h3><small>{new Date(p.clock_in).toLocaleString()} → {p.clock_out?new Date(p.clock_out).toLocaleString():'OPEN'}</small></div><span className={styles.pill}>{p.manager_approved_at?'manager approved':'needs review'}</span></div><div className={styles.actions}>{p.clock_out&&!p.manager_approved_at&&<button className={styles.button} disabled={busy} onClick={()=>approve(p)}>Approve</button>}<button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>editPunch(p)}>Correct</button></div></div>)}</div></section>
   <section className={styles.section}><div className={styles.card}><h2>Pay periods & wages</h2><label className={styles.field}><span>Pay period</span><select value={periodId} onChange={e=>selectPeriod(e.target.value)}><option value="">Choose period</option>{periods.map(p=><option key={p.id} value={p.id}>{p.starts_on} – {p.ends_on} · {p.status}</option>)}</select></label>{periods.find(p=>p.id===periodId)&&<div className={styles.actions}>{periods.find(p=>p.id===periodId)?.status==='open'?<><button className={styles.button} disabled={busy} onClick={()=>periodAction(periods.find(p=>p.id===periodId)!,'approve')}>Approve all closed punches</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>periodAction(periods.find(p=>p.id===periodId)!,'close')}>Close pay period</button></>:<button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>periodAction(periods.find(p=>p.id===periodId)!,'reopen')}>Reopen pay period</button>}</div>}{wages&&<><div className={styles.grid} style={{marginTop:12}}><Metric label="Approved hours" value={String(wages.summary.worked_hours)}/><Metric label="OT hours" value={String(wages.summary.overtime_hours)}/><Metric label="Base wages" value={money(wages.summary.base_wages)}/><Metric label="Estimated wages" value={money(wages.summary.estimated_wages)}/></div><div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>Employee</th><th>Hours</th><th>Rate</th><th>OT</th><th>Estimated wages</th></tr></thead><tbody>{wages.rows.map(r=><tr key={r.employee_id}><td>{r.full_name}</td><td>{r.worked_hours}</td><td>{money(r.hourly_rate)}</td><td>{r.overtime_hours}</td><td>{money(r.estimated_wages)}</td></tr>)}</tbody></table></div></>}</div></section>
   <section className={styles.section}><div className={styles.card}><h2>Time clock settings</h2><div className={styles.formGrid}><Bool label="Enable time clock" value={settings.enabled} onChange={v=>setSettings({...settings,enabled:v})}/><Bool label="Enable mobile/web punch" value={settings.mobile_punch_enabled} onChange={v=>setSettings({...settings,mobile_punch_enabled:v})}/><Bool label="Enable kiosk" value={settings.kiosk_punch_enabled} onChange={v=>setSettings({...settings,kiosk_punch_enabled:v})}/><Bool label="Require matching scheduled shift" value={settings.require_scheduled_shift} onChange={v=>setSettings({...settings,require_scheduled_shift:v})}/><Bool label="Employee punch approval" value={settings.employee_approval_enabled} onChange={v=>setSettings({...settings,employee_approval_enabled:v})}/><Bool label="Use geofence" value={settings.geofence_enabled} onChange={v=>setSettings({...settings,geofence_enabled:v})}/><Num label="Geofence latitude" value={settings.geofence_latitude} onChange={v=>setSettings({...settings,geofence_latitude:v})}/><Num label="Geofence longitude" value={settings.geofence_longitude} onChange={v=>setSettings({...settings,geofence_longitude:v})}/><Num label="Radius meters" value={settings.geofence_radius_meters} onChange={v=>setSettings({...settings,geofence_radius_meters:Number(v)||250})}/><label className={styles.field}><span>Pay period</span><select value={settings.pay_period_frequency} onChange={e=>setSettings({...settings,pay_period_frequency:e.target.value as 'weekly'|'biweekly'})}><option value="weekly">Weekly</option><option value="biweekly">Biweekly</option></select></label></div><div className={styles.actions}><button className={styles.button} disabled={busy} onClick={saveSettings}>Save settings</button></div></div></section>
  </>}
 </main>
}
function Metric({label,value}:{label:string;value:string}){return <div className={styles.metric}><span>{label}</span><strong>{value}</strong></div>}
function Bool({label,value,onChange}:{label:string;value:boolean;onChange:(v:boolean)=>void}){return <label className={styles.checkbox}><input type="checkbox" checked={value} onChange={e=>onChange(e.target.checked)}/>{label}</label>}
function Num({label,value,onChange}:{label:string;value:number|null;onChange:(v:number|null)=>void}){return <label className={styles.field}><span>{label}</span><input type="number" step="0.000001" value={value??''} onChange={e=>onChange(e.target.value===''?null:Number(e.target.value))}/></label>}
