'use client';

import {FormEvent,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase';
import styles from '../../ops-tools.module.css';
import {businessDateInZone} from '@/lib/intermediate-hardening';
import {addDateDays,dateDayOfWeek} from '@/lib/scheduling-engine';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Period={id:string;starts_on:string;ends_on:string;status:string;revision:number};
type Template={id:string;name:string;description:string|null;active:boolean;created_at:string;updated_at:string};
type Shift={id:string;employee_id:string|null;role_id:string|null;starts_at:string;ends_at:string;status:string;notes:string|null};
type Employee={id:string;full_name:string};type Role={id:string;name:string};
const mondayOf=(d:string)=>addDateDays(d,-((dateDayOfWeek(d)+6)%7));
export default function ScheduleTemplatesPage(){
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[profile,setProfile]=useState<Profile|null>(null),[weekStart,setWeekStart]=useState(()=>mondayOf(businessDateInZone())),[period,setPeriod]=useState<Period|null>(null),[periods,setPeriods]=useState<Period[]>([]),[templates,setTemplates]=useState<Template[]>([]),[shifts,setShifts]=useState<Shift[]>([]),[employees,setEmployees]=useState<Employee[]>([]),[roles,setRoles]=useState<Role[]>([]),[sourcePeriod,setSourcePeriod]=useState(''),[copyAssignments,setCopyAssignments]=useState(true),[templateForm,setTemplateForm]=useState({name:'',description:'',include_assignments:true}),[selectedTemplate,setSelectedTemplate]=useState(''),[applyMode,setApplyMode]=useState<'merge'|'replace'>('merge'),[applyAssignments,setApplyAssignments]=useState(true),[repeatShift,setRepeatShift]=useState(''),[repeatDates,setRepeatDates]=useState<string[]>([]),[repeatAssignment,setRepeatAssignment]=useState(true);
 const canManage=profile?.app_role==='admin'||profile?.app_role==='manager';const weekDates=useMemo(()=>Array.from({length:7},(_,i)=>addDateDays(weekStart,i)),[weekStart]);
 useEffect(()=>{void init()},[]);
 async function init(){const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}const p=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();if(p.error||!p.data?.location_id){setMessage('Could not load schedule templates.');setReady(true);return}const pr=p.data as Profile;setProfile(pr);await load(pr,weekStart);setReady(true)}
 async function load(pr=profile,ws=weekStart){if(!pr?.location_id)return;setBusy(true);try{if(!(pr.app_role==='admin'||pr.app_role==='manager'))return;const pe=await supabase.rpc('ensure_schedule_period',{p_starts_on:ws});if(pe.error)throw pe.error;const current=pe.data as Period;setPeriod(current);const [ps,t,sh,e,r]=await Promise.all([supabase.from('schedule_periods').select('id,starts_on,ends_on,status,revision').eq('location_id',pr.location_id).order('starts_on',{ascending:false}).limit(30),supabase.from('schedule_templates').select('id,name,description,active,created_at,updated_at').eq('location_id',pr.location_id).eq('active',true).order('name'),supabase.from('schedule_shifts').select('id,employee_id,role_id,starts_at,ends_at,status,notes').eq('schedule_period_id',current.id).neq('status','cancelled').order('starts_at'),supabase.from('employees').select('id,full_name').eq('location_id',pr.location_id).eq('active',true).is('deleted_at',null),supabase.from('employee_roles').select('id,name').eq('location_id',pr.location_id)]);for(const x of [ps,t,sh,e,r])if(x.error)throw x.error;const plist=(ps.data??[]) as Period[];setPeriods(plist);setTemplates((t.data??[]) as Template[]);setShifts((sh.data??[]) as Shift[]);setEmployees((e.data??[]) as Employee[]);setRoles((r.data??[]) as Role[]);if(!sourcePeriod){const source=plist.find(x=>x.id!==current.id);if(source)setSourcePeriod(source.id)}if(!selectedTemplate&&t.data?.length)setSelectedTemplate(t.data[0].id)}catch(e:any){setMessage(e?.message||'Could not load schedule templates.')}finally{setBusy(false)}}
 async function changeWeek(days:number){if(busy)return;const ws=addDateDays(weekStart,days);setWeekStart(ws);setRepeatDates([]);setRepeatShift('');await load(profile,ws)}
 async function copyWeek(){if(!period||!sourcePeriod||busy)return;if(shifts.length&& !window.confirm('The target week already has shifts. Whole-week Copy requires an empty target. Continue and let the database validate it?'))return;setBusy(true);const {data,error}=await supabase.rpc('copy_schedule_period',{p_source_period_id:sourcePeriod,p_target_period_id:period.id,p_expected_revision:period.revision,p_copy_assignments:copyAssignments});setMessage(error?error.message:`Copied ${(data as any)?.copied??0} shifts into this week.`);await load();setBusy(false)}
 async function saveTemplate(e:FormEvent){e.preventDefault();if(!period||busy||!templateForm.name.trim())return;setBusy(true);const {data,error}=await supabase.rpc('save_schedule_period_as_template',{p_period_id:period.id,p_name:templateForm.name.trim(),p_description:templateForm.description.trim()||null,p_include_assignments:templateForm.include_assignments});setMessage(error?error.message:`Template saved${data?' successfully.':'.'}`);if(!error)setTemplateForm({...templateForm,name:'',description:''});await load();setBusy(false)}
 async function applyTemplate(){if(!period||!selectedTemplate||busy)return;if(applyMode==='replace'&&!window.confirm('Replace will remove the current draft shifts and rebuild the week from this template. Continue?'))return;setBusy(true);const {data,error}=await supabase.rpc('apply_schedule_template',{p_template_id:selectedTemplate,p_target_period_id:period.id,p_expected_revision:period.revision,p_mode:applyMode,p_copy_assignments:applyAssignments});setMessage(error?error.message:`Template applied: ${(data as any)?.copied??0} shifts.`);await load();setBusy(false)}
 async function repeatSelected(){if(!repeatShift||!repeatDates.length||busy)return;setBusy(true);const {data,error}=await supabase.rpc('duplicate_schedule_shift',{p_shift_id:repeatShift,p_target_dates:repeatDates,p_copy_assignment:repeatAssignment});setMessage(error?error.message:`Repeated ${(data as any)?.copied??0} shift${Number((data as any)?.copied||0)===1?'':'s'}.`);if(!error)setRepeatDates([]);await load();setBusy(false)}
 const emp=(id:string|null)=>employees.find(x=>x.id===id)?.full_name||'Open';const role=(id:string|null)=>roles.find(x=>x.id===id)?.name||'Role';const selected=shifts.find(x=>x.id===repeatShift);const selectedDate=selected?new Date(selected.starts_at).toISOString().slice(0,10):'';
 if(!ready)return <div className="full-loader"><span>Opening templates…</span></div>;
 return <main className={styles.page}><div className={styles.top}><div><h1>Copy & Templates</h1><p>Copy a whole schedule, save reusable named layouts, merge or replace a week, and repeat individual shifts.</p></div><Link className={styles.back} href="/schedule">Back to Schedule</Link></div>{message&&<div className={message.toLowerCase().includes('could not')?styles.error:styles.notice}>{message}</div>}{!canManage?<div className={styles.error}>Manager access is required.</div>:<>
 <section className={styles.section}><div className={styles.card}><div className={styles.entryHead}><div><h2>Target week · {weekStart}</h2><small>{period?.status||'draft'} · revision {period?.revision??0} · {shifts.length} current shifts</small></div><div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>changeWeek(-7)}>Previous</button><button className={`${styles.button} ${styles.secondary}`} disabled={busy} onClick={()=>changeWeek(7)}>Next</button></div></div></div></section>
 <section className={styles.section}><div className={styles.card}><h2>Copy another week</h2><p>Whole-week copy requires an empty draft target. Choose whether to keep employee assignments or copy the structure as open shifts.</p><div className={styles.formGrid}><label className={styles.field}><span>Source week</span><select value={sourcePeriod} onChange={e=>setSourcePeriod(e.target.value)}><option value="">Choose week</option>{periods.filter(x=>x.id!==period?.id).map(x=><option key={x.id} value={x.id}>{x.starts_on} · {x.status}</option>)}</select></label><label className={styles.field}><span>Keep assignments</span><input type="checkbox" checked={copyAssignments} onChange={e=>setCopyAssignments(e.target.checked)}/></label></div><div className={styles.actions}><button className={styles.button} disabled={busy||!sourcePeriod||period?.status!=='draft'} onClick={copyWeek}>Copy Week</button></div></div></section>
 <section className={styles.section}><div className={styles.card}><h2>Save this week as a named template</h2><form onSubmit={saveTemplate}><div className={styles.formGrid}><label className={styles.field}><span>Template name</span><input maxLength={120} value={templateForm.name} onChange={e=>setTemplateForm({...templateForm,name:e.target.value})} placeholder="Summer FOH"/></label><label className={styles.field}><span>Description</span><input maxLength={2000} value={templateForm.description} onChange={e=>setTemplateForm({...templateForm,description:e.target.value})}/></label><label className={styles.field}><span>Remember employee assignments</span><input type="checkbox" checked={templateForm.include_assignments} onChange={e=>setTemplateForm({...templateForm,include_assignments:e.target.checked)}/></label></div><div className={styles.actions}><button className={styles.button} disabled={busy||!period}>Save Template</button></div></form></div></section>
 <section className={styles.section}><div className={styles.card}><h2>Apply named template</h2><div className={styles.formGrid}><label className={styles.field}><span>Template</span><select value={selectedTemplate} onChange={e=>setSelectedTemplate(e.target.value)}><option value="">Choose template</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><label className={styles.field}><span>Mode</span><select value={applyMode} onChange={e=>setApplyMode(e.target.value as 'merge'|'replace')}><option value="merge">Merge with existing draft</option><option value="replace">Replace existing draft</option></select></label><label className={styles.field}><span>Use saved assignments</span><input type="checkbox" checked={applyAssignments} onChange={e=>setApplyAssignments(e.target.checked)}/></label></div>{selectedTemplate&&<p>{templates.find(t=>t.id===selectedTemplate)?.description||'No template description.'}</p>}<div className={styles.actions}><button className={styles.button} disabled={busy||!selectedTemplate||period?.status!=='draft'} onClick={applyTemplate}>Apply Template</button></div></div></section>
 <section className={styles.section}><div className={styles.card}><h2>Repeat / duplicate one shift</h2><div className={styles.formGrid}><label className={styles.field}><span>Shift</span><select value={repeatShift} onChange={e=>{setRepeatShift(e.target.value);setRepeatDates([])}}><option value="">Choose shift</option>{shifts.map(s=><option key={s.id} value={s.id}>{new Date(s.starts_at).toLocaleString()} · {emp(s.employee_id)} · {role(s.role_id)}</option>)}</select></label><label className={styles.field}><span>Keep employee assignment</span><input type="checkbox" checked={repeatAssignment} onChange={e=>setRepeatAssignment(e.target.checked)}/></label></div>{selected&&<div className={styles.details}>{weekDates.filter(d=>d!==selectedDate).map(d=><label className={styles.detail} key={d}><b>{d}</b><input type="checkbox" checked={repeatDates.includes(d)} onChange={e=>setRepeatDates(e.target.checked?[...repeatDates,d]:repeatDates.filter(x=>x!==d))}/></label>)}</div>}<div className={styles.actions}><button className={styles.button} disabled={busy||!repeatShift||!repeatDates.length||period?.status!=='draft'} onClick={repeatSelected}>Repeat Shift</button></div><p>The database rechecks overlap, availability, time off, qualification, skill level, rest, weekly hours and consecutive-day rules for every repeated assigned shift.</p></div></section>
 <section className={styles.section}><h2>Saved templates</h2><div className={styles.list}>{templates.map(t=><div className={styles.entry} key={t.id}><div className={styles.entryHead}><div><h3>{t.name}</h3><small>{t.description||'No description'} · updated {new Date(t.updated_at).toLocaleString()}</small></div><span className={styles.pill}>active</span></div></div>)}{!templates.length&&<div className={styles.card}><b>No named templates yet.</b></div>}</div></section>
 </>}</main>
}
