'use client';

import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase';
import styles from '../../ops-tools.module.css';
import {businessDateInZone} from '@/lib/intermediate-hardening';
import {addDateDays,dateDayOfWeek} from '@/lib/scheduling-engine';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Employee={id:string;full_name:string;start_date:string|null};
type SchedProfile={employee_id:string;notes:string|null};
type Compliance={employee_id:string;date_of_birth:string|null};
type Milestone={employee_id:string;name:string;date:string;kind:'birthday'|'anniversary';detail:string};
const mondayOf=(d:string)=>addDateDays(d,-((dateDayOfWeek(d)+6)%7));
function occurrenceInWeek(md:string,weekStart:string){for(let i=0;i<7;i++){const d=addDateDays(weekStart,i);if(d.slice(5)===md)return d}return null}
export default function ScheduleTeamPage(){
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[profile,setProfile]=useState<Profile|null>(null),[weekStart,setWeekStart]=useState(()=>mondayOf(businessDateInZone())),[employees,setEmployees]=useState<Employee[]>([]),[notes,setNotes]=useState<Record<string,string>>({}),[birthdays,setBirthdays]=useState<Record<string,string>>({});
 const canManage=profile?.app_role==='admin'||profile?.app_role==='manager';
 useEffect(()=>{void init()},[]);
 async function init(){const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}const p=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();if(p.error||!p.data?.location_id){setMessage('Could not load team scheduling notes.');setReady(true);return}const pr=p.data as Profile;setProfile(pr);await load(pr);setReady(true)}
 async function load(pr=profile){if(!pr?.location_id||!(pr.app_role==='admin'||pr.app_role==='manager'))return;setBusy(true);try{const [e,s,c]=await Promise.all([supabase.from('employees').select('id,full_name,start_date').eq('location_id',pr.location_id).eq('active',true).is('deleted_at',null).order('full_name'),supabase.from('employee_schedule_profiles').select('employee_id,notes').eq('location_id',pr.location_id),supabase.from('employee_compliance_profiles').select('employee_id,date_of_birth').eq('location_id',pr.location_id)]);for(const x of [e,s,c])if(x.error)throw x.error;const es=(e.data??[]) as Employee[];setEmployees(es);const nm:Record<string,string>={};for(const x of s.data??[])nm[x.employee_id]=x.notes||'';for(const emp of es)if(nm[emp.id]===undefined)nm[emp.id]='';setNotes(nm);const bm:Record<string,string>={};for(const x of c.data??[])if(x.date_of_birth)bm[x.employee_id]=x.date_of_birth;setBirthdays(bm)}catch(e:any){setMessage(e?.message||'Could not load team scheduling notes.')}finally{setBusy(false)}}
 async function saveNote(employeeId:string){if(!canManage||!profile?.location_id||busy)return;setBusy(true);const {error}=await supabase.from('employee_schedule_profiles').upsert({employee_id:employeeId,location_id:profile.location_id,notes:notes[employeeId]?.trim()||null},{onConflict:'employee_id'});setMessage(error?error.message:'Scheduling note saved.');await load();setBusy(false)}
 const milestones=useMemo(()=>{const out:Milestone[]=[];for(const e of employees){const dob=birthdays[e.id];if(dob){const date=occurrenceInWeek(dob.slice(5),weekStart);if(date){const age=new Date(date+'T12:00:00Z').getUTCFullYear()-Number(dob.slice(0,4));out.push({employee_id:e.id,name:e.full_name,date,kind:'birthday',detail:`Birthday · turning ${age}`})}}if(e.start_date){const date=occurrenceInWeek(e.start_date.slice(5),weekStart);if(date&&date>=e.start_date){const years=new Date(date+'T12:00:00Z').getUTCFullYear()-Number(e.start_date.slice(0,4));if(years>0)out.push({employee_id:e.id,name:e.full_name,date,kind:'anniversary',detail:`Work anniversary · ${years} year${years===1?'':'s'}`})}}}return out.sort((a,b)=>a.date.localeCompare(b.date))},[employees,birthdays,weekStart]);
 if(!ready)return <div className="full-loader"><span>Opening team scheduling…</span></div>;
 return <main className={styles.page}><div className={styles.top}><div><h1>Team Scheduling Notes</h1><p>Manager-only notes and schedule-week milestones without creating another employee directory.</p></div><Link className={styles.back} href="/schedule">Back to Schedule</Link></div>{message&&<div className={message.toLowerCase().includes('could not')?styles.error:styles.notice}>{message}</div>}{!canManage?<div className={styles.error}>Manager access is required.</div>:<>
 <section className={styles.section}><div className={styles.card}><div className={styles.entryHead}><div><h2>Milestones · week of {weekStart}</h2><small>Birth dates stay in the manager-only compliance store; employee accounts do not gain access to them here.</small></div><div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} onClick={()=>setWeekStart(addDateDays(weekStart,-7))}>Previous</button><button className={`${styles.button} ${styles.secondary}`} onClick={()=>setWeekStart(addDateDays(weekStart,7))}>Next</button></div></div><div className={styles.list} style={{marginTop:12}}>{milestones.map(m=><div className={styles.entry} key={`${m.kind}-${m.employee_id}`}><div className={styles.entryHead}><div><h3>{m.name}</h3><small>{m.date} · {m.detail}</small></div><span className={styles.pill}>{m.kind}</span></div></div>)}{milestones.length===0&&<small>No birthdays or work anniversaries fall in this week.</small>}</div></div></section>
 <section className={styles.section}><h2>Scheduling notes</h2><div className={styles.list}>{employees.map(e=><div className={styles.entry} key={e.id}><div className={styles.entryHead}><div><h3>{e.full_name}</h3><small>{e.start_date?`Started ${e.start_date}`:'Start date not recorded'}{birthdays[e.id]?' · birthday on file':''}</small></div></div><label className={styles.field}><span>Manager scheduling note</span><textarea maxLength={2000} rows={3} value={notes[e.id]||''} onChange={ev=>setNotes({...notes,[e.id]:ev.target.value})} placeholder="Scheduling context managers should remember…"/></label><div className={styles.actions}><button className={styles.button} disabled={busy} onClick={()=>saveNote(e.id)}>Save Note</button></div></div>)}{employees.length===0&&<div className={styles.card}><b>No active employees loaded.</b></div>}</div></section>
 </>}</main>
}
