'use client';

import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {supabase} from '@/lib/supabase';
import {useI18n} from '@/lib/i18n';
import styles from '../../ops-tools.module.css';
import {businessDateInZone} from '@/lib/intermediate-hardening';
import {addDateDays,dateDayOfWeek} from '@/lib/scheduling-engine';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Employee={id:string;full_name:string;start_date:string|null};
type Milestone={employee_id:string;name:string;date:string;kind:'birthday'|'anniversary';years:number|null};
const mondayOf=(d:string)=>addDateDays(d,-((dateDayOfWeek(d)+6)%7));
function occurrenceInWeek(md:string,weekStart:string){for(let i=0;i<7;i++){const d=addDateDays(weekStart,i);if(d.slice(5)===md)return d}return null}
export default function ScheduleTeamPage(){
 const {locale}=useI18n();const localeCode=locale==='es'?'es-US':'en-US';const c=locale==='es'?{load:'No se pudieron cargar las notas de horarios del equipo.',saved:'Nota de horario guardada.',opening:'Abriendo horarios del equipo…',title:'Notas de Horarios del Equipo',body:'Notas solo para gerencia e hitos de la semana de horarios sin crear otro directorio de empleados.',back:'Volver al Horario',manager:'Se requiere acceso de gerente.',milestones:'Hitos · semana del',privacy:'Las fechas de nacimiento permanecen en el registro de cumplimiento solo para gerencia; las cuentas de empleados no obtienen acceso a ellas aquí.',previous:'Anterior',next:'Siguiente',birthday:'Cumpleaños',turning:(n:number)=>`cumple ${n}`,anniversary:'Aniversario laboral',years:(n:number)=>`${n} año${n===1?'':'s'}`,noneMilestones:'No hay cumpleaños ni aniversarios laborales esta semana.',notes:'Notas de horarios',started:'Comenzó',noStart:'Fecha de inicio no registrada',birthdayFile:'cumpleaños registrado',note:'Nota de horario de gerencia',placeholder:'Contexto de horarios que la gerencia debe recordar…',save:'Guardar Nota',noneEmployees:'No hay empleados activos cargados.'}:{load:'Could not load team scheduling notes.',saved:'Scheduling note saved.',opening:'Opening team scheduling…',title:'Team Scheduling Notes',body:'Manager-only notes and schedule-week milestones without creating another employee directory.',back:'Back to Schedule',manager:'Manager access is required.',milestones:'Milestones · week of',privacy:'Birth dates stay in the manager-only compliance store; employee accounts do not gain access to them here.',previous:'Previous',next:'Next',birthday:'Birthday',turning:(n:number)=>`turning ${n}`,anniversary:'Work anniversary',years:(n:number)=>`${n} year${n===1?'':'s'}`,noneMilestones:'No birthdays or work anniversaries fall in this week.',notes:'Scheduling notes',started:'Started',noStart:'Start date not recorded',birthdayFile:'birthday on file',note:'Manager scheduling note',placeholder:'Scheduling context managers should remember…',save:'Save Note',noneEmployees:'No active employees loaded.'};
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[profile,setProfile]=useState<Profile|null>(null),[weekStart,setWeekStart]=useState(()=>mondayOf(businessDateInZone())),[employees,setEmployees]=useState<Employee[]>([]),[notes,setNotes]=useState<Record<string,string>>({}),[birthdays,setBirthdays]=useState<Record<string,string>>({});
 const canManage=profile?.app_role==='admin'||profile?.app_role==='manager';
 useEffect(()=>{void init()},[]);
 async function init(){const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}const p=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();if(p.error||!p.data?.location_id){setMessage(c.load);setReady(true);return}const pr=p.data as Profile;setProfile(pr);await load(pr);setReady(true)}
 async function load(pr=profile){if(!pr?.location_id||!(pr.app_role==='admin'||pr.app_role==='manager'))return;setBusy(true);try{const [e,s,comp]=await Promise.all([supabase.from('employees').select('id,full_name,start_date').eq('location_id',pr.location_id).eq('active',true).is('deleted_at',null).order('full_name'),supabase.from('employee_schedule_profiles').select('employee_id,notes').eq('location_id',pr.location_id),supabase.from('employee_compliance_profiles').select('employee_id,date_of_birth').eq('location_id',pr.location_id)]);for(const x of [e,s,comp])if(x.error)throw x.error;const es=(e.data??[]) as Employee[];setEmployees(es);const nm:Record<string,string>={};for(const x of s.data??[])nm[x.employee_id]=x.notes||'';for(const emp of es)if(nm[emp.id]===undefined)nm[emp.id]='';setNotes(nm);const bm:Record<string,string>={};for(const x of comp.data??[])if(x.date_of_birth)bm[x.employee_id]=x.date_of_birth;setBirthdays(bm)}catch(e:any){setMessage(e?.message||c.load)}finally{setBusy(false)}}
 async function saveNote(employeeId:string){if(!canManage||!profile?.location_id||busy)return;setBusy(true);const {error}=await supabase.from('employee_schedule_profiles').upsert({employee_id:employeeId,location_id:profile.location_id,notes:notes[employeeId]?.trim()||null},{onConflict:'employee_id'});setMessage(error?error.message:c.saved);await load();setBusy(false)}
 const milestones=useMemo(()=>{const out:Milestone[]=[];for(const e of employees){const dob=birthdays[e.id];if(dob){const date=occurrenceInWeek(dob.slice(5),weekStart);if(date){const age=new Date(date+'T12:00:00Z').getUTCFullYear()-Number(dob.slice(0,4));out.push({employee_id:e.id,name:e.full_name,date,kind:'birthday',years:age})}}if(e.start_date){const date=occurrenceInWeek(e.start_date.slice(5),weekStart);if(date&&date>=e.start_date){const years=new Date(date+'T12:00:00Z').getUTCFullYear()-Number(e.start_date.slice(0,4));if(years>0)out.push({employee_id:e.id,name:e.full_name,date,kind:'anniversary',years})}}}return out.sort((a,b)=>a.date.localeCompare(b.date))},[employees,birthdays,weekStart]);
 const milestoneDetail=(m:Milestone)=>m.kind==='birthday'?`${c.birthday} · ${c.turning(m.years||0)}`:`${c.anniversary} · ${c.years(m.years||0)}`;
 if(!ready)return <div className="full-loader"><span>{c.opening}</span></div>;
 return <main className={styles.page}><div className={styles.top}><div><h1>{c.title}</h1><p>{c.body}</p></div><Link className={styles.back} href="/schedule">{c.back}</Link></div>{message&&<div className={message===c.load?styles.error:styles.notice}>{message}</div>}{!canManage?<div className={styles.error}>{c.manager}</div>:<>
 <section className={styles.section}><div className={styles.card}><div className={styles.entryHead}><div><h2>{c.milestones} {new Date(`${weekStart}T12:00:00`).toLocaleDateString(localeCode)}</h2><small>{c.privacy}</small></div><div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} onClick={()=>setWeekStart(addDateDays(weekStart,-7))}>{c.previous}</button><button className={`${styles.button} ${styles.secondary}`} onClick={()=>setWeekStart(addDateDays(weekStart,7))}>{c.next}</button></div></div><div className={styles.list} style={{marginTop:12}}>{milestones.map(m=><div className={styles.entry} key={`${m.kind}-${m.employee_id}`}><div className={styles.entryHead}><div><h3>{m.name}</h3><small>{new Date(`${m.date}T12:00:00`).toLocaleDateString(localeCode)} · {milestoneDetail(m)}</small></div><span className={styles.pill}>{m.kind==='birthday'?c.birthday:c.anniversary}</span></div></div>)}{milestones.length===0&&<small>{c.noneMilestones}</small>}</div></div></section>
 <section className={styles.section}><h2>{c.notes}</h2><div className={styles.list}>{employees.map(e=><div className={styles.entry} key={e.id}><div className={styles.entryHead}><div><h3>{e.full_name}</h3><small>{e.start_date?`${c.started} ${new Date(`${e.start_date}T12:00:00`).toLocaleDateString(localeCode)}`:c.noStart}{birthdays[e.id]?` · ${c.birthdayFile}`:''}</small></div></div><label className={styles.field}><span>{c.note}</span><textarea maxLength={2000} rows={3} value={notes[e.id]||''} onChange={ev=>setNotes({...notes,[e.id]:ev.target.value})} placeholder={c.placeholder}/></label><div className={styles.actions}><button className={styles.button} disabled={busy} onClick={()=>saveNote(e.id)}>{c.save}</button></div></div>)}{employees.length===0&&<div className={styles.card}><b>{c.noneEmployees}</b></div>}</div></section>
 </>}</main>
}
