'use client';

import {FormEvent,useEffect,useMemo,useState} from 'react';
import {BookOpen,CalendarDays,CheckCircle2,ChevronLeft,Clock3,GraduationCap,Home,MessageSquare,PlayCircle,UserRound} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import {useI18n} from '@/lib/i18n';
import styles from '../employee.module.css';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Setup={status:string;employee_id?:string|null};
type Course={id:string;name:string;description:string|null;active:boolean};
type Assignment={id:string;course_id:string;employee_id:string;status:'assigned'|'in_progress'|'completed'|'cancelled';due_at:string|null;assigned_at:string;started_at:string|null;completed_at:string|null};
type Lesson={id:string;title:string;lesson_type:'text'|'image'|'video'|'quiz'|'task'|'acknowledgment';content:string|null;media_url:string|null;pass_score:number|null;active:boolean};
type CourseLesson={id:string;course_id:string;lesson_id:string;position:number;required:boolean};
type Progress={assignment_id:string;course_lesson_id:string;status:'not_started'|'in_progress'|'waiting_review'|'completed'|'rejected';last_score:number|null;attempts:number;review_note:string|null};
type Payload={assignment_id:string;course_lesson_id:string;position:number;required:boolean;lesson:{id:string;title:string;lesson_type:Lesson['lesson_type'];content:string|null;media_url:string|null;pass_score:number|null};questions:{id:string;position:number;prompt:string;options:string[]}[];unlocked:boolean};

const statusLabel=(value:string,locale:'en'|'es')=>{
 const map:Record<string,[string,string]>={assigned:['Assigned','Asignado'],in_progress:['In progress','En progreso'],completed:['Completed','Completado'],cancelled:['Cancelled','Cancelado'],not_started:['Not started','No iniciado'],waiting_review:['Waiting review','En revisión'],rejected:['Rejected','Rechazado'],text:['Text','Texto'],image:['Image','Imagen'],video:['Video','Video'],quiz:['Quiz','Cuestionario'],task:['Task','Tarea'],acknowledgment:['Acknowledgment','Confirmación'],lesson:['Lesson','Lección']};
 return map[value]?.[locale==='es'?1:0]||value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())
};

export default function EmployeeTraining(){
 const {locale}=useI18n();
 const c=locale==='es'?{
  noDue:'Sin fecha límite',openError:'No se pudo abrir la capacitación.',refreshError:'No se pudieron actualizar algunos detalles de capacitación.',course:'Curso de capacitación',lessonComplete:'Lección completada.',answerAll:'Responde todas las preguntas antes de enviar.',score:'Puntuación',passed:'Aprobado',again:'Inténtalo de nuevo',taskSubmitted:'Tarea enviada para revisión de gerencia.',opening:'Abriendo capacitación…',back:'Volver al inicio del personal',staff:'Personal de El Molino',training:'Capacitación',development:'Mi desarrollo',openAssignment:'asignación abierta',openAssignments:'asignaciones abiertas',hero:'Completa los cursos obligatorios, cuestionarios y tareas revisadas por gerencia desde tu cuenta de empleado.',overdueNeed:'elemento vencido requiere atención',overdueNeedPlural:'elementos vencidos requieren atención',nothingOverdue:'Nada vencido',completedCourse:'curso completado',completedCourses:'cursos completados',assignments:'Asignaciones',overdueFirst:'Vencidos primero',overdue:'vencido',assignedCourse:'Curso de capacitación asignado',none:'No tienes capacitación asignada en este momento.',complete:'completado',lessonsComplete:'lecciones completadas',done:'Listo',courseStatus:'estado del curso',due:'vence',lesson:'Lección',required:'Obligatorio',optional:'Opcional',noLessons:'Este curso aún no tiene lecciones.',openMedia:'Abrir material de capacitación',submitQuiz:'Enviar cuestionario',completionNote:'Nota de finalización (opcional)',whatComplete:'¿Qué completaste?',submitReview:'Enviar para revisión',ack:'Confirmo',completeLesson:'Completar lección',close:'Cerrar',staffNav:'Navegación del personal',home:'Inicio',schedule:'Horario',requests:'Solicitudes',team:'Equipo',more:'Más'
 }:{
  noDue:'No due date',openError:'Could not open training.',refreshError:'Some training details could not be refreshed.',course:'Training course',lessonComplete:'Lesson completed.',answerAll:'Answer every question before submitting.',score:'Score',passed:'Passed',again:'Try again',taskSubmitted:'Task submitted for manager review.',opening:'Opening training…',back:'Back to staff home',staff:'El Molino · Staff',training:'Training',development:'My development',openAssignment:'open assignment',openAssignments:'open assignments',hero:'Complete required courses, quizzes and manager-reviewed tasks from your employee account.',overdueNeed:'overdue item needs attention',overdueNeedPlural:'overdue items need attention',nothingOverdue:'Nothing overdue',completedCourse:'course completed',completedCourses:'courses completed',assignments:'Assignments',overdueFirst:'Overdue first',overdue:'overdue',assignedCourse:'Assigned training course',none:'No training is assigned to you right now.',complete:'complete',lessonsComplete:'lessons complete',done:'Done',courseStatus:'course status',due:'due',lesson:'Lesson',required:'Required',optional:'Optional',noLessons:'This course has no lessons yet.',openMedia:'Open training media',submitQuiz:'Submit quiz',completionNote:'Completion note (optional)',whatComplete:'What did you complete?',submitReview:'Submit for review',ack:'I acknowledge',completeLesson:'Complete lesson',close:'Close',staffNav:'Staff navigation',home:'Home',schedule:'Schedule',requests:'Requests',team:'Team',more:'More'
 };
 const dueLabel=(iso:string|null)=>iso?new Date(iso).toLocaleString(locale==='es'?'es-US':'en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):c.noDue;
 const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[me,setMe]=useState<string|null>(null);
 const [courses,setCourses]=useState<Course[]>([]),[assignments,setAssignments]=useState<Assignment[]>([]),[lessons,setLessons]=useState<Lesson[]>([]),[links,setLinks]=useState<CourseLesson[]>([]),[progress,setProgress]=useState<Progress[]>([]);
 const [selected,setSelected]=useState(''),[payload,setPayload]=useState<Payload|null>(null),[answers,setAnswers]=useState<Record<string,number>>({}),[taskComment,setTaskComment]=useState('');
 useEffect(()=>{void load()},[]);
 async function load(preferred?:string){
  setBusy(true);setNotice('');const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return}
  const p=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();if(p.error||!p.data?.location_id){setNotice(c.openError);setReady(true);setBusy(false);return}const profile=p.data as Profile;if(profile.app_role!=='employee'){location.href='/training/courses';return}
  const st=await supabase.rpc('employee_self_setup_status',{});if(st.error){setNotice(st.error.message);setReady(true);setBusy(false);return}const setup=(st.data||{status:'not_started'}) as Setup;if(setup.status!=='approved'||!setup.employee_id){location.href='/employee/setup';return}setMe(setup.employee_id);
  const [a,coursesResult,l,cl,pg]=await Promise.all([
   supabase.from('training_course_assignments').select('id,course_id,employee_id,status,due_at,assigned_at,started_at,completed_at').eq('employee_id',setup.employee_id).order('assigned_at',{ascending:false}).limit(250),
   supabase.from('training_courses').select('id,name,description,active').order('name'),
   supabase.from('training_lessons').select('id,title,lesson_type,content,media_url,pass_score,active').order('created_at'),
   supabase.from('training_course_lessons').select('id,course_id,lesson_id,position,required').order('position'),
   supabase.from('training_course_lesson_progress').select('assignment_id,course_lesson_id,status,last_score,attempts,review_note').eq('employee_id',setup.employee_id).limit(3000)
  ]);
  if([a,coursesResult,l,cl,pg].some(x=>x.error))setNotice(c.refreshError);
  const as=(a.data??[]) as Assignment[];setAssignments(as);setCourses((coursesResult.data??[]) as Course[]);setLessons((l.data??[]) as Lesson[]);setLinks((cl.data??[]) as CourseLesson[]);setProgress((pg.data??[]) as Progress[]);
  const requested=preferred||new URLSearchParams(window.location.search).get('assignment')||selected||as.find(x=>['assigned','in_progress'].includes(x.status))?.id||as[0]?.id||'';setSelected(as.some(x=>x.id===requested)?requested:(as[0]?.id||''));setReady(true);setBusy(false)
 }
 const courseName=(id:string)=>courses.find(course=>course.id===id)?.name||c.course;
 const lesson=(id:string)=>lessons.find(l=>l.id===id)||null;
 const assignment=assignments.find(a=>a.id===selected)||null;
 const assignmentLinks=useMemo(()=>assignment?links.filter(x=>x.course_id===assignment.course_id).sort((a,b)=>a.position-b.position):[],[assignment,links]);
 const assignmentProgress=useMemo(()=>assignmentLinks.map(x=>progress.find(p=>p.assignment_id===selected&&p.course_lesson_id===x.id)).filter(Boolean) as Progress[],[assignmentLinks,progress,selected]);
 const completed=assignmentProgress.filter(p=>p.status==='completed').length;
 const percent=assignmentLinks.length?Math.round(completed/assignmentLinks.length*100):(assignment?.status==='completed'?100:0);
 const open=assignments.filter(a=>['assigned','in_progress'].includes(a.status));
 const overdue=open.filter(a=>a.due_at&&new Date(a.due_at).getTime()<Date.now());
 const ordered=useMemo(()=>[...assignments].sort((a,b)=>{const ao=a.due_at&&new Date(a.due_at).getTime()<Date.now()&&['assigned','in_progress'].includes(a.status)?0:1;const bo=b.due_at&&new Date(b.due_at).getTime()<Date.now()&&['assigned','in_progress'].includes(b.status)?0:1;return ao-bo||(a.due_at||'9999').localeCompare(b.due_at||'9999')}),[assignments]);
 async function openLesson(cl:CourseLesson){if(!assignment||busy)return;setBusy(true);const {data,error}=await supabase.rpc('training_lesson_payload',{p_assignment_id:assignment.id,p_course_lesson_id:cl.id});if(error){setNotice(error.message);setBusy(false);return}const out=data as Payload;setPayload(out);setAnswers({});setTaskComment('');const pr=progress.find(p=>p.assignment_id===assignment.id&&p.course_lesson_id===cl.id);if(!pr||['not_started','in_progress','rejected'].includes(pr.status)){const start=await supabase.rpc('start_training_lesson',{p_assignment_id:assignment.id,p_course_lesson_id:cl.id});if(start.error)setNotice(start.error.message);else await load(assignment.id)}setBusy(false)}
 async function completeLesson(){if(!payload||busy)return;setBusy(true);const {error}=await supabase.rpc('complete_training_lesson',{p_assignment_id:payload.assignment_id,p_course_lesson_id:payload.course_lesson_id});setNotice(error?error.message:c.lessonComplete);if(!error)setPayload(null);await load(selected);setBusy(false)}
 async function submitQuiz(e:FormEvent){e.preventDefault();if(!payload||busy)return;if(payload.questions.some(q=>answers[q.id]===undefined)){setNotice(c.answerAll);return}setBusy(true);const {data,error}=await supabase.rpc('submit_training_quiz',{p_assignment_id:payload.assignment_id,p_course_lesson_id:payload.course_lesson_id,p_answers:Object.fromEntries(Object.entries(answers))});const out=data as any;setNotice(error?error.message:`${c.score} ${Number(out?.score||0)}% · ${out?.passed?c.passed:c.again}.`);if(!error&&out?.passed)setPayload(null);await load(selected);setBusy(false)}
 async function submitTask(e:FormEvent){e.preventDefault();if(!payload||busy)return;setBusy(true);const {error}=await supabase.rpc('submit_training_task',{p_assignment_id:payload.assignment_id,p_course_lesson_id:payload.course_lesson_id,p_comment:taskComment.trim()||null});setNotice(error?error.message:c.taskSubmitted);if(!error)setPayload(null);await load(selected);setBusy(false)}
 if(!ready)return <main className={styles.page}>{c.opening}</main>;
 const completedCourses=assignments.filter(a=>a.status==='completed').length;
 return <main className={styles.page}>
  <header className={styles.header}><a className={styles.iconButton} href="/employee" aria-label={c.back}><ChevronLeft size={20}/></a><div className={styles.brand}><small>{c.staff}</small><strong>{c.training}</strong></div><span className={styles.iconButton} aria-hidden="true"><GraduationCap size={20}/></span></header>
  {notice&&<div className={styles.notice}>{notice}</div>}
  <section className={styles.hero}><small>{c.development}</small><h1>{open.length} {open.length===1?c.openAssignment:c.openAssignments}.</h1><p>{c.hero}</p><div className={styles.next}><b>{overdue.length?`${overdue.length} ${overdue.length===1?c.overdueNeed:c.overdueNeedPlural}`:c.nothingOverdue}</b><span>{completedCourses} {completedCourses===1?c.completedCourse:c.completedCourses}</span></div></section>
  <section className={styles.section}><div className={styles.sectionHead}><h2>{c.assignments}</h2><span>{c.overdueFirst}</span></div><div className={styles.list}>{ordered.map(a=>{const late=Boolean(a.due_at&&new Date(a.due_at).getTime()<Date.now()&&['assigned','in_progress'].includes(a.status));return <button key={a.id} className={`${styles.row} ${a.id===selected?styles.notificationUnread:''}`} onClick={()=>{setSelected(a.id);setPayload(null)}}><span className={styles.notificationIcon}>{a.status==='completed'?<CheckCircle2 size={18}/>:late?<Clock3 className={styles.criticalText} size={18}/>:<BookOpen size={18}/>}</span><span className={styles.rowMain}><span className={styles.notificationMeta}><span className={late?styles.criticalText:''}>{late?c.overdue:statusLabel(a.status,locale)}</span><span>{dueLabel(a.due_at)}</span></span><b>{courseName(a.course_id)}</b><small>{courses.find(course=>course.id===a.course_id)?.description||c.assignedCourse}</small></span></button>})}{!assignments.length&&<div className={styles.empty}>{c.none}</div>}</div></section>
  {assignment&&<section className={styles.section}><div className={styles.sectionHead}><h2>{courseName(assignment.course_id)}</h2><span>{percent}% {c.complete}</span></div><div className={styles.metricGrid}><div className={styles.metric}><b>{completed}/{assignmentLinks.length}</b><span>{c.lessonsComplete}</span></div><div className={styles.metric}><b>{assignment.status==='completed'?c.done:dueLabel(assignment.due_at)}</b><span>{assignment.status==='completed'?c.courseStatus:c.due}</span></div></div><div className={styles.list}>{assignmentLinks.map(cl=>{const l=lesson(cl.lesson_id);const pr=progress.find(p=>p.assignment_id===assignment.id&&p.course_lesson_id===cl.id);const locked=Boolean(pr&&pr.status==='waiting_review');return <button key={cl.id} className={styles.row} disabled={busy||locked} onClick={()=>openLesson(cl)}><span className={styles.notificationIcon}>{pr?.status==='completed'?<CheckCircle2 size={18}/>:<PlayCircle size={18}/>}</span><span className={styles.rowMain}><b>{cl.position}. {l?.title||c.lesson}</b><small>{statusLabel(pr?.status||'not_started',locale)} · {statusLabel(l?.lesson_type||'lesson',locale)}{pr?.last_score!==null&&pr?.last_score!==undefined?` · ${pr.last_score}%`:''}{pr?.review_note?` · ${pr.review_note}`:''}</small></span><span className={styles.pill}>{cl.required?c.required:c.optional}</span></button>})}{!assignmentLinks.length&&<div className={styles.empty}>{c.noLessons}</div>}</div></section>}
  {payload&&<section className={styles.section}><div className={styles.setupCard}><div className={styles.sectionHead}><h2>{payload.lesson.title}</h2><span>{statusLabel(payload.lesson.lesson_type,locale)}</span></div>{payload.lesson.content&&<p style={{whiteSpace:'pre-wrap',lineHeight:1.55}}>{payload.lesson.content}</p>}{payload.lesson.media_url&&<p><a className={styles.button} href={payload.lesson.media_url} target="_blank" rel="noreferrer">{c.openMedia}</a></p>}{payload.lesson.lesson_type==='quiz'?<form className={styles.form} onSubmit={submitQuiz}>{payload.questions.map((q,i)=><fieldset key={q.id} className={styles.setupCard}><legend><b>{i+1}. {q.prompt}</b></legend><div className={styles.roles}>{(q.options||[]).map((option,index)=><label className={styles.role} key={`${q.id}-${index}`}><input type="radio" name={q.id} checked={answers[q.id]===index} onChange={()=>setAnswers(v=>({...v,[q.id]:index}))}/>{option}</label>)}</div></fieldset>)}<button className={styles.button} disabled={busy}>{c.submitQuiz}</button></form>:payload.lesson.lesson_type==='task'?<form className={styles.form} onSubmit={submitTask}><label className={styles.field}><span>{c.completionNote}</span><input maxLength={2000} value={taskComment} onChange={e=>setTaskComment(e.target.value)} placeholder={c.whatComplete}/></label><button className={styles.button} disabled={busy}>{c.submitReview}</button></form>:<div className={styles.actions}><button className={styles.button} disabled={busy} onClick={completeLesson}><CheckCircle2 size={16}/>{payload.lesson.lesson_type==='acknowledgment'?c.ack:c.completeLesson}</button></div>}<div className={styles.actions}><button className={`${styles.button} ${styles.secondary}`} onClick={()=>setPayload(null)}>{c.close}</button></div></div></section>}
  <nav className={styles.tabs} aria-label={c.staffNav}><a className={styles.tab} href="/employee"><Home size={19}/>{c.home}</a><a className={styles.tab} href="/employee/schedule"><CalendarDays size={19}/>{c.schedule}</a><a className={styles.tab} href="/employee/requests"><Clock3 size={19}/>{c.requests}</a><a className={styles.tab} href="/employee/team"><MessageSquare size={19}/>{c.team}</a><a className={`${styles.tab} ${styles.tabActive}`} href="/account"><UserRound size={19}/>{c.more}</a></nav>
 </main>
}
