'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Check, ChevronDown, ChevronRight, Loader2, Plus, Search, Trash2, Undo2, X } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { OPS_CATEGORIES, OPS_MODULES, OPS_MODULE_BY_KIND, OpsKind, normalizeOpsData, validateOpsRecord } from '@/lib/ops-modules';
import {useI18n} from '@/lib/i18n';
import {opsBooleanText,opsCategoryText,opsFieldText,opsModuleText,opsOptionText,opsStatusText,opsValidationText} from '@/lib/ops-i18n';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Row={id:string;kind:OpsKind;title:string;status:string;priority:string;sensitivity:string;data:Record<string,unknown>;due_at:string|null;occurred_at:string|null;created_at:string;updated_at:string;archived_at:string|null;deleted_at:string|null};
type UndoState={label:string;id:string;patch:Record<string,unknown>;expectedUpdatedAt:string}|null;

const blank=()=>({title:'',priority:'normal',due_at:'',data:{} as Record<string,unknown>});
const pretty=(k:string)=>k.replace(/_/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
const formatDate=(v:string|null,localeCode:string)=>v?new Date(v).toLocaleString(localeCode):'';
const normalizedTitle=(x:string)=>x.trim().toLowerCase().replace(/\s+/g,' ');

export default function OpsPage(){
  const {locale}=useI18n();const t=(en:string,es:string)=>locale==='es'?es:en;const localeCode=locale==='es'?'es-US':'en-US';
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  const [profile,setProfile]=useState<Profile|null>(null),[rows,setRows]=useState<Row[]>([]);
  const [category,setCategory]=useState('All'),[kind,setKind]=useState<OpsKind>('shift_handoff'),[query,setQuery]=useState(''),[showForm,setShowForm]=useState(false);
  const [draft,setDraft]=useState(blank()),[editing,setEditing]=useState<Row|null>(null),[showArchived,setShowArchived]=useState(false),[undo,setUndo]=useState<UndoState>(null);
  const canManage=profile?.app_role==='admin'||profile?.app_role==='manager';
  const module=OPS_MODULE_BY_KIND[kind];const moduleText=opsModuleText(module,locale);
  const visibleModules=useMemo(()=>OPS_MODULES.filter(m=>(category==='All'||m.category===category)&&(canManage||m.sensitivity==='team')),[category,canManage]);
  const filtered=useMemo(()=>rows.filter(r=>r.kind===kind&&(showArchived?Boolean(r.archived_at):!r.archived_at)&&(!query.trim()||`${r.title} ${JSON.stringify(r.data)}`.toLowerCase().includes(query.toLowerCase()))),[rows,kind,query,showArchived]);

  useEffect(()=>{const params=new URLSearchParams(location.search);const requested=params.get('kind') as OpsKind|null;if(requested&&OPS_MODULE_BY_KIND[requested]){setKind(requested);setCategory(OPS_MODULE_BY_KIND[requested].category);if(params.get('new')==='1')setShowForm(true)}void load()},[]);
  async function load(){setLoading(true);const {data:u}=await supabase.auth.getUser();if(!u.user){location.href='/';return;}const [p,r]=await Promise.all([supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single(),supabase.from('ops_records').select('*').is('deleted_at',null).order('updated_at',{ascending:false}).limit(1000)]);if(p.data)setProfile(p.data as Profile);if(r.error)setMessage(r.error.message);setRows((r.data??[]) as Row[]);setLoading(false)}
  function flash(x:string){setMessage(x);setTimeout(()=>setMessage(''),3500)}
  function selectKind(next:OpsKind){setKind(next);setCategory(OPS_MODULE_BY_KIND[next].category);setDraft(blank());setEditing(null);setShowForm(false);history.replaceState(null,'',`/ops?kind=${next}`)}
  function setField(key:string,value:unknown){setDraft(d=>({...d,data:{...d.data,[key]:value}}))}
  function beginEdit(row:Row){setKind(row.kind);setCategory(OPS_MODULE_BY_KIND[row.kind].category);setEditing(row);setDraft({title:row.title,priority:row.priority,due_at:row.due_at?row.due_at.slice(0,16):'',data:{...row.data}});setShowForm(true);window.scrollTo({top:0,behavior:'smooth'})}
  function resetForm(){setEditing(null);setDraft(blank());setShowForm(false)}
  async function save(e:FormEvent){e.preventDefault();if(busy||!profile?.location_id)return;const clean=normalizeOpsData(kind,draft.data);const errors=validateOpsRecord(kind,draft.title,clean);if(errors.length){flash(opsValidationText(errors[0],locale));return;}const duplicate=rows.find(r=>r.kind===kind&&r.id!==editing?.id&&normalizedTitle(r.title)===normalizedTitle(draft.title)&&!r.deleted_at);if(duplicate)return flash(`${t('A record named','Ya existe un registro llamado')} “${duplicate.title}”.`);setBusy(true);const {data:u}=await supabase.auth.getUser();if(!u.user){setBusy(false);return;}const payload={location_id:profile.location_id,kind,title:draft.title.trim(),priority:draft.priority,sensitivity:module.sensitivity,data:clean,due_at:draft.due_at?new Date(draft.due_at).toISOString():null,created_by:u.user.id};if(editing){const {created_by,...update}=payload;const result=await supabase.from('ops_records').update({...update,updated_by:u.user.id}).eq('id',editing.id).eq('updated_at',editing.updated_at).select('id').maybeSingle();setBusy(false);if(result.error){flash(result.error.message);return;}if(!result.data){await load();flash(t('This record changed on another device. The latest version has been loaded instead of overwriting it.','Este registro cambió en otro dispositivo. Se cargó la versión más reciente sin sobrescribirla.'));return;}await supabase.from('activity_log').insert({location_id:profile.location_id,actor_user_id:u.user.id,action:'updated',entity_type:'ops_record',entity_id:result.data.id,summary:`Updated ${module.title}: ${draft.title.trim()}`});resetForm();await load();flash(t('Updated.','Actualizado.'));return}const result=await supabase.from('ops_records').insert(payload).select('id').single();setBusy(false);if(result.error){flash(result.error.message);return;}await supabase.from('activity_log').insert({location_id:profile.location_id,actor_user_id:u.user.id,action:'created',entity_type:'ops_record',entity_id:result.data.id,summary:`Created ${module.title}: ${draft.title.trim()}`});resetForm();await load();flash(t('Saved.','Guardado.'))}
  async function setStatus(row:Row,status:string){if(busy)return;setBusy(true);const prior=row.status;const {data,error}=await supabase.from('ops_records').update({status}).eq('id',row.id).eq('updated_at',row.updated_at).select('id,updated_at').maybeSingle();setBusy(false);if(error)return flash(error.message);if(!data){await load();return flash(t('This record changed on another device. The latest version has been loaded.','Este registro cambió en otro dispositivo. Se cargó la versión más reciente.'))}setUndo({label:`${t('Undo status change for','Deshacer cambio de estado de')} ${row.title}`,id:row.id,patch:{status:prior},expectedUpdatedAt:data.updated_at});await load();flash(`${t('Marked','Marcado')} ${opsStatusText(status,locale)}.`)}
  async function archive(row:Row){if(busy)return;setBusy(true);const prior=row.archived_at;const next=row.archived_at?null:new Date().toISOString();const {data,error}=await supabase.from('ops_records').update({archived_at:next}).eq('id',row.id).eq('updated_at',row.updated_at).select('id,updated_at').maybeSingle();setBusy(false);if(error)return flash(error.message);if(!data){await load();return flash(t('This record changed on another device. The latest version has been loaded.','Este registro cambió en otro dispositivo. Se cargó la versión más reciente.'))}setUndo({label:`${t('Undo','Deshacer')} ${row.archived_at?t('restore','restauración'):t('archive','archivo')} ${t('for','de')} ${row.title}`,id:row.id,patch:{archived_at:prior},expectedUpdatedAt:data.updated_at});await load();flash(row.archived_at?t('Restored from archive.','Restaurado del archivo.'):t('Archived.','Archivado.'))}
  async function remove(row:Row){if(busy||!confirm(`${t('Move','¿Mover')} “${row.title}” ${t('to trash?','a la papelera?')}`))return;setBusy(true);const {data,error}=await supabase.from('ops_records').update({deleted_at:new Date().toISOString()}).eq('id',row.id).eq('updated_at',row.updated_at).select('id,updated_at').maybeSingle();setBusy(false);if(error)return flash(error.message);if(!data){await load();return flash(t('This record changed on another device. The latest version has been loaded.','Este registro cambió en otro dispositivo. Se cargó la versión más reciente.'))}setUndo({label:`${t('Restore','Restaurar')} ${row.title}`,id:row.id,patch:{deleted_at:null},expectedUpdatedAt:data.updated_at});await load();flash(t('Moved to trash.','Movido a la papelera.'))}
  async function applyUndo(){if(busy||!undo)return;setBusy(true);const current=undo;const {data,error}=await supabase.from('ops_records').update(current.patch).eq('id',current.id).eq('updated_at',current.expectedUpdatedAt).select('id').maybeSingle();setBusy(false);if(error)return flash(error.message);if(!data){setUndo(null);await load();return flash(t('Undo was not applied because this record changed again. The latest version has been loaded.','No se deshizo porque el registro volvió a cambiar. Se cargó la versión más reciente.'))}setUndo(null);await load();flash(t('Change undone.','Cambio deshecho.'))}

  if(loading)return <div className="full-loader"><Loader2 className="spin"/><span>{t('Opening operations…','Abriendo operaciones…')}</span></div>;
  return <div className="app-shell">
    <header className="topbar"><a className="round-button" href="/tools" aria-label={t('Back','Volver')}><ArrowLeft/></a><div style={{flex:1}}><div className="brand-kicker">El Molino Ops</div><div className="brand-title">{t('Operations Center','Centro de Operaciones')}</div></div><button className="round-button" disabled={busy} onClick={()=>setShowForm(x=>!x)} aria-label={t('Create record','Crear registro')}>{showForm?<X/>:<Plus/>}</button></header>
    <main className="page">
      {message&&<div className="toast-message">{message}</div>}{undo&&<div className="notice" style={{display:'flex',alignItems:'center',justifyContent:'space-between',gap:10,marginBottom:12}}><span>{undo.label}</span><button className="mini-action" disabled={busy} onClick={applyUndo}><Undo2 size={14}/> {t('Undo','Deshacer')}</button></div>}
      <div className="page-heading"><h1>{t('Restaurant systems','Sistemas del restaurante')}</h1><p>{t('Operational records, logs, maintenance, food safety, inventory, training and communication.','Registros operativos, bitácoras, mantenimiento, seguridad alimentaria, inventario, capacitación y comunicación.')}</p></div>
      <div className="ops-category-tabs" role="tablist"><button className={category==='All'?'active':''} onClick={()=>setCategory('All')}>{t('All','Todos')}</button>{OPS_CATEGORIES.map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{opsCategoryText(c,locale)}</button>)}</div>
      <div className="ops-module-grid">{visibleModules.map(m=><button key={m.kind} onClick={()=>selectKind(m.kind)} className={`ops-module-card ${kind===m.kind?'active':''}`}><b>{opsModuleText(m,locale).title}</b><small>{opsModuleText(m,locale).description}</small><ChevronRight/></button>)}</div>

      <div className="section-title"><div><h2>{moduleText.title}</h2><span>{moduleText.description}</span></div><button className="btn" disabled={busy} onClick={()=>{setEditing(null);setDraft(blank());setShowForm(true)}}><Plus/> {t('Add','Agregar')}</button></div>

      {showForm&&<form className="card form" onSubmit={save} style={{marginBottom:16}}>
        <div className="card-title-row"><h3>{editing?t('Edit','Editar'):t('New','Nuevo')} {moduleText.title}</h3><button type="button" className="icon-action" disabled={busy} onClick={resetForm} aria-label={t('Close form','Cerrar formulario')}><X/></button></div>
        <div className="field"><label>{t('Title','Título')}</label><input className="input" maxLength={200} value={draft.title} onChange={e=>setDraft(d=>({...d,title:e.target.value}))} placeholder={`${t('Name this','Nombra este registro de')} ${moduleText.title.toLowerCase()}`} required/></div>
        {module.fields.map(field=><div className="field" key={field.key}><label>{opsFieldText(field,locale)}{field.required?' *':''}</label>{field.type==='textarea'?<textarea className="textarea" value={String(draft.data[field.key]??'')} onChange={e=>setField(field.key,e.target.value)} required={field.required} maxLength={12000}/>:field.type==='select'?<select className="select" value={String(draft.data[field.key]??'')} onChange={e=>setField(field.key,e.target.value)} required={field.required}><option value="">{t('Select…','Seleccionar…')}</option>{field.options?.map(o=><option key={o} value={o}>{opsOptionText(o,locale)}</option>)}</select>:field.type==='boolean'?<label className="remember-row"><input type="checkbox" checked={Boolean(draft.data[field.key])} onChange={e=>setField(field.key,e.target.checked)}/>{opsFieldText(field,locale)}</label>:<input className="input" type={field.type==='datetime'?'datetime-local':field.type} min={field.min} max={field.max} value={String(draft.data[field.key]??'')} onChange={e=>setField(field.key,e.target.value)} required={field.required} placeholder={field.placeholder}/>}</div>)}
        <div className="two-col"><div className="field"><label>{t('Priority','Prioridad')}</label><select className="select" value={draft.priority} onChange={e=>setDraft(d=>({...d,priority:e.target.value}))}><option value="low">{opsOptionText('low',locale)}</option><option value="normal">{opsOptionText('normal',locale)}</option><option value="high">{opsOptionText('high',locale)}</option><option value="urgent">{opsOptionText('urgent',locale)}</option></select></div><div className="field"><label>{t('Due date / follow-up','Fecha límite / seguimiento')}</label><input className="input" type="datetime-local" value={draft.due_at} onChange={e=>setDraft(d=>({...d,due_at:e.target.value}))}/></div></div>
        <button className="btn" disabled={busy}>{busy?<Loader2 className="spin"/>:<Check/>}{editing?t('Save changes','Guardar cambios'):t('Create record','Crear registro')}</button>
      </form>}

      <div className="ops-toolbar"><div className="search-box"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`${t('Search','Buscar')} ${moduleText.title.toLowerCase()}…`}/></div><button className="mini-action" disabled={busy} onClick={()=>setShowArchived(x=>!x)}>{showArchived?t('Current','Actuales'):t('Archived','Archivados')}</button></div>
      <div className="list">{filtered.map(row=><details className="list-item" key={row.id}><summary style={{display:'flex',alignItems:'center',gap:12,width:'100%'}}><div className="list-main"><b>{row.title}</b><small>{opsStatusText(row.status,locale)} · {opsOptionText(row.priority,locale)}{row.due_at?` · ${t('due','vence')} ${formatDate(row.due_at,localeCode)}`:''}</small></div><span className="status">{opsStatusText(row.status,locale)}</span><ChevronDown/></summary><div className="ops-detail"><dl>{Object.entries(row.data).map(([k,v])=><div key={k}><dt>{opsFieldText(module.fields.find(field=>field.key===k)||{key:k,label:pretty(k),type:'text'},locale)}</dt><dd>{typeof v==='boolean'?opsBooleanText(v,locale):String(v)}</dd></div>)}</dl><div className="row-actions">{canManage&&<><button className="mini-action" disabled={busy} onClick={()=>beginEdit(row)}>{t('Edit','Editar')}</button>{row.status!=='complete'&&<button className="mini-action" disabled={busy} onClick={()=>setStatus(row,'complete')}>{t('Complete','Completar')}</button>}<button className="mini-action" disabled={busy} onClick={()=>archive(row)}>{row.archived_at?t('Restore','Restaurar'):t('Archive','Archivar')}</button><button className="mini-action danger-action" disabled={busy} onClick={()=>remove(row)}><Trash2/> {t('Trash','Papelera')}</button></>}</div></div></details>)}{!filtered.length&&<div className="empty-state"><b>{t('No records yet','Aún no hay registros')} {showArchived?t('(archived)','(archivados)'):''}</b><span>{t('Create the first record when you need it.','Crea el primer registro cuando lo necesites.')}</span></div>}</div>
    </main>
  </div>
}
