'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { supabase } from '@/lib/supabase';
import styles from '../ops-tools.module.css';

type Profile={app_role:'admin'|'manager'|'employee';location_id:string|null};
type Employee={id:string;full_name:string;user_id:string|null};
type Rec={id:string;kind:string;title:string;status:string;priority:string;sensitivity:string;data:any;assigned_employee_id:string|null;due_at:string|null;created_at:string};
const today=()=>new Date().toISOString().slice(0,10);

export default function TrainingPage(){
  const [ready,setReady]=useState(false),[busy,setBusy]=useState(false),[profile,setProfile]=useState<Profile|null>(null),[employees,setEmployees]=useState<Employee[]>([]),[me,setMe]=useState<Employee|null>(null),[rows,setRows]=useState<Rec[]>([]),[message,setMessage]=useState('');
  const [moduleForm,setModuleForm]=useState({title:'',content:''}),[assignForm,setAssignForm]=useState({module_id:'',employee_id:'',due_on:''}),[certForm,setCertForm]=useState({employee_id:'',name:'',expires_on:'',notes:''}),[coachForm,setCoachForm]=useState({employee_id:'',category:'attendance',note:'',severity:'normal'});
  const canManage=profile?.app_role==='admin'||profile?.app_role==='manager';
  useEffect(()=>{void init()},[]);
  async function init(){const {data:u}=await supabase.auth.getUser();if(!u.user){window.location.href='/';return;}const {data:p}=await supabase.from('profiles').select('app_role,location_id').eq('id',u.user.id).single();setProfile((p||null) as Profile|null);if(p?.location_id)await load(p.location_id,u.user.id);setReady(true);}
  async function load(locationId=profile?.location_id||'',userId?:string){if(!locationId)return;const [e,r]=await Promise.all([supabase.from('employees').select('id,full_name,user_id').eq('location_id',locationId).eq('active',true).is('deleted_at',null).order('full_name'),supabase.from('ops_records').select('id,kind,title,status,priority,sensitivity,data,assigned_employee_id,due_at,created_at').eq('location_id',locationId).in('kind',['training_module','training_progress','certification','onboarding','acknowledgment','system_note']).is('deleted_at',null).order('created_at',{ascending:false}).limit(300)]);const emp=(e.data??[]) as Employee[];setEmployees(emp);setRows((r.data??[]) as Rec[]);const uid=userId||(await supabase.auth.getUser()).data.user?.id;setMe(emp.find(x=>x.user_id===uid)||null);if(e.error||r.error)setMessage('Some training data could not be loaded.');}
  const modules=useMemo(()=>rows.filter(r=>r.kind==='training_module'&&r.status==='active'),[rows]),progress=useMemo(()=>rows.filter(r=>r.kind==='training_progress'),[rows]),certs=useMemo(()=>rows.filter(r=>r.kind==='certification'),[rows]),coaching=useMemo(()=>rows.filter(r=>r.kind==='system_note'&&(Array.isArray(r.data?.tags)?r.data.tags.includes('accountability'):r.data?.category==='accountability')),[rows]);
  const myProgress=useMemo(()=>progress.filter(r=>!me||r.assigned_employee_id===me.id),[progress,me]),overdue=useMemo(()=>progress.filter(r=>r.status!=='completed'&&r.due_at&&new Date(r.due_at)<new Date()).length,[progress]),expiring=useMemo(()=>certs.filter(r=>{const d=r.data?.expires_on;if(!d)return false;const days=(new Date(`${d}T12:00:00`).getTime()-Date.now())/86400000;return days>=0&&days<=30}).length,[certs]);
  const empName=(id:string|null)=>employees.find(e=>e.id===id)?.full_name||'Employee';
  async function createModule(e:FormEvent){e.preventDefault();if(!canManage||!profile?.location_id||busy||!moduleForm.title.trim()||!moduleForm.content.trim())return;setBusy(true);try{const {data:u}=await supabase.auth.getUser();const {error}=await supabase.from('ops_records').insert({location_id:profile.location_id,kind:'training_module',title:moduleForm.title.trim().slice(0,200),status:'active',priority:'normal',sensitivity:'team',data:{content:moduleForm.content.trim().slice(0,12000)},tags:['training'],created_by:u.user?.id||null,updated_by:u.user?.id||null});if(error)throw error;setModuleForm({title:'',content:''});await load();setMessage('Training module created.');}catch{setMessage('Could not create training module.');}finally{setBusy(false)}}
  async function assign(e:FormEvent){e.preventDefault();if(!canManage||!profile?.location_id||busy||!assignForm.module_id||!assignForm.employee_id)return;const mod=modules.find(m=>m.id===assignForm.module_id);if(!mod)return;setBusy(true);try{const {data:u}=await supabase.auth.getUser();const due=assignForm.due_on?new Date(`${assignForm.due_on}T23:59:59`).toISOString():null;const {error}=await supabase.from('ops_records').insert({location_id:profile.location_id,kind:'training_progress',title:mod.title,status:'assigned',priority:'normal',sensitivity:'private',data:{module_id:mod.id,module_title:mod.title,assigned_at:new Date().toISOString()},assigned_employee_id:assignForm.employee_id,due_at:due,tags:['training','assignment'],created_by:u.user?.id||null,updated_by:u.user?.id||null});if(error)throw error;await load();setMessage('Training assigned.');}catch{setMessage('Could not assign training.');}finally{setBusy(false)}}
  async function complete(r:Rec){if(busy||r.status==='completed')return;setBusy(true);try{const {data:u}=await supabase.auth.getUser();const {error}=await supabase.from('ops_records').update({status:'completed',data:{...r.data,completed_at:new Date().toISOString()},updated_by:u.user?.id||null}).eq('id',r.id).eq('kind','training_progress');if(error)throw error;await load();setMessage('Training marked complete.');}catch{setMessage('Could not complete training.');}finally{setBusy(false)}}
  async function addCert(e:FormEvent){e.preventDefault();if(!canManage||!profile?.location_id||busy||!certForm.employee_id||!certForm.name.trim())return;setBusy(true);try{const {data:u}=await supabase.auth.getUser();const {error}=await supabase.from('ops_records').insert({location_id:profile.location_id,kind:'certification',title:certForm.name.trim().slice(0,200),status:'active',priority:'normal',sensitivity:'private',data:{expires_on:certForm.expires_on||null,notes:certForm.notes.trim().slice(0,3000)},assigned_employee_id:certForm.employee_id,tags:['certification'],due_at:certForm.expires_on?new Date(`${certForm.expires_on}T12:00:00`).toISOString():null,created_by:u.user?.id||null,updated_by:u.user?.id||null});if(error)throw error;setCertForm({employee_id:'',name:'',expires_on:'',notes:''});await load();setMessage('Certification saved.');}catch{setMessage('Could not save certification.');}finally{setBusy(false)}}
  async function addCoach(e:FormEvent){e.preventDefault();if(!canManage||!profile?.location_id||busy||!coachForm.employee_id||!coachForm.note.trim())return;const employee=employees.find(x=>x.id===coachForm.employee_id);setBusy(true);try{const {data:u}=await supabase.auth.getUser();const {error}=await supabase.from('ops_records').insert({location_id:profile.location_id,kind:'system_note',title:`${coachForm.category} · ${employee?.full_name||'Employee'}`,status:'active',priority:coachForm.severity,sensitivity:'manager',data:{category:'accountability',employee_id:coachForm.employee_id,employee_name:employee?.full_name||'',topic:coachForm.category,note:coachForm.note.trim().slice(0,6000),tags:['accountability']},tags:['accountability',coachForm.category],occurred_at:new Date().toISOString(),created_by:u.user?.id||null,updated_by:u.user?.id||null});if(error)throw error;setCoachForm({...coachForm,note:''});await load();setMessage('Manager accountability note saved.');}catch{setMessage('Could not save accountability note.');}finally{setBusy(false)}}
  if(!ready)return <main className={styles.page}>Loading training…</main>;
  if(!profile?.location_id)return <main className={styles.page}>No restaurant location is assigned.</main>;
  return <main className={styles.page}><div className={styles.top}><div><h1>Training & Certifications</h1><p>Onboarding, role readiness, compliance and coaching history.</p></div><Link className={styles.back} href="/">Back to Ops</Link></div>{message&&<div className={message.startsWith('Could not')||message.startsWith('Some')?styles.error:styles.notice}>{message}</div>}
    <div className={styles.grid}><Metric label="Training modules" value={String(modules.length)}/><Metric label="Open assignments" value={String(progress.filter(r=>r.status!=='completed').length)}/><Metric label="Overdue training" value={String(overdue)}/><Metric label="Certs expiring ≤30 days" value={String(expiring)}/></div>
    <section className={styles.section}><h2>{canManage?'Training assignments':'My training'}</h2><div className={styles.list}>{myProgress.length?myProgress.map(r=><div className={styles.entry} key={r.id}><div className={styles.entryHead}><div><h3>{r.title}</h3><small>{canManage?`${empName(r.assigned_employee_id)} · `:''}{r.due_at?`due ${new Date(r.due_at).toLocaleDateString()}`:'no due date'}</small></div><span className={styles.pill}>{r.status}</span></div>{r.status!=='completed'&&(!canManage||r.assigned_employee_id===me?.id)&&<div className={styles.actions}><button className={styles.button} disabled={busy} onClick={()=>complete(r)}>Mark complete</button></div>}</div>):<div className={styles.empty}>No training assignments.</div>}</div></section>
    {canManage&&<><div className={styles.split}><section className={styles.section}><div className={styles.card}><h2>Create training module</h2><form onSubmit={createModule}><div className={styles.formGrid}><Field label="Title" wide><input value={moduleForm.title} onChange={e=>setModuleForm({...moduleForm,title:e.target.value})}/></Field><Field label="Training content" wide><textarea value={moduleForm.content} onChange={e=>setModuleForm({...moduleForm,content:e.target.value})}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy}>Create module</button></div></form></div></section><section className={styles.section}><div className={styles.card}><h2>Assign training</h2><form onSubmit={assign}><div className={styles.formGrid}><Field label="Module"><select value={assignForm.module_id} onChange={e=>setAssignForm({...assignForm,module_id:e.target.value})}><option value="">Choose module</option>{modules.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></Field><Field label="Employee"><select value={assignForm.employee_id} onChange={e=>setAssignForm({...assignForm,employee_id:e.target.value})}><option value="">Choose employee</option>{employees.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></Field><Field label="Due date"><input type="date" min={today()} value={assignForm.due_on} onChange={e=>setAssignForm({...assignForm,due_on:e.target.value})}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy}>Assign</button></div></form></div></section></div>
    <div className={styles.split}><section className={styles.section}><div className={styles.card}><h2>Certification</h2><form onSubmit={addCert}><div className={styles.formGrid}><Field label="Employee"><select value={certForm.employee_id} onChange={e=>setCertForm({...certForm,employee_id:e.target.value})}><option value="">Choose employee</option>{employees.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></Field><Field label="Certification"><input value={certForm.name} onChange={e=>setCertForm({...certForm,name:e.target.value})}/></Field><Field label="Expiration"><input type="date" value={certForm.expires_on} onChange={e=>setCertForm({...certForm,expires_on:e.target.value})}/></Field><Field label="Notes"><input value={certForm.notes} onChange={e=>setCertForm({...certForm,notes:e.target.value})}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy}>Save certification</button></div></form></div></section><section className={styles.section}><div className={styles.card}><h2>Coaching / accountability</h2><form onSubmit={addCoach}><div className={styles.formGrid}><Field label="Employee"><select value={coachForm.employee_id} onChange={e=>setCoachForm({...coachForm,employee_id:e.target.value})}><option value="">Choose employee</option>{employees.map(x=><option key={x.id} value={x.id}>{x.full_name}</option>)}</select></Field><Field label="Topic"><select value={coachForm.category} onChange={e=>setCoachForm({...coachForm,category:e.target.value})}><option value="attendance">Attendance</option><option value="performance">Performance</option><option value="policy">Policy</option><option value="recognition">Recognition</option><option value="coaching">Coaching</option></select></Field><Field label="Severity"><select value={coachForm.severity} onChange={e=>setCoachForm({...coachForm,severity:e.target.value})}><option value="low">Low</option><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option></select></Field><Field label="Manager note" wide><textarea value={coachForm.note} onChange={e=>setCoachForm({...coachForm,note:e.target.value})}/></Field></div><div className={styles.actions}><button className={styles.button} disabled={busy}>Save manager note</button></div></form></div></section></div></>}
    <section className={styles.section}><h2>Certifications</h2><div className={styles.list}>{certs.length?certs.map(c=><div className={styles.entry} key={c.id}><div className={styles.entryHead}><div><h3>{c.title}</h3><small>{empName(c.assigned_employee_id)} · expires {c.data?.expires_on||'not set'}</small></div><span className={styles.pill}>{c.status}</span></div></div>):<div className={styles.empty}>No certifications recorded.</div>}</div></section>
    {canManage&&<section className={styles.section}><h2>Recent accountability notes</h2><div className={styles.list}>{coaching.slice(0,30).map(c=><div className={styles.entry} key={c.id}><div className={styles.entryHead}><div><h3>{c.title}</h3><small>{new Date(c.created_at).toLocaleString()}</small></div><span className={styles.pill}>{c.priority}</span></div><div className={styles.details}>{detail('Note',c.data?.note)}</div></div>)}</div></section>}
  </main>}
function Metric({label,value}:{label:string;value:string}){return <div className={styles.metric}><span>{label}</span><strong>{value}</strong></div>}
function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={`${styles.field} ${wide?styles.wide:''}`}><span>{label}</span>{children}</label>}
function detail(label:string,value?:string){return value?.trim()?<div className={styles.detail}><b>{label}</b><span>{value}</span></div>:null}
